Shopify/polaris-react

.storybook/webpack.config.js
UNRELEASED.md
package.json
scripts/splash/README.md
scripts/splash/index.tsx

Yarn splash can be really noisy at times
Enables maintainers running `yarn dev` to hide [`yarn splash`](https://github.com/Shopify/polaris-react/tree/master/scripts/splash) reports from the console by running `DISABLE_SPLASH=1 yarn dev` ([#2372](https://github.com/Shopify/polaris-react/pull/2372))

Make yarn splash optional

---

.circleci/config.yml
.storybook/config.js
package.json
yarn.lock

Keeping up to date, making it easier to do new version bumps in the future now that we use their new package
Move from storybook-chroma to storybook-chromatic as the package is
being unified
See that the chroma GH check runs successfully

Update to latest chromatic package

---

UNRELEASED.md
src/components/Popover/Popover.tsx
src/components/Popover/tests/Popover.test.tsx
src/components/Portal/Portal.tsx
src/components/Portal/tests/Portal.test.tsx
src/components/shared.ts
src/utilities/focus.ts
src/utilities/is-element-in-viewport.ts
src/utilities/tests/focus.test.ts
src/utilities/tests/is-element-in-viewport.test.ts

Fixes #2188 
* When the popover is closed it'll focus the next focusable element. If a next focusable element is not present the activator will be focused
* Create two focus utilities
* Add tests for utilities
* Add missing focus tests
<details>
<summary>With another focusable element</summary>
```jsx
import {Popover, Button, ActionList} from '../src';
const [popoverActive, setPopoverActive] = useState(true);
const togglePopoverActive = useCallback(
() => setPopoverActive((popoverActive) => !popoverActive),
[],
);
const activator = (
<Button onClick={togglePopoverActive} disclosure>
More actions
</Button>
);
return (
<div style={{height: '250px'}}>
<Popover
active={popoverActive}
activator={activator} …
```

[Popover ] Fixed incorrect element being focused when closed

---

UNRELEASED.md
src/components/Popover/Popover.tsx
src/components/Popover/tests/Popover.test.tsx

related to: https://github.com/Shopify/polaris-react/issues/1995
I'm wanting to make use of a hook inside popover for my current project, so I took the opportunity to convert popover to a function components.
Functionality remains the same. However there are changes.
1. ComponentDidMount and ComponentDidUpdate bundle into a single useEffect hook.
~2. Use React.createElement to workaround creating jsx typing issue with the WrapperComponent~
~3. Tighten the type of activatorWrapper too so that it may only include strings of element names, e.g. 'button' and 'div' are valid, but not 'fff' or 'Button'~ (breaking change)
thank you for those last two @BPScott! …

[Popover] Convert Popover to functional component

---

UNRELEASED-v5.md
src/components/Modal/Modal.tsx
src/components/Modal/README.md
src/components/Modal/index.ts
src/components/Modal/tests/Modal.test.tsx

Opening this new PR since the old one https://github.com/Shopify/polaris-react/pull/2341 was closed when the `v5.0.0` branch was deleted.
Part of https://github.com/Shopify/polaris-react/issues/1995
Some notable changes,
- The activator now uses `useRef` instead of `createRef`.
- The external activator example needs to call `requestAnimationFrame` when focusing the button.

[Modal] Convert modal to function

---

CHANGELOG.md
UNRELEASED.md

Update to Changelog for 4.8.0
<details>
```jsx
return (
</Page>
);
}
```
</details>

[Polaris-release] Update to Changelog for 4.8.0

---

src/components/Frame/components/Toast/Toast.scss

Part of https://github.com/Shopify/polaris-ux/issues/346
Implementing the new color system in the `Toast` component.
| Light mode | Dark mode | MSEdge high contrast | 
| - | - | - |
| ![image](https://user-images.githubusercontent.com/22782157/68506809-6ee2c180-0238-11ea-8aea-7e46cb9c5350.png)| ![image](https://user-images.githubusercontent.com/22782157/68506825-7609cf80-0238-11ea-9575-584fd5c06d5b.png)| ![image](https://user-images.githubusercontent.com/22782157/68506635-072c7680-0238-11ea-9ebd-648e3e07fb30.png) |
Updates color variables and the `border-radius`.

[Toast] Use the color system variables

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Part of https://github.com/Shopify/polaris-react/issues/795
If the text field does not have a `prefix` or `suffix`, then it doesn't have an `aria-labelledby` value. Since `label` is a required prop on TextField, we will always have an id to link to.
Removing the check for an empty array since the labelledby property should have a value regardless if the `TextField` has a prefix or suffix.
- Open up Storybook
- Go to the "Modal with primary action" example
- Inspect the modal's TextField
- The TextField should have an `aria-labelledby` matching the label element.
- Notice the label's id `PolarisTextField2Label` on the input. …

[TextField] Should always have an aria-labelledby property

---

UNRELEASED.md
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/utilities/color-transformers.ts
src/utilities/theme/tests/utils.test.ts

Passing an optional alpha to CSS `hsl()` breaks in Edge. Per MDN docs:
> As of CSS Colors Level 4, `hsla()` is an alias for `hsl()`. In browsers that implement the Level 4 standard, they accept the same parameters and behave the same way.
But turns out Edge (EdgeHTML) did not implement the Level 4 standard: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14995939/
For those curious, here is a [reduced test case](https://codepen.io/timlayton/pen/qBBKYrq).
`hsl()` -> `hsla()`
📄 [Changelog …

[Color system] Use CSS hsla() instead of hsl() to fix Edge bug

---

UNRELEASED.md
src/components/ResourceItem/ResourceItem.tsx
src/components/ResourceItem/tests/ResourceItem.test.tsx

This change was introduced since when it comes to launching an app in the app list, certain apps should be opened in the embedded setting (i.e. same tab) or externally (i.e. another tab). The external prop identifies which apps should be opened externally.
This PR doesn't make any design changes. 
<details>
When external is true:
When external is false/undefined:
</details>
In playground copy and paste: 
<details>
``` …
```

[ResourceList] Add external prop to ResourceList

---

src/index.ts
src/utilities/theme/index.ts

Other programs should be able to use the color factory.
It adds the `buildColors` to the list of exports.

Export color factory function

---

UNRELEASED.md
src/components/DatePicker/DatePicker.tsx

Fixes #2333 
See https://github.com/Shopify/polaris-react/pull/2089#discussion_r322790348
When I converted DatePicker to a functional component using hooks, I decided to simplify the code a bit as well. Since our tests and examples for the DatePicker are not thorough, this introduced a race condition that was hard to test locally. The only browser that triggered this condition consistently was Firefox, and only when also using the `Month` component.
This fixes that by waiting until state changes have resolved to trigger the callback
`yarn run build-consumer web` and check out the analytics page on FF, as per the original issue

Fix bug that introduced a race condition in consumers

---

UNRELEASED.md
package.json
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/DropZone/tests/DropZone.test.tsx
src/components/RangeSlider/RangeSlider.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/Toast/Toast.tsx
src/utilities/tests/is-element-in-viewport.test.ts
yarn.lock

[⏫ TypeScript 3.6.3](https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/)

Upgrade typescript to 3.7.2

---

UNRELEASED.md
scripts/build-shrink-ray.js
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Breadcrumbs/Breadcrumbs.scss
src/components/Frame/Frame.tsx
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/Sticky/Sticky.tsx
src/components/TextField/TextField.tsx
src/index.ts
src/styles/foundation/_colors.scss
src/styles/foundation/_filters.scss
src/utilities/color-transformers.ts
src/utilities/tests/compose.test.ts
src/utilities/theme/utils.ts
yarn.lock

Keeping up to date.
https://prettier.io/blog/2019/11/09/1.19.0.html has the lowdown, but stuff of interest is:
- Support for new syntax added in TS 3.7
- Fixing comment moving weirdness in useEffect style functions (see https://prettier.io/blog/2019/11/09/1.19.0.html#fix-moving-comments-in-function-calls-like-useeffect-6270-by-sosukesuzuki)
- Nicer formatting of union types
Updating the package in yarn then running a `yarn run format` to fixup expected changes
Removing a few unneeded prettier-ignores as Prettier no longer does ugly looking things in those cases.
Linting passes with no additional changes required

Update Prettier to 1.19.1

---

UNRELEASED.md
src/components/Page/Page.tsx
src/components/SkeletonPage/SkeletonPage.tsx

The parser will only read the interface `{Component}Props` so we need to combine the props and deprecated props interface

[Page][SkeletonPage] Combine interfaces

---

UNRELEASED.md
src/components/Popover/Popover.tsx
src/components/Popover/README.md
src/components/Popover/set-activator-attributes.ts
src/components/Popover/tests/Popover.test.tsx
src/components/Popover/tests/set-activator-attributes.test.ts

Fixes #2187
* Add prop
* Consume prop
* Use prop were it's needed in doc examples
* Add accessibility docs
<details>
```jsx
function PopoverWithActionListExample() {
const [popoverActive, setPopoverActive] = useState(true);
const togglePopoverActive = useCallback(
() => setPopoverActive((popoverActive) => !popoverActive),
[],
);
const activator = (
<Button onClick={togglePopoverActive} disclosure>
More actions
</Button>
);
return (
<div style={{height: '250px'}}>
<Popover
active={popoverActive}
activator={activator}
onClose={togglePopoverActive}
ariaHaspopop
>
<ActionList items={[{content: 'Import'}, {content: 'Export'}]} />
</Popover>
</div>
);
}
```
</details>

[Popover] Add ariaHaspopup

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/Button/README.md
src/components/Button/tests/Button.test.tsx

We have a need to use a `Button` to control the collapsed/expanded state of a `Collapsible`.  When the collapsible is collapsed, we want to say `Show more` with downwards caret.  When expanded, we want to say `Show less` with upwards caret.
The previous API is respected, so this is purely an opt-in enhancement
The icon will animate via CSS transition
<details> …

[Button] Improve the disclosure API for button, allowing user to spec﻿﻿﻿ify the direction the disclosure icon faces

---

src/components/Indicator/Indicator.scss

addresses:  https://github.com/Shopify/polaris-ux/issues/349
Paired with Miru apply CS to Indicator component:
<details>
```jsx
import {
HomeMajorMonotone,
ProductsMajorTwotone,
OrdersMajorTwotone,
OnlineStoreMajorTwotone,
CirclePlusOutlineMinor,
} from '@shopify/polaris-icons';
import {
Page,
Breadcrumbs, …
```

[Color System] Apply CS to Indicator component

---

.storybook/config.js
playground/KitchenSink.tsx
playground/stories.tsx

This means we're no longer using the old storiesOf API and pushes the story config for playgrounds in the playground folder instead of the storybook config
Defines playground stories in the playground stories.tsx.
Check  playground stories still render as before

Use CSF format for rendering playground stories

---

UNRELEASED.md
src/components/Form/Form.tsx

While doing an a11y audit on our Form component I found that our Form component is failing because `ARIA hidden element must not contain focusable elements`.
Our Form contains an implicitSubmit prop which generates a visually hidden submit button with aria-hidden set to true.
adds a tabIndex={-1} to our Form implied submit button. 
Using Fast pass on the [Accessibility extension for web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en) ensure there are no errors with the playground below.
<details>
```jsx
import {Page, Form, FormLayout, TextField, Button} from '../src';
export function Playground() …
```

[Form] Add tabIndex={-1} to implicit submit form

---

UNRELEASED.md
src/components/Frame/Frame.scss

There's an issue in web where the content of the TopBar has not loaded when the StickyManager gets instantiated. The height of the bar is 0, therefore, the elements that should 'stick' below the top bar don't.
The height of the bar is set on the TopBar, but not on the wrapper in the Frame where the querySelector happens. This change adds the same height on the wrapper.
<details> …

[Frame TopBar] Add height to TopBar

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/ButtonGroup/ButtonGroup.scss
src/components/ButtonGroup/ButtonGroup.tsx
src/components/ButtonGroup/components/Item/Item.tsx
src/components/ButtonGroup/components/Item/tests/Item.test.tsx
src/components/ButtonGroup/tests/ButtonGroup.test.tsx
src/utilities/theme/utils.ts
yarn.lock

addresses part of: https://github.com/Shopify/polaris-ux/issues/382
and also 
fixes: https://github.com/Shopify/polaris-react/issues/1240
1. Keep layout CSS as part of `ButtonGroup` (essentially margins).
2. Adds data attributes to ButtonGroup
3. Moves necessary styles to Button
4. adds the theme to ButtonGroup
<details>
```jsx
import React, {useState, …
```

[ButtonGroup] Add theme to ButtonGroup and move CSS to Button

---

UNRELEASED.md
src/components/Card/Card.scss
src/components/Card/Card.tsx
src/components/Card/README.md
src/components/Card/tests/Card.test.tsx

Reverts https://github.com/Shopify/polaris-react/pull/2104
See https://github.com/Shopify/polaris-react/issues/2075 for more context on this change
It seemed to be generally accepted that this change is rendering buttons strangely, as seen in https://github.com/Shopify/polaris-react/issues/2075#issuecomment-535561407.
After the PR I am reverting, polaris-react renders secondary buttons on the left, then primary buttons, which is contrary to the expected `Primary > Secondary` reading order.  The blue button should be on the left.
So, I set out to revert this change (because every consumer of `Card` would be expecting right-aligned buttons prior to that change, IMO that was a breaking change), and give the ability to control alignment.
Final product:
- Adds new `footerActionAlignment` prop …

[Card][ButtonGroup] Revert change to footer button alignment, add new footerActionAlignment prop

---

UNRELEASED.md
src/components/MessageIndicator/MessageIndicator.scss

To improve the contrast of `MessageIndicator` shown when `message` is set on `TopBar.UserMenu`. Thanks for the design @AdamWhitcroft 🎉 
cc @mirualves for UI Kit
Added a border for the message indicator colored with the `--p-surface-background` CSS variable. The indicator's color now uses the `--p-highlight-icon` CSS variable.
|---|---|
|<img width="128" alt="Screen Shot 2019-11-14 at 4 07 24 PM" src="https://user-images.githubusercontent.com/18447883/68896224-03e23080-06f9-11ea-8450-1875a63182e3.png">|<img width="133" alt="Screen Shot 2019-11-13 at 1 48 35 PM" src="https://user-images.githubusercontent.com/18447883/68896236-0ba1d500-06f9-11ea-9c80-f95f48177d62.png">|
|<img width="133" alt="Screen Shot 2019-11-14 at 4 24 09 PM" …

[ColorSystem][MessageIndicator] Improve contrast and use color system

---

.vscode/settings.json

v3 of the prettier vscode plugin has been released and it has changed how eslint/stylelint integration works. It now no-longer tries to call a built-in version of prettier-eslint / prettier-stylelint - those commands are only used if they're installed locally in your project (this is a good thing as it stops potential for weird version mismatches between local packages and the ones provided by the vscode plugin).
We don't use those packages in polaris because instead we run prettier as a rule within eslint and stylelint (using https://github.com/prettier/eslint-plugin-prettier and https://github.com/prettier/stylelint-prettier).
The `prettier.stylelintIntegration` and `prettier.eslintIntegration` vscode settings now do nothing at all except throw warning popup saying they're deprecated …

Remove prettier.stylelintIntegration config

---

UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/EmptyState/EmptyState.tsx
src/components/EmptyState/README.md
src/components/EmptyState/tests/EmptyState.test.tsx

This PR is one of two that will enable the improvement of transitions from skeleton loading states to empty states by adding support for use of the empty state component in a content context. For example, within a `Card` or `ResourceList`**. 
Adds content context consumer to `EmptyState`
Empty state in a card (small screen on right):
**Note: I'm adding empty state handling to `ResourceList` in a [separate PR](https://github.com/Shopify/polaris-react/pull/2160).
<details>
<summary>Click to view collapsed tophatting instructions</summary>
<br />
📄 [Changelog …

[EmptyState] Add content context variant

---

UNRELEASED.md
src/components/Page/components/Header/Header.scss

When printing a page, we don't want the breadcrumbs or actions to be visible.
removing actions and breadcrumbs from Page header in print mode using the `print` media query mixin.
Run the playground below and click the `Print` action to view the print mode page without any nav or actions.
<details>
```jsx …
```

[Page] print mode adjustments

---

UNRELEASED.md
src/components/PageActions/README.md

Updating the example on the style guide to follow best practices.
<details>
```jsx
return (
</Page>
);
}
```
</details>

[PageActions] Update delete button to destructive button

---

UNRELEASED.md
src/components/ResourceItem/ResourceItem.scss
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/components/BulkActions/BulkActions.scss
src/components/ResourceList/components/BulkActions/BulkActions.tsx
src/components/ResourceList/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx
src/components/ResourceList/components/BulkActions/tests/BulkActions.test.tsx
src/components/ResourceList/components/CheckableButton/CheckableButton.scss
src/components/ResourceList/components/CheckableButton/CheckableButton.tsx
src/components/ResourceList/components/CheckableButton/tests/CheckableButton.test.tsx
src/components/ResourceList/tests/ResourceList.test.tsx
tests/build.test.js

partly addresses: https://github.com/Shopify/polaris-ux/issues/360 and https://github.com/Shopify/polaris-ux/issues/361
While applying the design language to [ButtonGroup](https://github.com/Shopify/polaris-react/pull/2441), we were able to change how ButtonGroups work. This allowed us to refactor the ResourceList BulkActions and remove the custom components.
1. applies design language
2. makes use of Buttongroups
3. removes the need for custom BulkAction buttons
To 🎩 ensure BulkActions are working as expected in Storybook. Including small screen, and select mode.
Also use yarn `build-consumer web`
<details>
```jsx
return …
```

[BulkActions] Add theming to BulkAction and remove custom ButtonGroup from ResourceList 

---

UNRELEASED.md
src/components/ResourceList/README.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

Builds on #1570 
Right now our empty states are vastly different from our loading and with-data states. We'd like to make the transition from loading to empty state smoother, as well as make the with-data state more familiar once a feature has been used. For list views, this means having our empty states within the context of the resource list.
Currently, `ResourceList` only has an empty state for when there are no results for a filter or search query. This PR adds support for disabling filters and providing markup to render when there are not yet any resources to list. That way the same static content can be rendered in a loading, empty, and with-data state. See the tophatting instructions to view the smooth visual transition between these states using the playground code.
** This is a …

[ResourceList] Add support for in context empty state

---

UNRELEASED.md
src/components/TextField/TextField.tsx

[TextField] Replaced setMounted with custom hook

---

.vscode/extensions.json
.vscode/settings.json

The shinn.stylelint extension has been removed from the marketplace,
suggest using hex-ci.stylelint-plus instead as it is a an up-to-date
fork that adds autofixing - this removes an error saying "you're trying to
recommend a non-existent extension".
Add style autofixing config to vscode. This ensures autofixable
stylelint rules are fixed on save. This stopped working recently when
the prettier extension changed how it handled stylelint integration (it
now suggests using the autofixing built into the stylelint-plus and
eslint extensions directly)
Updates VSCode workspace settings
Remove your locally installed version of `shinn.stylelint` in vscode and instead install [hex-ci.stylelint-plus](https://marketplace.visualstudio.com/items?itemName=hex-ci.stylelint-plus)
To test formatting on …

Fixup stylelint setup in VSCode after plugin changes

---

pre-commit

This will run `yarn colordocs` and add the updated docs when committing a change to `role-variants.ts`

add pre-commit hook to generate new color docs if the source changes

---

UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/EmptyState/EmptyState.tsx
src/components/Filters/README.md

#2475 Brought up that the `imageContained` prop description was a duplicate of the `largeImage` prop description, and that the `largeImage` and `image` prop descriptions are unclear. I also noticed that the spacing is off in the data table `Filters` thanks to a Slack thread earlier today.
- Fixes the spacing in the data table `Filters` example
|---|---|
|<img width="786" alt="Screen Shot 2019-11-27 at 12 55 28 PM" src="https://user-images.githubusercontent.com/18447883/69747954-4a7e5480-1115-11ea-8655-76f9f0fec339.png">|<img width="780" alt="Screen Shot 2019-11-27 at 12 55 02 PM" src="https://user-images.githubusercontent.com/18447883/69747974-51a56280-1115-11ea-899d-1149925d5db3.png">|
- Fixes the `image`, `largeImage`, and `imageContained` prop descriptions of …

[Filters] Fix example spacing; [EmptyState] Fix prop descriptions and cascade order

---

UNRELEASED.md
src/components/Tooltip/README.md

I was confusing instances of light colored tooltips with a Popover since it wasn't immediately obvious to me that this prop existed. This PR surfaces that prop via an example in the style guide.
I don't mind if we close this PR if we feel we don't need this addition.

[Tooltip] Add an example for a light tooltip

---

UNRELEASED.md
src/components/Focus/Focus.tsx
src/components/Focus/README_INTERNAL.md
src/components/Focus/tests/Focus.test.tsx
src/components/TrapFocus/README_INTERNAL.md
src/components/TrapFocus/TrapFocus.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

Part of https://github.com/Shopify/polaris-react/issues/795
This PR is fixing `TrapFocus` so that focus remains within a designated container.
The focus flow on each press of tab works like,
> focus container -> focus first element -> focus second element(last element) -> focus first element -> focus second element -> etc
Instead of returning focus back to the container.
<kbd>![1](https://user-images.githubusercontent.com/22782157/68225788-f45b3d00-ffbe-11e9-8a39-aca956397a70.gif)</kbd>
Use Storybook. Open up a modal and press tab. Once you reach the last element, the next tab should focus the first element in the modal.

[TrapFocus] Focus should stay within the container

---

UNRELEASED.md
src/components/Popover/Popover.scss
src/components/Popover/Popover.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/tests/Popover.test.tsx

Consumers may want their `<Popover />` to be wider or taller than its current max width and max height.
My use case is for fitting a multi-month `<DatePicker />` inside of a `<Popover />`, which currently doesn't fit.
Adds a `fluidContent` prop (taken from @joshuajay 's fork in Shopify admin :pray:) that lets the popover's content determine its width and height.
**Before**
**After**
<details> …

[Popover] Add fluidContent prop

---

package.json
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/DropZone/tests/DropZone.test.tsx
src/components/RangeSlider/RangeSlider.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/Toast/Toast.tsx
src/utilities/tests/is-element-in-viewport.test.ts
yarn.lock

This reverts commit 9085064a484a63dcee29121ec9a52d58dd190927.
https://github.com/Shopify/polaris-react/pull/2237
Microsoft has commited a breaking change in a minor release of typescript
https://github.com/microsoft/TypeScript/issues/33939
Fixes #0000 
<details>
```jsx
return …
```

Revert "Upgrade typescript to 3.7.2 (#2237)"

---

src/components/ResourceList/components/CheckableButton/CheckableButton.scss

As part of https://github.com/Shopify/polaris-react/pull/2467 I missed the use case where we can have a selectable list without actions. In which case the border right was missing. 
Using the button group selector we remove the border.
Using the button group selector we remove the border.
In Storybook ensure these 2 examples render as expected (while selected):
- Resource list with selection and no bulk actions
- Resource list with bulk actions …

[CheckableButton] add border-right when there are no actions

---

documentation/Color system.md
pre-commit
scripts/color-system-docs.js
src/index.ts
src/utilities/theme/index.ts
src/utilities/theme/tokens.ts
src/utilities/theme/utils.ts

It’s nice to see what override CSS variables are available without looking at the source.
- Updates the color doc script to include override values
- Updates the pre-commit hook to also run when overrides are changed
- Move overrides to `tokens.ts` because 1) these values will eventually be either moved to tokens or replace the Sass values directly and 2) to avoid triggering the color docs pre-commit hook for every change to utils.ts
1. Commit a change to `src/utilities/theme/tokens.ts` (now contains the override values)
1. ensure docs get updated and added to the commit.

[Color system] Add override docs

---

src/components/InlineError/InlineError.scss

Fixes https://github.com/Shopify/polaris-ux/issues/350

[InlineError] Applied color system

---

UNRELEASED.md
src/components/TrapFocus/TrapFocus.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

Closes https://github.com/Shopify/polaris-react/issues/2531
We initially removed this line so that we could trap focus within a container, even if focus leaves the page content (or an iframe).
Although this is not a breaking change on its own, it causes a bug with the style guide which disallows the user to interact with the rest of the page such as the examples drop down and the search bar.
We'll be fixing `TrapFocus` in another PR which handles keyboard inputs instead of handling when focus leaves the container.
Follow [these](https://github.com/Shopify/polaris-react/blob/6579045fbbf668b8f1624631cd5c7f609f4bff57/documentation/Tophatting%20documentation.md#how-to--documentation) instructions to test the style guide.
</details>

[TrapFocus] Don't trap the focus if the relatedTarget is null

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx
src/utilities/tests/use-event-listener.test.tsx
src/utilities/use-event-listener.ts

Removing all reference to `window` on code that can execute on the client

[Dropzone] Removed reference to window

---

src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/test-utilities/react-testing.tsx

The current way of testing using mountWithAppProvider causes problems when adding support for nested theme providers in #2459 - we need a way to test a ThemeProvider that has been wrapped only in a FeaturesContext so we don't get interference from the ThemeProvider provided by the PolarisTestProvider.
Migrates ThemeProvider to use react-testing instead of enzyme, and sets up a custom mounter to deal with the above along the way.
We also leverage some of the new matchers provided by react-testing
tests pass

Use react-testing to test ThemeProvider

---

UNRELEASED.md
package.json
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/DropZone/tests/DropZone.test.tsx
src/components/Filters/Filters.tsx
src/components/Page/Page.tsx
src/components/RangeSlider/RangeSlider.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/components/BulkActions/BulkActions.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/Toast/Toast.tsx
src/components/TrapFocus/TrapFocus.tsx
src/utilities/tests/is-element-in-viewport.test.ts
yarn.lock

#2237 bumped us up to typescript 3.7, but it got reverted in #2501 because it didn't play nice in consuming projects.
This reverts the revert and fixes the issues that caused the problems in consuming projects.
Updates to TS 3.7, fixing any type checking issues.
If you have an uninitialized property that then gets referenced (like by
having a getter for it) then TS emits declarations that break in
consuming projects. Convert a bunch of cases where we created getters for non-existant
properties to use boring old method functions, thus allowing consumer builds to work again..
Tests / linting pass
Test this in a consuming project:
- Checkout the latest version of polaris-styleguide
- In polaris-react: `yarn run build-consumer polaris-styleguide`
- Then in the styleguide `yarn run build` and …

TypeScript 3.7 (take 2)

---

src/components/ActionMenu/components/MenuGroup/tests/MenuGroup.test.tsx
src/components/ActionMenu/components/RollupActions/tests/RollupActions.test.tsx
src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
src/components/Banner/tests/Banner.test.tsx
src/components/ChoiceList/tests/ChoiceList.test.tsx
src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
src/components/DropZone/tests/DropZone.test.tsx
src/components/Filters/components/ConnectedFilterControl/tests/ConnectedFilterControl.test.tsx
src/components/Filters/tests/Filters.test.tsx
src/components/Layout/tests/Layout.test.tsx
src/components/Pagination/tests/Pagination.test.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
src/components/Portal/tests/Portal.test.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/ResourceList/components/FilterControl/components/FilterCreator/tests/FilterCreator.test.tsx
src/components/ResourceList/tests/ResourceList.test.tsx
src/components/Select/tests/Select.test.tsx
src/components/TextField/components/Spinner/tests/Spinner.test.tsx
src/components/TopBar/components/SearchField/tests/SearchField.test.tsx
src/test-utilities/legacy.tsx
src/utilities/tests/is-input-focused.test.tsx
src/utilities/tests/with-app-provider.test.tsx

We want to use `@shopify/react-testing` in place of Enzyme. Let's avoid some usage of enzyme
- Rewrite tests using enzyme's `mount` and `shallow` to use react-testing
- Remove direct imports of enzyme, instead reexport `ReactWrapper` from enzyme.
- Simplify a few type generics to use default values as we can do `ReactWrapper` instead of `ReactWrapper<any, any>
- Remove matchByTestID helper that was only used once, rewrite the test using it to use findByTestID instead
Confirm tests pass

Enzyme tidying

---

src/components/Modal/components/Dialog/Dialog.scss

Noticed we missed this while I was working on https://github.com/Shopify/polaris-react/pull/2459
|before|after|
|-|-|
|<img width="1552" alt="Screen Shot 2019-12-13 at 2 11 08 PM" src="https://user-images.githubusercontent.com/1403188/70825568-b79b1680-1db2-11ea-98ae-2590ee26f3cc.png">|<img width="1552" alt="Screen Shot 2019-12-13 at 2 11 00 PM" src="https://user-images.githubusercontent.com/1403188/70825574-c08be800-1db2-11ea-9b0a-44b7bfb3cb1f.png">|

[Color system] update modal to use border radius from new design language

---

src/components/ActionMenu/components/RollupActions/RollupActions.tsx
src/components/ButtonGroup/components/Item/Item.tsx
src/components/Card/Card.tsx
src/components/DropZone/DropZone.tsx
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/ResourceList/components/FilterControl/components/FilterCreator/FilterCreator.tsx
src/components/TopBar/TopBar.tsx
src/utilities/use-toggle.ts

Having useToggle and useForcibleToggle is a little confusing. lets have one way of doing things.
This new API mimics the useToggle() hook implemented in the
@shopify/react-hooks package so we can easily move to that if we wish to
do so in the future
Replaces useToggle with a new implementation, remove useForcibleToggle. update usage
typecheck / tests pass

Rework useToggle and remove useForcibleToggle

---

.vscode/settings.json

v2 of vscode's eslint plugin got released and it changed some settings around. Notably it now autodetects typescript, and autofixing is exposed through the standard "editor.codeActionsOnSave" setting.
Updates vscode settings
Check you're using v2. of eslint plugin
Confirm autofixing on save still works

Update vscode eslint plugin settings

---

.vscode/settings.json
UNRELEASED.md
src/components/Page/Page.scss
src/styles/foundation/_colors.scss
src/styles/foundation/_layout.scss
src/styles/foundation/_typography.scss
src/styles/foundation/_utilities.scss
src/styles/shared/_breakpoints.scss
src/styles/shared/_icons.scss
src/styles/shared/_layout.scss
yarn.lock

Keeping up to date and fixing false positives in VScode.
This removes false positive warnings in TSX files when we define style
props like `<div style={{width: 100}}>Hi</div>` that vscode's stylelint
plugin reports. These never get surfaced when we run SK because that
doesn't run stylelint over tsx files but they're still annoying to see
in VSCode sidebars.
Update dependencies
Update code to follow new rules, mostly removing uneeded "!= null"
statements and parenthesis.
Disable autoFixing for the stylelint plugin - it turns out that it now
modifies app code on save even when nothing should change and that
causes conflicts with our ESLint rules. It can't be enabled on a
per-language basis so it needs to go entirely for now. (note that we still 
have prettier autoformatting on save so that …

Update stylelint-config-shopify to latest

---

UNRELEASED.md
src/components/TextField/TextField.tsx

Fixes #2282. I made a single PR because it was one issue, but maybe it should be split in two
1. Removes default props for `max`, `min`, `step` so they no longer show up in markup unless explicitly passed
2. Prevents `aria-invalid="false"` from being rendered when there is no error

[TextField] delete irrelevant default numeric-range props, prevent unconditional aria-invalid='false'

---

src/components/Focus/tests/Focus.test.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/types.ts

Lets not break consumers using TS <3.5 by using the built-in Omit type that was added in 3.5
Stop using omit in shippable code.
It's fine to use in tests though.
`yarn run build-consumer polaris-styleguide`  then run a build in the styleguide and confirm that it works.

Don't use Omit type in shipped code

---

.shopify-build/polaris-react.yml
.shopify-build/setup-consumer-test.sh

Getting the consumer build tests working again
Remove unneeded copying of the build folder - it did nothing except cause things to break - `yarn build` puts everything in the right place already.
Skip web tests for now as the version of node we need for eslint is incompatible with what web runs - but they're looking to update SOON so check in on them later
Run buildkite build for this branch. Here's one i made earlier: https://buildkite.com/shopify/polaris-react/builds/1387#c0194ee8-dcc7-4a8d-89d3-1f7b2e45fd48

Fixup consumer build tests

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx
src/components/DropZone/components/FileUpload/FileUpload.scss
src/components/DropZone/tests/DropZone.test.tsx

`DropZone` currently opens the file dialog via prop. However this is a security issue, and browsers *no not* allow file dialogs to be opened from artificial events. However using class-based components seen to be a workaround, probably related to how react handles synthetic events in class components. This is something we'll want to address in the future, and possible change our API.
* Wrapping the input element in a class component and managing dialog triggers within
* Adding tests
* test cross-browser
* specifically test the `drop-zone-with-custom-file-dialog-trigger` example
</details>

[DropZone] Fixed cross browser security issue

---

src/components/Frame/Frame.tsx
src/components/Modal/Modal.tsx
src/components/Portal/Portal.tsx
src/components/ResourceList/components/BulkActions/BulkActions.tsx
src/components/Scrollable/Scrollable.tsx
src/components/Tooltip/Tooltip.tsx
src/components/TrapFocus/TrapFocus.tsx
src/utilities/sticky-manager/sticky-manager.ts
tsconfig.json

We try to be strict mode compliant but this was disabled. This fixes the
components that fell afoul of that lint. Mostly this is accounting for
refs that may be null
Enable strictPropertyInitialization in our tsconfig
Add correct initializations to properties that were flagged. In most cases this was we were saying a value may be null but actually we never initialized it so it was `undefined`. Initilaizing to null is the fix.
- Ensure Modal still renders as you'd expect
- Ensure a component that uses a portal (like Toast or Popover) still renders its portaled content correctly.
- Ensure sticky managed items still work

Enable strictPropertyInitialization TS config

---

UNRELEASED.md
src/components/TrapFocus/TrapFocus.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

Causing production errors
`return element.querySelector(exports.FOCUSABLE_SELECTOR)`
`write(() => focusFirstFocusableNode(firstNode));`

[TrapFocus] Remove cast

---

src/utilities/i18n/I18n.ts

Don't call toString() on the item in the replacements array as JS can
handle the casting fine itself. This accounts for people passing in a
key of undefined and TS not catching it in consuming apps

Bring back some old type oddness in i18n to help a release

---

UNRELEASED.md
src/components/Filters/Filters.scss

Fixes #2286 
On Safari, there is 2px of `margin-top` and `margin-bottom` being applied to the `FilterTrigger` button in the `Filter` component.
- Added a rule to explicitly set margin to 0 in the `FilterTrigger` class
since there is already no margin on Chrome/FireFox, it seemed like a 
sensible solution to explicitly ensure there is no margin applied regardless
of browser.
- It seemed like overkill to use the `unstyled-button`
mixin so I opted for the single margin rule,
but it could make sense to use the mixin since we want to reset this
button element to an 'unstyled' state.
*Question for Code Owners*:
*What would be the best practice for this Design System in this case? To use the `unstyled-mixin` and removing the duplicated rules such as `background` and `border` or just adding the …

[Filters] Fix FilterTrigger class to clear margins

---

UNRELEASED.md
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.scss

* The range slider currently doesn't have a visible focus state, which is especially noticeable when it is used without the numeric output bubble 
* Removed a class selector from the `SingleThumb` styles which was preventing the focus styles from being applied to the input
* The `.RangeSlider` selector was never used anywhere in the component, and was left over from the before the `DualThumb` component existed
* Added an outline to the entire `SingleThumb` input when focused in high contrast mode
* Updated the `SingleThumb` styles to prevent focus from taking over the error track colour
* This should improve consistency across other input components (e.g. checkbox, select), where it will maintain some error styles but the focused area will receive an indigo outline
* Copied over the focus …

[RangeSlider] Fix range slider focus state

---

UNRELEASED.md
src/components/Tooltip/Tooltip.tsx

[Tooltip] Converted to a functional component

---

.vscode/extensions.json

The story of stylelint in vscode has had a rough month or so.
The original extension we used `shinn.stylelint` was removed as the author no longer supported it, so we switched over to a recent fork `hex-ci.stylelint-plus` as a stopgap. This also triggered the stylelint org to sort out creating an official extension, which was recently published as `stylelint.vscode-stylelint` and is now being actively maintained.
Now there is an official extension, we should use it. It offers a few improvements over the hex-ci fork, most notably it uses the version of stylelint in our project instead of the version bundled with the extension. The new official extension also supports autofixing issues, but we can't use that just yet as it [incorrectly modifies some …

Recommend official stylelint extension

---

UNRELEASED-v5.md
src/components/AppProvider/AppProvider.tsx
src/components/AppProvider/README.md
src/utilities/i18n/I18n.ts
src/utilities/i18n/tests/I18n.test.ts

Previously you had to put the language you wanted at the end of the
array which was not obvious and didn't match the behaviour of
react-i18n.
Now if you pass an array into `<AppProvider i18n>` then the first object
in that array should be your preferred language.
This leads to simpler integration and simpler documentation on our side.
Check tests

[V5] invert translations order in AppProvider i18n

---

src/components/ProgressBar/ProgressBar.scss

Fixes https://github.com/Shopify/polaris-ux/issues/356

[ProgressBar] Applied color system

---

src/components/Tooltip/Tooltip.scss

Part of https://github.com/Shopify/polaris-ux/issues/368
Mockups [here](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/DL%E2%80%93Polaris-(Web)%3A-Components?node-id=2098%3A94).
This introduces the color system to the tooltip.
|-| No theme        | Light mode         | Dark mode  |
|:-:| ------------- |:-------------:| -----|
|Regular tooltip|      ![image](https://user-images.githubusercontent.com/22782157/71740631-bea1cb80-2e2a-11ea-87a2-63d20993be2b.png)  |      ![image](https://user-images.githubusercontent.com/22782157/71740637-c2cde900-2e2a-11ea-904e-e081915c6d60.png)  |   ![image](https://user-images.githubusercontent.com/22782157/71740648-c7929d00-2e2a-11ea-833c-7c24c10ea170.png)  |
|High contrast:|![image](https://user-images.githubusercontent.com/22782157/71740961-99618d00-2e2 …

[Tooltip] Implement color system

---

UNRELEASED.md
src/components/Filters/Filters.tsx
src/components/Filters/tests/Filters.test.tsx

When the Filters components mounts onto the DOM, the `aria-expanded` attribute on the Popover activator is set to `undefined`, which is an invalid value; the `aria-expanded` attribute should be set to either `true` or `false`.
This results in an error when running a Lighthouse accessibility audit on a page that uses the Filters component.
The `aria-expanded` attribute is set to `true` or `false` once a user starts interacting with the Popover activator.
This PR ensures the `aria-expanded` attribute of the Popover activator in the Filters component is always set to either `true` or `false`.
The activator's `aria-expanded` attribute is determined by the `popoverOpen` key of a given action, which is set to the value of ```this.state[`${key}${Suffix.Shortcut}`]``` in the Filters component. …

[Filters] Ensure aria-expanded is not set to undefined on mount

---

UNRELEASED.md
src/components/Stack/Stack.tsx
tests/build.test.js

This open in a tab, will polish and request reviews after hack days.

[Stack] Converted to a functional component

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/utilities/i18n/I18n.ts
src/utilities/i18n/tests/I18n.test.ts

Following up https://github.com/Shopify/polaris-react/pull/2579.
Make passing `{foo: undefined}` into translations replacements a runtime error, in addition to a TS type error for those fun cases where people power through mistyping things using `any` (looking at you enzyme's trigger function that isn't type-safe).
Make TextField's `normalizedValue` be an empty string if you pass anything other than a string into it. Once again this is limited to be a string only by typescript but people using those not-type-safe functions can pass in a number and not be warned. Having normalizedValue be a number mucks up a bunch of things so catch that at runtime too.
Make TextField a little lazier by only working out character count stuff if we're actually about to display it. 
tests pass

Be explict about some i18n oddness around undefined keys, and TextField's value

---

UNRELEASED.md
src/components/Card/README.md

`Card` footer actions are now right aligned by default, but the custom footer example was left aligned.
Wrap the `ButtonGroup` in a `Stack`.

[Card] Custom footer actions example should be right aligned

---

UNRELEASED.md
src/components/Frame/Frame.tsx
src/components/Frame/tests/Frame.test.tsx

There's an issue in production where if any item within the Navigation component has focus and you hit the escape key, the nav will try to hide itself off to the left.
[Screencast](https://screenshot.click/screencast_2020-01-08_15-48-59.mp4)
There's no github issue for this. I randomly stumbled upon it while working on something else.
This pr adds a check to make sure the nav is both active and on a small screen before calling dismiss.
🎩
1. Visit the details page in storybook
1. Click on a nav item
1. While that item is still active, hit escape. Nothing should happen …

[Navigation] Fix navigation hide on key press

---

.storybook/polaris-readme-loader.js
.storybook/webpack.config.js

Previously we used "not-production" because I thought the
babel-plugin-transform-react-constant-elements plugin messed things up,
but it turns out it was my complicated codeInvoker stuff in the readme
loader.
We've actually been using production mode for our source files for aaages so that was never a problem.
This helps prove that said plugin isn't messing up our builds.
This removes the envName config (as webpack will set it to "production"
in production mode automatically), and removes the minified option as
webpack uses Terser in production mode to minify everything anyway so we
don't need Babel doing it too.
The readme loader now requires a manual list of polaris imports that
should be available (just like icons). Eventually it'd be good if
READMEs could have some metadata specifying …

Update storybook to use production babel config

---

UNRELEASED.md
package.json
src/components/KeypressListener/KeypressListener.tsx
src/components/KeypressListener/index.ts
src/components/Modal/components/Dialog/Dialog.scss
src/components/Modal/components/Dialog/Dialog.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/TrapFocus/TrapFocus.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx
src/utilities/focus.ts
src/utilities/tests/focus.test.ts
yarn.lock

Currently, `TrapFocus` does not listen for keyboard events such as tabbing. Instead, it handles what happens _after_ we lose focus of the container (`handleBlur`). The problem with this approach is two things:
- If we focus an element outside of the page (such as the browser's search bar), we can't get focus back to the page contents, even if the `activeElement` is what it should be.
- If we prevent focus from ever leaving the page contents (by removing the check `relatedTarget == null`, then we introduce a bug where we rip focus away from the rest of the page if the container was rendered separately such as in an iFrame (see this PR explaining why this change broke the style guide https://github.com/Shopify/polaris-react/pull/2530)
- Functionalize `TrapFocus` and `KeypressListener`
- …

[TrapFocus] Fix tab focusing

---

UNRELEASED.md
src/components/Popover/Popover.scss
src/components/PositionedOverlay/PositionedOverlay.tsx
src/components/PositionedOverlay/tests/PositionedOverlay.test.tsx
src/components/PositionedOverlay/utilities/math.ts
src/components/Scrollable/Scrollable.scss
src/components/Scrollable/Scrollable.tsx
src/components/TopBar/components/Menu/Menu.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1673
From what I can tell the issue is that the Scrollable scrollbars appear inside the Popover after the PositionOverlay has done its calculations and since the content is responsive, once the scrollbars are added the content wraps. 
For example. If the window is 1000px wide, the overlay 100px wide, the left position will be calculated at 900px. Once the scrollbars appear, the left position does not get recalculated because the content is responsive. The left position pushed the overlay against the right side of the browser and when too close to the chrome causes the content to wrap. This occurs only when the popover is too close to the right of the window. 
This is one of a few attempts at fixing this issue. When a popover has a …

[Popover] Set right position when preferred alignment is right.

---

src/components/ActionMenu/components/MenuAction/MenuAction.scss
src/components/ActionMenu/components/MenuAction/MenuAction.tsx
src/components/ActionMenu/components/MenuAction/tests/MenuAction.test.tsx

Fixes *partly* https://github.com/Shopify/polaris-ux/issues/332
I wasn't sure if I should go with `-p-text/icon` or `-p-text/icon-subdued` and Figma hasn't been updated with `Page` yet. @allylane Johan mentioned you might have the context to answer this. What are your thoughts?

[ActionMenu] Applied color system

---

UNRELEASED.md
package.json
yarn.lock

Keeping up to date
We don't need anything in this, but it helps kick consumers onto the build with better chunking support
Updates polaris-icons version.

Bump polaris-icons version to 3.9.0

---

UNRELEASED.md
src/components/AppProvider/AppProvider.tsx
src/components/Icon/Icon.tsx
src/utilities/telemetry/context.tsx
src/utilities/telemetry/hooks.tsx
src/utilities/telemetry/index.ts

We introduced these changes to gather some data in web about icons usage. We have finished gathering data, so there's no need to keep this code around any longer
Reverts #2368
<details>
```jsx
return ( …
```

Remove unstable telemetry feature added for icons

---

UNRELEASED.md
src/components/TopBar/TopBar.scss
src/components/TopBar/TopBar.tsx
src/components/TopBar/components/Search/Search.scss
src/components/TopBar/components/Search/Search.tsx
src/components/TopBar/components/Search/tests/Search.test.tsx
src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss
src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.tsx
src/components/TopBar/components/SearchDismissOverlay/index.ts
src/components/TopBar/components/SearchDismissOverlay/tests/SearchDismissOverlay.test.tsx
src/components/TopBar/components/index.ts
src/components/TopBar/tests/TopBar.test.tsx

_Updated 10th of December_
Fixes [#10308](https://github.com/Shopify/store/issues/10308) (store)
Fixes [#5219](https://github.com/Shopify/store/issues/5219) (store)
In the `TopBar` component, there is a `Search` component that handles the display of the `searchResults` prop. The `Search` component includes a dismissal overlay, that calls the `onDismiss` prop when you click anywhere on the screen that isn't a part of the search field or search results. Currently this only works in certain areas as the overlay doesn't cover the entire screen space, specifically, there is a dead zone on the left side of the screen.
This PR also introduces a new design featuring a translucent background to the search dismissal overlay whenever the search results container is visible. This feature is behind an …

[TopBar.Search] Fix search dismissal overlay

---

src/components/RangeSlider/RangeSlider.scss
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.scss

Part of https://github.com/Shopify/polaris-ux/issues/358
This PR implements the color system into the `RangeSlider's` track. The reason for this separation is so that we can break the `RangeSlider` into multiple PRs since there are a lot of new changes being applied. The thumb will be modified in a follow up PR.
|     -   |   Light         | Dark |
| ------------- |:-------------:| -----|
|     Regular     |       ![image](https://user-images.githubusercontent.com/22782157/72177381-8b24eb00-33ae-11ea-9340-9236bc96d41a.png) |   ![image](https://user-images.githubusercontent.com/22782157/72177396-90823580-33ae-11ea-86dd-dd77a6bacaf0.png)   |
|        Error      |       ![image](https://user-images.githubusercontent.com/22782157/72177443-ad1e6d80-33ae-11ea-811e-bffe08d64c7e.png)    | …

[Color System] Style the RangeSlider's track

---

UNRELEASED.md
locales/cs.json
locales/da.json
locales/de.json
locales/en.json
locales/es.json
locales/fi.json
locales/fr.json
locales/hi.json
locales/it.json
locales/ja.json
locales/ko.json
locales/ms.json
locales/nb.json
locales/nl.json
locales/pl.json
locales/pt-BR.json
locales/pt-PT.json
locales/sv.json
locales/th.json
locales/tr.json
locales/zh-CN.json
locales/zh-TW.json
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/Button/README.md
src/components/Button/tests/Button.test.tsx
src/styles/shared/_buttons.scss
src/types.ts

There is currently no way to expose merchants to related primary actions in the `ContextualSaveBar` or `Page` `Header` because they only support a single primary action. For example, if the primary action is to save a resource like an order, but you can also save the order as a draft. 
This PR adds support for a split button variant. This is the same UX as the split button you are probably familiar with in Gmail. It renders a disclosure button connected right which toggles a popover action list with related actions.
| Split button | Split button with disclosure active |
|---|---|
|<img width="180" alt="Screen Shot 2019-10-18 at 4 33 15 PM" src="https://user-images.githubusercontent.com/18447883/67127048-81805280-f1c6-11e9-8f65-691222a35d70.png">|<img width="219" alt="Screen Shot …

[Button] add support for split disclosure button

---

src/components/Autocomplete/Autocomplete.tsx
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Badge/Badge.tsx
src/components/Badge/tests/Badge.test.tsx
src/components/ColorPicker/ColorPicker.tsx
src/components/ColorPicker/components/AlphaPicker/AlphaPicker.tsx
src/components/ColorPicker/components/HuePicker/HuePicker.tsx
src/components/ColorPicker/components/Slidable/Slidable.tsx
src/components/Filters/Filters.tsx
src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
src/components/Filters/components/ConnectedFilterControl/tests/ConnectedFilterControl.test.tsx
src/components/Form/Form.tsx
src/components/Popover/Popover.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/PositionedOverlay/PositionedOverlay.tsx
src/components/Stack/Stack.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx

While rumbling through #2625 I found a bunch of cases where our components exported types that either weren't needed outside of that component, or could be made so with a bit of refactoring, and pushing usage towards referencing something living on a Props interface.
This shrinks the amount of exports in a few components.
Note that this has no effect on the types we export publicly - they all remain the same.
Stop exporting a handful of types that weren't used outside that the file they are defined in.
Perform some refactoring so that some types are no longer used outside of the file they are defined in.
A common example is that instead of importing and using `PreferredPosition` from `src/components/PositionedOverlay`, instead import `PositionedOverlayProps` and reference …

Type tidying

---

src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.tsx

Fixes warning notice when building
Use a default import for styles instead of namespace import, like we do everywhere else
Run `yarn run build` and see the following notice messages are no longer present:
```
'SearchDismissOverlay' is not exported by 'build-intermediate/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss'
'visible' is not exported by 'build-intermediate/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss'
```

Use default import for styles

---

UNRELEASED.md
src/components/ThemeProvider/ThemeProvider.tsx
src/utilities/app-bridge/index.ts
src/utilities/features/index.ts
src/utilities/frame/context.ts
src/utilities/frame/index.ts
src/utilities/i18n/index.ts
src/utilities/link/index.ts
src/utilities/media-query/context.tsx
src/utilities/media-query/index.ts
src/utilities/resource-list/context.ts
src/utilities/resource-list/index.ts
src/utilities/scroll-lock-manager/index.ts
src/utilities/scroll-lock-manager/scroll-lock-manager.ts
src/utilities/sticky-manager/index.ts
src/utilities/sticky-manager/sticky-manager.ts
src/utilities/theme/index.ts
src/utilities/unique-id/index.ts

Following on from #2619 and #2625 I looked at the utility index files and spotted that in almost all cases our index files rexport everything in the files they reference, or what they references is never used externally, so they can also use `export *` too.
* Updates utility indexes to use `export *` because doing things one way everywhere is easier than doing things one way in `components` and another way in `utilities`
[I did run into some issues](https://github.com/Shopify/polaris-react/pull/2636/files#diff-4eb03b66a1f37179b50db6bcb635f31cR4) with some interfaces that get used as the type that gets pushed into a React context.
I could either have those as a type or export the interface. I figured exporting the interface was an acceptable compromise as "a slightly leaky internal export …

Use export * in utility indexes too

---

UNRELEASED.md
src/components/DataTable/DataTable.tsx
src/components/DataTable/tests/DataTable.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/2597 
We needed check boxes in our header but it was not supported. (Part of https://github.com/Shopify/store/issues/12522)
Allow the header prop of DataTable to receive and display React Nodes.
<details>
```jsx
import React from "react";
import { Card, DataTable, Page, Button } from "@shopify/polaris"; …
```

[DataTable] Allow JSX in the headers

---

UNRELEASED.md
src/components/Popover/Popover.scss

Fixes https://github.com/Shopify/polaris-react/issues/2605. (You can find all context in the issue)
`PopoverOverlay` changing the container's `display` from `block` to `flex` when it's measuring on subtree change (those changes happen to take place on scroll when a library like react-virtualized is used). This then seems to cause some browsers to stop the scrolling.
The Popover switches its container `display` from `block` to `flex` and vice versa when measuring. 
We wondered why we are switching `display` from `flex` to `block` when measuring and couldn't come up with a good explanation. So in this PR we are attempting to remove it. We did a pairing session with @chloerice where we also tried the custom build in web (looked at user menu and some autocomplete lists) and everything seemed …

[Popover] fix scrolling with scrollbar not working when content changes on scroll

---

UNRELEASED.md
src/styles/shared/_controls.scss

Fixes https://github.com/Shopify/polaris-react/issues/2629
The current version of CRA' s build uses a version of https://github.com/postcss/postcss-custom-properties that crashes when it comes across ~var()s inside calc()s~ a very specific order of calls: `  top:calc(var(--control-border-width)*-1)`. See https://github.com/Shopify/polaris-react/issues/2629#issuecomment-577319704 for more info.  This has been fixed in the newest version of postcss-custom-properties but that's not made its way into CRA (via postcss-preset-env) and probably won't be for some time.
Flip the order of values (yes I know this sounds silly)
Ask @dleroux nicely to see that there are no visual regressions.
- Do a build `yarn run build`
- Create a new CRA project with `yarn create react-app testing`
- Copy the build …

Update sass to work around CRA build crashes

---

UNRELEASED.md
src/components/Tabs/Tabs.scss

Fixes https://github.com/Shopify/store/issues/12366
When tabs have a `url` prop, the styling becomes different because a `a` tag is rendered with a different `visited` styling. The selected tab change color when hovered. It doesn't show the same behaviour when the tab has no `url` prop.
This PR remove the visited state styling to make the behaviour consistent.
<details> …

[Tabs] Remove the visited state styling for tabs with url

---

UNRELEASED.md
src/components/ActionMenu/ActionMenu.tsx
src/components/ActionMenu/tests/ActionMenu.test.tsx
src/components/ActionMenu/tests/utilities.test.ts
src/components/ActionMenu/utilities.ts
src/components/Page/components/Header/Header.tsx
src/types.ts

The Orders team needs to be able to specify the order of their `Page` actions because one of their actions varies from being a `secondaryAction` or an `actionGroup` depending on the status of the order.
Adds support for overriding the order of actions in the action menu. 
<details>
```jsx
import {Page, Thumbnail, Badge} from '../src'; …
```

[ActionMenu] Add support for explicit item order

---

UNRELEASED.md
src/components/DataTable/DataTable.tsx
src/components/DataTable/tests/DataTable.test.tsx

Needed in Web because we are using the DataTable in a modal and the scroll indicator doesn't look very good. 
Adding a prop `showNavigationOnCollapse` (default true), that when false, hides the scroll indicator.
<details>
```jsx
import {Card, DataTable, Page} from '@shopify/polaris';
return (
<Page …
```

[DataTable] Add prop to disable scroll indicator

---

src/components/Checkbox/Checkbox.tsx
src/components/RadioButton/RadioButton.scss
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/tests/RadioButton.test.tsx

partly addresses: https://github.com/Shopify/polaris-ux/issues/357
- Added the proper branding to radio button
- Decided on not using the backdrop mixin. This was added complexity with very little to no benefit as a lot of the stuff needed to be overwritten. Once I'm done all the form elements I will most likely delete the mixin all together as I have a feeling only Checkbox will be using it. 
<details> …

[Radio Button] applying colour system

---

UNRELEASED.md
src/components/Modal/components/Dialog/Dialog.tsx
src/components/TrapFocus/TrapFocus.tsx

Closes https://github.com/Shopify/polaris-react/issues/2644
Moving focus logic into an effect
Example code below
<details>
```jsx
import React, { useState } from "react";
import {
Button,
Card,
Stack,
Modal,
TextContainer,
TextField
} from "../src";
const [open, setOpen] = useState(false);
return (
<div>
<Card sectioned>
<Stack vertical>
<Button onClick={() => setOpen(true)}>Open</Button>
<Modal open={open} onClose={() => setOpen(false)}>
<Modal.Section>
<TextContainer>
<TextField label="test" autoFocus />
</TextContainer>
</Modal.Section>
</Modal>
</Stack>
</Card>
</div>
);
}
```
</details>

Fixed side effects from Dialog

---

scripts/tsconfig.json

Making `tests/built.test.ts` a .ts file means that the package.json gets included in the
esnext directory as part of doing the build. That in turn messes up the
what gets included in the npm package as it redefines the included files
within that folder, which results in most of the files being omitted.
Explicitly ignore the tests directory in the build ts config, so that the tests don't get included. This removes the reference to the package.json so it doesn't get included too, 
- Run `yarn build` then `npm pack` to create local tgz that represents what will be included in the build.
- Open the tgz and inspect the esnext folder and see that the components and utilities folders are present (in contrast with https://unpkg.com/browse/@shopify/polaris@4.12.0-rc.1/esnext/ where these folders …

Remove tests and package.json from compiled esnext directory

---

src/components/TopBar/components/SearchField/SearchField.scss

Before:
After:
I'm not sure what I changed that would have caused this exactly. I just noticed that the input doesn't span the full container width anymore, even though the icon is still pushing it to the right.
<details>
```jsx
return (
{/* Add the …
```

[SearchField] Fix width

---

UNRELEASED.md
src/components/Card/README.md

Removes the term "Isis" from Card examples.
I know that when it's not capitalized it just means an Egyptian goddess, but I don't think that's a distinction that users should have to make.
I simply changed "Isis" to "Oasis" in these examples, to stay on-theme.
This is just a content change.

[Card] Change "Isis" in examples to "Oasis"

---

UNRELEASED.md
locales/cs.json
locales/da.json
locales/de.json
locales/en.json
locales/es.json
locales/fi.json
locales/fr.json
locales/hi.json
locales/it.json
locales/ja.json
locales/ko.json
locales/ms.json
locales/nb.json
locales/nl.json
locales/pl.json
locales/pt-BR.json
locales/pt-PT.json
locales/sv.json
locales/th.json
locales/tr.json
locales/zh-CN.json
locales/zh-TW.json
src/components/DataTable/DataTable.tsx
src/components/DataTable/README.md
src/components/DataTable/tests/DataTable.test.tsx

- Fixes plurality of **Totals** content - the plurality of the **Totals** content is determined by the `totals` array prop that is passed in.
- Adds an optional `totalsMarkupLabel` prop for custom **Totals** content labels on the `<DataTable />` [component](https://github.com/Shopify/polaris-react/tree/master/src/components/DataTable).  
Fixes https://github.com/Shopify/polaris-react/issues/2614.  The **Totals** content was not pluralized initially, and so this PR fixes this initial bug.
It also adds the ability for consumers to pass in a `totalsMarkupLabel` for custom labeling of the **Totals**, using a similar pattern as the `<ResourceList />`.
For example, these are the labels being changed:
| Singular  | Plural  |
|---|---|
| <img width="156" alt="Screen Shot 2020-01-24 at 2 46 05 PM" …

[DataTable] Add optional totalsMarkupLabel prop and fixing Totals plurality

---

src/components/Banner/Banner.scss
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx
src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/tests/Checkbox.test.tsx
src/components/RadioButton/RadioButton.scss
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/tests/RadioButton.test.tsx

Certain elements, when getting the focus ring on focus don't look quite right. There is a CSS selector `focus-visible` that is currently only supported by Firefox that would allow us to show the ring only on keyboard focus. It will take some time for this behavior is available in all our supported browsers.
Currently, Banners, Radio, Checkboxes would benefit from this behavior.
This PR makes use of state to apply the proper style. It would be nice to stick to browser behavior but I think this is an acceptable use of Javascript with very little overhead. **I have not written tests yet, will wait to to see if this is something we want to move forward with first.**
** Percy is complaining about the focus on the banner but I'm thinking something in their rendering is stealing the focus. ** …

[Checkbox, Radio, Banner] Focus ring on tab and not click

---

src/components/Connected/Connected.scss
src/components/TextField/TextField.scss

Part of https://github.com/Shopify/polaris-ux/issues/379
This is applying the color system to the connected state of the `TextField`.
- Caret is colorized
- Button edges are curved when in a connected state

[TextField] Apply color system to connected state

---

.shopify-build/polaris-react.yml

Keeping in sync with polaris-styleguide
Updates the styleguide build container to match https://github.com/Shopify/polaris-styleguide/blob/master/.shopify-build/polaris-styleguide.yml (that's a private repo)

Update container image for styleguide integration test

---

UNRELEASED.md
documentation/Color system.md
src/components/Button/Button.scss
src/components/Checkbox/Checkbox.scss
src/components/RadioButton/RadioButton.scss
src/components/ResourceList/components/CheckableButton/CheckableButton.scss
src/styles/shared/_controls.scss
src/utilities/theme/tokens.ts

Touches on:
https://github.com/Shopify/polaris-ux/issues/371
https://github.com/Shopify/polaris-ux/issues/382
https://github.com/Shopify/polaris-ux/issues/361
For Button this fixes the focus state of outline monochrome buttons (Not .globalTheming hence the change log entry)
For Split Button this fixes the focus ring
For Checkable Button this fixes the alignment of the checkbox which was off by a few pixels
For ButtonGroup and BulkActions this fixes the focus ring
- Top hat using the playground:
1. Button focus states with and without enabling theming.
2. BulkActions and Button Group 
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentati …

[Checkable Button, Button and ButtonGroup, BulkAction] apply design language

---

src/styles/foundation/_focus-ring.scss

Fixes this [Sass build error](https://buildkite.com/shopify/polaris-styleguide/builds/77#d3f3c745-0992-438b-bc25-e2cda12c72fd) 
Ran build consumer for the style guide and then did a production build of the style guide locally and no errors 👍 
@kyledurand need your 👀 to make sure the focus ring still works as expected 🙏 

[Design Lang 🎨] Fix focus-ring Sass compile error

---

src/components/Select/Select.scss
src/components/Select/Select.tsx
src/components/Select/tests/Select.test.tsx

**Design still pending, no need to review until [WIP] is removed**
partly addresses: https://github.com/Shopify/polaris-ux/issues/363
Applying design language to Select. Current Select shouldn't be affected.
I'm also removing the Design Language modification from Backdrop. Once we roll this out, we'll be able to delete that mixin.
The icons have not been updated. My understanding is that these will be updated when icons get updated.
<details> …

[Select] Apply design language to Select

---

UNRELEASED.md
src/styles/shared/_buttons.scss

High contrast for button https://github.com/Shopify/polaris-ux/issues/371
Add high contrast border to button.
**Button**
**Button hovered**
**Button focused**

High contrast border for button

---

documentation/Color system.md
playground/DetailsPage.tsx
src/components/Frame/Frame.scss
src/components/Frame/Frame.tsx
src/components/Frame/components/CSSAnimation/CSSAnimation.scss
src/components/Frame/components/CSSAnimation/CSSAnimation.tsx
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
src/components/Frame/tests/Frame.test.tsx
src/utilities/theme/tokens.ts

Fixes https://github.com/Shopify/polaris-ux/issues/344
1. Hit the details page in storybook
1. Type something into the product title field
1. Dismiss the save bar
Make sure both fade up and in and fade out and down look alright

[ContextualSaveBar] Apply design language

---

UNRELEASED.md
src/components/ActionList/ActionList.scss

Fixes high contrast for https://github.com/Shopify/polaris-ux/issues/332
Adding outline to hovered items in action list
**Default button**
**Hovered button**
**Open action list**
**Hovered item in action list**

High contrast actionlist hover

---

UNRELEASED.md
src/components/Modal/components/Dialog/Dialog.scss

There is currently an issue with the Modal's width as it doesn't take into account the scroll bar when visible.
I've changed the value from `vw` to `%` as this one take the scroll bar into account

[Modal] Fix container's width

---

src/components/RadioButton/RadioButton.scss
src/styles/shared/_controls.scss

The radio button wasn't displaying a checked state. This was because a background-color was being set on a pseudo element for high contrast mode, but high contrast mode ignores background rules. To fix this I changed `background` to a `border` that is wide enough to fill the radio.
The checkbox was a little simpler. The border was being removed on checked which I felt a little strange so I added one for the checked state.
<details> …

[Radio, Checkbox] Fix high contrast mode

---

src/components/Navigation/components/Section/Section.tsx

This avoids having an Collapsible id that increments on every rerender
of the Navigation.Section
Replace createUniqueIDFactory usage with useUniqueId();
The following playground has a toy in it that triggers a rerender once a second to make the Navigation.Section rerender.
Find the `Collapsible` component that renders by as part of the Navigation rollup by running `document.querySelector('[class^=Collapsible-Collapsible]')` in your console.
Note that the id of the Collapsible div remains constant across multiple rerenders (compare this with master where the id increments on each render).
Note: the id will be "PolarisAdditionalItems2" not "PolarisAdditionalItems1" because by default the playground renders in strict mode which [double invokes render …

Navigation.Section: Use useUniqueId

---

src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Addresses https://github.com/Shopify/polaris-ux/issues/379
- Modifies the border radius of the `Backdrop` when there are connected elements
<details>
```jsx
return (
</Page>
);
}
```
</details>

[TextField] Flatten focus ring on connected TextField

---

UNRELEASED.md
src/components/Select/Select.scss

Fixes the `Select` from appearing like,
In [this commit](https://github.com/Shopify/polaris-react/commit/1be5ea13e0816026da8d268d43738a89aabe44cb#diff-5d08ed568b63ab57718732512bd1058fR152) the order of the position property was moved above the focus ring mixin.
Since the focus ring applies a relative position when it is not focused, this was overwriting the position value for the `Select` component's `Backdrop`.
<details>
<summary>Copy-paste …

[Select] Fix position being overwritten by the focus ring

---

UNRELEASED.md
src/components/ResourceItem/ResourceItem.scss
src/components/ResourceItem/ResourceItem.tsx
src/components/ResourceItem/tests/ResourceItem.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/2727
1. Ensures the right position of the Actions is correct.
2. Changes focus state on MouseOut
<details>
```jsx
return (
</Page>
);
}
```
</details>

[ResourceList] Fix persistent Action on MouseOut

---

UNRELEASED.md
src/components/Avatar/Avatar.tsx
src/components/Avatar/tests/Avatar-ssr.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1419 
In every project that uses/renders the Avatar component on server and client, we get a React warning about the initial rendering not being equal.
While mismatches in server-rendered in client-rendered results usually don't seem to be as much of an issue anymore as of react 16, they can be if nodes are missing in the server-rendered output, which I think is precisely the case here.
> Also, React 16 is better at hydrating server-rendered HTML once it reaches the client. It no longer requires the initial render to exactly match the result from the server.
**However, it's dangerous to have missing nodes on the server render as this might cause sibling nodes to be created with incorrect attributes.** …

[Avatar] fix initial server / client render mismatch

---

UNRELEASED.md
src/components/Card/tests/Card.test.tsx
src/components/Popover/Popover.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
src/components/Popover/tests/Popover.test.tsx
src/components/PositionedOverlay/PositionedOverlay.tsx
src/components/PositionedOverlay/tests/PositionedOverlay.test.tsx

Co-authored-by: Robin Drexler <robin.drexler@shopify.com>
Fixes https://github.com/Shopify/polaris-react/issues/2752
Fixes https://github.com/Shopify/polaris-react/issues/1415
When the activator of a Popover (or PositonedOverlay) contains an input element, the Overlay always uses said element to calculate its position and width/height.
Introduces a `preferInputActivator` prop to the `Popover` (and hence `PositonedOverlay` component). This prop would be `true` by default to not introduce a breaking change. 
When it's `true`, the behavior does not change. The Overlay will continue to search for an `input`, and if it finds one, use it.  If the consumer sets the prop to `false`, the Overlay will never search for an `input` and always use the `activator` to calculate its dimensions.
🖥 [Local …

[Popover] Add preferInputActivator prop to Popover

---

src/styles/_common.scss
src/styles/foundation/_accessibility.scss
src/styles/foundation/_focus-ring.scss
src/styles/shared/_accessibility.scss

*accessibility*
* Creating a mixin to apply outline in windows high contrast
View focus states in windows high contrast

Added high contrast outline to focus ring mixin

---

UNRELEASED.md
src/components/index.ts

Wanting to reference the type of an OptionList prop we noticed that OptionListProps wasn't being exported. Looking at `src/components/index.ts` it's seemingly just an omission since the props type of other components are exported.
`OptionsListProps` is added to the exports.

[OptionList] Export OptionListProps

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx
src/components/DropZone/README.md
src/components/DropZone/tests/DropZone.test.tsx

Fix https://github.com/Shopify/polaris-react/issues/1860
Fix https://github.com/Shopify/polaris-react/issues/2621
Fix https://github.com/Shopify/polaris-react/issues/1229
Fix https://github.com/Shopify/store/issues/13016
Removes the `numFiles` state variable. This variable was being used to check if multiple files had already been uploaded and accordingly block the dropzone from allowing more files to be uploaded. From reading the issues, it seems this blocking behaviour is unwanted and should be instead handled outside of the component if needed.
📄 [Changelog …

[DropZone] Allow changing the file if allowMultiple={false} 

---

UNRELEASED.md
src/components/Pagination/Pagination.scss
src/components/Pagination/Pagination.tsx

Fixes https://github.com/Shopify/polaris-react/issues/2745 
Properly styling the buttons even if there is a tooltip wrapper on one of them
|Before|After|
|-|-|
|<img width="448" alt="image" src="https://user-images.githubusercontent.com/21130966/75187929-297bce80-5719-11ea-8637-65532c6e6f47.png">|<img width="431" alt="image" src="https://user-images.githubusercontent.com/21130966/75187997-53cd8c00-5719-11ea-82da-85e7516c6856.png">|
Make sure …

[Pagination] Fix sizing on small screens when they have tooltips

---

src/components/RangeSlider/RangeSlider.scss
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
src/utilities/theme/tokens.ts

Part of https://github.com/Shopify/polaris-ux/issues/358
This applies the color system to the `RangeSlider's` thumb and output bubble (everything else except the track).
Some noticeable differences:
- The thumb size changes depending on if its active or not
- The output bubble only displays when the thumb is active
| Light        | Dark           |
|  ![image](https://user-images.githubusercontent.com/22782157/73105006-d0284180-3ec5-11ea-91c9-8f5831094bd2.png)  |  ![image](https://user-images.githubusercontent.com/22782157/73105014-d4ecf580-3ec5-11ea-925b-c6b9fdeb688c.png) |
| Light        | Dark           |
|  ![image](https://user-images.githubusercontent.com/22782157/73105034-e7672f00-3ec5-11ea-8d93-18ecd4d0c1c1.png) | …

[RangeSlider] Apply color system to thumb

---

package.json
src/utilities/theme/types.ts
src/utilities/theme/utils.ts
yarn.lock

If needed, gives 100% control over color via the blessed path. Fixes https://github.com/Shopify/polaris-ux/issues/399
Adding a `config` prop on the `ThemeProvider` and merging its value with the base config from Polaris Tokens. This either overwrites existing variants or adds new ones.
Allows for very custom color like the gif below while adhering to the color system fundamentals.
```tsx
<ThemeProvider
theme={{
colors: {primary: '#d0f224'},
config: {
primary: [
{
name: 'actionPrimary',
light: {lightness: 90.3},
dark: {lightness: 90.3},
},
{
name: 'actionPrimaryHovered',
light: {lightness: 81.3},
dark: {lightness: 81.3},
},
{
name: 'actionPrimaryPressed',
light: {lightness: 72.3},
dark: {lightness: 72.3},
},
{
name: 'textOnPrimary',
light: {lightness: 0},
dark: {lightness: 0},
},
],
},
}} …
```

[ThemeProvider] Allow passing in a custom config

---

src/components/Filters/Filters.scss

linear-gradients can cause performance issues in safari

Removed linear-gradient from var

---

UNRELEASED.md
src/components/Card/Card.scss
src/components/Indicator/Indicator.scss
src/components/OptionList/components/Checkbox/Checkbox.scss
src/components/OptionList/components/Option/Option.scss
src/components/Popover/Popover.scss
src/components/ResourceList/components/CheckableButton/CheckableButton.scss

Fixes minor issues with Popover, Card
Applies high contrast to the indicator, checkable button, option list
**Bulk actions and checkable button**
**indicator**
**popover**
**card**
**option list**
<details>
```jsx
return (
{/* Add the code you want to …
```

[Various component] Add high contrast to design language

---

src/components/ActionMenu/components/MenuAction/MenuAction.scss
src/components/DropZone/DropZone.scss
src/components/Filters/Filters.scss
src/components/Pagination/Pagination.scss
src/components/Tag/Tag.scss
src/styles/shared/_buttons.scss

New design language project
Adding high contrast outlines
- You may notice a blue outline, inside a white outline. This blue outline is only shown in chromium edge, so we need the white outline as well for backward compatibility.

[Dropzone][Filters][Tag][Pagination][PageActions] Fixed high contrast issues

---

src/components/Button/Button.scss
src/components/Frame/components/Toast/Toast.scss
src/components/Icon/Icon.scss
src/components/Icon/Icon.tsx
src/components/Icon/tests/Icon.test.tsx
src/types.ts

Addresses: https://github.com/Shopify/polaris-ux/issues/348
Updates the `Icon` component to consume the new design language. It adds the following as new color options:
- `base` : default in new design language
- `subdued`
- `critical`
- `warning`
- `highlight`
- `success`
- `primary`
And aliases all old design language color options to logical equivalents in the new design language.
- decided to remove the interaction-state-related color options
- decided to alias sky and white to `subdued`, ink and black to `base`, and purple to `highlight`
- if we have second thoughts after this is merged, we can always change without it being considered breaking
- decided on using `--p-surface`
- decided this is the right decision
|old design language|new design language - light|new design language - …

[Color system] Icon

---

UNRELEASED.md
src/components/Popover/Popover.tsx
src/components/Popover/set-activator-attributes.ts
src/components/Popover/tests/Popover.test.tsx
src/components/Popover/tests/set-activator-attributes.test.ts
src/utilities/focus.ts

Currently, the `Popover` sets accessibility attributes on either the activator (if focusable) or the element it wraps the activator with. If the activator is not focusable because it is disabled, the activator's wrapper gets these attributes. This is a problem because the activator wrapper is a `div` (unless the `activatorWrapper` prop is set to something else) and the `div` having a `tabIndex="-1"` makes it focusable ironically! 
A good example of this can be seen in the "All filters disabled" `Filters` example. When viewing the playground code on `master`, you can view the unwanted attributes being set on and staying set on the wrapper `div` after toggling the disabled state of the filters.
- Uses a version of the `findFirstFocusableNode` utility that doesn't eliminate disabled …

[Popover] Prevent setting a11y attributes when activator disabled 

---

UNRELEASED.md
src/components/ResourceItem/README.md
src/components/ResourceItem/ResourceItem.scss
src/components/ResourceItem/ResourceItem.tsx
src/components/ResourceItem/tests/ResourceItem.test.tsx

Alignment of the `<ResourceItem>` content is slightly inconsistent. While the main content is center aligned all the other components like the checkbox, media and shortcut actions are set to `flex-start`.
I would suggest to center align all of the items, or maybe in the future enable the consumers to choose the alignment.
An issue have been reported on the product details page:
Sandbox example:
https://codesandbox.io/s/patient-platform-43qls?fontsize=14&hidenavigation=1&theme=dark
This PR would enable the consumers to change the vertical item alignment of the main container, keeping the default alignment with the current flex-start.
Before: 
After adding the `alignment="center"` property
Before:
After adding the `alignment="center"` property …

[ResourceItem] Fix vertical alignment of checkbox and media

---

.storybook/polaris-readme-loader.js
.storybook/preview.js
UNRELEASED.md

Unblocks #2756. Some examples already contain an AppProvider so we want to omit the AppProvider added by the contexts decorator.
Creates an omit list for components’ stories which already have AppProvider’s in their examples. This applies to certain "All examples" stories, too. There were also a few other "All examples" stories which we should never have rendered like top bar, sheet, loading, etc which have fixed position elements thus the elements in each story were stacking on top of each other.
This is a step forward in the quality of stories, although a better solution would remove the "New Design Language" context for stories which don’t support it. That requires some extra hoop jumping and given the temporary nature of the "New Design Language" context, I opted for a minimally …

Omit AppProvider from some examples

---

UNRELEASED.md
src/components/Card/Card.scss

This addresses #2662. 
It changes the `overflow` on the Card component to `visible` by default.
<details>
```jsx
import {Page, Layout, Card, List} from '../src';
return (
<Layout>
<Layout.Section>
<Card title="Staff accounts">
<Card.Section>
<List>
<List.Item>Felix …
```

[Card] Removes overflow hidden

---

src/components/Button/README.md

The example currently does not render well when the button dropdown is clicked, as it renders past the boundaries of the host div, and is obscured. Due to this, it appears that the button is broken and does nothing.
This follows the pattern in <Autocomplete />'s README and hosts the example in a div with enough height.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/8219340/75488682-cab78e80-597e-11ea-9d9e-00750d817dbf.png)|![image](https://user-images.githubusercontent.com/8219340/75488607-abb8fc80-597e-11ea-991d-7476fd0d411e.png)|

[Button] Nest split button example in tall enough <div>

---

scripts/build-consumer.js

If a developer is following the instructions in the ["Tophatting Documentation" guide](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md), but has never run `dev up` on `Shopify/polaris-styleguide`, an error will occur, but the build script will continue as if everything is fine.
```
Cleaning up old build...
Creating new build directory...
mkdir: no such file or directory: /Users/sambostock/src/github.com/Shopify/polaris-styleguide/node_modules/@shopify
Copying build to node_modules...
cp: dest is not a directory (too many sources)
Build copied to consuming project. You can now run the consuming app and it will include your changes from Polaris.
✨  Done in 50.34s.
```
This enables the `config.fatal` setting for `shelljs`, so errors are noisy, …

Improve build-consumer.js' robustness

---

src/components/DatePicker/DatePicker.scss

Design language rollout
Applying high contrast values to datepicker
View gif (& |) run high contrast mode on windows

Added support for high contrast to datepicker

---

.storybook/polaris-readme-loader.js
.storybook/preview.js
UNRELEASED.md
documentation/Component READMEs.md
src/components/AppProvider/README.md
src/components/ContextualSaveBar/README.md
src/components/Frame/README.md
src/components/TopBar/README.md

To conditionally render an `AppProvider` around examples, which is needed for https://github.com/Shopify/polaris-react/pull/2756 otherwise examples are broken.
Switches to a front matter concept using `omitAppProvider` in the component README. This front matter is then used for both Storybook and the Style Guide.

introduce omitAppProvider front matter

---

.storybook/polaris-readme-loader.js
src/components/AppProvider/README.md
src/components/ThemeProvider/README.md

|:tophat:|
|-|
|![screencapture-polaris-myshopify-io-components-structure-theme-provider-2020-02-19-10_04_07](https://user-images.githubusercontent.com/1403188/74846967-60a84500-52ff-11ea-9a06-cbc8a60b78d6.png)|

[Color system] add theme provider readme

---

src/components/KeyboardKey/KeyboardKey.scss

|Old DL|New DL - light|New DL - dark|
|-|-|-|
|<img width="39" alt="Screen Shot 2020-03-10 at 10 28 30 AM" src="https://user-images.githubusercontent.com/1403188/76322742-24db1c80-62ba-11ea-9c69-015805d58a98.png">|<img width="39" alt="Screen Shot 2020-03-10 at 10 28 35 AM" src="https://user-images.githubusercontent.com/1403188/76322761-2b699400-62ba-11ea-9aa0-2efbc1432cad.png">|<img width="43" alt="Screen Shot 2020-03-10 at 10 28 41 AM" src="https://user-images.githubusercontent.com/1403188/76322785-315f7500-62ba-11ea-8598-7a85e9c59526.png">|
Addresses https://github.com/Shopify/polaris-ux/issues/402

[Color system] consume design language in keyboard key

---

src/components/FooterHelp/FooterHelp.scss
src/components/FooterHelp/FooterHelp.tsx
src/components/FooterHelp/tests/FooterHelp.test.tsx

|Old DL|New DL - light|New DL - dark|New DL - box
|-|-|-|-|
|<img width="457" alt="Screen Shot 2020-03-10 at 10 11 34 AM" src="https://user-images.githubusercontent.com/1403188/76320971-c6ad3a00-62b7-11ea-8381-6593802f6cc9.png">|<img width="387" alt="Screen Shot 2020-03-10 at 10 11 08 AM" src="https://user-images.githubusercontent.com/1403188/76321000-d298fc00-62b7-11ea-89b9-4fbcb48aa91b.png">|<img width="444" alt="Screen Shot 2020-03-10 at 10 11 46 AM" src="https://user-images.githubusercontent.com/1403188/76321058-e2b0db80-62b7-11ea-9d9a-1622706d7203.png">|<img width="572" alt="Screen Shot 2020-03-10 at 10 11 17 AM" src="https://user-images.githubusercontent.com/1403188/76321088-ec3a4380-62b7-11ea-8d8a-3fb5f635b0e8.png">|
Figma: …

[Color system] consume new design language in footer help

---

UNRELEASED.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/tests/Autocomplete.test.tsx

Because of unexpected search options result was displayed like unexpected options result or duplicated options (see animation below).
Fixes #2764 
Prevents passed component props mutation.
<details>
```jsx
return ( …
```

[ComboBox]: prevent component props mutation.

---

UNRELEASED.md
src/components/Tag/README.md
src/components/Tag/Tag.scss
src/components/Tag/Tag.tsx
src/components/Tag/tests/Tag.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/2772
Exposing an optional `onClick` handler to enable consumers to handle tag actions differently than an explicit remove.  
Because `onRemove` is optional, it had to be prioritized for backwards compatibility.
cc @tmlayton for design language 🌈 👀 and @sarahill for UI Kit  🖌🎨👀 
|Current|Light mode|Dark mode|
|---|---|---|
|<img width="389" alt="Screen Shot 2020-03-03 at 4 38 45 PM" src="https://user-images.githubusercontent.com/18447883/75822270-b522da00-5d6d-11ea-8ee5-6019359629bb.png">|<img width="384" alt="Screen Shot 2020-03-03 at 4 38 13 PM" src="https://user-images.githubusercontent.com/18447883/75822285-bbb15180-5d6d-11ea-95a8-d28fe8530277.png">|<img width="389" alt="Screen Shot 2020-03-03 at 4 38 33 PM" …

[Tag] Add optional onClick handler prop

---

UNRELEASED.md
src/components/TextField/TextField.tsx

There is a redundant `null` check in `<TextField />`'s `normalizeAutocomplete` function. It should already be covered by
```typescript
else {
return autocomplete;
}
```
The redundant condition is removed.

[TextField] Remove redundant null check

---

src/components/Button/Button.scss
src/styles/shared/_buttons.scss

Addresses https://github.com/Shopify/polaris-ux/issues/371
What should happen to a `depressed` button when it's hovered or pressed? For this PR, I have made it so that there is no change. Is this correct? My understanding is that when buttons are in a depressed state, they are as far in as they will go, and they do not move (go to another state) until they are clicked, at which point they are released.
In the old design language, depressed buttons get a slight background color change when hovered or pressed.
- **Storybook**: https://5d559397bae39100201eedc1-udltheedvy.chromatic.com/iframe.html?id=all-components-button--pressed-button&contexts=New%20Design%20Language=Enabled%20-%20Light%20Mode
- **Figma**: https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/DL%E2%80%93Polaris-(Web)%3A-Compone …

[Color system] add depressed states for button in new design language

---

UNRELEASED.md
src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/README.md
src/components/Collapsible/tests/Collapsible.test.tsx

This will be a major part of adding animation to the navigation component: https://github.com/Shopify/polaris-react/pull/2796
☝️ This will be ready for review shortly after this merges
[Screencast](https://screenshot.click/screencast_2020-03-13_11-05-15.mp4)
This adds a `transition` prop to collapsible which takes `duration` and `timingFunction` to allow consumers to tailor the transition to their needs.
<details>
<summary>Copy-paste this code …

[Collapsible] Add transition properties

---

UNRELEASED.md
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx

Replacing type assertion with type check introduced a small issue in case of the `<PopoverOverlay /> ` click handler. 
If the target element is an SVGElement the descendent check is not even invoked and the Popover get's closed similarly when you click outside of it.
Reported issue:
https://github.com/Shopify/web/issues/24540
Partially reverting changes from #2638 
<details> …

[Popover] Revert to type assertion to handle SVGElements

---

CHANGELOG.md
UNRELEASED.md

Want to get this out mainly for https://github.com/Shopify/polaris-react/pull/2827 and to get Shopify Web back on the latest.

Prep v4.16.0

---

src/components/Frame/Frame.scss

Fixes an issue where the contextual save bar doesn't span full width when no nav is present and new design language is true
Comment out line 528 in `DetailsPage.tsx`
`// navigation={navigationMarkup}` and type into the first text input box on the page: `Title`

[Contextual save bar] Full width when no Navigation is present

---

src/components/Navigation/Navigation.scss
src/components/Navigation/_variables.scss
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx

This addresses the issue where the nav items were receiving a focus state on click. Now the ring only appears on tab
[Screencast](https://screenshot.click/screencast_2020-03-12_23-19-36.mp4)
I'm setting state when the item receives a key up and the key is tab. The state adds a class which is then removed on blur.
Run locally and visit the [details page](http://localhost:6006/iframe.html?id=playground-playground--details-page&contexts=New%20Design%20Language=Enabled%20-%20Light%20Mode)

[Navigation] Only focus items on tab

---

src/components/Navigation/Navigation.scss
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Item/components/Secondary/Secondary.tsx
src/components/Navigation/components/Item/components/Secondary/tests/Secondary.test.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx

This is a WIP until part 1 is merged: https://github.com/Shopify/polaris-react/pull/2789
[Screencast](https://screenshot.click/screencast_2020-03-13_14-16-01.mp4)
Adding animation to collapsible componennt
<details>
```jsx
return (
{/* Add the code …
```

[Navigation] Design language animation

---

examples/next.js/next.config.js
examples/next.js/package.json
examples/next.js/yarn.lock

I like net negative diffs.
Since 9.2 next.js supports css imports out the box, so we don't need the
zeit/next-css package or any of its config anymore in the next.js example
Deleting things
- `cd examples/next.js`
- `yarn install && yarn server`
- open in a browser (link will be in your console), and see that the example still renders

Simplify next.js example

---

src/components/Navigation/Navigation.scss

Fixes: https://github.com/Shopify/polaris-ux/issues/404
Chose min-height over height for apps or channels that might want to show more content or a larger logo
What this change will look like in production:

[Navigation] Add min-height to context control wrapper

---

documentation/Color system.md
package.json
src/components/Banner/Banner.scss
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx
src/components/Button/Button.scss
src/utilities/theme/tokens.ts
yarn.lock

- adds filled icons for new design language
- updates border and background color for new design language
- updates spacing for new design language
Addresses https://github.com/Shopify/polaris-ux/issues/381
Figma: https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/DL%E2%80%93Polaris-(Web)%3A-Components?node-id=20%3A22
|:tophat:|
|-|
|<img width="995" alt="Screen Shot 2020-03-17 at 1 02 45 PM" src="https://user-images.githubusercontent.com/1403188/76881899-3a1ef080-6850-11ea-8809-84793eff110c.png">|
|<img width="997" alt="Screen Shot 2020-03-17 at 1 03 16 PM" src="https://user-images.githubusercontent.com/1403188/76882062-7c483200-6850-11ea-86a7-b82d453384b5.png">|
|<img width="995" alt="Screen Shot 2020-03-17 at 1 03 01 PM" src="https://user-images.githubusercontent.com/1403188/76881949-502 …

[Color system] finish applying new design language to banner component

---

UNRELEASED.md
src/components/Tag/Tag.scss
src/components/Tag/Tag.tsx

On the `<Tag />` [component](https://polaris.shopify.com/components/forms/tag), when no props are passed, the styling for the padding is missing on the right side.
[Can be seen on the sandbox](https://codesandbox.io/s/twelv?module=App.js)
This PR adds a padding to the base `Tag` so that it has an even styling, and removes padding when a `Tag` is removable to not have right padding when there is an `<Icon />`.
|  Before |  After |
|---|---|
|<img width="89" alt="Screen Shot 2020-03-19 at 10 56 19 AM" src="https://user-images.githubusercontent.com/5506721/77081060-7711f100-69d0-11ea-808a-19d11ad2a25a.png">| <img width="101" alt="Screen Shot 2020-03-19 at 10 56 31 AM" src="https://user-images.githubusercontent.com/5506721/77081076-7bd6a500-69d0-11ea-91dc-303995ade0e7.png">|
🖥 [Local …

[Tag] Fixing styling of base Tag padding

---

UNRELEASED.md
src/components/Navigation/Navigation.scss
src/components/Navigation/components/Item/Item.tsx

Fixes https://github.com/Shopify/destinations/issues/569
This removes unnecessary margin for secondary navigation when no icon is present.
Before:
After:
Comment out all the icons in DetailsPage.tsx

[Navigation] Fix secondary navigation spacing when no icon is present

---

documentation/Color system.md
src/components/ActionMenu/ActionMenu.scss
src/components/ActionMenu/ActionMenu.tsx
src/components/ActionMenu/components/MenuAction/MenuAction.scss
src/components/ActionMenu/components/MenuAction/MenuAction.tsx
src/components/ActionMenu/components/MenuAction/tests/MenuAction.test.tsx
src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx
src/components/ActionMenu/components/MenuGroup/tests/MenuGroup.test.tsx
src/components/ActionMenu/components/RollupActions/RollupActions.tsx
src/components/ActionMenu/tests/ActionMenu.test.tsx
src/components/Badge/Badge.scss
src/components/Breadcrumbs/Breadcrumbs.scss
src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx
src/components/Button/Button.scss
src/components/Page/README.md
src/components/Page/components/Header/Header.scss
src/components/Page/components/Header/Header.tsx
src/components/Page/components/Header/components/Title/Title.scss
src/components/Page/components/Header/components/Title/Title.tsx
src/components/Page/components/Header/components/Title/tests/Title.test.tsx
src/components/Page/components/Header/tests/Header.test.tsx
src/components/Pagination/Pagination.scss
src/components/Pagination/Pagination.tsx
src/components/Pagination/tests/Pagination.test.tsx
src/components/ResourceList/components/CheckableButton/CheckableButton.scss
src/styles/shared/_page.scss
src/utilities/components.tsx
src/utilities/theme/tokens.ts

Part of https://github.com/Shopify/polaris-ux/issues/415
|Design|Actual|
|---|---|
|<img height="600" src="https://user-images.githubusercontent.com/344839/77625508-f176cf80-6f00-11ea-995b-c54d1bd9da96.png">|<img src="https://user-images.githubusercontent.com/344839/77625193-64cc1180-6f00-11ea-8fab-8cbcf56102e2.png" height="600">|
|Design|Actual|
|---|---|
|<img height="600" src="https://user-images.githubusercontent.com/344839/77625480-e58b0d80-6f00-11ea-915e-54d8044f985e.png">|<img src="https://user-images.githubusercontent.com/344839/77625224-6f86a680-6f00-11ea-9c22-dad77500b531.png" height="600">|
Applies the design language to the `Page` component while keeping the existing page component visually unchanged.
- Uses button and button group subcomponents instead of custom CSS
- …

[Page] Apply design language

---

UNRELEASED.md
package.json
scripts/build.js
tests/build.test.ts
tsconfig.json
yarn.lock

We want to use new and shiny typescript features. But some of our consumers are on old versions and won't understand the type definition files that use new features, which will cause them to fail. Using [`downlevel-dts`](https://github.com/sandersn/downlevel-dts) we can generate multiple type versions, so that consuming apps using older versions can receive and use type definitions that they understand, while we get to use the new shiny.
An example of this new shiny is `export type` as introduced in 3.8.
- Stop moving types from `types/src` to `types/` - TS generates those files at that location, let's just use it.
- Use `downlevel-dts` to generate types compatible with older TS version. The lowest it goes is 3.4 so let's use that.
- Update our types and typeVersions specifications in …

Support consumers using older TS versions

---

.storybook/preview.js
UNRELEASED.md
playground/DetailsPage.tsx
src/components/Frame/Frame.scss
src/components/Frame/README.md
src/utilities/custom-properties/custom-properties.ts
src/utilities/theme/tests/utils.test.ts
src/utilities/theme/types.ts
src/utilities/theme/utils.ts

Fixes https://github.com/Shopify/destinations/issues/664
This adds space for consumers to add either a secondary nav, or a completely new nav altogether
This adds a `frameOffset` property to the theme provider which generates a custom property that is used to push the frame and its sub components to the right by the pixel value provided.
Here's the details page with frame offset and global ribbon. 
1. Tophat by removing context control from …

[Frame] add offset prop and pass it through theme provider

---

UNRELEASED.md
src/components/Form/Form.tsx

This PR fixes two typo errors in the `Form` documentation string.
There were two typo errors. It's better to fix them.

[Form] Fix two typo errors

---

UNRELEASED.md
src/components/TopBar/TopBar.scss

When the user has a white TopBar the navigation icon is not visible when using the mobile navigation. This PR makes the navigation icon color the same as the search icon color, allowing it to be updated by the topbar theme. This will also fix https://github.com/Shopify/destinations/issues/744 when merged in web.
Makes the navigation icon use the same color as the search icon.
Open this Playground on a mobile device. Change the text color, the navigation icon should change.
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Ver …

TopBar icon color to use the same icon color as search

---

README.md
UNRELEASED.md
package.json
src/components/README.md
src/components/ResourceList/components/FilterControl/index.ts
src/components/ResourceList/index.ts
src/utilities/features/index.ts
src/utilities/frame/index.ts
src/utilities/link/index.ts
src/utilities/resource-list/index.ts

Partial fix for #2896
Web needed some wrangling because we try to import empty files in esnext - this is because those files contained types but they all go stripped away during the build. Let's make sure we don't try to reference empty files so consuming apps complain about us doing so
- Don't use export * for files that contain only types, as this may cause issues where you try and `export *` from a types-only file and that will result in the export not being elided
We want to get this change out ASAP so we unblock other consumers from updating.
The long-term fix is to urn on `importsNotUsedAsValues: error` in tsconfig.json, which will force us to use `import type`/`export type` when referring to types, which makes these import get elided.
Cut a beta release, and try and use it in web …

Fix unexpected module shaking issues

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

I'm currently working on a component that I would like to have utilize everything ResourceList has to offer but I don't need the select all functionality.
- It makes `showHeader` an optional prop that is either a boolean or undefined 
- It doesn't render a header if you set `showHeader` to `false` explicitly 
1. Render a `ResourceList` like this
```tsx
<ResourceList
showHeader={false}
selectable
items={items}
renderItem={renderItem}
/>
```
2. Without the changes in this PR it will render a header. With the changes it this PR it will not.
<details>
```jsx
import {
Page,
ResourceList,
ResourceItem,
Card,
Avatar,
TextStyle,
return ( …
```

[ResourceList] hides header if showHeader is false

---

UNRELEASED.md
src/components/TopBar/README.md
src/components/TopBar/TopBar.scss
src/components/TopBar/components/Menu/Menu.scss

Currently we hide the `secondaryMenu` in the top bar on small screens. We need to use this for a feature we are working on, but it needs to show on small screens too.
This PR removes the styles on the secondary menu that was hiding it at a breakpoint. I also added an example to the `TopBar` readme.
This is what it looks like now:
Look at the [example in storybook](http://localhost:6006/?path=/story/all-components-top-bar--top-bar-with-all-of-its-elements) on a small screen and make sure the menu still shows.

[TopBar] Show secondary menu on small screens

---

UNRELEASED.md
src/components/MediaCard/MediaCard.scss
src/components/VideoThumbnail/VideoThumbnail.scss

Fixes minor visual bug with VideoThumbnail
Adds a top left and right border-radius to the image in the VideoThumbnail
Look at the VideoThumbnail example in Storybook

[MediaCard] Add border-radius when necessary

---

UNRELEASED.md
src/components/Tooltip/Tooltip.scss

Fixes #2869 
Increasing content and wrapper max-height to `500px` which is a great size for the tooltip in my opinion, If you guys don't consider this a good solution I'm open to change it.
**Before**
**After**
<details>
```jsx
import {Tooltip, Link} from '../src'
return ( …
```

[Tooltip] Remove content max-height

---

UNRELEASED.md
src/components/Layout/README.md

Let's add an example to clear up for folks how we recommend they space content that lives above the first section.
Adds an example to `Layout`
1. `yarn dev`
1. Open the example and make sure it looks and works as expected

Adds Banner example to <Layout />

---

UNRELEASED.md
src/components/DescriptionList/DescriptionList.scss

This PR fixes an overflow and wrapping styling issue on the [DescriptionList component](https://polaris.shopify.com/components/lists-and-tables/description-list).  
More specifically, that long strings passed to the keys (`term` and `description`) of an `Item` in the `items` props of the component will not conserve their specific styling widths.
| [Sample codebox with the issue](https://codesandbox.io/s/snowy-leftpad-uz4rs) |
|---|
| <img width="1027" alt="Screen Shot 2020-03-31 at 8 58 37 AM" src="https://user-images.githubusercontent.com/5506721/78028959-d4416700-732d-11ea-9b25-6abb9b082efc.png">|
We add a couple css styles to not have long content overflow.  This lets the component maintain it's already enforced widths for long content passed in.
| with this styling fix applied  | …

[DescriptionList] Long content styling fix

---

src/components/Frame/README.md

Fixes https://github.com/Shopify/polaris-ux/issues/422
This change fixes a problem where the frame would continually grow in height in the style guide:

Adding fixed height to frame with offset example

---

UNRELEASED.md
src/components/TopBar/README.md
src/components/TopBar/components/Menu/Menu.scss
src/utilities/custom-properties/custom-properties.ts

Currently displays white on white when no colour theme is provided to the the top bar. The defaults provided didn't seem correct so I'm updating them :).
Addresses issue https://github.com/Shopify/destinations/issues/760.
Before:
After:
<details>
```jsx
return (
<Page …
```

Update the background menu color when no theme is set.

---

UNRELEASED.md
src/components/Filters/Filters.tsx
src/components/Focus/Focus.tsx
src/components/Focus/tests/Focus.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/2741
There are two issues with the current behavior:
- When toggling open a new filter, it does not focus the first selectable input (it does so after selecting and re-toggling)
- When selecting an input on a newly toggled filter, it will force a focus away
The reference being passed to the `<Focus />` component from `<Filters />` was the direct reference to it's `current` value, which would be a stale reference by the time the component is mounted and rendered, forcing that focused element to be "one step behind."
This PR adds an union type to be passed to the `root` of `<Focus />`, which is the entire `React.RefObject`, and lets the `Focus` component grab it's `current` node instead, so that we are sure that the `current` node we …

[Focus] and [Filters] Fixing initial reference focusing

---

UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/EmptyState/EmptyState.tsx
src/components/EmptyState/README.md
src/components/EmptyState/tests/EmptyState.test.tsx

Part of https://github.com/Shopify/facebook-ads/issues/7751
There is a team trying to ship a new channel for facebook ads. They anticipated the DL rollout would be complete by now. The illustration for their app is already complete in the new DL. They're blocked because the empty state doesn't currently support the new illustration style.
This PR adds a new prop to empty state allowing anyone to use this new centered empty state layout. I chose this way to do it because it will actually help us deprecate the justified layout while giving merchants a chance to update their images for the next major release after the new DL.
Before:
After: 
New DL: …

[Empty state] Add centered layout

---

UNRELEASED.md
src/components/ResourceItem/ResourceItem.tsx

Fixes #2164 
The resource item component does a deep equality check of previous and next props in the `shouldComponentUpdate` lifecycle method. This causes significant performance issues in production because `children` are included in that check. 
The ideal way to fix this forward would be to rewrite `ResourceItem` as a functional component and 🔥`shouldComponentUpdate` entirely. Even more ideally, it shouldn't be handling its own selected state but instead rely on a `selected` boolean prop. But we don't have cycles for that effort right now. 
This PR hot fixes the problem by stripping `children` out of the check to reduce complexity of the comparison down to only the explicit props. 
To tophat this change, I made a release candidate and pushed the [`web` upgrade branch to Web …

[ResourceItem] Remove children from the equality check in shouldComponentUpdate

---

UNRELEASED.md
src/components/Page/README.md
src/components/Page/components/Header/Header.scss
src/components/Page/components/Header/Header.tsx
src/components/Page/components/Header/tests/Header.test.tsx

For a project I am working on currently, we need to make better use of the space between the breadcrumbs and pagination/actions menu. Currently we have some hacks with absolute positioning, but I would rather this be a part of the page component so we can make it more reliable and also re-arrange if needed (probably in the new design language too). My current implementation gets the wrong tab order as well because I need to place the elements inside the page content instead of in the proper place in the header.
This adds a new `additionalNavigation` prop to `<Page>` that accepts a React Node and renders it in the correct space.
This is what it looks like with an avatar in that spot:
I added an example to our `Page with all header elements` example in the README …

[Page] Adding additionalNavigation prop

---

CHANGELOG.md
UNRELEASED.md

This updates the changelog for v4.21.0. It looks like we missed this in 4.20.1. Does that look right to you @chloerice?

Updating changelog for 4.21.0

---

.github/CONTRIBUTING.md

Documentation - Add /handbook/ directory to webfoundation urls 
[Web-Foundation](github.com/Shopify/web-foundation) was restructured so links in the 'Best practices' section 
of  [.github/CONTRIBUTING.md](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) were outdated.
Old urls
`github.com/Shopify/web-foundation/tree/master/Best%20practices`
New handbook urls
`github.com/Shopify/web-foundation/tree/master/`**handbook/**`Best%20practices`
related commit for web-foundation
https://github.com/Shopify/web-foundation/commit/357d8311b9e952fc677f368a83741159577e5abb
External project changed it's repo structure so github urls became outdated resulting 404's when visting old links

Updated CONTRIBUTING.md WebFoundation urls

---

UNRELEASED.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx

The Autocomplete component causes the following warning if used with server-side rendering:
```
Warning: Prop `aria-controls` did not match. Server: "ComboBox2" Client: "ComboBox1"
```
This is a known problem: #1761
Although this PR does not directly fix that problem, converting the Combobox to a functional component and having it use the `useUniqueId` hook is a prerequisite for fixing the automatic ID generation in the future.
Converts the Autocomplete Combobox component into a functional component and uses the `useUniqueId` hook.
Not easily testable without server side rendering 🤔 
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentati …

[Autocomplete.Combobox] Convert to functional component

---

UNRELEASED.md
src/components/ResourceList/ResourceList.scss

Fixes https://github.com/Shopify/store/issues/14834
No matter the viewport size, it truncates the sortOption label if it doesn't fit. Previously, we were only truncating for mobile/small screens. This PR addresses running into the same problem on various screens.
<details>
```jsx
import {Avatar, Card, ResourceItem, …
```

[ResourceList] Trunctate long sortOption label

---

src/components/Card/components/Header/tests/Header.test.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/Page/tests/Page.test.tsx
src/components/PageActions/tests/PageActions.test.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
src/components/Portal/tests/Portal.test.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

Easing future upgrade paths
require.requireActual and require.requireMock have both been deprecated
for ages and have finally been removed in Jest 26.
Let's use the supported functions for doing this.
check tests pass

Use supported mocking functions in jest.

---

UNRELEASED.md
src/components/Banner/Banner.scss

I noticed this while working on slides, so I fixed it. The shadow no longer has an impact on Chromium edge and Windows high contrast mode.
Adds an outline to Banner.
<details>
```jsx
return (
</Page>
);
} …
```

Fix border on Windows high contrast

---

src/components/AppProvider/README.md

Because these docs didn't exist before, yet they're pretty vital to setting up a new embedded app
Adds docs
Read words

Add docs for AppProvider's linkComponent

---

UNRELEASED.md
src/components/Pagination/Pagination.tsx

I want to put some chunkier text into the Pagination label
Loosen the type of Pagination label to allow for React.ReactNode instead of only strings.
See that the below code type checks.
<details>
```jsx
import {Page, Pagination, DisplayText} from '../src';
return (
<Pagination
hasNext
hasPrevious
label={<DisplayText>CHONK</DisplayText>}
/>
</Page>
);
}
```
</details>

Loosen Pagination label type

---

UNRELEASED.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1089
Allows user to directly focus the textfield when there aren't options while navigating with a keyboard. 
It makes the tabindex dynamic based on the number of options. 
<details>
```jsx
import {Page, Card, Autocomplete, TextField, FormLayout, Button} from '../src';
const [options, setOptions] = useState<{value: string; label: string}[]>([]);
const addOptions = () => {
setOptions([
{value: 'montreal', label: 'Montreal'},
{value: 'tokyo', label: 'Tokyo'},
{value: 'seoul', label: 'Seoul'},
]);
};
return (
<Card sectioned>
<FormLayout>
<TextField label="Name" …
```

[ComboBox] set tabIndex depending of number of options

---

UNRELEASED.md
src/components/EmptyState/EmptyState.tsx

While working on https://github.com/Shopify/email/pull/4656 we had the need to show a Loading indicator on the empty state primary action.
This switched the type for the Actions in the EmptyState from Action to ComplexAction.
Two questions: Do we want to add something on this to the Playground? Also, it could be just the LoadableAction but I used the ComplexAction because it was the typing for the button.

[EmptyState] Switched to ComplexAction as type for the EmptyState actions

---

UNRELEASED.md
config/rollup/plugins/styles.js
src/styles/_public-api.scss
src/styles/foundation.scss
src/styles/shared.scss
tests/build.test.ts

Consuming applications currently have to reference two files to use our public sass API. Instead we should get people to use a single entry point now [recent (since Nov 2019) versions of sewing-kit no-longer hardcode opinions about what our public api endpoints are named](https://github.com/Shopify/sewing-kit/blob/master/migration-guide.md#01130).
Deprecate using foundation.scss and shared.scss to access our public
sass API. Instead consuming apps should import `_public-api.scss`.
By exposing a single entrypoint we make it slightly easier for consuming
apps to use our public API.
foundation.scss and shared.scss remain present for now to retain
compatability with sewing-kit versions older than 0.113.0 (released
Nov 2019), as older versions hardcoded those paths. They should be
deleted in …

Create a single entrypoint for public sass API

---

UNRELEASED.md
src/components/Banner/Banner.scss

Rounded corners on banners were missing
A fallback to `inherit` doesn’t appear to work, also border-radius is different for in-context banner so putting those properties in the if-else.

[Banner] Fix rounded corners on banners

---

UNRELEASED.md
src/components/ResourceList/README.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx
src/components/Select/Select.scss

The plus global nav team wants the ability to customize the empty state of the resource list.
Add a prop that takes in a react node to be rendered instead of the default empty state
<details>
```jsx
return (
{/* Add the code you want to test in here …
```

Add customizable empty state prop in resource list

---

examples/next.js/pages/_app.js

App Container has been deprecated in Next.js:
https://github.com/zeit/next.js/blob/master/errors/app-container-deprecated.md

[Examples] Remove deprecated Container in Next.js

---

UNRELEASED.md
package.json
tsconfig.json
yarn.lock

Keeping up to date. tyepscript 3.9 is hot off the presses. Speeding up builds
TS 3.9 offers a few speed improvements. Nothing huuuuuge, but it shaves 3
seconds of our build and type-check commands.
Enabling skipLibCheck (as set by our parent TS configs) meanwhile saves
an additional 10 seconds as we don't bother checking TS declaration files
that we don't use. Recently TS's init scripts were updated so now this
is set to true in newly creacted configs so I'm now more confident in
following suit.
On master: type-check took ~38s, build took ~52s
This commit: type-check took ~24.5s, build took ~37s
TypeScript 3.9 Release blog: https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/
PR where TypeScript changed the value of skipLibCheck in new projects to be true: …

Update typescript to 3.9 and enable skipLibCheck

---

UNRELEASED.md
src/components/Button/Button.scss

In cases that a button was passed the props destructive = true and plain
= true you would end up with a button that had text in one color (red /
destructive) and an icon in another color (blue / primary?).
This was not the intentional behaviour. I've added some CSS to color the
icon the same color as the destructive text.
Fixes https://github.com/Shopify/polaris-react/issues/2958
| Before | After |
| ------- | ------ |
| <img width="200" alt="Screen Shot 2020-05-09 at 9 50 12 PM" src="https://user-images.githubusercontent.com/13607675/81491122-1ae48400-923f-11ea-8ef6-49e1e7fdf082.png"> | <img width="213" alt="Screen Shot 2020-05-09 at 9 49 46 PM" src="https://user-images.githubusercontent.com/13607675/81491124-2172fb80-923f-11ea-973a-e010d8ba5a85.png"> | …

[Button] Fix color icon red if button is plain and destructive

---

UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/ResourceList/README.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

The initial approach to knowing when to render the `emptyState` when provided used an existing prop, `hasMoreItems`, which conflicted with its use by consumers like `web` to show empty search result markup. That prop is also used internally to determine whether or not to show a "Load more items" link-like button in the list. 
Initially this PR was adding a new boolean prop, `showEmptyState` so consumers could explicitly tell the `ResourceList` whether or not to render the `emptyState` when provided. After discussing with @dleroux, we've decided that `emptyState` will render when set if items are empty*. 
*`emptySearchState` is a new prop recently added that complicates this a bit, as no results state is handled internally in spite of filters being a separate component. We have no idea …

Refactor and revert revert resourcelist emptystate

---

UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/EmptyState/EmptyState.tsx
src/components/EmptyState/README.md

Fixes: https://github.com/Shopify/deliveries/issues/206
This change is adding another empty state component with a full width property. This full width property works with the centered layout property on the empty state component to provide the user with full width of the content. 
I've added an example in the README.txt file that shows how the property is supposed to be used.

[Empty State] Add full width prop

---

UNRELEASED.md
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/ContextualSaveBar/README.md
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
src/utilities/frame/types.ts

Fixes https://github.com/Shopify/polaris-react/issues/2533 and https://github.com/Shopify/deliveries/issues/695
Contextual save bar looks like garbage on a `fullWidth` page 🗑.
Gives the option to make the contextual savebar `fullWidth` with a prop.
New example added in `Readme.md`.

ContextualSaveBar fullWidth

---

UNRELEASED.md
src/components/Page/Page.tsx
src/components/Page/README.md
src/components/Page/components/Header/Header.tsx
src/components/Page/components/Header/tests/Header.test.tsx

The current `primaryAction` on `Page` only allows for one button, I'm currently working on a project that has a need for more flexible primary actions.
This PR maintains the existing `primaryAction` prop, while adding the option to pass a `ReactNode` instead for customizability.
We had considered building the API/UI for `primaryAction` to suit our specific need. We decided against this because we are not sure it's the right solution for everyone.  This way if the provided option `PrimaryAction` doesn't cover every scenario, a custom option can be implemented. 
📄 …

[Page] Add ReactNode as an accepted primaryAction prop value

---

src/components/Icon/Icon.tsx
src/components/Icon/tests/Icon.test.tsx
src/types.ts

`warning` color shows up in TS auto complete when using the Icon component but is unusable without the new DL enabled. I thought about adding a fallback in css but this seems to make more sense to me.
<details>
```jsx
import {AlertMinor} from '@shopify/polaris-icons';
import {Icon, Page} from '../src'; …
```

[Icon] Warn when using a new DL color and new DL is disabled

---

UNRELEASED.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx

Fixes https://github.com/Shopify/store/issues/14970
Currently, the `<Popover/>` in the `<ComboBox/>` is only activated onClick, and not on keyDown. This leads to autocomplete suggestions not pulling up when the consumer types in the `<TextField/>` and uses the keyboard to select a suggestion, then types again to search further results:
This PR sets `popoverActive` to true on keyDown, so suggestions are indeed rendered in the above scenario. It uses the same activator function that is already being called onClick.
📄 [Changelog …

[ComboBox] Set popover to active on keyDown

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

In order to make the render item function infer the item's type we refactored to a functional component and made ResourceList generic.
Fixes #543 
More info in the discussion [here](https://github.com/Shopify/polaris-react/issues/543). 
ResourceList will also be a functional component as part of  #1995
+ use the 18n hook for internationalization
+ made item generic
+ made the item render functions use the items type
ResourceList is in the …

[ResourceList] refactor to functional component

---

scripts/build.js
src/styles/global.scss
tests/build.test.ts

In our code we replace `{{POLARIS_VERSION}}` and `<%= POLARIS_VERSION %>` with the actual version of polaris.
Having two formats for that is silly. Lets just have one.
- Replaces occurrence of `<%= POLARIS_VERSION %>` with `{{POLARIS_VERSION}}`
- Remove the build step that searches for `<%= POLARIS_VERSION %>` as it is no longer used
- Refactor the tests that prove that the version is replaced so that they give more meaningful output if they fail - they will now list the files that included the template string rather than saying the total number of files was different.
Search the codebase for `<%= POLARIS_VERSION %>` and see that no results are found
Ensure tests pass
Do a build and see that the files mentioned in the build test contain all contain the version string (e.g. `4.23.0`) …

Use a single template style for POLARIS_VERSION

---

UNRELEASED.md
config/rollup/plugins/styles.js
src/styles/global.scss
src/styles/shared/_skeleton.scss
tests/build.test.ts

A step towards #3009.
We have two locations for our public sass API
- `styles/_public-api.scss` for consumers that don't use css-modules
- `esnext/styles/_public-api.scss` for consumers that do use css-modules (e.g. folks using sewing-kit)
Having two locations is confusing to document, adds complexity to our build, and is ripe for confusing our consumers.
It is this way because in one of our mixins we use css-modules' `:global {}` pseudo-selector to get at a globally defined animation name. If we can remove the need for that then we don't need to strip that selector out at build time and then the contents of the api files in `styles/{shared,foundation}/` and `esnext/styles/{shared,foundation}/` become identical.
Let's unify our mixin files so they don't need to differ between these …

Unify the output of the styles folder build

---

UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/EmptyState/EmptyState.tsx
src/components/EmptyState/README.md

The new illustration styles have ~40px of white space between them and their viewbox. We need some additional padding below for visual balance.
I experimented with an aspect ratio wrapper component that could handle this but I think it would be too much added work for teams across the company to implement. 
Instead I'm adding more context to the empty state props regarding spacing while within content
Copy-paste this image into its own file …

[EmptyState] Add spacing within content

---

UNRELEASED.md
src/components/EmptyState/EmptyState.scss

This pull request is changing the max-width to 400px for the Empty State content. 
You can check out this on the StoryBoard under the Empty state within context component.

[EmptyState] Set max-width to 400px

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx

Fixes an issue where consumers would have to add an <any> type argument in order to access resource list props. i.e. `ResourceListProps<any>['bulk-actions']`
<details>
<summary>Summary of your gif(s)</summary>
</details>
-->

[ResourceList] Default to any for ItemType

---

UNRELEASED.md
src/components/Banner/Banner.scss

Co-authored-by: Shannon Broekhoven <shannon.broekhoven@shopify.com>
This is required for https://github.com/Shopify/web/pull/28529 
Add flex to ContentWrapper on Banner component so that ContentWrapper fills width of Banner. This is required to allow for aligning elements on the right side of the Banner.
CURRENT
AFTER
<details>
```jsx
import {Page, Card, Banner, Stack} from '../src';
return (
<Card>
<Banner status="warning" onDismiss={() => {}}>
<Stack>
<Stack.Item fill>Balance (Customer owes you)</Stack.Item>
<Stack.Item>$10.11</Stack.Item>
</Stack>
</Banner>
</Card>
</Page>
);
}
```
</details>

Add flex to ContentWrapper on Banner component

---

UNRELEASED.md
src/styles/foundation/_colors.scss
src/styles/foundation/_filters.scss
src/styles/foundation/_shadows.scss

I found out public_api doesn't compile in dart-sass: `npx node-sass src/styles/_public-api.scss`. Looks like it is because dart-sass and libsass handles newlines in strings a bit differently.
dart-sass doesn't like multi-line strings (which I kinda agree with - css doesn't like unescaped multiline strings either). Escaping the newlines (`\n`)
results in libsass not displaying them properly. Result: remove
linebreaks.
Also change a block-style comment to be inline so it doesn't get output.
- Confirm the public api can be compiled with no output using node-sass: `npx node-sass src/styles/_public-api.scss`
Confirm the public api can be compiled with no output (and no errors!) using dart-sass : `npx sass@latest src/styles/_public-api.scss`
For bonus points, add a usage of these mixins and see …

Write sass errors that are valid in dart-sass

---

UNRELEASED.md
src/components/Banner/tests/Banner.test.tsx
src/components/Checkbox/tests/Checkbox.test.tsx
src/components/Focus/tests/Focus.test.tsx
src/components/Frame/tests/Frame.test.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/ResourceList/components/FilterControl/components/FilterCreator/tests/FilterCreator.test.tsx
src/components/ResourceList/tests/ResourceList.test.tsx
src/components/TextField/tests/TextField.test.tsx
src/components/TopBar/components/SearchField/tests/SearchField.test.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

An imminent bump to SK and thus Jest exposes a case where enzyme doesn't handle component mounting to jsdom in a way that results in spec compliant focus management, which then results in tests that assert on document.activeElement failing.
Fortunately react-testing doesn't have this problem, so we can just usethat instead.
Gory details: https://github.com/enzymejs/enzyme/issues/2337#issuecomment-608984530
Migrates a handful of test cases from enzyme to use react-testing
Run tests and see they still pass

Update activeElement tests to use modern testing utils

---

UNRELEASED.md
src/components/Page/components/Header/Header.scss

Co-Authored-By: Dan Ross <hypd@users.noreply.github.com>
Fixes https://github.com/Shopify/deliveries/issues/1102 and fixes https://github.com/Shopify/polaris-react/issues/2739
The ellipsis in the page actions currently does not use the same spacing as the header on the left hand side. This makes the padding around the Page component appear consistent.
Example of issue:
This PR does:
Open up the Page component in StoryBook and test the ellipsis and action locations on desktop and mobile.

[Page] action rollup consistent padding and alignment

---

CHANGELOG.md
UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/EmptyState/README.md

These changes are a part of the [new illustration style rollout project](https://vault.shopify.io/projects/13698). Empty states are changing and to align with the new style we need to remove the padding from the top of the details container. 
Before:
After: 
To make sure that we show the right layout in the style guide examples, I updated the example image to the dimensions (226 x 226 px) that Creative Direction uses for the new empty state illustrations. This applies to all the examples with centered content. 
📄 [Changelog …

[Empty state] Adjust padding and replace example image

---

src/components/ActionMenu/ActionMenu.tsx
src/components/ActionMenu/tests/ActionMenu.test.tsx
src/components/Page/README.md

`Page` actions were no longer triggering their callbacks with the new design language because the callback was being passed through to `Button` as `onAction`, not `onClick`. TypeScript should have caught this, I have not looked at why this happened.
Destructuring `onAction` from the `rest` props and passing to `onClick` for `Button` or `onAction` for `MenuAction`, depending if the new design language is enabled or not.
Also adds the tests first so you can see the failure then the fix as a separate commit to verify.

[ActionMenu] Fix regression with new design language

---

UNRELEASED.md
src/components/ResourceItem/ResourceItem.scss
src/components/ResourceItem/ResourceItem.tsx

Fixes https://github.com/Shopify/deliveries/issues/837
Fixing alignment of resource items when there is no media.
Currently the text is below the checkbox:
Now the text is inline with the checkbox:
Open the simple resource list item example in storybook and compare the spacing in multiple browsers.

ResourceItem fix alignment of checkbox when no media

---

UNRELEASED.md
src/components/Icon/Icon.scss
src/components/Icon/Icon.tsx

There's a couple of places in web where a blue duotone icon is used. This is done to match the "in progress" badge.
This PR adds `blueDark` to the acceptable values of for duotone Icons. (I know this will changed in the new design language)
<details>
```jsx
import {CircleInformationMajorTwotone} from '@shopify/polaris-icons';
import …
```

[Icon] Add blueDark to icons with backdrops

---

UNRELEASED.md
src/components/AppProvider/README.md

The sample test app is updated to use PolarisTestProvider but this documentation snippet still refers to the old 3.x functions.
Changing the AppProvider docs

[ AppProvider] Update AppProvider Testing Components section for version 4

---

babel.config.js
rollup.config.js

Not repeating myself
Rollup will now use the config in babel.config.js as a base and augment
when needed

Build: Avoid repeating babel config in rollup config

---

UNRELEASED-v5.md
package.json
src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/components/Day/Day.tsx
src/components/DatePicker/components/Month/Month.tsx
src/components/DatePicker/components/Month/tests/Month.test.tsx
src/components/DatePicker/components/Weekday/Weekday.tsx
src/components/DatePicker/components/Weekday/tests/Weekday.test.tsx
src/components/DatePicker/tests/DatePicker.test.tsx
src/components/DatePicker/utilities.tsx
src/utilities/dates.ts
src/utilities/focus.ts
yarn.lock

Removes dependency on deprecated package
Date functions have been moved into utilities/dates, though they are
only used within the DatePicker component.
This goes to highlight the terrible ergonomics of the Weekday/Month enums. People already use DatePicker by passing in numbers to `month` and `weekStartsOn` number,  which is what our example does e.g. `<DatePicker year={2019} month={0} weekStartsOn={0} />` instead of an enum value e.g. `<DatePicker year={2019} month={Months.January} weekStartsOn={Weekdays.Sunday} />` (note that they would have had to import `Weekdays` from the javascript-utilities package as we never exposed it). Because of that I'm highly tempted to convert these enums into just `number` to avoid needing to export additional enums that are just nice-to-haves (I tried …

Remove dependency on @shopify/javascript-utilities

---

UNRELEASED-v5.md
UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/EmptyState/EmptyState.tsx
src/components/EmptyState/README.md
src/components/EmptyState/tests/EmptyState.test.tsx

⚠️ This PR targets the v5 branch since it includes a breaking change
The `centeredLayout` prop was added before empty states were included in a card context so it's no longer necessary. This removes that prop, its styles, and adds a `newDesignLanguage` class that piggy backs on the `withinContentContainer` styles
http://localhost:6006/iframe.html?id=all-components-empty-state--all-examples&contexts=New%20Design%20Language=Enabled%20-%20Light%20Mode

[Empty State] Remove centered layout prop and add new design language class

---

UNRELEASED.md
locales/en.json
src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/components/Day/Day.tsx
src/components/DatePicker/components/Month/Month.tsx
src/components/DatePicker/components/Month/tests/Month.test.tsx
src/components/DatePicker/components/Weekday/Weekday.tsx
src/components/DatePicker/components/Weekday/tests/Weekday.test.tsx
src/components/DatePicker/utilities.tsx
src/components/ResourceList/components/FilterControl/components/DateSelector/DateSelector.tsx
src/components/index.ts
src/utilities/dates.ts

This PR is the same as #3113, except without requiring translations, as we're time constrained and want to test these breaking changes without waiting for the translations.
---
Follow up to #3108, where I discovered that the API of DatePicker is clunky without adding much type safety, so we could strip it back a little.
Remove usage of enums and replace them with plain numbers as it results
in a smaller API surface area without having a negative affect on type
strictness.
- BREAKING: Removed export of `Year` type and `Months` enum
- DatePickerProps['month'] was an enum `Months` (representing the numbers
0 to 11), it is now a plain `number` instead
- DatePickerProps['weekStartsOn'] was an enum `Weekdays` (representing
the numbers 0 to 6), it is now a plain `number` instead
- …

[v5] Date picker type juggling, take 2

---

UNRELEASED.md
src/types.ts
src/utilities/color-transformers.ts
src/utilities/get.ts
src/utilities/is-object.ts
src/utilities/merge.ts
src/utilities/pick.ts
src/utilities/use-component-did-mount.ts
src/utilities/use-deep-callback.tsx
src/utilities/use-deep-effect.tsx

Shrinking our API surface area
Remove `TypeOf` enum, `GeneralObject`, `DeepPartial`,
`EffectCallback`, `DependencyList` and `Comparator` types from being publicly exported.
These should always have been internal only, but people occasionally forget that everything in `src/types.ts` is publicly exported.
None of these are ever used in web or in our component APIs, and I highly doubt anywhere else is using them as they are never documented, so I'm gonna skip mentioning them in the migration guide.

Remove some enums and public types with no value

---

UNRELEASED.md
src/components/TextField/README.md

The multiline example shows new lines being created by `\n` when the multiline prop takes a number. The number example is much more useful as people may want an empty text field to show the user it is multiple lines.
Change the textfield multiline example to use a number.

[TextField] Multiline change example to use number instead of boolean

---

.prettierrc
package.json

The ordering of fields in our package.json is silly.
Reorders package.json keys: dependencies, then peerDependencies, then devDependencies, then
linting configs
Remove stylelint configs that we not longer need to diverge from - `selector-class-pattern` matches the rule provided by `@shopify/stylelint-plugin/prettier`, and we no longer use `:global` in css modules so no need to allow its usage with `selector-pseudo-class-no-unknown`.
Extend from our shared prettier config package
See linting and tests pass

Reorder package.json and simplify some linting config

---

src/components/Badge/Badge.scss
src/components/Badge/Badge.tsx

When implementing the badge in rails I noticed that the colors were using `mix-blend-mode`. Looking at the Figma documentation, the colors were changed to use text-default color.
Documentation here: https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/DL%E2%80%93Polaris-(Web)%3A-Components?node-id=367%3A343
Removing parent div and `mix-blend-mode`.

[Badge] Colors to use updated values in design language

---

UNRELEASED.md
package.json

Consuming apps may end up reading this config and we don't want them to
need `@shopify/browserslist-config` installed to work.
Fixes #3130
Reverts #3101
Use explicit browserslist instead of extending from a shared config

Use explicit browserslist instead of config

---

UNRELEASED.md
src/components/PositionedOverlay/PositionedOverlay.scss
src/components/PositionedOverlay/PositionedOverlay.tsx
src/components/PositionedOverlay/tests/PositionedOverlay.test.tsx
src/components/Tooltip/README.md
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx
src/components/Tooltip/tests/Tooltip.test.tsx

Fixes Shopify/online-store-ui/issues/1598
Currently, when a `Tooltip` is activated, the tooltip remains visible when the mouse leaves the activator and hovers the overlay, which gets in the way of interacting and clicking on interactive content beneath the overlay. This is a problem in the Online Store Editor, where the tooltips rendered on hovering buttons in the RTE toolbar prevent interaction with the textarea which can have very limited height.
This PR adds a new optional boolean prop which sets `pointer-events: none` on the `PositionedOverlay` so that as soon as the cursor leaves the activator (children), the `Tooltip` disappears.
- `git checkout tooltip && yarn dev` (`git remote prune origin` first if you run into ref errors)
- Copy/paste the playground code below into …

[Tooltip] Added optional boolean dismissOnMouseOut prop

---

UNRELEASED.md
scripts/build-consumer.js

`build-consumer` currently doesn't work because it doesn't handle excluded files in package.json's files array.
Ignores excluded files when running build-consumer
This means these excluded files will be copied across when running
build-consumer but this won't have any negative impact other than being
not optimally efficient.
Run build-consumer and see it completes (vs throwing an error on master). Assuming you've got the styleguide checked out: `yarn run build-consumer polaris-styleguide`

Ignore excluded files when running build-consumer

---

UNRELEASED.md
src/components/VideoThumbnail/README.md
src/components/VideoThumbnail/VideoThumbnail.scss
src/components/VideoThumbnail/VideoThumbnail.tsx
src/components/VideoThumbnail/tests/VideoThumbnail.test.tsx

Currently, `VideoThumbnail` displays a video length to set the expectation about how long video is before user starts playing it. Many users are not finishing watching the video at one session, and we are working to allow them to resume the video at the time they left it off.
As a visual confirmation that video has been started, we are adding video progress indicator to the video thumbnail.
Add video progress indicator to `VideoThumnbail` component, so it can visualize how far user has gone through the video and set the expectation that video will resume from where it has been left off.
Progress indicator is calculated based on `videoLength` and `videoProgress` values, and represents percentage of video users watched. …

[VideoThumbnail] Add video progress indicator

---

UNRELEASED.md
config/rollup/plugin-styles.js
package.json
rollup.config.js
scripts/build-validate.js

Getting tree-shaking working. 
#3133 did a really good job of highlighting dead code elimination and got us to a point where that is close to ideal for a single file when using rollup. but I never addressed the lowest-hanging fruit - and the most obvious one that webpack seems to care about - splitting the build into multiple files so consumers can shake out unused imports (which is a lot easier than doing general-purpose dead code elimination).
Earlier this week I was a little wary of doing this as I wasn't sure how I could do it in a way that was both a non-breaking change, and wouldn't require oddness in our build steps. Today I had my moment of inspiration - doing a multi-file commonjs build isn't important, we only need it for the es-modules build. So we can leave index.js and …

Multi-file ESM build

---

src/components/DatePicker/README.md
src/components/DatePicker/components/Month/Month.tsx
src/utilities/dates.ts

Polish, and adding extra examples for a ranged, multi-month and disabled dates functionality in DatePicker
Fixes #2374
- Replace usage of 'isSameDate' with 'isSameDay' as they are identical
- Remove isSameDay helper
- Add extra examples for ranged DatePicker
Check out the new date picker examples

DatePicker improvements

---

UNRELEASED.md
src/components/Labelled/Labelled.scss

When using the TextField component and passing helpText, we noticed it did not wrap properly if there were no spaces or dashes to break up the text. 
Before: 
**HelpText does not wrap properly when there are no spaces or dashes to break up the words**
After:
**HelpText wraps even though there are no spaces in the text**
<details>
```jsx …
```

[Labelled] Add `text-breakword` to styling

---

UNRELEASED.md
src/components/index.ts

The `Popover` component makes a number of choices related to focus management and accessibility attributes which are incompatible with building an accessible combobox (autocomplete) implementation. In particular, the `Popover` makes itself focusable, taking focus away from the `TextField` which should maintain focus even while suggestions are navigated through. That said, its positioning logic is useful for implementing a custom `Popover`. This PR exposes that component so it can be consumed directly.

export PositionedOverlay for use in custom popover

---

src/components/Connected/Connected.scss
src/components/Connected/Connected.tsx
src/components/TextField/README.md

Co-Authored-By: Kyle Durand <kyledurand@users.noreply.github.com>
Fixes connected fields layout when the new design language is used.
Adds a margin gap for the new design language.
Before:
After:
Open up the connected field example.

Seperate connected fields with new design language

---

src/components/Navigation/_variables.scss

Before:
After:
Fixes an alignment issue where the icon in the previous DL was pushing the item labels a little farther right than on desktop.

[Nav] Fix alignment on small screens

---

UNRELEASED.md
esnext/index.js
package.json

sewing-kit v0 now uses `esnext` as the custom mainField, to match the
behaviour of sewing-kit v1. Update to match that.
This is not a breaking change as sewing-kit v0 still has an alias that forces
the use of the esnext folder, so this mainField doesn't do anything
currently, it's just for future compatibility, once SK v0 drops support
for Polaris <5.0 - which will now be "dropping support for < 5.2".
See https://github.com/Shopify/sewing-kit/pull/2279
Renames field in package.json

Use esnext as custom mainfield for esnext build

---

UNRELEASED.md
src/components/Tabs/README.md
src/components/Tabs/tests/Tabs.test.tsx
src/components/Tabs/types.ts

We want to add badges to the Tabs content. In our use-case, our tab opens up a list and we would like a badge to show the # of items in that list.
Fixes https://github.com/Shopify/polaris-react/issues/3162
* Loosen the type of Tabs content to allow for React.ReactNode instead of only strings
* Add Tabs example with Badge in content
See that the below code type checks.
<details>
```jsx
import {Page, Card, Tabs, Badge} from '../src';
const [selected, setSelected] = useState(0);
const handleTabChange = useCallback(
(selectedTabIndex) => setSelected(selectedTabIndex),
[],
);
const tabs = [
{
id: 'all-customers',
content: (
<span> …
```

[Tabs] Loosen content type

---

src/components/Autocomplete/README.md

The styleguide is still transpiling examples with babel v6 so doesn't
understand the shorthand fragment syntax.
Long-term fix would be updating the styleguide to transpile examples with babel 7 but that's a bit more effort than this band-aid.
Note that we're still good to use the shorthand syntax in our code, just not the README examples.
Fixes #3149
Use longhand fragment syntax.
- `yarn run build-consumer polaris-styleguide`
- Run your local styleguide, Visit https://polaris.myshopify.io/components/forms/autocomplete and see that the "Autocomplete with empty state" example renders correctly.

Use React.Fragment in README examples

---

UNRELEASED.md
src/components/Frame/Frame.scss

We have an issue with Safari 10. `height: 100%` doesn't work as expected because all the parent element doesn't set `height: 100%`. To fix that, we can use a `position: absolute` trick. To be able to use this trick, we need to set `position: relative` on the Frame content.
This is a screenshot of the AppBridge Frame on safari 10.
Setting `position: relative` on the Frame content so we can use `position: absolute` inside a children.
```
position: absolute;
top: 0;
left: 0;
right: 0;
bottom: 0;
```

Being able to target element position inside the Frame content

---

src/components/Tabs/Tabs.scss

Fixes https://github.com/Shopify/polaris-ux/issues/410. Font weight is supposed to be 500

[Tabs] Bold in new design language

---

.storybook/polaris-readme-loader.js
.storybook/preview.js
playground/stories.tsx
scripts/pa11y.js

Storybook v6 is released 🎉 
Lets preemptively fix some deprecation notices that result in a Percy claiming every snapshot has changed, thanks to story renaming.
That means that when the time comes to update to v6, we can see any regressions more clearly instead of EVERYTHING IS RENAMED
- Remove usage of | as separator (this has been removed in v6, and changing this means all our snapshots get renamed)
- set showRoots as it is the new default
- use 1rem for story padding as v6 applies a 1rem padding around stories
by default
Run storybook, note that the storynames have been changed
Note that percy has renamed all the snapshots, that's expected.

Fix SB Deprecations in preparation for v6

---

src/components/TextField/TextField.scss

Fixes https://github.com/Shopify/polaris-ux/issues/396 and fixes https://github.com/Shopify/polaris-react/issues/3170. This reverts a change in https://github.com/Shopify/polaris-react/commit/f5aec8efcb7137704cd2af0963b4ef3ecf2ce270 that was to make them flat.
The focus ring should now be round on connected fields in the new design language. There should be no regressions. 
https://5d559397bae39100201eedc1-wxlqoeshyp.chromatic.com/iframe.html?id=all-components-text-field--text-field-with-connected-fields&contexts=New%20Design%20Language%3DEnabled%20-%20Light%20Mode

[TextField] Remove border-radius reset

---

UNRELEASED.md
src/components/ActionList/ActionList.scss
src/components/ActionList/ActionList.tsx
src/components/ActionList/README.md
src/components/ActionList/components/Item/Item.tsx
src/components/ActionList/components/Item/tests/Item.test.tsx
src/types.ts

Some consumers would like to have a way to provide a "suffix" to an item and this PR adds this functionality.

Add a `suffix` to an Action List Item

---

UNRELEASED.md
src/components/Button/Button.scss

Having `connectedTop={false}` on the `ButtonGroup` was still applying the css because the css doesn't check the value.
I made the same fix for fullWidth.

Fix ButtonGroup with connectedTop=false

---

documentation/Color system.md
src/styles/shared/_buttons.scss
src/utilities/theme/tokens.ts

Fixes https://github.com/Shopify/polaris-ux/issues/436
[Figma](https://www.figma.com/file/O3sxnpfbMTuV2e4Yb3HOsh/Tokens%3A-Shadows-Light-Mode-(WIP)?node-id=0%3A1)
Primary / destructive are less noticeable but the shadow is still there. I also had to update the text color because that was reverting to --p-text and not visible at all
Fixes pressed button states for default and primary / destructive buttons
Paste this into playground to test …

[Button] Add -1 layer shadow for pressed state

---

UNRELEASED.md
src/components/TextField/README.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

I have noticed the `TextField` doesn’t support [the `inputMode` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode). Thought I’d add support for it as I discussed this attribute twice in PRs this week. Here‘s [a good article](https://css-tricks.com/finger-friendly-numerical-inputs-with-inputmode/) about it.
Passing down the `inputMode` prop to the `TextField`’s `input`.
TextField without an `inputMode` attribute:
TextField with `inputMode="numeric"`
☝️ This doesn’t work on `master`, the prop is swallowed.

[TextField] Support `inputMode` attribute

---

UNRELEASED.md
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx

We’re getting server/client `id` mismatches on the Admin dashboard on pages that use `Banner`s. This is because the current way of generating unique `id`s is not foolproof.
The first commit is refactoring `Banner` to a functional component since we can’t use hooks in class components.
The second commit fixes the `id` server/client mismatch by using the `useUniqueId` hook instead of the `Banner`’s custom `uniqueID()` util.
We can’t 🎩  the bug fix on the Playground since it’s not server-side rendered.
Here‘s how I tested it:
- Go to a page on your local `web` that renders a `Banner`; I used `/admin/settings/payments`. Notice how there’s a warning in the console that looks like this one:
- Checkout the `fix-mismatch-banner-ids` branch on `polaris-react`
- Run `yarn build` then `yarn …

[Banner] Refactor to a functional component and fix its `id` server/client mismatch

---

UNRELEASED.md
src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/tests/Collapsible.test.tsx

This `expandOnPrint` prop will allow a consumer the option to setup their collapsible such that when it is printed, the content in the collapsible is always shown regardless of its `open` state on the page. This makes it easier for users to see collapsed details without having to click and open the collapsibles on the page before printing. 
Allows a consumer to  show the collapsible content in a print preview even when collapsible is closed
<details>
<summary>Behaviour with expandOnPrint true - print preview shows content even when collapsible is closed</summary>
</details>
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatt …

[Collapsible]Add expandOnPrint prop to support showing content in print

---

UNRELEASED.md
src/components/Badge/Badge.scss

When printing a Badge, both the border and the pip fill colors were not showing.
<kbd>![image](https://user-images.githubusercontent.com/22782157/92636596-a16ca900-f2a5-11ea-8b5b-3489bc46d67e.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/22782157/92636561-8e59d900-f2a5-11ea-9c8a-8febb0198822.png)</kbd>
Instead of going with a fill or background color approach, I went with `box-shadow` since some browsers may have the print with color setting turned off.
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Ve …

[Badge] Show border and fill in pips when printing

---

playground/DetailsPage.scss
src/components/Navigation/Navigation.scss
src/components/Navigation/_variables.scss

Fixes https://github.com/Shopify/polaris-ux/issues/442
This gives nav item labels more room within the nav. Necessary for languages that are generally longer than english. More context in the issue above
Before | After
---|---
<details>
```jsx
return (
<Page …
```

[Navigation] reduce left and right padding by 0.4rem

---

UNRELEASED.md
src/components/Popover/Popover.scss
src/components/Popover/Popover.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx

If there is a print action in a popover, the Popover overlay is still shown when printing the page which can cause obstruction of data on the page. Added `hideOnPrint` prop to `Popover` to allow a consumer to hide the overlay when printing.
Adding a new prop to allow hiding the popover overlay when printing. 
<details>
<summary>Gif of hiding the popover when printing</summary>
</details>
<details> …

[Popover] Add prop to allow hiding popover overlay when printing.

---

src/styles/shared/_interaction-state.scss

Fixes https://github.com/Shopify/polaris-react/issues/3246
Fixes state mixin that is used by partners and app developers.
1. Go the video thumbnail and focus the play button
2. The focus should no longer be a purple line but the updated blue focus
Before:
After:

Update _interaction-state.scss to use ndl

---

src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss

Fixes #3163  [https://github.com/Shopify/polaris-react/issues/3163]
Fixes the issue of the filter customers textfield and more filters button when the screen is small. 
Before
After

[Filters] Fix spacing issues with filters button group

---

playground/DetailsPage.tsx
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx

This fixes #3219 
It moves the discard modal out of the `ContextualSaveBar`'s theme provider so that it doesn't inherit the same dark theme.
This is what it looks like after this change:
Use the details page view in storybook and make a change to the title and then try to discard with the context bar

Move discard modal out of theme provider

---

src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/3271
While auditing the new design language, we noticed that the Page breadcrumb is missing an accessible text label even when a `content` prop is defined:
|Markup|Output
|---|---
|`<Page title="Playground" breadcrumbs={[{content: 'Visually hidden breadcrumb content', url: 'https://shopify.com'},]}>`|![image](https://user-images.githubusercontent.com/8534230/93615958-1163e900-f9a2-11ea-8023-dba3fecbb0f2.png)
This fails to meet web accessibility guidelines that requires either visible or visually hidden text labels for all links and controls.
This is a regression from the previous design language, which rendered a visible text label for the breadcrumb component. 
It is also divergent from the Polaris Rails breadcrumb component, which …

[Breadcrumbs] Render content as a visually hidden label if new design language is enabled

---

documentation/Color system.md
src/components/ButtonGroup/ButtonGroup.scss
src/utilities/theme/tokens.ts

Fixes https://github.com/Shopify/polaris-react/issues/3243
This PR is fixing the gap between segmented buttons.
After 
Button group with segmented buttons
Filters (Some filters disabled)
</details>

[ButtonGroup] Fix Segmented Button Gap Fix

---

src/components/Banner/Banner.scss

Focus ring border radius wasn't being applied properly on focusable banners:
before:
after:
In storybook ensure that with and without the design language enable, both the regular Banner and the Banner inside modal get the proper border-radius when focuses.
<details>
```jsx
return (
</Page>
);
}
```
</details>

[Banner] Fix focus ring border radius on in-content banners

---

.storybook/main.js

Our a11y tests are now very slow, taking 45mins to complete. That's not acceptable if we want speedy dev feedback cycles. https://github.com/Shopify/polaris-react/pull/3284 is a testbed for a bunch of changes that can be added incrementally. I'll be splitting them out over a few PRs. Here's the first one
The Storybook iframe load time goes from ~800ms to ~3200ms if you enable
docs.
This has a massive knock-on effect to our a11y tests - we we load the
iframe for each story (606 times) this means our test end up quite a bit
longer than before SB 6.
Losing Docs is a shame, but we've not really used them to their fullest extent and we can look reenabling them once other speed improvements get applied, but this is a good first bandaid for now even if it isn't ideal long-term.
Disables …

Disable SB docs as it drastically slows down iframe load

---

src/components/AppProvider/README.md
src/components/Frame/README.md
src/components/TopBar/README.md

If we only pass in a "background" to the legacy theme then we adjust its
lightness to generate the "backgroundLighter" color, however changing 
lightness does not guarantee in a large enough contrast.
This problem goes away with new theming so no need to think too hard
about it. Ideally we could push people towards having to specify their own
accessible backgroundLighter color but as i say it won't be a problem for much longer.
Our theming examples use colors that don't produce a shade with high enough contrast so they cause a11y failures in storybook - as surfaced in #3284 where I investigate moving to use axe for our a11y tests so CI matches what storybook addons report. Let's fix the examples to use colors that generate accessible color schemes.
Updates examples:
- Examples that only …

Use contrasting colors in theming examples

---

CHANGELOG.md
UNRELEASED.md
src/components/Navigation/README.md

Addresses point 2 in https://github.com/Shopify/polaris-react/issues/1949
Make sure that sub navigation is surfaced on the navigation examples

Add sub navigation example

---

UNRELEASED.md
src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx
src/components/ActionMenu/components/RollupActions/RollupActions.tsx
src/components/Popover/Popover.tsx

The header actions for the `Page` component are hidden by default when printing. However any popover menus that were opened by these actions are currently not. These changes attempt to fix that and hide any menu popovers. 
After some discussion, the changes have been made to hide `ActionMenu` popovers by default without adding any new props.
Stems from 'hide when printing' requirements https://github.com/Shopify/store/issues/8609
<details>
<summary>Hide page action popovers on print</summary>
</details>
📄 [Changelog …

Hide popover menu (rollup or non rollup) for action menus on print

---

src/components/TopBar/TopBar.scss

Fixes https://github.com/Shopify/polaris-react/issues/3291
Go to the details page with and without the new design language the search bar location should remain the same.

TopBar alignment with page

---

src/components/ResourceList/components/CheckableButton/CheckableButton.scss

Missing button styles on checkable button
Add button styles

Add button style to CheckableButton

---

.storybook/main.js
.travis.yml

@amrocha had good idea: (paraphrasing) "Docs are still useful, what if we only disable them during the a11y test?"
I keep fogetting that SB has decent support for environment variables.
Only disable docs when running a11y tests
- See that a11y test speed does not regress back down to ~45mins
- See that opening storybook normally / in chromatic you still have access to the docs panel

Only disable Storybook docs when running a11y tests

---

src/components/Tag/Tag.scss

Fixes https://github.com/Shopify/polaris-react/issues/3289
The tabs are now the same color as the background, however they should not be used on that color. This makes tophatting a bit weird.

Update tag background

---

locales/zh-CN.json

The Chinese datepicker translations are inconsistent and take up quite a lot of space (3 characters), most Chinese sites just go with 一, 二, 三 (1, 2, 3) for the header labels.
Updates the datepicker header labels (abbreviated day names).
_Before (in Storybook test)_
_After (in Storybook test)_
- Visit [#help-i18n-and-translation](https://shopify.slack.com/messages/C7TJQLVC7) for questions about the this pull request.
@Shopify/polaris-team

Update translations: default

---

src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx

Fixes https://github.com/Shopify/polaris-react/issues/3211

Rangeslider focus

---

UNRELEASED.md
src/components/Frame/components/Toast/Toast.scss

Fixes https://github.com/Shopify/polaris-ux/issues/398
Use `currentColor` on the SVG fill to make sure it follows the text color when in high contrast mode. See https://sarahmhigley.com/writing/whcm-quick-tips/ for more information.
Open the [toast](https://5d559397bae39100201eedc1-wydjwmvuxu.chromatic.com/?path=/story/all-components-toast--all-examples) up in windows high contrast mode.
</details>

Toast highcontrast

---

UNRELEASED.md
src/components/DatePicker/DatePicker.scss
src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/components/Month/Month.tsx

Fixes https://github.com/Shopify/polaris-react/issues/3325 and unblocks https://github.com/Shopify/web/pull/32054
It adds a wrapping div around each month table so that the flex layout gets correctly calculated before showing the popover.
This is what it looks like now:
<details>
```jsx
import {Page, Button, …
```

[DatePicker] Fix multimonth layout in Firefox

---

UNRELEASED.md
src/components/Tabs/README.md
src/components/Tabs/Tabs.scss
src/components/Tabs/Tabs.tsx
src/components/Tabs/tests/Tabs.test.tsx

Order's uses a custom disclosure so let's systemize that!
Allowing the disclosure in tabs to be replaced by text provided by the consumer
<details>
```jsx
return (
</Page>
);
}
```
</details>

Added disclosure text to tabs

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Link/Link.scss
src/styles/shared/_buttons.scss

Fixes https://github.com/Shopify/polaris-react/issues/3239
Reverts link changes, look at Percy. Should match https://polaris.shopify.com

Only show underline on hover/active/focus for plain button and link

---

UNRELEASED.md
src/components/ProgressBar/ProgressBar.scss

Closes https://github.com/Shopify/polaris-react/issues/3340
As per https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-(Web)%3A-Components?node-id=5540%3A55

Bug fix: updates ProgressBar's background colour

---

src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss

During a design review for the orders list with @patrickkidney & @AdamWhitcroft we discussed increasing the spacing between the connected filter to make the difference between grouped buttons & separated ones clearer.

Adjust connected filter control spacing

---

src/components/ActionMenu/components/Actions/Actions.tsx

Addresses: https://github.com/Shopify/polaris-react/pull/3308#discussion_r498211820
Thanks for the suggestion @tleunen this seems to work well
<details>
```jsx
return (
</Page>
);
}
```
</details>

[Actions] Remove disable exhaustive deps lint

---

src/components/Tag/Tag.scss

Adjusts border radius and darkens the background color
Updated border radius / background color

Update background-color & border radius for new design language

---

src/components/Banner/Banner.scss

In the new design language, Banners that are in content (card or modal) had 3 issues:
1. The dismissable icon wasn't vertical aligned properly
2. The ribbon right spacing wasn't being applied
3. The dismiss icon was overlapping text is some cases.
before:
after:
Fixes #0000 
<details>
```jsx …
```

[Banner] Adjusting spacing

---

UNRELEASED.md
src/components/DescriptionList/DescriptionList.scss
src/components/DescriptionList/DescriptionList.tsx

The DescriptionList is used for the [Email modal in web](https://github.com/Shopify/shopify/issues/261981) and from rails to react there's a significant difference in the spacing being used. 
Adds a prop to allow for tighter spacing in the description list.
Current:
Spacing: tight
<details>
```jsx
export …
```

[DescriptionList] Add spacing prop to DescriptionList

---

src/components/DescriptionList/DescriptionList.tsx

Fixes issues in current release candidate
Making the spacing prop optional on DescriptionList

DescriptionList - make spacing optional prop

---

src/components/ResourceItem/ResourceItem.tsx
src/components/ResourceList/ResourceList.tsx

Fixes warning logs seen on this page http://polaris-react.herokuapp.com/?path=/story/all-components-resource-list--all-examples
Generating the key with `React.Children.toArray`

Use React.Children.toArray to remove child component key warning logs

---

UNRELEASED.md
src/components/ActionList/ActionList.scss
src/components/ActionList/README.md
src/components/ActionList/components/Item/Item.tsx
src/components/ActionList/components/Item/tests/Item.test.tsx
src/types.ts

This PR does 2 things:
- Makes the "content" takes all the space, so the suffix/badge will always go right aligned. This is because it is already the behavior when the item has an icon/image. So this makes it be consistent with or without icons/images.
- Adds a `prefix` prop, in the same way `suffix` works, allowing any React nodes. This PR doesn't remove any other prop such as icon or image, but they could also be removed in favor of `prefix`. Ideally, we would remove all these extra props in a major release (v6?) and keeps the component flexible with these 2 props: prefix/suffix.
Does it make sense? Anything missing?

Add action list item prefix and fix content which should take as much as possible

---

examples/create-react-app-ts-react-testing/package.json
examples/create-react-app-ts-react-testing/yarn.lock
examples/create-react-app/package.json
examples/create-react-app/yarn.lock
examples/next.js/package.json
examples/next.js/yarn.lock
examples/webpack/package.json
examples/webpack/yarn.lock

Fixes #3334 using the dependency version from #3130 
Fresh builds of the create-react-app and create-react-app-ts examples were broken and yielded the following error:
```
Failed to compile.
./node_modules/@shopify/polaris/dist/styles.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@shopify/polaris/dist/styles.css)
Error: Cannot find module '@shopify/browserslist-config'
at Array.reduce (<anonymous>)
```
Bumping up `@shopify/polaris` from `5.0.0` to `5.1.0` resolves this. At the suggestion of @BPScott, all of the example apps were synced and their yarn.locks were rebuilt. All example builds are working now.

Bugfix: Bump up Polaris to 5.1.0 in Examples to Fix Broken Builds

---

src/components/Page/components/Header/Header.scss

Fixes a bug in the rc where titles don't wrap where intended
Force the title wrapper to take 100% of the spacing when wrapping

[Page Header] Fix mobile layout

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/Button/tests/Button.test.tsx

Fixes https://github.com/Shopify/web/issues/31389
- The icon flashes a black square right before the loading spinner is shown
- The width of the button changes when the loading spinner is rendered
|Before|After|
|-|-|
|![Before](https://user-images.githubusercontent.com/22782157/94958299-4b161300-04bd-11eb-9d9b-90fde5868b1a.gif) |![After](https://user-images.githubusercontent.com/22782157/94958406-77319400-04bd-11eb-9fb6-2fc54051a484.gif)|
- Visually hide the icon when `loading` is true since we only care to see the spinner in this state
- The spinner is always rendered but `visually: hidden` is added and removed based on the state of `loading` …

[Button] Fix icon from flashing and width from changing when transitioning to a loading state

---

src/components/Button/Button.scss

Fixes this issue:
Trickles the `$slim-min-height` local override down to the slim button's padding too.

[Button / Slim] Fix an issue where icons would vertically stretch the button

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Button/Button.tsx

Follow up from https://github.com/Shopify/polaris-react/pull/3370 which caused buttons with only icons (like pagination) to have extra spacing to the left of the icon.
This PR ensures that all buttons keep the same width when they are loading or not. The loading state renders a spinner which is an icon, this was removing the `margin-left` property from the initial icon since it is longer the first child (spinner becomes the first child instead).
The only button variation I found that still resizes its width is a button that uses the `iconOnly` style (since this sets the margin property to 0) and still has another element (see the 3rd example in the below gif of a button with only an icon and a connected disclosure). Though I believe this variation would never exist in the wild.
🖥 [Local …

[Button] Fix width so that it stays the same when loading

---

src/components/Banner/Banner.scss

Prevent having 2 box-shadow properties when the banner is "In page" context.
Should this really require a changelog? 😅

Prevent having 2 box-shadow properties when the banner is "In page" context

---

UNRELEASED.md
src/components/Modal/Modal.tsx
src/components/Modal/README.md
src/components/Modal/tests/Modal.test.tsx

In order to improve accessibility on our Modal, this adds the ability to include a ref as the activator type on Modal.
We recently added the activator prop in order to return focus to it once the modal closes. However, it's not always possible to pass in the element and consumers are left to manage their own focus, which is in most cases overlooked. By adding a ref as a possible type, the Modal can still be responsible for focusing the correct node when closing.
- Adds React.RefObject as a possible prop type for the activator
- updates test
- updates documentation
Storybook contains all the examples. Ensure they all work as expected.

Add ref type to modal activator

---

src/components/Banner/Banner.scss

Bug fix: content and dismiss overlap for banner

---

playground/DetailsPage.tsx
src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx

Fixes https://github.com/Shopify/polaris-react/issues/3393
Pages actions don't perfectly line up with button props. Converting onAction to onClick is necessary 
<details>
```jsx
return (
</Page>
);
}
``` …

[SecondaryAction] Pass on Action to onClick handler

---

UNRELEASED.md
src/components/Select/Select.scss
src/components/TextField/TextField.scss

Tweaks the border colors of TextField and Select per @jessebc request (#3364).
These design decisions are based on upcoming color tweaks in polaris-tokens, so they won't look right until a new release of polaris-token is out.

[TextField][Select] Tweak colors

---

UNRELEASED.md
src/components/Banner/Banner.scss
src/components/Banner/Banner.tsx
src/components/Banner/README.md
src/components/Button/Button.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/ResourceList/components/FilterControl/components/FilterCreator/tests/FilterCreator.test.tsx
src/components/UnstyledButton/UnstyledButton.scss
src/components/UnstyledButton/UnstyledButton.tsx
src/components/UnstyledButton/index.ts
src/components/UnstyledButton/tests/UnstyledButton.test.tsx
src/components/UnstyledButton/utils.tsx
src/components/index.ts

There are often times where we need a button with custom styles, but we don't want to have to do the same reset and implement functionality built into our existing `Button` component. For changes like the styling the actions in banners with the new design language we were forced 
This adds a new `UnstyledButton` component that will accept a `className` and updates the banner to use it and add its custom styling through that.
Go through the different banner and button examples and make sure everything is still working as expected.

[UnstyledButton] Add component and use in banners

---

src/components/Button/README.md

Noticed this while reading the documentation:
http://polaris-react.herokuapp.com/?path=/story/all-components-button--plain-monochrome-button
All I have done is remove that inline-style. I'm guessing that got added by accident?

🎨 [Button] Remove the inline style from plain monochrome example

---

playground/DetailsPage.tsx
src/components/Frame/README.md
src/components/TopBar/README.md
src/components/TopBar/_variables.scss
src/components/TopBar/components/Search/Search.scss
src/components/TopBar/components/Search/Search.tsx
src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss
src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.tsx
src/components/TopBar/components/SearchField/SearchField.scss

- Adjusts width of search results so that they match the search field
- Makes the backdrop cover 100% of the screen (behind the text input + results)
- Adds a background to the search results. We currently recommend that users pass in a Card as a background, but this change adds a "forced" background to the results. This is because the NDL requires 1) a light mode shadow around the component and 2) dark mode contents of the component. This is quite tricky to achieve so it makes sense for the Polaris component to take care of that logic.
View the changes locally in Storybook and go to the Details page. …

Update search input and results to new design language

---

src/components/Connected/Connected.scss
src/components/TextField/README.md

Fixes https://github.com/Shopify/polaris-ux/issues/445
Makes sure the border radius removal of connected fields happens when the newDesignLanguage is not on.

Connected fields stop child border radius

---

src/components/TextField/TextField.scss

Fixes #3403
This updates the background color of the stepper buttons on number fields.

[TextField] Updated number field spinner bg

---

src/components/TopBar/components/SearchField/SearchField.scss

Adjust the colors of the top bar search. Based on [this Figma file](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-(Web)%3A-Components?node-id=22369%3A1350).
The search background is now `--p-surface-neutral`.
Default:
Focused:
Default:
Focused:

[new DL] Tweak topbar search input colors

---

src/components/BulkActions/BulkActions.tsx

Co-Authored-By: Andrew Musgrave <24610840+andrewmusgrave@users.noreply.github.com>
Fixes bulk actions from hiding actions when on small screen sizes.
Adding a clamp around the counter to stop it from returning `-1`.
@AndrewMusgrave and Alex tophatted this in a build consumer for web.
</details>

Fixes bulk actions from hiding actions when on small screen sizes

---

playground/DetailsPage.tsx
src/components/Popover/Popover.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/TopBar/components/Menu/Menu.tsx
src/components/TopBar/components/SearchField/SearchField.scss
src/components/TopBar/components/UserMenu/UserMenu.tsx

Allows theming of the contents of `Popover` and `Menu`. This allows the `Topbar.UserMenu` to dark mode for its content
Makes the `Popover`, `Menu` and `Topbar.UserMenu` components accept a colorScheme prop which sets the color scheme for their contents. Apologies for the prop drilling.

[new DL] Update user menu to accept a colorScheme prop

---

src/components/Page/components/Header/Header.scss
src/components/Page/components/Header/Header.tsx

Fixes #3457. When rebuilding Page for the new design language I stripped much of the extra styling, wrappers, etc in an effort simplify the component to a basic conditional layout of primitives and subcomponents. Although a few of those wrappers handle the hiding of actions, etc when printing. 
Printing is frequently used on order pages.
Hiding elements that should not be printed.
|Legacy|Before|After|
|---|---|---|
|<img width="731" alt="Screen Shot 2020-10-09 at 12 54 44 PM" src="https://user-images.githubusercontent.com/344839/95626269-d566f580-0a2e-11eb-9b49-e66f25d762f5.png">|<img width="718" alt="Screen Shot 2020-10-09 at 12 56 03 PM" src="https://user-images.githubusercontent.com/344839/95626281-db5cd680-0a2e-11eb-916d-b33c9fdfa776.png">|<img width="697" alt="Screen Shot 2020-10-09 …

[Page] Fix up print styles

---

src/components/UnstyledButton/UnstyledButton.scss
src/components/UnstyledButton/UnstyledButton.tsx

We are having issues with the data attribute styling and since this isn't actually used yet, we will remove it.
This removes the attribute and styles.
Look around storybook and make sure buttons and banners still look correct.

Remove unstyled button styles

---

src/components/Badge/Badge.scss

Currently badges are a bit too big in the new design language
This sets the border width to 0 so they are the correct size.
*Before*
*After*

[Badge] Set border width to 0 in new design language

---

src/components/Page/components/Header/components/Title/Title.scss
src/components/Page/components/Header/components/Title/Title.tsx

This is a part of https://github.com/Shopify/polaris-rails/issues/2182
Changes the fontsize and breakpoints for the page title in the new design language.

Change breakpoint for page title

---

UNRELEASED.md
playground/DetailsPage.tsx
src/components/TopBar/components/Search/Search.scss
src/components/TopBar/components/Search/Search.tsx
src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss

- Makes the global search backdrop visible in the DetailsPage
- Changes the background of the backdrop to transparent (when new DL is on)
- Adjusts where in the DOM the backdrop lives. Before, the overlay lived inside the search results. Due to recent changes, the search results has a background, which caused the overlay to overlay that very background. So, I've moved the overlay outside the results wrapper.

[new DL] Change backdrop properties 

---

src/components/ActionMenu/components/Actions/Actions.tsx

This improves the rendering performance of the page actions.
Rather than storing everything in state, this moves some of the variables to refs and only uses state for the rollup and showable actions. This way all the calculations are done and then the actions get set which will cause the render.
Try the details page in Storybook. It should behave the same as before but a little more performant.

[Page] Only re-render actions when needed

---

src/components/Autocomplete/README.md

The useCallback function requires any variables used within the callback to be listed as dependencies. In three of the five example code samples, there are missing dependencies for the `useCallback` functions. This triggers the `list options as dependency` linting error.
No issue created, context given above - this is fixing the example code for this component
Adds the dependencies to the `useCallback` dependency list for:
* basic autocomplete
* autocomplete with loading
* autocomplete with lazy loading

[AutoSuggest] Add options as dependency to useCallback function

---

src/components/ActionList/ActionList.scss
src/components/ActionList/components/Item/Item.tsx

Adjusts the **divider** and **icon** colors inside the `ActionList` component.
Before:
After: 
Changes to light mode should me minimal. It looks like this now:

[new DL] Change actionlist colors

---

.travis.yml
src/components/Banner/tests/Banner.test.tsx
src/components/BulkActions/BulkActions.tsx
src/components/BulkActions/tests/BulkActions.test.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

`yarn run type-check` currently fails thanks to errors in test files. This is not picked up in CI as we don't currently run `type-check` on CI. We run `build` but the TypeScript compilation in that does not run over test files - as we don't want to ship d.ts files for tests.
We should check for these errors in test files on CI.
- Add running `yarn run type-check` to build
- Fix TS issues in test files so `yarn run type-check` passes.
- Check CI fails on the first commit, that introduces type-check into CI
- Check CI passes on the second commit that fixes the issues

Add type-check to build

---

src/components/TopBar/components/Menu/Menu.tsx
src/components/TopBar/components/UserMenu/UserMenu.tsx

Fixes a build failure we discovered while bumping to Polaris 5.8.1 in online-store-ui: https://buildkite.com/shopify/online-store-ui-ci-builder/builds/8306#27f9ee5a-def9-4cb1-91de-95d85ac9e0ba
The failures were introduced by this PR: https://github.com/Shopify/polaris-react/pull/3444, specifically, these commits:
- https://github.com/Shopify/polaris-react/pull/3444/files#diff-bb31735a2c3f8b76eb4bbf583ac614656bb24f0ddc16b96f8d1d8de0e7537e45R1
- https://github.com/Shopify/polaris-react/pull/3444/files#diff-6b3d63bdf419ad7549aa371f3c9553aaa45f93ea222df174c043ed1109f8b50bR1
The problem is that those imports should be relative paths rather than using aliased imports.
Changes the imports to relative paths

[Fix types] Change aliased import to relative path

---

src/components/ActionList/ActionList.scss

Adjusts the color of the pressed state of ActionList items
Before:
After:
</details>

[new DL] Adjust ActionList pressed state color

---

src/components/ActionList/ActionList.scss

When rendered in Rails, ActionList items using the `<a>` element (not `<button>`), gets underlines and blue color when hovered. 
This PR forces the link to inherit the color and not to have an underline.
- In the Storybook, I modified the `Playground` so that the ActionList items renders link elements, not buttons. This is done by passing a url for each item.
- I then injected a bit of CSS into the the page:
```jsx
<style
dangerouslySetInnerHTML={{
__html: 'a:hover { color: red; text-decoration: underline; }',
}}
/>
```
When inspecting each item, I could see that the injected styles were overridden...
...by the new styles that this PR adds:

[new DL][ActionList] Force color and no text decoration

---

src/components/DatePicker/DatePicker.scss

Before:
After:
https://screenshot.click/screencast_2020-10-19_11-22-39.mp4

[DatePicker] Fix selector order

---

UNRELEASED.md
src/utilities/components.tsx

Fixes https://github.com/Shopify/app-extension-libs/issues/996
This change allows Argo to bypass default type check when rendering to avoid nested StackItem.
According to discussion here https://github.com/Shopify/app-extension-libs/issues/996#issuecomment-710437088, adding `__type__` check is a generic way to support Argo usage without having a Argo and Polaris depended on each other. 
<details> …

Allow type override for components like StackItem

---

UNRELEASED.md
src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss

Fixes https://github.com/Shopify/polaris-react/issues/3506 (at least on indexes)
*Additional context:* The `SaveFilterControl` component in web that was built in collaboration with this needs the same overflow fix so I'll update that in web
Hide a measurement element that's causing overflow
Try this on master vs my branch
* Load up the playground
* Shrink your screen
* 🧙‍♂️
<details>
```jsx
import {
Page,
ResourceList,
ChoiceList,
Filters,
Card,
RangeSlider,
TextField,
Avatar,
TextStyle,
return (
<ResourceListFiltersExample />
</Page>
);
}
function ResourceListFiltersExample() { …
```

[Filters] Hide overflow

---

UNRELEASED.md
src/components/AppProvider/AppProvider.tsx
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/Frame/components/ToastManager/tests/ToastManager.test.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/Pagination/tests/Pagination.test.tsx
src/components/PolarisTestProvider/PolarisTestProvider.tsx
src/components/PolarisTestProvider/tests/PolarisTestProvider.test.tsx
src/components/Portal/Portal.tsx
src/components/Portal/tests/Portal.test.tsx
src/components/Tabs/tests/Tabs.test.tsx
src/utilities/portals/PortalsContainer.tsx
src/utilities/portals/PortalsManagerProvider.tsx
src/utilities/portals/context.tsx
src/utilities/portals/hooks.ts
src/utilities/portals/index.ts

This is an alternative approach to https://github.com/Shopify/polaris-react/pull/3465. 
It changes the portals to use a provider that passes context for the container to render into instead of relying on all the manual DOM manipulation we have currently.
<details>
```jsx …
```

Portals with provider

---

UNRELEASED.md
src/components/Button/Button.scss

Fixes #3535 
If a button text has more than 2 lines, the connected disclosure height does not follow the button height, it stays at 36px no matter what.
<details>
<summary>See example</summary>
</details>
This is happening because the connected disclosure div has no height set, and this in combination with the wrapper having a `align-items: center;` is making the connected disclosure height to never change regardless of what happens to its father div.
Makes sure the height of the disclosure div has a height of 100%, which will make sure it will follow the parent component height, so when the Button text makes the button bigger, the parent and the sibling (the connected disclosure) will follow the change height.
<details>
<summary>Before</summary>
</details>
<details> …

[Button] Fix connectedDisclosure height when text has more than 2 lines

---

UNRELEASED.md
src/components/MediaCard/MediaCard.tsx
src/components/MediaCard/README.md
src/components/MediaCard/tests/MediaCard.test.tsx

To keep add more functionality to the MediaCard similar to what regular Cards are already doing. So far, MediaCards do not accept ReactNodes as a title. If you do, the console log throws a bunch of warnings that you shouldn't nest stuff in paragraphs.
Also, when using a MediaCard, you are forced to set a primaryAction. This is not always wanted behavior. Maybe you just want to display something.
It allows the MediaCard title to accept a ReactNode. In addition, it makes the primaryAction optional.
</details>

[MediaCard] Update to accept ReactNode as title and optional primaryAction

---

UNRELEASED.md
src/components/Button/Button.tsx
src/components/Button/tests/Button.test.tsx
src/components/ResourceItem/tests/ResourceItem.test.tsx
src/components/UnstyledButton/UnstyledButton.tsx
src/components/UnstyledButton/tests/UnstyledButton.test.tsx
src/types.ts
src/utilities/focus.ts

**The goal of this PR is to consolidate concerns between `UnstyledButton` and `Button`.**
Not too long ago, [I posted this message on Slack](https://shopify.slack.com/archives/CJJD1Q7PT/p1602599400307500), which got answered by @dfmcphee - revealing that a [`UnstyledButton`](https://github.com/Shopify/polaris-react/pull/3406) had just got merged to help folks utilize the mechanics of `<Button />` while applying their own styling.
`UnstyledButton` will allow me to do away with a custom "action" component I crafted, and instead consume the Polaris component while passing my own styles + `children`. There will be some more work to be done however... and I am planning to propose a few API additions / component tweaks in the near future.
Before I do that, I thought it best to dig into what …

🎨 [Button] Simplify code by utilizing more of UnstyledButton

---

UNRELEASED.md
playground/DetailsPage.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/utilities/theme/index.ts
src/utilities/theme/utils.ts

This is an alternative approach to https://github.com/Shopify/polaris-react/pull/3546.
Currently we output the custom properties on each level of `ThemeProvider` even if they are identical to the parent.
This changes the ThemeProvider to compare the generated custom properties with the parent context and only output them if they differ.
I committed a change to the Details Page example to try this out. If you change to the new design language …

Optimize ThemeProvider custom properties output

---

UNRELEASED.md
src/components/Tooltip/Tooltip.tsx

Fixes #3541 
Change content prop's type to not only accept string, but any React.Node.
<details>
```jsx
return (
</Page>
);
}
```
</details>

[Tooltip] Change content type to allow React.Node

---

UNRELEASED.md
src/components/TopBar/TopBar.scss
src/components/TopBar/TopBar.tsx

Fixes #3522  
Currently, if I don't set `showNavigationToggle` or `searchField` but have a `logo` specified in my theme, the `logo` disappears when the screen width is smaller than `769px`. 
This PR fixes that by always showing the logo when `showNavigationToggle` or `searchField` is not set.
Video: https://screenshot.click/19-12-ukcl3-vzxzx.mp4
If `showNavigationToggle`  or `searchField` is set, we use the current css, just split into 2. This keeps the current functionality. 
If `showNavigationToggle` or `searchField` is NOT set, we always set `display: flex`. The result is the `logo` is always shown. …

[TopBar] Show logo when no navigation and search fields

---

UNRELEASED.md
package.json
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx
yarn.lock

Fixes https://github.com/Shopify/polaris-ux/issues/478
New icon:

Update banner critical icon to use diamond

---

.eslintrc
UNRELEASED.md
documentation/Console messages.md
package.json
src/components/DropZone/tests/DropZone.test.tsx
src/components/Filters/Filters.tsx
src/components/FormLayout/FormLayout.tsx
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/MediaQueryProvider/tests/MediaQueryProvider.test.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/Page/Page.scss
src/components/PolarisTestProvider/tests/PolarisTestProvider.test.tsx
src/components/ResourceList/components/FilterControl/types.ts
src/components/Sticky/Sticky.tsx
src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
src/components/TextField/TextField.tsx
src/components/TextField/components/Spinner/Spinner.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/components/Toast/Toast.tsx
src/components/index.ts
src/index.ts
src/utilities/color-transformers.ts
src/utilities/components.tsx
src/utilities/tests/use-is-after-initial-mount.test.tsx
src/utilities/theme/utils.ts
src/utilities/use-deep-compare-ref.tsx
src/utilities/use-deep-effect.tsx
tsconfig.build.json
tsconfig.json
yarn.lock

Keeping up to date, prepping for the future
Updates sewing-kit to 0.140.0
Updates typescript to 4.0.3
The typescript bump lets us cache TS type info when running type-checks without emiting any d.ts files - this means repeated runs of `yarn run type-check` are faster as it can use the cache. Repeated runs now take ~7s instead of ~20s).
The SK update pulls us onto newest major versions of eslint 7.x and stylelint 13.7.x. In particular this means better support for optional chaining and we fix a few false positives in react hooks lints.
Ensure tests pass

Update sewing-kit and typescript

---

src/components/Navigation/Navigation.scss

Fixes an issue I noticed on the weekend
Before:
After:
<details>
```jsx
return (
</Page>
);
}
```
</details>

[Navigation] Hide list item overflow

---

src/components/ActionMenu/components/Actions/Actions.tsx
src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
src/components/Page/components/Header/Header.scss

Fixes: https://github.com/Shopify/polaris-react/issues/3518
Fixes: https://github.com/Shopify/polaris-react/issues/3515
**Updates to above 768px breakpoint**
**All breakpoints**
<details>
```jsx
return ( …
```

[Page actions] Style updates

---

src/components/ActionMenu/components/Actions/Actions.tsx

Fixes https://github.com/Shopify/polaris-react/issues/3581
https://screenshot.click/screencast_2020-10-29_09-16-24.mp4
If there is only one action or group, always render it before rolling up to a default menu group
~~I'll add a chroma link~~ I can't because I can't modify the details page 🤦 
On the details page: Remove all secondary actions except for duplicate, remove both action groups. 
Make sure that only duplicate appears and not the `More actions` dropdown

[Page actions] Always render single action

---

UNRELEASED.md
src/components/DataTable/DataTable.scss

A better looking DataTable in the NDL.
- Only rows that come after rows have a `top border` divider to avoid an extra bottom border on the last element (without a footer)
<kbd>![image](https://user-images.githubusercontent.com/22782157/97360650-d98b7380-1874-11eb-8133-1d6b62547798.png)</kbd>
- Added missing border radius' to the footer elements.

[DataTable] Styling improvements to borders in the new design language

---

src/components/ResourceItem/ResourceItem.scss

Before: https://screenshot.click/screencast_2020-11-02_16-28-41.mp4
After: https://screenshot.click/screencast_2020-11-02_16-29-15.mp4
Adding border-bottom-radii to the last item in resource list
Hover over the last item in a resource list and its border radius gets weird.

[ResourceItem] Fix border-radius on last element

---

src/components/Icon/Icon.tsx
src/index.ts
src/types.ts
src/utilities/color-new-design-language.ts

Just happened to notice this while working on some other code. I'm moving a utility function out of `/types` and into its own `/utilities` file.

🚚 [Utilities] Move isNewDesignLanguageColor to a new file

---

UNRELEASED.md
scripts/accessibility-check.js
src/components/Button/Button.tsx
src/components/Button/tests/Button.test.tsx
src/components/UnstyledButton/UnstyledButton.tsx
src/components/UnstyledButton/tests/UnstyledButton.test.tsx
src/types.ts

Following up on https://github.com/Shopify/polaris-react/pull/3494 - I am adding a `role` prop to both the `UnstyledButton` and `Button` components.
We utilize this in `online-store-ui` to set a `menuitem` value for our `RTE > Toolbar` items.
We could have gotten away with passing any arbitrary prop to `UnstyledButton`, since it accepts `[key: string]: any;` in its `Props` interface... but! We do apply a `role="alert"` if `loading`... so it is best to explicitly define a `role` prop on the interface so that we can pass a custom value.
- Do I need to update the `Button > README` to include some information on this new `role` prop?
- Should we pass `role` to `UnstyledLink`?
- I ask because we did not set `role="alert"` when `loading`
- If we disallow `role` on `UnstyledLink`, should be log …

✨ [Button] Add new role prop

---

UNRELEASED.md
src/components/Popover/Popover.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
src/components/Popover/tests/Popover.test.tsx
src/components/index.ts

I'm currently working on an alternate implementation of Autocomplete and need a few minor changes done to Polaris. Although these will not impact the current Autocomplete they will help fix issues there as well should it be needed.
I'm also using this PR to export the `labelId` function, which I also need for a11y on my implementation of Autocomplete.
1. export the `labelId` function from label. This will be used to assign an `aria-labelledby` prop to the list/
2. added a `preventFocusOnClose` prop to popover to prevent the textfield to gain focus when tab out of the field.
3. remove the `tabindex=-1` when preventAutoFocus is enabled. This triggered the focus to that div when scrolling the popover which is not the desired behavior for popover and can be unexpected outside popover. 
For …

[Popover ] Fix for preventAutofocus and remove focus onClose

---

UNRELEASED.md
src/components/Modal/components/Header/Header.scss

This is supposed to be using the divider color. `border('divider')` returns `var(--p-divider)` with the new design language.

[Modal] Use correct color for header border

---

UNRELEASED.md
src/components/TopBar/components/SearchField/SearchField.scss

Fixes https://github.com/Shopify/web/issues/33665
1. `dev up && dev s`
1. Open 192.168.0.11:6006 on an iOS device with safari
1. Go to the details page and type into the search input
1. Test in other browsers to make sure the clear button has no regressions

Search clear button iOS alignment

---

UNRELEASED.md
src/utilities/color-transformers.ts
src/utilities/tests/color-transformers.test.ts

I was originally investigating this issue in Shopify web https://github.com/Shopify/shopify/issues/265949
and found that the color-transformers on Polaris would convert both hex values `#888888` and `#878787` to the same HSB value `{ hue: 0, saturation: 0, brightness: 0.53 }`. The calculating actually looked correct, `#888888` was being converted to `0.5333` and `#878787` was being converted to `0.5294`. But the final step of the conversion limits these to only two decimal places, which resulted in the brightness values being rounded to `0.53` in both cases and losing their precision.
The Shopify Web ticket has more details on the original issue.
This PR fixes the `color-transformers` issue by increasing the brightness value's precision from 2 decimal points to 4. 
It also adds two tests …

[color-transformers > rgbToHsbl] Fix brightness precision of HSB conversions by increasing from 2 decimal digits to 4

---

UNRELEASED.md
src/styles/foundation/_focus-ring.scss

This PR updates the `focus-ring` mixin to include `color('indigo')` as a fallback value for the `box-shadow` color.
This allows me to use `@include focus-ring` in my consuming app/library without the need to detect the "new design language" and have conditions in both my `TSX` and `SCSS`:
```tsx
import {classNames} from '@shopify/css-utilities';
import {useFeatures} from '../FeaturesProvider';
// Hook to detect if app is using `new design language`
const {newDesignLanguage} = useFeatures();
const myClassNames = classNames(styles.MyComponent, {
[styles.newDesignLanguage]: newDesignLanguage,
});
```
```scss
.MyComponent:not(.newDesignLanguage) {
// Old design language focus styles
}
.MyComponent.newDesignLanguage {
// New design language focus styles
}
```
This will still be "new design …

💄 [SCSS] Apply old design language color fallback to focus-ring

---

playground/DetailsPage.tsx
src/components/ActionMenu/components/Actions/Actions.tsx

Fixes https://github.com/Shopify/polaris-react/issues/3575
[Screencast](https://screenshot.click/screencast_2020-11-11_12-09-38.mp4)
Update the measuring calculation.
Stricter check on rolled up groups.
Only re-measure when showable actions and rolled up actions length are 0
This change should be tophatted in web because our playground behaves slightly differently in web. Although I did add some changes to the details page that should better reflect what's happening in web.
`yarn run build-consumer web`
Tophat around admin pages

[Actions] Do not re-measure on every re-render

---

src/components/Frame/Frame.scss
src/components/Frame/Frame.tsx
src/components/Frame/tests/Frame.test.tsx

Alternative to https://github.com/Shopify/polaris-react/pull/3598
Buttons use `Link` under the hood and web will not render an href for any links that may contain JS. This link does not need to use React router so why not just make it a plain anchor?

[Frame] Change skip to content from button to anchor tag

---

UNRELEASED.md
src/components/FocusManager/tests/FocusManager.test.tsx
src/components/TrapFocus/TrapFocus.tsx
src/utilities/focus-manager/hooks.ts
src/utilities/focus-manager/tests/hooks.test.tsx

* Only add a focus item when trapping is true - multiple trap focusing can be on a page, while not active
* Build consumer into web & test focus management with the Filters components

[Filters/FocusManager] Manage filter focusing

---

UNRELEASED.md
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/utilities/theme/types.ts

Fixes https://github.com/Shopify/polaris-react/issues/3634
The react render tree has theme provider wrapping portals so that portals can receive that context. 
They're doing sort of the right thing in terms of not rendering the custom properties when the color schemes match i.e. a theme provider with dark color scheme wrapping a popover with a dark color scheme won't render the custom properties because it's determining that it doesn't have to based on context. The problem is that it renders outside of where those properties are set in the DOM
This adds a `rendersOutsideOfContext` prop specifically for portal items that depend on context but also render outside of it.
I've thought of alternate approaches as well:
1. Wrapping this around portal provider. This doesn't work because it's …

[ThemeProvider] Add prop to force custom properties on elements that render outside of context

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/Button/README.md

Fixes https://github.com/Shopify/polaris-react/issues/3663
Adds possibility to stretch button content over its full width for dropdown triggers.
Corresponding feature request: https://github.com/Shopify/intl-shipping-methods/issues/910
<details>
```jsx
return (
<Button disclosure fullWidth stretchContent>
Stretched Button
</Button>
</Page>
);
}
```
</details>

[Button] Add content stretch capability, fix 3663

---

UNRELEASED.md
locales/cs.json
locales/da.json
locales/de.json
locales/en.json
locales/es.json
locales/fi.json
locales/fr.json
locales/it.json
locales/ja.json
locales/ko.json
locales/nb.json
locales/nl.json
locales/pl.json
locales/pt-BR.json
locales/pt-PT.json
locales/sv.json
locales/th.json
locales/tr.json
locales/zh-CN.json
locales/zh-TW.json
src/components/Badge/Badge.tsx
src/components/Badge/tests/Badge.test.tsx

Linking internal issue below
Separating progress & status labels. Previously they're combined (placing adjacent markup in spans). Resulting in `AttentionComplete` for example. Apart from being a single word, we're assuming this is optional for all locales. I added a separate translation key, so the correct orientation can be applied for each language.
* Play around with progress/status and voice tools.
<details>
```jsx
import {Page, Card, Badge} from '../src';
return (
<Example />
</Page>
);
}
function Example() {
return (
<div style={{height: '200px'}}>
<Card sectioned>
<Badge progress="complete" status="attention">
status …
```

Separate progress & status labels

---

UNRELEASED.md
src/components/Card/Card.scss
src/components/Card/README.md
src/components/Card/components/Section/Section.tsx

Addresses: https://github.com/Shopify/marketing-integrations/issues/1052
Adds a `flushed` prop to `Card.Section`. The `flushed` prop removes both the vertical and horizontal padding on the corresponding `Card.Section` that it has been applied to. 
Without the `flush` prop:
Withe the `flush` prop:
<details>
```jsx
import {Page, Card, …
```

[Card] Adds flushed prop to <Card/> Section

---

UNRELEASED.md
src/components/ActionList/ActionList.scss
src/components/OptionList/components/Option/Option.scss
src/styles/shared/_interaction-state.scss

Fixes #3611
ActionList indicator styles were [updated within Figma to use the same styles as OptionList](https://github.com/Shopify/polaris-react/issues/3258#issuecomment-694931240)
This PR fixes the alignment issue in #3611 by moving the OptionList indicator styles into a shared mixin that can be used by both the OptionList and the ActionList. 
Action list after:
Option list after:

[ActionList] Align ActionList ::before indicator with OptionList

---

src/components/DataTable/DataTable.scss

Fixes part of https://github.com/Shopify/polaris-ux/issues/453
Before:
After:
Adds the focus ring to Data Table headings
Visit the data table page in the chroma link below when it's been generated. Make sure the new design language has been enabled

[DataTable] Add focus ring to heading

---

UNRELEASED.md
src/components/Popover/Popover.tsx
src/components/Popover/README.md
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
src/components/index.ts

Fixes #3602
By using the existing utility function `findFirstFocusableNode` try to find the first focusable child node and set the focus on it when the `Popover` is activated.
If no focusable nodes are present keep the current focus on the container.
This PR extends the `focusContent` functionality of the `PopoverOverlay` component by searching for the first focusable node and setting the focus on it if available.
Simply enhancing the focus to look for the first focusable node would change the behaviour of the component so I decided to add a new prop `autofocusTarget` which can have three options: `none`, `container`, `first-node`.
- `none` is equal with the current `preventAutofocus`:`true` prop so I would suggest to gradually replace it
- `container` would be default option and would …

[Popover] Focus first focusable node

---

translation.yml

The file has not been updated with the rollout of Vietnamese (`vi`) in other repositories. This omission is causing mixed-language issues in multiple places in the admin.
Updating our `translation.yml` with the latest list of supported languages so that the translation platform keeps our locales in sync with what the product supports.

[i18n] Add Vietnamese to supported languages

---

UNRELEASED.md
src/components/DatePicker/DatePicker.scss
src/components/DropZone/DropZone.scss
src/components/Filters/Filters.scss
src/components/Tabs/Tabs.scss
src/components/Tabs/Tabs.tsx
src/components/Tag/Tag.scss
src/styles/foundation/_accessibility.scss
src/styles/foundation/_focus-ring.scss
src/styles/shared/_buttons.scss

Fixes #3673 (while navigating tabs via keyboard, the disclosure tab is not visibly accessible with `tab` key)
**1. Fixes Windows High Contrast hover state** 
| Before        | After           |
|![CURRENThoverstate](https://user-images.githubusercontent.com/43223543/101379122-eb9fff00-3881-11eb-8f24-08566f45e464.jpg)|![NOW with no disclosure](https://user-images.githubusercontent.com/43223543/101379346-273ac900-3882-11eb-9833-0f6b495fea8a.jpg)
(please note: that the mouse is CURRENTLY on `Prospects` on the `Before` photo, but there is no outline)
(ignore the different order - will post issue after)
| Before        | After           |
|![currentHOVER overProspects](https://user-images.githubusercontent.com/43223543/10137923 …

[Tabs][a11y]: implement focus ring for disclosure and fix high contrast mode on focus and hover

---

service.yml

`@Shopify/polaris` is not a team. The team is @Shopify/polaris-team
Fixing the metadata. This gets used by ServicesDB, which is then used by various tools (including the Translation Platform).

Fix the @-mention to be the actual team name

---

src/components/MediaCard/README.md
src/components/VideoThumbnail/README.md

Fixes #3712 
This PR fixes the URL of some images that are used for the examples of the [MediaCard](https://polaris.shopify.com/components/structure/media-card) and [VideoThumbnail](https://polaris.shopify.com/components/images-and-icons/video-thumbnail) components. 
Replaces this URL:
- https://burst.shopifycdn.com/photos/smiling-businesswoman-in-office.jpg?width=1850
by this one:
- https://burst.shopifycdn.com/photos/business-woman-smiling-in-office.jpg?width=1850

fix: image url in mediacard and thumbnail example

---

UNRELEASED.md
src/components/Filters/Filters.tsx
src/components/Filters/README.md
src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
src/components/Filters/components/ConnectedFilterControl/tests/ConnectedFilterControl.test.tsx
src/components/Filters/tests/Filters.test.tsx

Whenever a `Filters` component is used, it always includes the search text input field. 
Text search doesn't make sense in all contexts that a `Filters` can be used in.
Related Feature Request
https://github.com/Shopify/polaris-react/issues/3671
Original PR that was closed:
https://github.com/Shopify/polaris-react/pull/3674
This PR adds an optional boolean prop named `hideQueryField` which hides the query text field.
Here is the how the Filters component currently looks:
Here is what the Filters component looks with the query text field hidden:
📄 [Changelog …

[Filters] Make Filters Query Text Field Optional [#SOPS-81]

---

UNRELEASED.md
scripts/accessibility-check.js
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
src/components/Autocomplete/components/TextField/TextField.tsx
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Fixes accessibility issues related to autocomplete
1. ARIA attribute is not allowed: aria-expanded="false"
2. ARIA attribute is not allowed: aria-multiline="false"
1. Fixed with moving `role="combobox"` from the `div` to the `input`
2. Fixed by removing `multiline` in `TextField` if it is undefined or false (only added when needed )
Followed these two examples:
- [WCAG example of combobox](https://www.w3.org/TR/wai-aria-1.2/#example-6) from @dleroux original PR
- [Gov UK autocomplete](https://alphagov.github.io/accessible-autocomplete/examples/) component

Address accessibility issues in AutoComplete and TextField

---

UNRELEASED.md
scripts/accessibility-check.js
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx

Fixes accessibility issue `ARIA role slider is not allowed for given element`
Replacing `button` with `div`. When using `role="slider"` it should not be applied to a `button` element. [Following the examples on MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role#Example_2_Text_Values) we replace `button` with `div` update the types and add a `tab-index` for focus management.

RangeSlider - Use a non semantic element for role="slider"

---

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/ISSUE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/discoverability.yml
.prettierignore

Co-Authored-By: Ben Scott <227292+BPScott@users.noreply.github.com>
Not necessary to disable Prettier in this directory.
Removing the disable of prettier in `/.github/`

Remove /.github from .prettierignore

---

UNRELEASED.md
src/components/OptionList/OptionList.tsx
src/components/index.ts

We have a need for the `OptionDescriptor` and `SectionDescriptor` in `online-store-web`, so I am exporting both of these types for consumption.
Since both of these type names are somewhat generic... I've renamed their exports. Please let me know if this is following convention!

🏷️ [OptionList] Export types

---

UNRELEASED.md
src/components/OptionList/OptionList.tsx
src/components/index.ts

Reverts Shopify/polaris-react#3741
Per https://github.com/Shopify/polaris-react/pull/3741#issuecomment-749130568 I'm wary of exporting internal types and think folks should slice up the SomeComponentProps type for their component instead of us exposing the constituent types directly.
So gonna revert this for now to make sure it doesn't sneak out in a release, and we can have a conversation in the new year about if my proposal works for @beefchimi (and if not we get to bust of the fabled Revert Revert commit).

Revert "🏷️ [OptionList] Export types"

---

.github/workflows/ci.yml
package.json
yarn.lock

`pull_request` builds checkout use a merge commit (of your branch into the base branch's tip) instead of just your branch's tip.
This means that Chromatic / Percy need too be taught about that foible and have them set custom commit information. Rather than doing that ourselves lets use the vendor-provided actions that do that for us.
See https://github.com/percy/storybook-action and https://github.com/chromaui/action
Use Chromatic and Percy actions for their respective steps
Note that the "Storybook Publish" check that links to the published storybook is now being correctly set.
Note that Percy's PR / base branch info is now being set: https://percy.io/Shopify/polaris-react/builds-next/8256288/unchanged/469473165?browser=chrome&viewLayout=side-by-side&viewMode=new&width=1280 -> Click the …

Use vendor-provided actions for Chromatic and Percy

---

UNRELEASED.md
src/styles/foundation/_accessibility.scss

Fixes #3774
The mixin `ms-high-contrast-mode` in `_accessibility.scss` uses a media query that is non-standard and only supported by Microsoft Edge (version < 18). Alternatively, `forced-colors` media query could be used, but it is not optimal since it requires a beta flag to be manually enabled in Firefox (version > 81). The current color used (windowText) seems to also be deprecated.
The use of just a transparent outline seems to be commonly recommended solution to support a wider range of browsers, without disrupting non-high-contrast environments. 
More information can be found here: 
https://drafts.csswg.org/css-color-4/#deprecated-system-colors (windowText being a deprecated system color)
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast (non-standard media …

Improve accessibility HCM mixin to work in other browsers

---

src/components/Banner/Banner.scss
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx

Resolves Shopify/polaris-ux#590
Removes references to newDesignLanguage in the Banner component
Banner component with new design language should look identical

[Banner] Remove NDL fallbacks

---

UNRELEASED.md
src/components/Pagination/Pagination.tsx

Make accessibility required for version 6.
Removing the ability to not add pagination.

Make pagination labels required in v6

---

UNRELEASED.md
src/components/TrapFocus/TrapFocus.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

`TrapFocus` blocks focus inside of portals
|Before|After|
|-|-|
|![Screen Recording 2021-01-07 at 12 42 44 PM](https://user-images.githubusercontent.com/24610840/103925789-0adeb600-50e6-11eb-8f9a-63b77b5e7da0.gif)|![Screen Recording 2021-01-07 at 12 41 25 PM](https://user-images.githubusercontent.com/24610840/103925799-0dd9a680-50e6-11eb-9f06-7e63d79bdbe8.gif)|
Allowing focus inside of portals while trapping focus
* Playground setup with modal + popover + actionlist
<details>
```jsx
import React, {useCallback, useState} from 'react';
import {Page, Modal, Button, TextContainer, Popover, ActionList} from '../src';
return (
<ModalExample />
</Page>
);
} …
```

Added ability to navigate in portals during focus trapping

---

src/components/PositionedOverlay/tests/PositionedOverlay.test.tsx
src/components/SkeletonPage/SkeletonPage.scss
src/components/SkeletonPage/SkeletonPage.tsx
src/components/SkeletonPage/tests/SkeletonPage.test.tsx

Fixes https://github.com/Shopify/polaris-ux/issues/541
Removes new design language fallbacks
Keep in mind that changes still need to be made to page and card so there will be a few margins that are off when comparing to what's in heroku

[SkeletonPage] Remove new DL fallbacks

---

UNRELEASED.md
src/components/Tabs/Tabs.tsx
src/components/Tabs/tests/Tabs.test.tsx

Fixes https://github.com/Shopify/web/issues/34637
The way the Tabs component was build allows users to (unknowingly) introduce an a11y error (`aria-valid-attr-value`). This happens when the Tab component is used without children (tab panel). The component sets an `aria-controls` value, even if there is no associated panel with the same `id`. This then throws the a11y error because the aria controls value needs to match the id of the associated panel. 
[Here are more details about why this happens and a look at the code.](https://github.com/Shopify/polaris-react/issues/3692) 
This PR implements [Solution 1](https://github.com/Shopify/polaris-react/issues/3692) outlined in an issue where I describe the problem. I have updated the component to conditionally assign the aria-controls id based …

[Tabs] Fix aria-controls related a11y error

---

UNRELEASED.md
playground/DetailsPage.tsx
src/components/ActionMenu/components/Actions/Actions.tsx
src/components/ActionMenu/components/Actions/tests/Actions.test.tsx
src/components/Page/tests/Page.test.tsx

Fixes: https://github.com/Shopify/polaris-react/issues/3575
And allows actions and groups to re-render in their previously assigned position, only re-measuring if the lengths of actions and groups changes
There's now a toggle in the details page under more actions that changes the actions length. Make sure that works properly and re-measures on toggle
Also make sure that the view button logs out the updated product description

[Page Actions] Re-render without measuring when actions / groups change

---

src/components/Link/Link.scss
src/components/Link/Link.tsx
src/components/Link/tests/Link.test.tsx

These changes are introduced as part of polaris-v6, where all reference to the newDesignLanguage are being removed. Fixes Shopify/polaris-ux#563.
This pull request removes all references to the newDesignLanguage and any fallbacks in the Link component on polaris-react.
<details>
```jsx
import …
```

[Link] Remove new DL and fallbacks

---

src/components/Page/Page.tsx
src/components/Page/components/Header/Header.scss
src/components/Page/components/Header/Header.tsx
src/components/Page/components/Header/components/Title/Title.scss
src/components/Page/components/Header/components/Title/Title.tsx
src/components/Page/components/Header/components/Title/tests/Title.test.tsx
src/components/Page/components/Header/tests/Header.test.tsx
src/styles/shared/_page.scss

Fixes https://github.com/Shopify/polaris-ux/issues/556
Removes new DL conditions and merges styles with legacy for Page and Header components
Opening as a draft because I recommend considerable tophatting. 
Start with the page examples in storybook and then move to the details page
On the details page, remove / modify all page props in as many configurations you have time for. 
Test both at as many break points as possible

[Page, Header] remove new DL

---

src/components/Navigation/Navigation.scss

Fixes https://github.com/Shopify/polaris-react/issues/3785
This bug was introduced by me adding a tabindex to scrollable. Removing the outline on focus seems to be a valid solution here. It's not really adding much value
Before:
After:
<details>
```jsx
return (
<Page …
```

[Navigation] Remove outline on focus

---

src/components/ColorPicker/ColorPicker.scss

Fixes https://github.com/Shopify/polaris-ux/issues/582
Fixes https://github.com/Shopify/polaris-react/issues/3789
Removes references to newDesignLanguage in the Color picker component

[Color picker] Remove NDL fallback

---

src/components/DatePicker/DatePicker.scss
src/components/DropZone/DropZone.scss
src/components/Filters/Filters.scss
src/components/Tabs/Tabs.scss
src/components/Tag/Tag.scss
src/styles/foundation/_accessibility.scss
src/styles/foundation/_focus-ring.scss
src/styles/shared/_buttons.scss

The media query name was changed in https://github.com/Shopify/polaris-react/pull/3675 Sounds like it was supposed to be changed back in https://github.com/Shopify/polaris-react/pull/3775 but may have been missed. This change would need to be included in a major version as its a breaking change.
I'm omitting a changelog entry because this change hasn't been released yet.
Undoing a name change

Undo high contrast media query name change

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/Button/README.md
src/components/Button/tests/Button.test.tsx
src/styles/shared/_buttons.scss
src/types.ts

> **Tophat:** I recommend using the provided `Playground` snippet to more easily tophat each combination of `<Button />`
<details>
<summary><strong>Playground code:</strong></summary>
```tsx
import React, {useCallback, useState} from 'react';
import {OnlineStoreMajor} from '@shopify/polaris-icons';
import {Button, Card, ChoiceList, Layout, Page} from '../src';
const childrenOptions = {
none: undefined,
short: 'Short text',
long: 'This long line of text will wrap unless truncate is true',
};
const sizeOptions = {
none: undefined,
slim: 'slim',
medium: 'medium',
large: 'large',
};
const textAlignOptions = {
none: undefined,
left: 'left',
center: 'center',
right: 'right',
};
const disclosureOptions = {
none: undefined,
up: 'up',
down: 'down',
select: 'select',
};
const toggleOptions = [ …
```

🐛 + ✨ [Button] Bug fixes, small improvements, new "select" disclosure

---

UNRELEASED.md
src/components/Tag/Tag.scss

Found in `Tags.scss` a media query for `ms-high-contrast` without a selector. This is invalid css which prevents `dart-sass` compilation and possibly generate other issues.
Put the media query back to the `Tags` class selector as it was before https://github.com/Shopify/polaris-react/pull/2774 which introduced the bug.
**Before with `ms-high-contrast` active**
**After with `ms-high-contrast` active**
<details> …

[Tags] Fix invalid ms-high-contrast media query css without selector in Tags

---

UNRELEASED.md
src/components/Modal/Modal.tsx
src/components/Modal/README.md
src/components/Modal/components/CloseButton/CloseButton.scss
src/components/Modal/components/CloseButton/CloseButton.tsx
src/components/Modal/components/Header/Header.scss
src/components/Modal/components/Header/Header.tsx
src/components/Modal/tests/Modal.test.tsx

Fixes missing label on `dialog` element that is blocking  https://github.com/Shopify/polaris-react/pull/3749 from being merged
> Ensures every ARIA dialog and alertdialog node has an accessible name
> ARIA dialog and alertdialog nodes must have an accessible name
> https://dequeuniversity.com/rules/axe/4.1/aria-dialog-name?application=axeAPI
Changes in this PR

[Modal] Ensure dialog aria-labeled-by links to element when title hidden

---

src/components/InlineError/InlineError.scss

Fixes https://github.com/Shopify/polaris-ux/issues/566
Removes references to newDesignLanguage in the Inline error component

[Inline error] Remove ndl fallback

---

UNRELEASED.md
src/components/ColorPicker/ColorPicker.scss

Fixes https://github.com/Shopify/polaris-react/issues/3789
Rather than compose the checker board with `var(--p-surface)` and `transparent` which causes it to not be visible on a `var(--p-surface)` background, compose it with `var(--p-surface)` and `var(--p-surface-neutral-subdued)` so it is still visible no matter the background colour.
Simplifies how the checker board is generated by using `conic-gradient` rather than `linear-gradient`.
:----:|:----:
Before|After

[Color picker] Refactor checker board background

---

src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/tests/Collapsible.test.tsx

Display none was doing the heavy lifting before but we have too many instances in web where we don't want to render the children if collapsed. 
Only allow the children of collapsible to render if `expandOnPrint` or `!isFullyClosed`
<details>
```jsx
return (
<Page …
```

[Collapsible] Do not render children when fully closed

---

src/components/Scrollable/Scrollable.scss

Fixes issues where if you click on any non-focusable element in a scrollable container you'll see an outline
This outline is distracting and not really useful

[Scrollable] Remove focus outline

---

src/components/Layout/Layout.scss
src/components/Layout/Layout.tsx

This is the React portion of this issue: https://github.com/Shopify/polaris-ux/issues/564
Removes the new design language fallbacks from the Layout component
To tophat this, please compare your local version and http://polaris-react.herokuapp.com/
</details>

[Layout ] Remove new design language fallbacks

---

UNRELEASED.md
src/components/Button/Button.scss
src/styles/shared/_buttons.scss

The latest release has a regression for filled button focus styles brought up by @whizkydee
This PR adds back the offset and removes some duplicated code.
1. Open the button examples and focus through them

Fix button focus offset

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx
src/components/Label/Label.tsx
src/components/Labelled/Labelled.tsx
src/components/RangeSlider/types.ts
src/components/Select/Select.tsx
src/components/TextField/TextField.tsx

The current type for `label` is `string`, which doesn’t allow us to add anything else than unstyled text to a label. This would have greatly improved https://github.com/Shopify/web/pull/35964, we currently workaround it by passing an empty label and re-implementing fields’ labels, which is not ideal… I added some examples of what a `React.ReactNode` `label` enables in the tophatting section below.
This PR updates the `Label` and `Labelled`’s `label` prop types to `React.ReactNode` and makes the necessary change anywhere that prop is drilled down (which most form fields seem to do). I think I changed every occurence, I checked and I couldn’t find any code manipulating the label and expecting it to be a string, there isn’t any TypeScript error. 😌
The `helpText` prop is already typed with …

[Label, Labelled] Change `label` prop type to `React.ReactNode`

---

UNRELEASED.md
src/styles/shared/_buttons.scss

Filled buttons have an extra line around around them due to the transparent border. This causes an unflush button shadow. Brought up by @dleroux 
Fixes the button shadow
Look at the [Percy changes](https://percy.io/Shopify/polaris-react/builds-next/8367982/changed/475920613?browser=chrome&browser_ids=9&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280)

Remove border to fix button shadows

---

UNRELEASED.md
locales/cs.json
locales/da.json
locales/de.json
locales/en.json
locales/es.json
locales/fi.json
locales/fr.json
locales/it.json
locales/ja.json
locales/ko.json
locales/nb.json
locales/nl.json
locales/pl.json
locales/pt-BR.json
locales/pt-PT.json
locales/sv.json
locales/th.json
locales/tr.json
locales/vi.json
locales/zh-CN.json
locales/zh-TW.json

The translation key is incorrect
Using camel case on the translation key
* Add an accessibility label to tooltip & use a voice assistance tool
</details>

[Tooltip] Change accessibility label translation key

---

UNRELEASED.md
src/components/Thumbnail/Thumbnail.scss

Changes thumbnail icon color subdued, as referenced in https://github.com/Shopify/web/issues/32928
Makes thumbnail icon color subdued, as referenced in https://github.com/Shopify/web/issues/32928
<details>
```jsx
return (
{/* Add the code you want to …
```

Thumbnail icon subdued

---

UNRELEASED.md
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/Frame/components/ToastManager/tests/ToastManager.test.tsx

Fixes https://github.com/Shopify/web/issues/34584 
Toast messages using aria-live set to 'polite' are ignored by screen reader. There is discussion in the linked PR as for the decision made to choose this solution over extending the time a toast spends on screen. 

[ToastManager] Change aria-live to assertive for accessibility

---

src/components/Select/Select.scss
src/components/Select/Select.tsx
src/components/Select/tests/Select.test.tsx

These changes are introduced as part of polaris-v6, where all reference to the newDesignLanguages are being removed. Fixes Shopify/polaris-ux#546.
This pull request removes all references to the newDesignLanguage and any fallbacks in the Select component on polaris-react.
<details>
```jsx
import …
```

[Select] Remove new DL fallbacks

---

CHANGELOG.md

Fix the year of the date of the last 2 releases.
2020 updated to 2021
I was reviewing Polaris's CHANGELOG.md to see what recent changes were made and saw there hadn't been any updates since January 2020. 
Realizing the dates of the last 2 releases in the changelog was actually from 2021.
Updating the dates for the last 2 releases in CHANGELOG.md to reflect the proper year.

Fix CHANGELOG.md 2021 release dates

---

UNRELEASED.md
src/components/ActionList/ActionList.scss

I noticed when tophatting the Online Store Editor bump to Polaris 5.13.1 that the indicator styles were missing from the `.active` `ActionList` buttons.
This can be resolved by removing a stray `>` child selector in `ActionList.scss`
- #3725 removed the aria-selected from  `<li>` in `ActionList`
- The `aria-selected` was used as a selector in the styles, and required the `>` child selector to target the `button` within the `li`
- The `.active` class is applied directly to the `button`, so the `>` child selector is not needed (and is preventing the indicator styles from displaying) 
**Before:**
**After**
- removes  `>` child selector in `ActionList.scss`

[ActionList] Remove child selector from .active styles

---

UNRELEASED.md
src/components/Filters/Filters.tsx
src/components/Filters/tests/Filters.test.tsx

Fixes https://github.com/Shopify/web/issues/34673
AODA Compliance: The clear all filters button becomes disabled after being clicked but retains focus, resulting in a visual loss of focus. This change focuses the next focusable node.
This PR focuses the next node in the MoreFilters footer, the Done button.
Before:
After:
<details>
```jsx …
```

[Filters] Fix loss of focus after clicking clear all filters

---

src/components/ActionList/components/Item/Item.tsx
src/components/ActionList/components/Item/tests/Item.test.tsx
src/components/ActionList/components/Section/Section.tsx

Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>

[ActionList] Remove ndl fallbacks

---

src/components/Tooltip/Tooltip.scss
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx
src/components/Tooltip/tests/Tooltip.test.tsx

This removes the light prop which was causing the a11y issue originally and some unnecessary wrapping components
<details>
```jsx
return (
</Page>
);
}
```
</details>

[ToolTip] Clean up and fixes for a11y test

---

src/components/OptionList/OptionList.scss
src/components/OptionList/OptionList.tsx
src/components/OptionList/tests/OptionList.test.tsx

Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>

[OptionList] remove ndl fallbacks

---

UNRELEASED.md
src/components/Frame/README.md
src/utilities/theme/tests/utils.test.ts
src/utilities/theme/types.ts
src/utilities/theme/utils.ts

Fixes https://github.com/Shopify/global-nav/issues/843
Some consumers need relative units for the frame offset. This takes into account for font-size and matching up breakpoints.
This PR allows for any string to be passed in i.e. `12em` and still defaults to `0px`.
Check out the frame example and try different units
</details>

[ThemeProvider] Change frameOffset to accept a string

---

UNRELEASED.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/Button/README.md
src/components/Button/tests/Button.test.tsx
src/components/Popover/Popover.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
src/components/Popover/tests/Popover.test.tsx
src/components/UnstyledButton/UnstyledButton.tsx
src/components/UnstyledButton/tests/UnstyledButton.test.tsx
src/types.ts

Removing deprecated features in a major version
- Remove Button/UnstyledButton ariaPressed - This was replaced by the `pressed` prop in Polaris v4.7.0
- Remove Button stretchContent prop: This was replaced by combining using `fullWidth` and `textAlign=left` in Polaris v5.13.0
- Remove Popover/PopoverOverlay preventAutofocus prop:This was replaced by `autofocusTarget="none"` in 5.13.0
---
The FilterControl component remains deprecated but present as web never prioritized ripping out its one remaining but knotty usage in web.

Remove deprecated features

---

src/components/Filters/tests/Filters.test.tsx
src/components/OptionList/components/Checkbox/tests/Checkbox.test.tsx
src/components/Page/tests/Page.test.tsx

Removing mentions of newDesignLanguage
Deleting mentions of newDesignLanguage in tests for components that no longer use the new DL

Remove some mentions of new DL in tests

---

UNRELEASED.md
src/components/Choice/Choice.scss
src/components/DropZone/components/FileUpload/FileUpload.scss
src/components/Frame/Frame.scss
src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss
src/components/VideoThumbnail/VideoThumbnail.scss
src/styles/shared/_skeleton.scss
src/styles/shared/_typography.scss

Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>

Add missing fallbacks, remove unused vars and mixins

---

UNRELEASED.md
src/components/DataTable/README.md
src/components/Link/Link.scss
src/components/Link/Link.tsx
src/components/Link/README.md
src/components/Link/tests/Link.test.tsx

These changes are introduced after discussions regarding if the link component should be underline by default (https://github.com/Shopify/polaris-react/pull/3697), and if color alone is able to convey controls (https://github.com/Shopify/polaris-ux/issues/455). It was determined that making the link component underline by default makes the component more accessible when color is the only way to convey a link is interactive. It was also determined that it would be easier to add a 'removeUnderline' prop if the underline was not required, as opposed to adding an underline prop every time.
Fixes Shopify/polaris-ux#455
This pull request makes the link component underline by default, and adds a 'removeUnderline' prop that removes the underline on the link.
This screenshot shows the Link …

[Link] underlined by default and add removeUnderline prop

---

src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx

`DualThumb` relies on `thumbSize` being set to match the design and also for the tests to pass.
Add comment to make the `DualThumb` tests to make them more clear.

[Range Slider] Add test comments

---

UNRELEASED.md
src/components/Icon/Icon.scss
src/components/Icon/Icon.tsx
src/components/Icon/tests/Icon.test.tsx

This is irrelevant when V6 releases. We need a way to stop the 1500+ console warns in https://github.com/Shopify/web/pull/36936 and ship the icon and spinner changes with fallbacks.
Removes the warnings in
<details>
```jsx
return (
{/* Add the code …
```

[Icon] Temporary PR to remove warning and add fallbacks

---

UNRELEASED.md
src/components/Modal/Modal.tsx
src/components/Modal/README.md
src/components/Modal/components/Header/Header.tsx
src/components/Modal/tests/Modal.test.tsx

Keeping naming consistent.
Modal's hideTitle prop differs from Page and ChoiceList's naming of titleHidden
Rename's modal's `hideTitle` prop to `titleHidden`
We've already applied this change to the v5 branch, but doing this here will make the merge a little easier.

Rename Modal hideTitle prop to titleHidden

---

locales/cs.json
locales/da.json
locales/de.json
locales/en.json
locales/es.json
locales/fi.json
locales/fr.json
locales/hi.json
locales/it.json
locales/ja.json
locales/ko.json
locales/ms.json
locales/nb.json
locales/nl.json
locales/pl.json
locales/pt-BR.json
locales/pt-PT.json
locales/sv.json
locales/th.json
locales/tr.json
locales/vi.json
locales/zh-CN.json
locales/zh-TW.json
src/components/Icon/Icon.tsx

This got removed in v6, then a merge from main brought it back. Now I'm getting rid of it again
Removing Icon Backdrop warning message

Remove Icon backdrop warning message

---

.storybook/preview.js
scripts/accessibility-check.js

Getting ready for v6. By defaulting to the new DL in storybook we get to compare the version-6.0.0 branch against main so we can check for regressions.
Change the default rendering in Storybook to use the new design language.
This is going to do a number on percy on this PR but accepting everything here as a new baseline, then comparing v6 against this new baseline will help us catch regressions.

Default to new Design Language in storybook

---

UNRELEASED.md
src/components/Page/README.md
src/components/Page/components/Header/Header.scss
src/components/Page/components/Header/Header.tsx

In the new DL Pages never have separators.
This also fixes a spacing regression between main and version-6.0.0
Remove the spacing prop on Page

Remove Page separator prop as pages never have a separator

---

UNRELEASED.md
src/components/SkeletonPage/SkeletonPage.scss
src/components/SkeletonPage/SkeletonPage.tsx
src/styles/shared/_skeleton.scss

Fixing regression between v6 and main.
- Remove SkeletonPage vertical padding
- BREAKING CHANGE: Remove skeleton-page-header-has-secondary-actions mixin as it is never
used

Fix SkeletonPage vertical padding

---

UNRELEASED.md
src/components/Tabs/Tabs.scss
src/components/Tabs/Tabs.tsx

Fixes https://github.com/Shopify/polaris-react/issues/3925
The icon color was set in SASS and incorrect on the icon. This removes the SASS and provides the color through the Icon component.
<details>
```jsx
return (
{/* Add the code you want to test …
```

Change disclosure icon color with prop

---

UNRELEASED.md
src/components/Icon/Icon.scss
src/components/Icon/Icon.tsx
src/components/Icon/README.md
src/components/Icon/tests/Icon.test.tsx

Icons in the admin are defaulting the currentColor to black.
This adds back the `.isColored` classname and functionality back and adds visual examples.
<details>
```jsx
return (
</Page>
);
}
```
</details>

[Icon] Fix issue where currentColor defaults to black

---

UNRELEASED.md
src/components/Tag/README.md
src/components/Tag/Tag.tsx

#2986  brought to my attention that there isn't a removable tag example, and that it needs to be documented that clickable tags aren't removable.
This PR adds a removable tag example and clarifies that the remove button doesn't render when `onClick` is set. 
***Note: The pa11y test failure is due to [a bug reported with `Autocomplete`](https://github.com/Shopify/polaris-react/issues/3639).

[Tag] Clarify that onClick and onRemove are mutually exclusive

---

UNRELEASED.md
locales/en.json
src/components/Frame/Frame.tsx
src/components/Frame/README.md
src/components/Frame/tests/Frame.test.tsx
src/components/Modal/components/Dialog/Dialog.tsx
src/components/Sheet/Sheet.tsx

Keyboard focus is trapped whoever virtual cursors are not
|Modal|Sheet|Nav|
|-|-|-|
|![key-modal](https://user-images.githubusercontent.com/24610840/106061999-270dbb80-60c4-11eb-8828-d920f92b1e85.gif)|![key-sheet](https://user-images.githubusercontent.com/24610840/106062018-2ecd6000-60c4-11eb-91e0-60e1b9873222.gif)|![key-nav](https://user-images.githubusercontent.com/24610840/106062035-37259b00-60c4-11eb-8e5b-e1e79eede5e2.gif)|
||Before|After|
|-|-|-|
|<b>Modal</b>|![vc-modal-old](https://user-images.githubusercontent.com/24610840/106062455-ce8aee00-60c4-11eb-9178-93e93e1ac26e.gif)|![key-modal](https://user-images.githubusercontent.com/24610840/106062489-d77bbf80-60c4-11eb-801f-34189bb8b93e.gif)|
|<b>Sheet</b>|![vc-sheet-old](https://user-images.githubusercontent.com/24610840/106062517-e19 …

[Modal, Frame(Nav), Sheet] Trapped virtual cursor inside dialogs

---

.storybook/polaris-readme-loader.js
scripts/accessibility-check.js

Storybook generates docs pages for us. Let's teach it about where to pull component docs from.
Splitting off part of the functionality of #2888 which is general investigative PR
Teaching storybook what what component corresponds to each README file.
- open storybook
- Load docs page for any story generated by a README file (which is everything but the playground)
- See that a props table is generated and displayed.

Add prop docs to generated storybook docs pages

---

UNRELEASED.md
src/components/Badge/Badge.scss

I found a way to remove a bit under a quarter of badge's generated css (3031 bytes => 2358bytes) by using a css variable instead of using a mixin
- By using a css variable we can remove the usage a mixin that added
additional selectors
- Simplify print style for progressPartiallyComplete by using a really
large spread and an offset to make it look like half of the box has
been colored in. Thus avoiding needing a pseudo-element
- Use regular selector chaining instead of nesting
Note that per #3226 we can't simplify so that we always use either background or box-shadow for pips. backgrounds are stripped off in print styles, while box-shadow renders a slight halo on screens (this seems to be due to the pip border radius, rather than the box-shadow itself)
Check playground. Note that:
- …

Refactor and simplify Badge css

---

UNRELEASED.md
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/tests/Tooltip.test.tsx

Fixes #3956
| Before        | After|
|![](https://camo.githubusercontent.com/ab26598ecfcf3bb31aa2786c403a1111583429e0edf8504ce90a90a4efda63a6/68747470733a2f2f73637265656e73686f742e636c69636b2f30322d31372d6c36307a6e2d6a36786c6f2e676966)      | ![](https://screenshot.click/02-11-k8oxb-6ph1i.gif)|
In order to tophat this you can copy and paste the following code in the playground and open it with Apple Simulator to see the behaviour illustrated in the gifs above.
```jsx
function TooltipTextFieldExample() {
const [value, setValue] = useState('');
const handleChange = useCallback((newValue) => setValue(newValue), []);
return (
<div style={{padding: '75px 0', width: '300px'}}>
<TextField
id="atPrice"
value={value}
label="Compare at price" …
```

[Tooltip] Fixed the issue with tooltip not opening in iOS when used as suffix in a TextField

---

UNRELEASED.md
package.json
src/components/AppProvider/AppProvider.scss
src/components/AppProvider/AppProvider.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
src/components/Tooltip/README.md
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
yarn.lock

Currently we use a hack for not showing focus rings on things like buttons by blurring on `mouseup`. This works, but it takes adding this behaviour specifically to every component that needs it.
This adds the `focus-visible` polyfill so that we can start taking a CSS approach to this that will eventually be supported by browsers and we can remove the polyfill at that point.
Right now this would be about a __1kb__ bundle increase, but I think we could get it to about the same once we start removing the custom click/blur code.
Here is an example of clicking or tabbing to a tooltip activator before this change:
And after this change clicking would show this:
And tabbing to would show this:
This adds the polyfill package as well as some default `focus-visible` styles for all elements.
🖥 …

Adding focus-visible styles with polyfill

---

UNRELEASED.md
src/components/Connected/components/Item/Item.tsx
src/components/Filters/components/ConnectedFilterControl/components/Item/Item.tsx
src/components/List/List.tsx
src/components/Tabs/components/List/List.tsx

Death to class components!
Converting the following components to be functional components:
- Connected Item
- Filter ConnectedFilterControl Item
- List
- Tabs List

Convert some simple components to be functional

---

UNRELEASED.md
src/components/MediaCard/MediaCard.scss

Fixes an issue in MediaCard where the thumbnail would overflow outside of the parent card on small screens at the top, as well as on larger screens, to the left, as in these screenshots:
Uses the new design language custom properties instead of the Sass functions when applying border radius values.
Compare new and old versions on Chromatic, at various viewport sizes.

[MediaCard] Fix the thumbnail’s corner roundness, so it won’t overflow out of the parent Card

---

src/components/ResourceItem/ResourceItem.tsx
src/components/ResourceItem/tests/ResourceItem.test.tsx

To enable prefetching when a user hovers over the `ResourceItem` through a `data-href` attribute on the parent `li` tag. 
Fixes https://github.com/Shopify/marketing-technology/issues/6390. Also referenced [here](https://shopify.slack.com/archives/C4Y8N30KD/p1612387605186600) @billycai 
Adds the `dataHref` prop to `ResourceItem`. If a string is provided, the main `li` tag will render a `data-href` attribute. Also adds two tests to check functionality.

[ResourceItem] Add dataHref prop

---

UNRELEASED.md
src/components/ActionList/components/Item/Item.tsx
src/components/ActionList/components/Item/tests/Item.test.tsx

Fixes an issue where ActionList Items will disable visually but not functionally when the url prop is passed. 
Sets the Item url and onClick to null if a url is passed and disabled is passed as true.
<details>
```jsx
return (
<Page
title="Playground"
actionGroups={[
{
title: …
```

[ActionList/Item] Fix disabling ActionList Item when url prop is passed

---

UNRELEASED.md
src/components/CheckableButton/CheckableButton.scss

Fixes #3987
First noticed this in Admin, the right border disappears when the bulk actions checkbox is focused.
After investigation, the issue is with how we're dealing with overlapping borders. Subsequent buttons have a `margin-left: -1px`, so their left border overlaps the right border of the previous element so we don't have a double border:
However, `CheckableButton` has a `border-right: none;`. This is fine when the checkbox isn't focused since the `Edit customers` button's border overlaps the rightmost 1px of `2 selected` regardless of whether there's a border underneath or not, but when the checkbox is focused it's also given an increased `z-index: 20` which is higher than that of `Edit customers`. As a result, the rightmost edge of `2 selected` now appears **above** the `Edit …

[CheckableButton] 3987 - fix checkbox border issue on focus

---

UNRELEASED.md
src/components/Modal/tests/Modal.test.tsx
src/components/TrapFocus/TrapFocus.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

`TrapFocus` was stealing focus from `autoFocus` text fields.
* simplifying & adjusting the disable logic
* (issue unrelated to this change) It seems focus can be moved out of trap focus from clicks and be contained in secondary trap focuses. Do we consider this a bug?
Play around with the playground code!
<details>
```jsx
import React, {useState, useRef, useCallback} from 'react';
import {
Page,
Button,
Modal,
Stack,
TextContainer,
TextField,
TrapFocus,
Heading,
return (
<ModalWithPrimaryActionExample />
</Page>
);
}
function ModalWithPrimaryActionExample() {
const DISCOUNT_LINK = 'https://polaris.shopify.com/';
const [trappingActive, …
```

[TrapFocus] Fixed focus being stolen from internal elements

---

UNRELEASED.md
src/components/IndexTable/IndexTable.scss
src/components/IndexTable/IndexTable.tsx

Fixes #3989 
On the `IndexTable` component, the `select all` checkbox isn't vertically centered with the rest of the the table headers. This is due to the checkbox having a `display: inline-flex;`, which adds whitespace since it's an inline element. [This stackoverflow answer](https://stackoverflow.com/a/48119467/2131898) does a good job summarizing the issue.
This PR adds a wrapper around the checkbox header to fix the alignment.
👀 **_BEFORE_** 👀
_IndexTable / Simple Index Table example_
_IndexTable / Simple Index Table example w/sticky headers_
👀 **_AFTER_** 👀
_IndexTable / Simple Index Table example w/sticky headers_
_IndexTable / Simple Index Table example_

[IndexTable] Align IndexTable checkbox header with other headers

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/Button/tests/Button.test.tsx

- To cover use cases for consumers who need to use a button (for interactive purposes that don't include linking to something), and want to render a truly plain, monochrome button with no underline 
- Adds optional `removeUnderline` prop to `<Button/>`
- Removes underline from the button text, including on on hover/focus
<details>
```jsx …
```

[Button] Add optional `removeUnderline` prop

---

UNRELEASED.md
src/components/Tabs/Tabs.tsx
src/components/Tabs/tests/Tabs.test.tsx

Fixes #3993
(also fixes shopify/web issue [#37890](https://github.com/Shopify/web/issues/37890))
When the `Popover` component is [handling the close event](https://github.com/Shopify/polaris-react/blob/main/src/components/Popover/Popover.tsx#L128), it checks for the next focuseable element and focuses that, and otherwise focuses the popover trigger. However, the "next focuseable element" is determined by the [nextFocuseableNode](https://github.com/Shopify/polaris-react/blob/main/src/utilities/focus.ts#L16) utility, which just checks based on element type and doesn't take `tabindex` values into consideration.
This breaks when used by the `Tabs` component, because `Tabs` has a set of buttons with `tabindex="-1"` that are used to determine appropriate widths when resizing (the `TabMeasurer` …

[Tabs] Fix Tabs focus state issue on close

---

UNRELEASED.md
src/components/Frame/Frame.tsx
src/components/Frame/tests/Frame.test.tsx

References https://github.com/Shopify/global-nav/issues/775
The "Skip to Content" link by default targets a hidden anchor element within Frame via `#AppFrameMainContent`. This presents an accessibility concern since the focus does not advance to actual visible content item. This is also undesirable when Voice Over is activated since it will cause it to focus on and describe the hidden anchor.
By targeting the main container (`#AppFrameMain`) instead the focus gets moved to the first focusable (or "voiceable") element inside of `main`.
Remove the `#AppFrameMainContent` link from Frame. Update `Skip to Content` to target #AppFrameMain. …

Remove #AppFrameMainContent link and update SkipToContent link to target #AppFrameMain instead

---

UNRELEASED.md
src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
src/components/Tabs/utilities.ts

Fixes #3976
The Tabs component (and specifically the TabsMeasurer) currently doesn't take into account what happens when tab widths aren't integers. This can result in the "disclosure tab" (the `...` overflow button) being wrapped to the next line.
This PR rounds up the tab width values and adds equality to the comparison check in `Tabs/utilities.ts` when determining whether a tab should be wrapped, with the end result being that tabs are hidden 1px sooner but the disclosure tab isn't wrapped.
**before**
**after**
📄 [Changelog …

[Tabs] Tabs wrap on window resize

---

UNRELEASED.md
src/components/IndexTable/IndexTable.scss

The IndexTable sticky header's bulk action checkbox can "steal" tab focus while still hidden due to it appearing higher in the dom than the non-sticky bulk action checkbox. This change was already [merged in shopify/web with this pr](https://github.com/Shopify/web/pull/38160), migrating the change here as well.
This PR positions the sticky header out of the viewport so that [the focus utility](https://github.com/Shopify/polaris-react/blob/main/src/utilities/focus.ts#L28) properly skips the hidden checkbox.
📄 [Changelog …

[IndexTable] Merge IndexTable accessibility change from web

---

UNRELEASED.md
src/components/TextStyle/TextStyle.scss

The `::after` pseudo element goes on top of the code, making it impossible to select when clicking/selecting or double clicking on it.
It adds `pointer-events: none` to the pseudo element that covers the code, so that clicking on code isn't impacted by it.

[TextStyle] Fix an issue where inline code would be hard to select

---

UNRELEASED.md
src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/tests/Collapsible.test.tsx

* Fix a bug where transitions of elements inside the collapsible would trigger the component's transition end event logic ([codesandbox example](https://6ke03.csb.app/))
* In the example above, using the button outside of the collapsible opens and closes it as expected. However, if a toggle button inside the collapsible is clicked, its transition is prematurely triggering the `onTransitionEnd` logic which fully closes the collapsible 
* Add a check to the `onTransitionEnd` event that ensures it's coming from the container target, and not an element within it 
* This [check](https://github.com/Shopify/polaris-react/blob/v5.12.0/src/components/Collapsible/Collapsible.tsx#L169) used to exist before `Collapsible` was converted to a functional component  …

[Collapsible] Fix collapsible transition behaviour

---

UNRELEASED.md
src/components/Frame/components/Toast/Toast.scss

Fixes shopify/web [#38294](https://github.com/Shopify/web/issues/38294).
The close button on the Toast component isn't centered on mobile views
** 👀  before 👀  **
** 👀  after 👀  **

[Toast] Fix toast close button alignment for mobile

---

src/components/DisplayText/README.md

All items in [this list](https://polaris.shopify.com/components/titles-and-text/display-text#section-content-guidelines) should use the same tense:

[DisplayText] Content guidelines: use present tense consistently

---

UNRELEASED.md
src/styles/shared/_buttons.scss

In **Safari** the buttons has a default white color when clicked via `:active`.
Demo: https://codepen.io/sylvhama/pen/ExNwarY
Reset the `color` too based on [this tweet](https://twitter.com/bdc/status/988745695757824003).

[Mixin] reset color in unstyled-button

---

UNRELEASED.md
src/components/IndexTable/IndexTable.tsx
src/components/IndexTable/tests/IndexTable.test.tsx

Found this while working [on shopify/web #38318](https://github.com/Shopify/web/issues/38318).
The `IndexTable`'s bulk actions are operations that can be performed on selected `IndexTableRow`s. The mobile responsive view shows the bulk actions even when no rows are selected though.
Hides bulk actions dropdown unless 1+ rows are selected.
https://user-images.githubusercontent.com/3619012/108529102-1fe06480-72a2-11eb-8fb6-923cd3091da3.mp4 …

[IndexTable] Fix issue where bulk actions appear on mobile when no rows are selected

---

UNRELEASED.md
src/components/ActionList/ActionList.scss
src/components/Avatar/Avatar.scss
src/components/Banner/Banner.scss
src/components/CheckableButton/CheckableButton.scss
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
src/components/Frame/components/Toast/Toast.scss
src/components/Modal/components/Dialog/Dialog.scss
src/components/Navigation/Navigation.scss
src/components/ProgressBar/ProgressBar.scss
src/components/RadioButton/RadioButton.scss
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
src/components/Tag/Tag.scss
src/styles/foundation/_accessibility.scss
src/styles/shared/_forms.scss

(partly) Fixes #3826 : it only "partly" fixes the issue since this PR only removes the `outline` and `border` uses of  `-ms-high-contrast`. 
Inspired by this [interesting article](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/), which states that 
```CSS
@media (forced-colors: active) {
/* Styles here only apply to Forced Colors Mode */
}
```
basically does the same thing as `-ms-high-contrast: active` HOWEVER, 😭 it doesn’t work for firefox. See [this article ](https://hacks.mozilla.org/2020/07/adding-prefers-contrast-to-firefox/)which talks about creating a custom media query called prefers-contrast, which is quite laborious. This is a temporary fix and will require thought as to how to account for firefox in high …

[a11y]: Remove outline & border uses of ms-high-contrast

---

UNRELEASED.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx

This fixes #3048.
**Before this change**
**After this change**
It updates the effect used in the `Combobox` component to `useLayoutEffect` instead of `useEffect`. This makes sure the changes are committed before the browser paint cycle. This resolves the issue we were seeing in the autocomplete because it makes sure that change is updated before the popover tries to calculate the height to display itself.
<details>
```jsx
import React, {useCallback, useState, useMemo} from 'react';
import {SearchMinor} from '@shopify/polaris-icons';
import {Icon, Autocomplete, TextContainer} from '../src';
const deselectedOptions = useMemo(
() => [
{value: 'rustic', label: 'Rustic'},
{value: …
```

[Autocomplete] useLayoutEffect in combobox

---

src/components/Autocomplete/components/ComboBox/ComboBox.tsx

As @BPScott pointed out in https://github.com/Shopify/polaris-react/pull/4015#issuecomment-785281704 `useLayoutEffect` will throw a warning during SSR.
This follows the suggestions in [this issue](https://github.com/facebook/react/issues/14927) conditionally using `useEffect` instead on the server.
Try this in the playground:
<details>
```jsx
import React, {useCallback, useState, useMemo} from 'react';
import {SearchMinor} from '@shopify/polaris-icons';
import {Icon, Autocomplete, TextContainer} from '../src';
const deselectedOptions = useMemo(
() => [
{value: 'rustic', label: 'Rustic'},
{value: 'antique', label: 'Antique'},
{value: 'vinyl', label: 'Vinyl'},
{value: 'vintage', …
```

[ComboBox] Use isomorphic layout effect

---

UNRELEASED.md
config/rollup/plugin-styles.js

Fixes #4014 
Our generated css file was not handling the consolidation and hoisting of `@charset` declarations.
Pulls the `@charset` declaration up to the top of the file. Will error if there is are multiple competing charsets though that shouldn't ever happen because prettier should force all our source files to be utf-8.
- `yarn run build` and check `dist/styles.css` and note that `@charset "UTF-8";` is at the top of the file and not half way down.
If you'd like to be more thorough compare output against main:
- Create a build of main: `git checkout main && yarn clean && yarn build  && mv dist dist-orig`
- Create a build from this branch: `git checkout fix-charset && yarn clean && yarn build`
- Diff the old and new dist folders and note that the only change is the location of the …

Ensure @charset is at the top of generated css

---

CHANGELOG.md
UNRELEASED.md

This PR updates the `UNRELEASED.md` and `CHANGELOG.md` files to show the latest changes.
Several of the links were pointing to issues. I changed those to point to the PRs.
Also added a few changes that were not added to `UNRELEASED.md`. Specifically:
- Added `IndexTable / IndexProvider` component ([#3646](https://github.com/Shopify/polaris-react/pull/3646))
- Added `dataHref` prop to `ResourceItem` which gets passed to the main `li` element as `data-href`([#3975](https://github.com/Shopify/polaris-react/pull/3975))

Update CHANGELOG.md for 6.1.0

---

UNRELEASED.md
src/components/Modal/components/Section/Section.scss

I was creating a Modal component with different sections and I noticed that the color of the divider line between the section was darker than the line that divides the footer and header of the modal. I went to Polaris channel and I was told that the color was not the correct one, so I change to use the border('divider').
This is before:
This is After:

[Modal.Section]: Fix in Modal.Section divider color

---

UNRELEASED.md
src/components/InlineError/README.md

The **Inline error** component currently uses the term `invalid` to describe form inputs that aren't accepted. We are moving away from using that term in our content, and instead we want to use `not valid` when necessary. For more information, see https://github.com/Shopify/polaris-styleguide/issues/3873
Removing the term `invalid` to describe form inputs that aren't accepted. Where necessary, replacing with the phrase `not valid`.

Remove "invalid" language from components

---

UNRELEASED.md
locales/cs.json
locales/da.json
locales/de.json
locales/en.json
locales/es.json
locales/fi.json
locales/fr.json
locales/it.json
locales/ja.json
locales/ko.json
locales/nb.json
locales/nl.json
locales/pl.json
locales/pt-BR.json
locales/pt-PT.json
locales/sv.json
locales/th.json
locales/tr.json
locales/vi.json
locales/zh-CN.json
locales/zh-TW.json
src/utilities/index-provider/tests/hooks.test.tsx

Fixes [shopify/web issue #38565](https://github.com/Shopify/web/issues/38565)
The IndexTable component assumes that the resource present in the list is a root-level resource, which means that the messaging when selecting all items in the list assumes that you're selecting all of that resource type across the entire store. This assumption may not always hold, which is what we're bumping up against in web.
This PR removes the `in your store` assumption from the `IndexTable` bulk action strings.

[IndexTable] Remove `in your store` from IndexTable bulk selection

---

.storybook/manager.js
UNRELEASED.md
package.json
src/utilities/theme/types.ts
src/utilities/theme/utils.ts
yarn.lock

Gives us esm support for legacy tokens, and lets us remove some deep
imports inside dist-modern.
- Update `@shopify/polaris-tokens` to v2.21.0
- Import from `@shopify/polaris-tokens/dist-modern` where possible
- Use named imports in storybook manager config (the default export still works but is deprecated)

Update tokens to v2.21.1

---

UNRELEASED.md
src/components/Badge/Badge.tsx
src/components/Badge/README.md
src/components/Badge/tests/Badge.test.tsx

Experimenting with a proposed feature request #4027 
- Adds a `customAccessibilityLabel` for consumer's who need to pass more specific labels.
- Access  `Badge with customAccessibilityLabel` story 
- Enable Voiceover

[Badge] Add customAccessibilityLabel prop

---

UNRELEASED.md
src/components/ActionList/ActionList.scss
src/components/ActionList/components/Item/Item.tsx
src/components/ActionList/components/Item/tests/Item.test.tsx

Fixes #3649 
Applied the same approach used on Polaris Button component. 
https://user-images.githubusercontent.com/67908111/110001290-850d6e80-7d14-11eb-8b34-0379f1263774.mov

[ActionList] Remove focus ring on click #3649

---

UNRELEASED.md
src/components/Popover/Popover.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
src/components/Popover/tests/Popover.test.tsx
src/components/PositionedOverlay/PositionedOverlay.tsx
src/components/PositionedOverlay/tests/PositionedOverlay.test.tsx

Fixes https://github.com/Shopify/polaris-ux/issues/602
<details>
```jsx
import {Page, Popover} from '../src';
return (
<Popover
active
activator={<div>asdf</div>}
onClose={() => {}}
zIndexOverride={402}
>
<ul>
<li>one</li>
<li>two</li>
</ul>
</Popover>
<div style={{background: …
```

[Popover] Add zIndexOverride prop

---

UNRELEASED.md
src/components/Avatar/Avatar.tsx
src/components/Avatar/tests/Avatar.test.tsx

Due to surface area constraints, in our app, we use custom a user menu — the activator is a standalone avatar within a button which toggles a `Popover`. The popover includes an avatar and the full name of the user in question, as opposed to displaying the full name alongside the avatar directly on the top bar.
For Identity users that haven't uploaded an avatar, we attempt to grab an image from gravatar based on their `uuid` which eventually resolves to their email — that request can either return the image or `404` if the account doesn't exist.
The problem with that is each time the user menu activator is clicked, the popover is re-rendered which results in extraneous requests to the same url that previously failed in an attempt to retrieve the gravatar.
This adds an `onError` hook to the …

[Avatar] Expose `onError` hook

---

src/components/SettingToggle/README.md
src/components/SettingToggle/SettingToggle.tsx

For the setting toggle component, replaced recommendation to use `enable`/`disable` with `activate`/`deactivate`.
Addresses issue https://github.com/Shopify/polaris-styleguide/issues/3872 
- Replaced `enable`/`disable` with `activate`/`deactivate`
- Replaced `enabled`/`disabled` with `activated`/`deactivated`
_Note_: The changes mentioned apply only to content guidelines. There are instances within the code base (like props) where we have not addressed this because it is a breaking change.

[Setting toggle] Replace instances of enable/disable

---

UNRELEASED.md
src/components/IndexTable/IndexTable.tsx
src/components/IndexTable/tests/IndexTable.test.tsx
src/components/IndexTable/utilities/index.ts
src/components/IndexTable/utilities/tests/utilities.test.ts
src/components/IndexTable/utilities/utilities.ts
src/components/InlineError/README.md
src/utilities/sticky-manager/sticky-manager.ts

Resolves #3991.
The IndexTable currently has some UX, jank, and performance issues when resizing. This PR aims to address a lot of these by making UX and performance fixes to make this resize buttery-smooth.
**1) Fixed sticky header alignment issues**
All the sticky headers are sized on load and not resized when the window width changes.
👀 _before (watch the Location column)_ 👀 
https://user-images.githubusercontent.com/3619012/109985851-31c6fc00-7cd3-11eb-9f50-962d805a235e.mp4
👀 _after (watch the Location column)_ 👀 
https://user-images.githubusercontent.com/3619012/109988962-0b569000-7cd6-11eb-8954-89f70faf2d5c.mp4
**2) Fixed first (non-sticky) column alignment issues when resizing browser**
First column header doesn't resize when window does.
👀 _before_ 👀 …

[IndexTable] Fix UX / jank when resizing

---

UNRELEASED.md
src/components/Portal/Portal.tsx

Fixes #4064
We shouldn't need the `isMounted` check at all in this so updating to only call the `onPortalCreated` within the `useEffect` instead.
Try some of the examples that use a portal in storybook and make sure they still work as expected.

[Portal] Don’t use isMounted in useEffect

---

UNRELEASED.md
src/components/IndexTable/IndexTable.tsx
src/components/IndexTable/tests/IndexTable.test.tsx
src/utilities/sticky-manager/sticky-manager.ts

Currently, the IndexTable header is sticky at the top of the window even after scrolling past the end of the table. This PR passes a `boundingElement` to the `<Sticky>` component to fix this.
**NOTE FOR REVIEWERS**
Hoping for opinions / insight on my change to `sticky-manager.ts`. The sticky manager calculates the sticky item height based on the `getBoundingClientRect().height` of the sticky node. The problem is, if the sticky node is positioned absolutely the height will be 0, so this calculation will be wrong. My fix is to fall back to the height of the first child (if present) if the height of the sticky node is 0. **_Does this approach make sense?_**
** 👀  Before 👀  **
https://user-images.githubusercontent.com/3619012/111670790-9a8f9780-87ee-11eb-8bc7-1570228b19de.mp4
** 👀  After 👀 …

[IndexTable] Hide table header after scrolling past end of table body

---

UNRELEASED.md
src/components/Card/Card.scss
src/components/Card/Card.tsx
src/components/Card/components/Section/Section.tsx
src/components/Card/components/Section/tests/Section.test.tsx
src/components/Card/tests/Card.test.tsx

During the [Port Draft Orders To React](https://vault.shopify.io/projects/10929) project requirements were created to prevent form elements from appearing on printed draft orders. Some of these elements were cards and card sections.
Polaris currently does not support a hideOnPrint prop for Cards and Card Sections, and so attempts were made to use div wrappers to allow use of the  Polaris`@hidden-when-printing` mixin. This results in the desired behaviour of the element (ie, the element not appearing in a printed document), but interrupts proper usage of the Card component itself. 
An example of this broken UI behaviour can be seen below where two Cards no longer have proper margins separating them:
This pull request creates a hideOnPrint prop for the Card and Card Section Polaris …

[Card] Add hideOnPrint prop to Card and Card.Section

---

UNRELEASED.md
src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss

Fixes @shopify/web issue [#37890](https://github.com/Shopify/web/issues/37890)
Currently, if you tab into a `<Filters>` component from a component that relies on the `focus.ts` utility to determine the [nextFocuseableNode](https://github.com/Shopify/polaris-react/blob/main/src/utilities/focus.ts#L16) (e.g. Popover, Modal, etc), the focus state is lost and returned to the `window`.
This happens because the `ConnectedFilterControl` subcomponent on `Filters` has a hidden `ProxyButtonContainer` that `focus.ts` picks as the next focusable node programmatically, although you can't tab to it normally.
(similar approach on an IndexTable [fix here](https://github.com/Shopify/polaris-react/pull/4004))
👀 **before** 👀 
https://user-images.githubusercontent.com/3619012/112056062-f8ddb280-8b2d-11eb-8d7e …

[A11y][Filters] position hidden proxy container offscreen to prevent focus

---

UNRELEASED.md
src/components/BulkActions/BulkActions.scss

There's a flicker when the `IndexTable` transitions between unselected and bulk actions state
https://user-images.githubusercontent.com/3619012/112192948-cee3c900-8bdd-11eb-9d74-e4c1461e319b.mp4
In this dev tools perf video, you can see when the header transitions from unselected state -> bulk actions state, there's a period where no elements are present:
https://user-images.githubusercontent.com/3619012/112193178-081c3900-8bde-11eb-867e-7d7b1a56d384.mp4
I caught up with the #motion-guild channel about alternate approaches to this, but the recommendation from them was that "These types of transitions should soften and reduce perceived change, not add. The current execution gives it a broken and untrustworthy feel. Agree that the best short term fix is to remove." More details in the …

[IndexTable] Removed flicker from transition to bulk actions view

---

UNRELEASED.md
locales/cs.json
locales/da.json
locales/de.json
locales/en.json
locales/es.json
locales/fi.json
locales/fr.json
locales/it.json
locales/ja.json
locales/ko.json
locales/nb.json
locales/nl.json
locales/pl.json
locales/pt-BR.json
locales/pt-PT.json
locales/sv.json
locales/th.json
locales/tr.json
locales/vi.json
locales/zh-CN.json
locales/zh-TW.json
src/components/DropZone/DropZone.tsx
src/components/DropZone/components/FileUpload/FileUpload.tsx
src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
src/components/DropZone/context.tsx
src/components/DropZone/tests/DropZone.test.tsx
src/components/DropZone/utils/index.ts

Fixes https://github.com/Shopify/polaris-react/issues/3586
I have created a singular and a plural sentence for each call to action in DropZone.
I have based my changes on [this thread in Slack](https://shopify.slack.com/archives/C7TJQLVC7/p1614733227142400).
TLDR: We don't know how many files should be upload, so we don't have any `count` value. Using a random `count` value would be problematic in languages that have several plural rules. So we hope each translator will find a general sentence in both cases.
Also I could not use [scope](https://github.com/Shopify/quilt/tree/main/packages/react-i18n#dynamic-translation-keys), it seems not available in Polaris 🤔 
Run `yarn dev` and browse DropZone stories.

DropZone - show plural message when allowMultiple is true

---

UNRELEASED.md
src/components/Select/Select.scss

I want to align the error background color with [TextField](https://github.com/Shopify/polaris-react/blob/main/src/components/TextField/TextField.scss#L62) one.

update Select error background color

---

UNRELEASED.md
src/components/TrapFocus/TrapFocus.tsx

Fixes https://github.com/Shopify/polaris-react/issues/4086
The original update to react-form proves to cause more issues than fixing this in Polaris.
Essentially TrapFocus enables focusing the modal or whichever field as autofocus. This is a change that was made in the last couple of months. Unfortunately in conjunction with useReducer which is used with useField in react-form, this is breaking tabbing through forms in modal throughout the admin.
This pull request handles the focus logic within a useEffect which allows autofocus and doesn't break react forms
1. Load the playground and does the field autofocus ✅ 
2. Tab though it. Trap focus all good?  ✅ 
<details>
```jsx
import React, {useState, …
```

changed trapped focus logic

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

This fixes #4107
It reverts the change introduced in #4053 and will go back to using the `off` value for autocomplete on the text field.
</details>

[TextField] Use “off” for autocomplete

---

UNRELEASED.md
src/components/DataTable/DataTable.scss
src/components/DataTable/DataTable.tsx
src/components/DataTable/tests/DataTable.test.tsx

It is not always the case that rows within a `DataTable` are selectable and having a hover state implies that a table row can be clicked. In Taxes, we were encountering a few use cases where wanted to use this table, but did not think the hover effect made sense for a non-actionable UI.
This pull request creates a `hoverable` prop for the `DataTable` component that defaults to true. All existing implementations of `DataTable` will not be affected, but for any new use case, we can specify whether we want the hover style.
Gifs: 
<details>
<summary>`hoverable: true` (default)</summary>
</details>
<details>
<summary>`hoverable: false`</summary>
</details>
<details>
```jsx
import …
```

[DataTable] Add `hoverable` prop

---

UNRELEASED.md
src/components/IndexTable/IndexTable.scss

The sticky column background styles were more specific than the hover styles, added a line of CSS so it looks consistent:
👀  **Before** 👀 
https://user-images.githubusercontent.com/3619012/114405660-e70f8e00-9b74-11eb-8783-0be06266c370.mp4
👀  **After** 👀 
https://user-images.githubusercontent.com/3619012/114405671-e8d95180-9b74-11eb-9b16-61fd8b3eec52.mp4
Adds some specificity. (technically the same level as the css that sets the cell bg to white but it's later in the file)

[IndexTable] update sticky column hover styles

---

UNRELEASED.md
service.yml
src/components/DataTable/DataTable.tsx
src/components/DataTable/components/Cell/Cell.tsx
src/components/DataTable/tests/DataTable.test.tsx

While doing reactification projects, we've run into several cases where we needed a row cell to span the whole width of the row. We also thought it could be a useful for other uses of the Data Table in the future. 
both screenshots use this heading/row data
I determined `colSpan` by taking the headings length and dividing it by the number of cells in that row. if there are no headings, it falls back to the column content length. 
To use this, one would make a row array that has items less than the headings. 
note when `colLen / rowLen` has a remainder, I add that to the colSpan of the first cell item. Let me know if this default behaviour is an issue but devs can get around this by adding an empty column header.  
There are no changes for row items that are:
- row.length === …

[Data Table] Cells in a data table row fill to fit table headings width

---

src/components/SkeletonPage/SkeletonPage.tsx

Every time `SkeletonPage` renders, the secondaryAction markup changes widths. I ran into this while implementing a page with incremental loading where the widths changed every time a new part of the page was done loading.
Contrived example in a sandbox: https://codesandbox.io/s/exciting-shockley-icfwg?file=/App.js
Wrapping `secondaryActionMarkup` with a `useMemo` prevents the widths from being re-calculated when the `SkeletonPage` re-renders. For reference, the widths get randomly generated [on this line](https://github.com/Shopify/polaris-react/blob/7b8310e5e929a029c2e87ee63f5584a89137c99b/src/components/SkeletonPage/SkeletonPage.tsx#L90). …

[SkeletonPage] Prevent secondaryActions from changing width on re-render

---

UNRELEASED.md
src/components/CalloutCard/CalloutCard.scss
src/components/CalloutCard/CalloutCard.tsx

Fixes heading overflow issue when the CalloutCard is dismissible. 
Fixes the issue by adding padding to the right on the CalloutCard container when it is dismissible. The spacing was inspired by the [dismissible Banner](https://github.com/Shopify/polaris-react/blob/main/src/components/Banner/Banner.scss#L212-L214).
<details>
```jsx …
```

[CalloutCard] Fix heading overflow when dismissible

---

UNRELEASED.md
src/components/Filters/Filters.tsx
src/components/Filters/components/ConnectedFilterControl/tests/ConnectedFilterControl.test.tsx
src/components/Filters/tests/Filters.test.tsx

When the `ResourceList` & `Filter` components are used in either an empty state configuration, or one where no filters are passed in (i.e. just search via `TextField`), a class with extra right margin is added causing the input to appear misaligned. This can be seen on the "empty state resource list" story/example linked in the docs: https://codesandbox.io/s/uyg6i?module=App.js
<details>
<summary>Currently, with margin:</summary>
Empty state:
Existing web example:
</details>
<details>
<summary>This PR proposes:</summary>
Empty state:
</details>
Sets `rightActionMarkup` in `Filters.tsx` to `null` when no filters are passed in, which prevents appending an empty div with the offending classes in `ConnectedFilterControl` [here](https://github.com/Shopify/polaris-react/blob/main/src/components/ …

[Filters] Remove extra margin when rightAction is `null`

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx
src/components/DropZone/README.md
src/components/DropZone/tests/DropZone.test.tsx

Right now, `DropZone` has 4 sizes: `small`, `medium`, `large`, and `extraLarge`. These are calculated based on the width of the `DropZone`. These sizes determine the `min-height` of the component. This means you cannot have a `DropZone` that is narrower than the set height at a given size. 
We have a case where we need the height to be narrower than what is automatically set by this component.
I've opened [an issue](https://github.com/Shopify/polaris-react/issues/4137) about making this the default behaviour.
This PR adds a prop `variableHeight` that skips the size calculation and makes the `DropZone`'s height dependent on its children instead.  …

[DropZone] Add prop to DropZone so children control its height

---

service.yml

We need to deploy the master branch storybook builds to Shopify infrastructure. We can't run `dev runtime create` without the classification being updated.
Changing the classification from `library` to `tier4`

Update service classification to tier4

---

UNRELEASED.md
src/components/Modal/Modal.tsx
src/components/Modal/tests/Modal.test.tsx

Needed to fix https://github.com/Shopify/core-issues/issues/23913
We're building a component that has its own sticky toolbar header, and then the main body content is wrapped in a `<ScrollableContainer>`, so that's how the user scrolls through the modal contents. The problem is, if the browser window is short enough, it'll squish the modal contents such that an outer scrollbar appears, which belongs to Polaris's `<Modal>`. So we have an outer container and an internal container, each of which will only partially scroll the modal contents 😬
You can see a video in the above issue.
`<Modal>` component now has the prop `noScroll` which when true wraps the body content in a `div` instead of the `Scrollable` component

[Modal] add noScroll prop

---

.storybook/polaris-readme-loader.js
scripts/accessibility-check.js

We no longer need an all examples page for the visual regression testing. Removes some extra code.
Removes code that added the `all examples` pages

Remove all examples storybook

---

UNRELEASED.md
src/components/Frame/components/Loading/Loading.tsx

Loading can call set state after the component has unmounted
Adding an isMounted check
Unfortunately it's very hard to reproduce the error. @dleroux did you want to check it in off your branch?

[Frame/Loading] Fix async setState calls

---

.github/workflows/ci.yml
.github/workflows/size-limit.yml

Size limit is running on merge to main. This is causing it to fail, it should only run on PR.
Moving size-limit to a PR only workflow

size-limit pr only

---

UNRELEASED.md
src/components/Label/Label.scss
src/components/Label/Label.tsx
src/components/Labelled/Labelled.tsx
src/components/Labelled/tests/Labelled.test.tsx
src/components/Select/Select.tsx
src/components/Select/tests/Select.test.tsx
src/components/TextField/README.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Resolves #4098
Resolves #4118
Following the experiment outlined [here](https://github.com/Shopify/web/issues/40128), we are moving ahead with adding a required indicator to form labelled components so that they could indicate to be so.
The new prop `requiredIndicator` is added to the `Label` component (instead of the higher level `TextField` or `Select` components) with 2 considerations:
1. This indicator should work like an inline text to the label
2. All components using the `Labelled` component would be able to add the required indicator easily.
📄 [Changelog …

[Label] Add required indicator prop to Label component

---

UNRELEASED.md
src/components/Modal/Modal.tsx
src/components/Modal/README.md
src/components/Modal/components/Dialog/Dialog.scss
src/components/Modal/components/Dialog/Dialog.tsx
src/components/Modal/tests/Modal.test.tsx

Closes #4174 
We'd like to be able to `decrease` Modals' width similarly to how we're currently able to increase it through the prop `large`.
This PR adds a prop `small` to the `Modal` component so that users are able to decrease Modals' width in a similar manner that they can increase it through the prop `large`. 
We've considered adding a prop `width` that could receive either `small | medium(default) | large`, which would avoid having two props that control width being passed into the component simultaneously, but that would break the current API. Therefore, if both `small` and `large` are passed in at the same time, we'll default to `large`. …

[Modal] Add prop small to decrease Modal's width

---

UNRELEASED.md
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/4155
When using the [Dual thumb range slider](https://polaris.shopify.com/components/forms/range-slider) with a min value different from 0, there is an extra padding on the left. This prevents selecting a value when having a range [10, 50] for example:
| What's happening | What's expected |
|--|--|
| <img width="724" alt="current" src="https://user-images.githubusercontent.com/22640631/116860205-81f20a00-ac01-11eb-883c-6bb29f3cebca.png"> | <img width="724" alt="expected" src="https://user-images.githubusercontent.com/22640631/116860211-83233700-ac01-11eb-8119-ccfed8b1698f.png">
Substract the minimum range value position to the position.
🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#dev …

[DualThumb] Add an offset to push the minimum range value to the left

---

.github/CONTRIBUTING.md

The main branch was renamed recently from "master" to "main". The docs don't reflect that.
Replace "master" with "main" in Contributing.md
No tophat required

Replace "master" with "main" in Contributing.md

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx

We have a use-case where there is a `Button` inside the `dropzone`
Currently, if we're navigating (tabbing) through the component with the keyboard:
1. `Button` inside `Dropzone` is focused first
2. `Dropzone` is focused
We expect a meaningful order when navigating through. Expected order:
1. Focus the `Dropzone` first
2. Then any focusable contents inside it
<details>
<summary> Current </summary>
https://user-images.githubusercontent.com/23648577/119017743-4e391300-b969-11eb-9c15-21f6fffaca9b.mp4
</details>
<details>
<summary> Correct order </summary>
https://user-images.githubusercontent.com/23648577/119017814-63ae3d00-b969-11eb-8bfe-f91a9b9d1c8f.mp4
</details>
Changes DOM order to accommodate a meaningful tabbing sequence.  …

[DropZone] Change DOM order of Visually hidden input in order to focus it before its children

---

UNRELEASED.md
src/components/Scrollable/Scrollable.tsx

When launching our draft orders feature, a merchant reported an issue with the scrolalble area on th e product resource picker. The 'fetch more' action didnt seem to trigger when they scrolled to the bottom of a paginated list. The support specialist in touch with the merchant seemed to have narrowed it down to be reproducible only on lower resolution screens. 
See original issue [here](https://github.com/Shopify/core-issues/issues/25113)
<details>
<summary>Broken scroll (it shouldve loaded 4-5 more more products after Sleek Granite shoes)</summary>
</details>
After some pairing and irl chats with @dleroux we decided to add a small buffer to the height detection for the scrolledToBottom action on a Scrollable component. Unfortunately none of our dev machines are able to go down to a lower …

[Scrollable]adjust scroll to bottom for lower resolution issues

---

UNRELEASED.md
package.json
src/styles/foundation/_focus-ring.scss
yarn.lock

Co-Authored-By: Ben Scott <227292+BPScott@users.noreply.github.com>
Fixes https://github.com/Shopify/polaris-react/issues/4232
Unitless calc was breaking when users did not provide postcss-calc as a plugin. This fixes the outline on components like `<Button plain>` where the output of the focusring mixin was `calc(0 + 1rem)`. 
Remove this from `./storybook/main.js`
https://github.com/Shopify/polaris-react/blob/9081df8bde8c682240fbc1cccba35bb5dbdd6d08/.storybook/main.js#L57-L63
Then open the plain button example.

Remove unitless calc addition for when postcss-calc is not included

---

UNRELEASED.md
src/components/DataTable/DataTable.tsx
src/components/DataTable/tests/DataTable.test.tsx

Fixes #4245 
The DataTable component "debounces" an internal method which can cause state to be set after the component has mounted. This results in console warnings, which can break some test environments.
Cancels the debounced method when the component is unmounting so that it won't try to call setState. Introduces test coverage to capture the issue.
**Before**
**After**

[DataTable] Fix console warnings caused by setting state after unmount

---

UNRELEASED.md
src/components/ProgressBar/ProgressBar.scss
src/components/ProgressBar/ProgressBar.tsx
src/components/ProgressBar/README.md
src/components/ProgressBar/tests/ProgressBar.test.tsx

We have a use case in the admin app to render a `ProgressBar` without the load-in animation: https://github.com/Shopify/taxes/issues/2184
Sets the `animated` prop to default to true, which conditionally includes the `.Animated` class.
<details>
```jsx
import {Page, ProgressBar} from '../src';
return (
<ProgressBar progress={50} animated={false} />
</Page>
);
}
```
</details>

[ProgressBar] Add `animated` prop

---

package.json

Fix deploying of Storybook
[Error log in Splunk](https://logs.shopify.io/en-US/app/search/search?q=search%20kube_cluster%3Dapps-b-us-central1-4%20application%3Dpolaris-react-production-unrestricted-4b2e%20kube_pod%3Dweb-6f877dfb4c-2cggk%20kube_container%3Dweb%20(sourcetype%3Dfluentd%20OR%20sourcetype%3Drails%3Astructured%20OR%20sourcetype%3Dactive-job%3Astructured%20OR%20sourcetype%3Drails%3Acloudplatform%20OR%20sourcetype%3Dactive-job%3Acloudplatform)&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-24h%40h&latest=now&sid=1623338356.177683_6C35DFC2-A4DB-4844-B180-6F3D65F90A72)
Serves up the static Storybook build on `0.0.0.0` rather than `localhost`
Co-Authored-By: Kyle Durand <6844391+kyledurand@users.noreply.github.com>

Serve Storybook on 0.0.0.0 instead of localhost

---

UNRELEASED.md
src/components/Sheet/Sheet.tsx
src/components/Sheet/tests/Sheet.test.tsx

Needed to fix https://github.com/Shopify/banking/issues/4735
Adds an `activator` prop to the `Sheet` component so it re-focuses on the triggering element when the Sheet is closed. This is using the same implementation as the `Modal` component's `activator` prop.
Adds an `activator` prop that accepts an element or a Ref object to the `Sheet` component. When the Sheet is closed it will re-focus on the triggering element. If an element is passed into the prop it will also render that element.
https://user-images.githubusercontent.com/14224109/117994979-f23e1100-b30e-11eb-9074-d4f01ad423a3.mov
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/docum …

[Sheet] Add activator prop

---

UNRELEASED.md
src/components/Page/Page.scss
src/components/Page/Page.tsx
src/components/Page/README.md
src/components/Page/tests/Page.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/4238
Some pages within the admin have design requirements to include borders below the page header. 
The `divider` prop is added to the `Page` component to avoid the need to use unstable, hacky CSS like the snippet below.
```scss
.PageWrapper {
[class^='Polaris-Page__Content'] {
border-top: border();
}
}
```
This PR introduces the `divider` prop to the `Page` component. By default, the divider not rendered for the `Page` component. The PR adds the new prop, styles, tests, and adds an example to the documentation. 
```jsx
<Page {...PageProps} divider />
```
🖥  &nbsp; [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒  &nbsp; [General tophatting …

[Page] Add `divider` prop

---

UNRELEASED.md
src/components/TextField/README.md
src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx
src/styles/foundation/_typography.scss

- For our particular use case, we use a `<TextField />` to display an access token that needs to be clearly interpreted by the user
- The use of our current default font on `<TextField />` leads to some mix ups including not being able to differentiate certain characters like I (uppercase i) and l (lowercase L).
- This introduces a `monospaced` prop that applies a monospaced font to the `<TextField />` allowing for easy character distinction
Example - Top is default, bottom is with `monospaced` prop:
- adds a `monospaced` prop to `<TextField />`
- This applies the `.Monospaced` css class to the input
-  The font-families applied try to use the `SF Mono` font first, while falling back to system defaults as per our design suggestions
- I followed a suggestion to take a look at how …

[TextField] - Add monospaced prop

---

UNRELEASED.md
src/components/Stack/Stack.scss
src/components/Stack/Stack.tsx

Adds `base-tight` spacing option to the `<Stack/>` component. 
Exposes [`base-tight` spacing](https://github.com/Shopify/polaris-tokens/blob/main/dist/spacing.spacing-map.scss#L5) (12px) as an option on the `Stack.Spacing` prop.
<details>
```jsx
import {Page, Stack, Badge} from '../src';
return (
<Page …
```

[Stack] Add baseTight spacing option

---

UNRELEASED.md
package.json
yarn.lock

See https://github.com/Shopify/web-configs/issues/271.
Shopify Mobile Apps have dropped support for Safari versions older than 13.6. This means that Shopify web properties including Polaris can drop support for those versions too.
Updates our browserlist config to match  `@shopify/browserslist-config` v3.0.0 per https://github.com/Shopify/web-configs/pull/274 and https://github.com/Shopify/web-configs/issues/271.
Note that we have to copy the config here, rather than use an `extends` for reasons described in https://github.com/Shopify/polaris-react/pull/3132

Update browserslist to match shopify/browserslist-config v3.0.0

---

src/styles/foundation/_typography.scss

Ran into a parsing issue while experimenting with dart-sass and running sass-migrator:
```
Error: expected "}".
╷
17 │   monospace !default},
│             ^
╵
src/styles/foundation/_typography.scss 17:13  root stylesheet
Migration failed!
```
Removing dangling `!default` that causes the parsing issue. I don't know what it's supposed to do. According to @bpscott:
> This looks like a straight up bug and we can remove this ...

Remove dangling default

---

UNRELEASED.md
src/components/Heading/Heading.tsx
src/components/Heading/tests/Heading.test.tsx
src/components/Layout/README.md
src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx
src/components/Layout/tests/Layout.test.tsx

* In the SFN application, we want to link users from the home page to a section of the Settings page
* The `AnnotatedSection` subcomponents allow us to break up content of a Settings page, but do not support hash links
* The implicit layout used by `Layout` assumes that `Section` or `AnnotatedSection` will always be the direct child node of the parent, which does not allow consumers to wrap their content section in a labelled div
Example of broken layout with a wrapper div around the shipping section:
* Adds an optional ID prop to the `Heading` component
* Adds an optional ID prop to the `Layout.AnnotatedSection` component, passed through to the primary Heading
**I couldn't get this working locally 🤔, but the changes seem pretty straightforward**

[Layout][Heading] add ID prop to Heading, Layout.AnnotatedSection

---

UNRELEASED.md
src/components/ActionMenu/components/Actions/tests/Actions.test.tsx
src/components/ActionMenu/components/MenuGroup/tests/MenuGroup.test.tsx
src/components/ActionMenu/components/RollupActions/tests/RollupActions.test.tsx
src/components/ActionMenu/tests/ActionMenu.test.tsx

[Test modernization] Modernizes ActionMenu and its components

---

UNRELEASED.md
src/components/Tabs/components/Item/tests/Item.test.tsx
src/components/Tabs/components/List/tests/List.test.tsx
src/components/Tabs/components/Panel/tests/Panel.test.tsx
src/components/Tabs/components/Tab/tests/Tab.test.tsx
src/components/Tabs/components/TabMeasurer/tests/TabMeasurer.test.tsx

I am updating existing tests for Item, Panel, List, Tab, TabMeasurer components to use the new testing framework.
First time doing this, so if you have any suggestion, it would be really appreciate it.

[Test Modernization]: Add test modernization to Item, Panel, List, Tab, TabMeasurer

---

UNRELEASED.md
src/components/ColorPicker/components/AlphaPicker/tests/AlphaPicker.test.tsx
src/components/ColorPicker/components/HuePicker/tests/HuePicker.test.tsx
src/components/FooterHelp/tests/FooterHelp.test.tsx
src/components/FormLayout/components/Group/tests/Group.test.tsx
src/components/FormLayout/components/Item/tests/Item.test.tsx
src/components/FormLayout/tests/FormLayout.test.tsx

[Test modernization] Modernizes FormLayout and some components of ColorPicker 

---

UNRELEASED.md
src/components/Card/components/Header/tests/Header.test.tsx
src/components/Card/components/Section/tests/Section.test.tsx
src/components/Card/components/Subsection/tests/Subsection.test.tsx
src/components/Card/tests/Card.test.tsx

I am updating existing tests for the following components in Card component to use the new modern framework:
- Header
- Section
- Subsection
- Card
Part of test modernization (https://docs.google.com/spreadsheets/d/1GBuEZbOpVYJLNISK7gL69DU8rCxocn5L5GYaKtPXPbU/edit#gid=1498187033), updating tests using` {mountWithAppProvider} from 'test-utilities/legacy'` to `{mountWithApp} from 'test-utilities'.`

[Test Modernization]: Card components

---

UNRELEASED.md
src/components/TextField/TextField.scss

Fixes https://github.com/Shopify/polaris/issues/182
I think webkit overrides the color value of disabled inputs. We were using current color here before because I think legacy Polaris had different colors for different disabled states i.e. error. Now they're all using `--p-text-disabled`
<details>
```jsx
import {Page, TextField} from …
```

[TextField] Fix disabled text color in Safari

---

UNRELEASED.md
src/components/Navigation/Navigation.tsx
src/components/Navigation/README.md
src/components/Navigation/tests/Navigation.test.tsx

Fixes #4289 
Fixes Shopify/handshake-discovery-team#247
Currently it's not possible to pass a label to the Navigation component that can be used to differentiate this `nav` from other nav when navigating with landmarks.
This PR is adding a way to generate the following output (described here: https://www.w3.org/WAI/tutorials/menus/structure/#label-menus):
```html
<nav aria-labelledby="mainmenulabel">
<h2 id="mainmenulabel" class="visuallyhidden">Main Menu</h2>
</nav>
```
From this implementation:
```html
<Navigation ariaLabelledBy="mainmenulabel">
<VisuallyHidden>
<h2 id="mainmenulabel">Main</h2>
</VisuallyHidden>
</Navigation>
```
Adds `ariaLabelledBy` props to `Navigation` component. It is then passed as `aria-labelledby` property to the `<nav>` element. …

[Navigation] Add ariaLabelledBy prop in order to add menu label for screen readers

---

UNRELEASED.md
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx

The tests all pass but there is a warning in the terminal that I have not figured out how to clear.

[Test modernization] Modernizes DualThumb

---

UNRELEASED.md
src/components/Autocomplete/Autocomplete.scss
src/components/Autocomplete/Autocomplete.tsx
src/components/Autocomplete/README.md
src/components/Autocomplete/components/MappedOption/MappedOption.tsx
src/components/Autocomplete/tests/Autocomplete.test.tsx
src/components/OptionList/OptionList.tsx
src/components/OptionList/tests/OptionList.test.tsx
src/types.ts
src/utilities/options.ts

Fixes https://github.com/Shopify/polaris-react/issues/4180
The current Autocomplete options list only supports single sections, this PR makes sure we're able to support multiple sections to do things like this:
https://user-images.githubusercontent.com/15235605/119555696-26ccb680-bd6c-11eb-97f3-aa8fc38bd954.mp4
<details>
```tsx
import {SearchMinor} from …
```

[Autocomplete] Adding multi sections support

---

UNRELEASED.md
src/components/ActionList/ActionList.scss
src/components/ActionList/ActionList.tsx
src/components/ActionList/components/Section/Section.tsx
src/components/ActionList/tests/ActionList.test.tsx

Fixes linked issue (see mentions below)
Creating consistent spacing between the list, items, sections & titles.
Code below displaying a bunch of different combinations between sections/items/section titles
<details>
```jsx
import {ImportMinor, ExportMinor} from '@shopify/polaris-icons';
import {Page, Popover, Button, ActionList} from '../src';
const actionListProps = [
{
sections: [
{
title: 'File options',
items: [
{content: 'Import file', icon: ImportMinor},
{content: 'Export file', icon: ExportMinor},
],
},
{
title: 'File options',
items: [
{content: 'Import file', icon: ImportMinor},
{content: 'Export file', icon: ExportMinor},
],
},
{
items: [ …
```

[ActionList] Make spacing consistent

---

UNRELEASED.md
src/components/TopBar/components/Menu/components/Message/tests/Message.test.tsx
src/components/TopBar/components/Menu/tests/Menu.test.tsx
src/components/TopBar/components/Search/tests/Search.test.tsx
src/components/TopBar/components/SearchDismissOverlay/tests/SearchDismissOverlay.test.tsx
src/components/TopBar/components/SearchField/tests/SearchField.test.tsx
src/components/TopBar/components/UserMenu/tests/UserMenu.test.tsx
src/components/TopBar/tests/TopBar.test.tsx

I am updating existing tests for Message, Menu, Search, SearchDismissOverlay, SearchField, UserMenu and TopBar components to use the new modern framework.

[Test modernization] on TopBar components tests

---

UNRELEASED.md
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx

Related to https://github.com/Shopify/core-workflows/issues/26, we would like to instrument events in the admin nav to start tracking all clicks. Currently, we can do that fairly easily except for the case of using a `secondaryAction` on a `Nav/Item` component. To my knowledge, this is only used for the "View Storefront" icon but we may add more secondary actions in the future.
This allows a click handler to be passed in and used from the parent `Item` component when specifying a secondary action icon.
Prop chains to `UnstyledLink` when create the secondary action components.
- Run this Polaris version in local web
- Modify [this object] to contain an `onClick` prop with a function that does something
- Load web and click on the View Storefront icon. Notice the click handler executed …

[Nav/Item] Delegate onClick prop to UnstyledLink for secondaryAction

---

UNRELEASED.md
src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

This was noticed durning a bug hunt
Removing the complexity around changing the clear buttons state so the clear button won't be visible to screen readers when the field is empty
|Before|After|
|-|-|
|![Screen Shot 2021-08-09 at 12 06 07 PM](https://user-images.githubusercontent.com/24610840/128737989-04b40589-5991-459a-bafa-ee94c91dbeaf.png)|![Screen Shot 2021-08-09 at 11 38 29 AM](https://user-images.githubusercontent.com/24610840/128738003-c9843eb1-6bd8-4fe3-a0c6-835ff31d45f4.png)|

[TextField] Fully removed clear button when there is no text

---

UNRELEASED.md
src/components/Truncate/tests/Truncate.test.tsx
src/components/UnstyledButton/tests/UnstyledButton.test.tsx

I am updating existing tests for `Truncate` and `UnstyledButton` components to use the new modern framework.

[Test Modernization]: Add test modernization to Truncate and UnstyledButton

---

UNRELEASED.md
src/components/CalloutCard/tests/CalloutCard.test.tsx
src/components/Caption/tests/Caption.test.tsx
src/components/CheckableButton/tests/CheckableButton.test.tsx
src/components/TextField/components/Resizer/Resizer.tsx
src/components/TextField/components/Resizer/tests/Resizer.test.tsx
src/components/VideoThumbnail/tests/VideoThumbnail.test.tsx

I am updating existing tests for CalloutCard, Caption, CheckableButton, Resizer, VideoThumbnail components to use the new modern framework.

[Test Modernization]: Add test modernization to  CalloutCard, Caption, CheckableButton, Resizer, VideoThumbnail 

---

UNRELEASED.md
src/components/Avatar/Avatar.scss
src/components/Avatar/Avatar.tsx
src/components/Avatar/README.md

I work in Vault Tools and recently with the launch of Debrief the need for a new Avatar sizing came up.
In  section Prototypes being reviewed in  (exhibit A) we use an Avatar size of 24px to condense the list and reduce whitespace.
The Avatar small size has the following result (exhibit B).
Our designer, @chrishs, has also envisioned smaller avatar for single line text components (exhibit C)
Opening this contribution to extend applications of Avatar
1. Adds a new css variable for the extrasmall size at 24px
2. Created the `.sizeExtraSmall` css class and added an extra min-width so it doesn't affect the base value for that attr (currently `$sizeSmall`)
3. Added `extraSmall` to Size prop
Sizes for comparrison
🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/ma …

[Avatar] Add new sizing 'extra-small'

---

UNRELEASED.md
src/components/ProgressBar/ProgressBar.scss
src/components/ProgressBar/ProgressBar.tsx

Within web we have a use case where a full progress bar is indicative of a critical event that requires immediate action:
This PR adds the `Interactive/Critical` color to the `ProgressBar` component
<details>
```jsx
return (
<ProgressBar progress={70} color="critical" />
</Page>
);
}
```
</details>

[ProgressBar] Add critical color prop option

---

UNRELEASED.md
src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx
src/components/Layout/tests/Layout.test.tsx
src/components/MediaCard/tests/MediaCard.test.tsx

Updating existing tests to use the new modern framework and eliminate stale dependencies.
For the following component tests:
* MediaCard
* Layout
Part of test modernization, updating tests using `{mountWithAppProvider} from 'test-utilities/legacy'` to `{mountWithApp} from 'test-utilities'`

[Test Modernization]: Modernized MediaCard, and Layout tests

---

UNRELEASED.md
src/components/ColorPicker/tests/ColorPicker-ssr.test.tsx
src/components/ColorPicker/tests/ColorPicker.test.tsx

[Test Modernization] Switch to using mountWithApp on ColorPicker tests.

---

UNRELEASED.md
src/components/Icon/tests/Icon.test.tsx
src/components/Image/tests/Image.test.tsx

[Test Modernization] Modernizing Icon and Image tests.

---

UNRELEASED.md
src/components/Choice/tests/Choice.test.tsx
src/components/DisplayText/tests/DisplayText.test.tsx
src/components/DropZone/components/FileUpload/FileUpload.tsx
src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
src/components/MessageIndicator/MessageIndicator.tsx
src/components/MessageIndicator/tests/MessageIndicator.test.tsx
src/components/Modal/components/Dialog/tests/Dialog.test.tsx
src/components/Tag/tests/Tag.test.tsx
src/components/UnstyledLink/tests/UnstyledLink.test.tsx

I am updating existing tests for UnstyledLink, Tag, DisplayText, FileUpload, MessageIndicator, Choice and Dialog components to use the new modern framework.
Thanks @rdott for the suggestion on the tag tests!

[TestModernization]: Add test modernization to UnstyledLink, Tag, DisplayText, FileUpload, MessageIndicator, Choice and Dialog

---

UNRELEASED.md
esnext/index.js
package.json

Removing legacy configuration.
Removing the esnext folder.
The esnext folder was a relic from a time before sewing-kit supported reading
esnext entrypoints from the `esnext` key in package.json, which was
added in sewing-kit 0.135.0 (released Aug 2020).
The configuration that forced sewing-kit to always read from this folder (instead of looking at the esnext entrypoint) was removed in Shopify/sewing-kit#2566 and released as sewing-kit 0.152.0 (released Mar 2021).
If you are building an app using sewing-kit, you must use sewing-kit 0.152.0 or newer if you want esnext build support.

Remove the esnext folder

---

UNRELEASED.md
src/components/Collapsible/tests/Collapsible.test.tsx
src/components/Tabs/tests/Tabs.test.tsx
src/components/TextStyle/tests/TextStyle.test.tsx

I am updating existing tests for Collapsible, Tabs and TextStyle components to use the new modern framework. I worked with @rdott  in solving several of the details here on those tests.

[TestModernization]: Add test modernization to Collapsible, Tabs and TextStyle

---

UNRELEASED.md
src/components/Filters/tests/Filters.test.tsx

Wrapping up leftover `Filters` test from https://github.com/Shopify/polaris-react/pull/4434/

[Test Modernization] Modernizing leftover Filters test.

---

UNRELEASED.md
src/components/Checkbox/tests/Checkbox.test.tsx
src/components/ChoiceList/tests/ChoiceList.test.tsx

I am updating existing tests for Checkbox and Choicelist components to use the new modern framework.

[TestModernization]: Add test modernization to Checkbox and Choicelist

---

UNRELEASED.md
src/components/TextField/tests/TextField.test.tsx

I am updating existing tests for TextField components to use the new modern framework.

[TestModernization]: Add test modernization to TextField
