.eslintignore
=> Remove unneeded line in eslintignore

UNRELEASED.md, documentation/Accessibility testing.md
Moving this PR from https://github.com/Shopify/polaris-react-deprecated/pull/2391
Adding documentation updates based on feedback to the new repo. 🎉 
Updates `Accessibility testing.md`.
<details>
```jsx
import {Page, AppProvider} from '@shopify/polaris';
export default class Playground extends …
```
=> [a11y] Improved testing checklist

CHANGELOG.md, UNRELEASED.md, documentation/Versioning and changelog.md, src/components/ExceptionList/README.md, src/components/RangeSlider/RangeSlider.scss
Removes links to legacy PR urls
Update references to the legacy polaris repo to point to point to polaris-react
All the find and replace.
=> Update repo links

src/components/AppProvider/config.ts
While doing some dependency auditing i spotted these two files that are never included by any other file. I think one is a remnant of the initial pass at themeing support, which was then moved to elsewhere in the codebase.
Delete the files.
=> Remove two files that are never referenced

src/components/Frame/Frame.tsx, src/components/Frame/tests/Frame.test.tsx
The fallback value of this custom property does not take effect in safari. 
Ensuring the property is always present.
Note: I pulled `setGlobalRibbonRootProperty` out of the `setGlobalRibbonHeight` so that it can be called on without needing a `globalRibbon` prop
Using the playground verify the that `--global-ribbon-height` is added to the <HTML> with and without the `globalRibbon` prop on the Frame.
<details>
```jsx
import {
Page,
AppProvider,
Frame,
Toast,
Card,
Loading,
ActionList,
ContextualSaveBar,
TopBar,
Navigation,
TextContainer,
Modal,
Layout,
FormLayout,
TextField,
SkeletonBodyText,
SkeletonDisplayText,
SkeletonPage,
Stack,
} from …
```
=> Always setting a value to --global-ribbon-height CSS prop

src/components/Navigation/Navigation.scss, src/components/Navigation/README.md, src/components/Navigation/components/Item/Item.tsx, src/components/Navigation/components/Item/tests/Item.test.tsx, src/components/index.ts
Currently we don't have a way to indicate to merchants that an item in the navigation has a sub item that is new.
This adds a `new` prop to items and subitems that will callout a new item to the merchant.
<details>
```jsx
import {Page, AppProvider, Navigation} from '@shopify/polaris';
export default class …
```
=> [Navigation] Add new indicators to nav items 

src/components/AppProvider/README.md, src/components/Frame/README.md, src/components/TopBar/README.md
Based on the proposed [color difference threshold](https://codesandbox.io/embed/z25wk6w98m?hidenavigation=1&view=preview), our examples would fail 😢 
I just quickly grabbed colors that would work, but maybe this needs some more love? Or maybe our checker formula needs tweaking?
The two possible versions look like this:
=> [Top bar] Update example color

src/test-utilities/enzyme.tsx, src/utilities/app-bridge-transformers.ts
Until we get a clear story for how to handle absolute paths lets avoid
them except in test files.
=> Avoid absolute paths for the moment

src/components/Frame/Frame.scss
Closes #556.
|Before|With `when-not-printing`|After|
|-|-|-|
|![screen shot 2018-11-07 at 12 01 18 pm](https://user-images.githubusercontent.com/1403188/48147336-12477200-e285-11e8-99d2-b8e71bf01e71.png)|![screen shot 2018-11-07 at 12 02 25 pm](https://user-images.githubusercontent.com/1403188/48147359-1ecbca80-e285-11e8-821f-bc36af34048b.png)|![screen shot 2018-11-07 at 12 02 49 pm](https://user-images.githubusercontent.com/1403188/48147377-2a1ef600-e285-11e8-92fd-5c748287797c.png)|
Uses print styles that override padding and background color when `Frame` is printing.
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.m …
=> [Frame] disable navigation left padding and main background color when printing

src/components/Autocomplete/components/ComboBox/ComboBox.tsx, src/components/index.ts
Resolves https://github.com/Shopify/polaris-react/issues/467
Adds `popoverWasActive` state and sets popover to active if there are options again. I'm not sure this is testable.
<details>
```jsx
import {Page, AppProvider, Stack, Tag, TextContainer} from '@shopify/polaris';
import Autocomplete from …
```
=> [Autocomplete] Reopen popover if popoverWasActive and there are options

src/components/Navigation/components/UserMenu/index.ts
Hopeful fix for #586
Removed an unused import/export
=> Scss files should not be exported from components

.github/changelog.yml
Adding support for this in https://github.com/Shopify/probot-shopify/pull/110
=> Add link to unreleased file in our changelog check

UNRELEASED.md, src/components/Scrollable/Scrollable.tsx
Resolves https://github.com/Shopify/polaris-react/issues/535
This PR adds an `onScrollToBottom` prop to the `Scrollable` component.
For the web resource pickers, we implemented infinite loading using the `Scrollable` component. We had to duplicate it to expose a new `onScrollToBottom` prop. We now want to push back the changes we made so can 🔥 out cloned component.
Add support for an `onScrollToBottom` prop.
Note that there is no test for this new prop. @AndrewMusgrave helped me debug it but in the test environment, `scrollHeight`, `scrollTop` and `clientHeight` are all zero. The test would just always pass so it does not bring any real value. If you have a better suggestion, let me know!
<details>
<summary>Example of test</summary>
```jsx
import {noop} …
```
=> [Scrollable] Add onScrollToBottom prop

UNRELEASED.md, src/components/DataTable/DataTable.tsx, src/components/DataTable/components/Cell/Cell.tsx
Causes build to fail
Uses a relative import
TBD: Not totally sure. Possibly run web in production?
=> [DataTable] Use relative path

src/components/TextField/components/Resizer/Resizer.tsx, src/components/TextField/components/Resizer/tests/Resizer.test.tsx
Re-opening my PR for resizer tests.
=> [Resizer] Add tests

src/components/Tabs/Tabs.tsx, src/components/Tabs/components/List/tests/List.test.tsx, src/components/Tabs/components/TabMeasurer/tests/TabMeasurer.test.tsx, src/components/Tabs/tests/Tabs.test.tsx, src/components/Tabs/utilities.ts
Re-opening my PR for tabs tests.
=> [Tabs] Add tests

CHANGELOG.md, UNRELEASED.md, documentation/Accessibility testing.md, src/components/ActionList/README.md, src/components/AppProvider/README.md, src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx, src/components/FooterHelp/README.md, src/components/InlineError/tests/InlineError.test.tsx, src/components/Navigation/README.md, src/components/TextField/README.md, src/components/TextField/TextField.tsx, src/components/TextStyle/README.md, src/components/TopBar/README.md, src/components/TopBar/components/UserMenu/UserMenu.tsx, src/locales/en.json
What do you do when you have a few spare minutes while waiting for folks to join a meeting?
```
ag "[a-zA-Z]'[a-zA-Z]"
-> fix occurrences of ' into ’
```
[What is `ag`?](https://geoff.greer.fm/ag/)
https://polaris.shopify.com/content/grammar-and-mechanics#section-punctuation
=> Fix straight quotes into apostrophes

UNRELEASED.md
Fixing up formatting to avoid including unrelated changes in another PR. Will squash and merge
=> Cleanup changelog

CHANGELOG.md, UNRELEASED.md
Commits: https://github.com/Shopify/polaris-react/compare/v3.2.0...master
=> Changelog for v3.2.1

UNRELEASED.md, src/components/Page/components/Header/Header.tsx
=> [Page] only render actions wrapper in header component if actions are present

src/components/Scrollable/tests/Scrollable.test.tsx
Adds a test for unmounting scrollable, gets us above 80%
=> [Scrollable] Test unmount

documentation/Console messages.md
@tmlayton as mentioned earlier, this is where we have _some_ docs around deprecation.
This PR just makes it look nicer.
=> [Documentation] Add syntax highlighting to console logging guidelines

UNRELEASED.md, src/components/TextField/TextField.tsx, src/components/TextField/tests/TextField.test.tsx
See https://github.com/Shopify/polaris-react/pull/708#issuecomment-446746548 for rationale.
=> [Texfield] revert autocomplete nope

src/components/ResourceList/components/Item/Item.tsx
Noticed this was fixing some RL issue. Any reason this shouldn't 🔥 ?
=> [ResourceList] Remove comment

UNRELEASED.md, src/components/CalloutCard/CalloutCard.scss, src/components/CalloutCard/CalloutCard.tsx, src/components/CalloutCard/README.md, src/components/CalloutCard/tests/CalloutCard.test.tsx
Resolves #353 
In the app I'm working on we use a `CalloutCard` with dismiss button like banners have. I noticed this functionality is missing from the component & that there's an issue requesting this.
Add a prop `onDismiss` which when present, adds the dismiss button with the same functionality & style as the `Banner` component.
Before:
After (with onDismiss):
From this issue: https://github.com/Shopify/polaris-react-deprecated/issues/1596 it seems like the same dismiss functionality as `Banner` is desired.
📄 [Changelog …
=> [CalloutCard] Add dismiss button & callback

src/components/Tooltip/README.md
Along with https://github.com/Shopify/polaris-styleguide/pull/2463, this fixes the tooltip's markup not being captured and displayed with the component example markup.
Sets the tooltip to start out as `active`. This initial render of the example with the tooltip showing allows for the markup to be correctly captured and displayed with the rest of the example's markup.
- `git checkout tooltip-example-always-active && yarn dev
- Open …
=> [Tooltip] Updated example to initially be active

UNRELEASED.md, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/tests/Checkbox.test.tsx
Fixes #716 
When the checkbox's onChange handler is called, if it was previously checked and is currently not checked it'll be focused.
https://cl.ly/24094f0ef8b4
Toggle the checkboxes
<details>
```jsx
import {Card, ResourceList, Avatar, TextStyle} from '@shopify/polaris';
state = {
};
};
return (
id={id}
url={url}
media={media}
accessibilityLabel={`View …
```
=> [Checkbox] Fix checkbox losing focus

UNRELEASED.md, src/components/ResourceList/ResourceList.tsx, src/components/ResourceList/tests/ResourceList.test.tsx
Fixes #735
Removing ref from state and make it a class property
Thank you for the playground @andrewpye
<details>
```jsx
import {
Avatar,
Button,
Card,
Label,
List,
ResourceList,
Select,
TextStyle,
Page,
const initialItemList = [
{
id: 341,
url: 'customers/341',
name: 'Mae Jemison',
location: 'Decatur, USA',
},
{
id: 256,
url: 'customers/256',
name: 'Ellen Ochoa',
location: 'Los Angeles, USA',
},
];
state = {
items: [],
};
};
addItems = () => {
this.setState({items: initialItemList});
}; …
```
=> [ResourceList] Fix heading not loading

src/components/RangeSlider/components/DualThumb/DualThumb.tsx
=> [RangeSlider] event handler cleanup

src/components/Button/Button.tsx
This was dead code that would never be called
🔥 🔥 🔥
=> Remove the last vestiges of Indicator from Button

UNRELEASED.md, src/components/Button/Button.scss, src/components/Button/Button.tsx, src/components/Button/README.md, src/components/Button/tests/Button.test.tsx, src/components/InlineError/InlineError.scss, src/components/Link/Link.scss, src/components/Link/Link.tsx, src/components/Link/README.md, src/styles/shared/links.scss
In order to satisfy this request https://github.com/Shopify/web/issues/9320 we added a `monochrome` option to Button and to Link
Adding a `monochrome` prop to `Link`, `Button plain` and `Button outline`  makes the component's colours (icon, text, borders) the same as the `currentColor` and adds an underline to text on `plain`.
Also this adjusts the top and bottom margin on the `plain` and `monotone` button so that they line up with the text.
Also added aria-pressed because for accessibility the above web example will require it. 
📄 [Changelog …
=> [Button and Link] monochrome variant

src/components/RangeSlider/components/DualThumb/DualThumb.tsx, src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
Addresses #841
|before|after|
|-|-|
|<img width="1131" alt="screen shot 2019-01-17 at 11 51 13 am" src="https://user-images.githubusercontent.com/1403188/51334561-0f6bb900-1a4e-11e9-92c7-f462cc1f86cc.png">|<img width="1132" alt="screen shot 2019-01-17 at 11 49 19 am" src="https://user-images.githubusercontent.com/1403188/51334467-d9c6d000-1a4d-11e9-8f1b-4ab50f3f46d8.png">|
=> [Range slider] test dual thumb key press

.vscode/launch.json
The [`vscode-jest` extension](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) enables VSCode debugger integration which significantly improves the test diagnostics experience.
In order to support the `vscode-jest` extension with `sewing-kit` we need to add a special [`vscode-jest-tests` launch config](https://github.com/jest-community/vscode-jest#how-do-i-debug-tests) that routes debug invocations to `sewing-kit`.
First install the `vscode-jest` extension
Then find a test, set breakpoint, and hit the clickable `Debug` link above the test
Eventually, the debugger will connect and the execution will stop on your breakpoint allowing you to hover over code to inspect it.
We also have full access to the debugger context to inspect variables, add watch expressions, and …
=> Add launch configuration to enable vscode-jest

package.json, yarn.lock
It is never used now that we use storybook as  a playground
🔥
=> Remove react-html

src/components/Stack/README.md
=> Improve Stack vertical alignment example

UNRELEASED.md, src/components/DataTable/DataTable.tsx
Fixes #873 
Currently, if the first click or keypress of a sortable column heading is on the *initially sorted column,  the `sortDirection` is not yet set on state so it's value when destructured from state in the sort event handler is `undefined`. This throws off the logic that ensures the sorting is reversed on second sort.
This PR simply adds the value set on the `defaultSortDirection` prop as the default value of the `sortDirection` destructuring assignment within the sort handling callback.  (Wow, what a mouthful 😅)
\* Whatever column is set on the `initialSortColumnIndex` prop, which defaults to the first sortable column if unset. …
=> [DataTable] Fixes initial sort direction not set in sort handler

UNRELEASED.md, src/components/DataTable/README.md
Resolves #889  
Adds a final "kitchen sink" example that includes all the props.
<details>
```jsx
import {Page, Link, Card, DataTable} from '../src';
state = {
sortedRows: null,
};
sortCurrency = (rows, index, direction) => {
return [...rows].sort((rowA, rowB) => {
const amountA = parseFloat(rowA[index].substring(1));
const amountB = parseFloat(rowB[index].substring(1));
return direction === 'descending' ? amountB - amountA : amountA - amountB;
});
};
handleSort = (rows) => (index, direction) => {
this.setState({sortedRows: this.sortCurrency(rows, index, direction)});
};
render() {
const …
```
=> [DataTable] Add full example of data table to documentation

UNRELEASED.md, src/components/TopBar/TopBar.scss, src/components/TopBar/components/Search/Search.scss
Resolves https://github.com/Shopify/polaris-react/issues/1008
Aligning the search and its results with the page content
<details>
```jsx
import {ActionList, AppProvider, Card, ContextualSaveBar, DisplayText, Form, FormLayout, Frame, Label, Layout, List, Loading, Modal, Navigation, Page, TextContainer, TextField, Toast, TopBar, …
```
=> [TopBar] align search with page content

scripts/open-styleguide-pr.js
=> Ping Ben when a PR is opened on the style guide

UNRELEASED.md
Just a quick PR reference fix.
=> [Range slider] Fix changelog entry

UNRELEASED.md, src/components/TextField/TextField.scss
Fixed: #1048
We were facing an issue only on Chrome when we used the `TextField` inside a `Collapsible` and which the wrapper can scroll. The `Backdrop` popped over the `input`when you focus on an input that was fully hidden on the first rendering (you need to scroll) which hide value inside the input (See screenshot below). 
You can check this small [CodePen](https://codepen.io/anon/pen/QYZWrZ) if you want to find which attribute causing the issue 😛 
We change the way we do the animation when we focus a `Textfield`. We add a pseudo element on the `Backdrop` and change the `opacity` instead of animate the `box-shadow`.
**We could solve the problem by adding the `backface-visibility: hidden;` to the input element but it seems more a hack fix.** …
=> [TextField] Fix the weird Backdrop issue on Chrome

UNRELEASED.md
I realized the changelog wasn't clear enough.
=> Update unrealease changes about DatePicker

package.json, src/styles/foundation/spacing.scss, yarn.lock
Related to https://github.com/Shopify/polaris-tokens/pull/48 and https://github.com/Shopify/polaris-react/issues/1007
Imports token for spacing map.
<details>
```jsx
render() {
return (
<Page …
```
=> [Sass] Import token for spacing

UNRELEASED.md, src/components/Banner/Banner.scss, src/components/Button/Button.scss, src/components/Select/Select.scss
Resolves https://github.com/Shopify/polaris-react/issues/1007
Adds `base-tight` to the Sass spacing map (base * 3) and replaces instances of `rem(12px)`.
<details>
```jsx
import {Page, Banner, Button, Card, Select} from '../src';
render() { …
```
=> [Sass] Spacing base-tight

UNRELEASED.md, src/components/Modal/README.md
Documentation is not explicit on what properties are available to a Modal in an embedded app context.
It seems that others have run into this issue because the error message provided when using Modal is not clear:
#641 
It makes it explicit as to what properties are available to `Modal` in an embedded app context.
<details>
```jsx …
```
=> [Documentation] Improve Docs For Modal Embedded App Props

UNRELEASED.md, src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts, src/components/AppProvider/utilities/createAppProviderContext/tests/createAppProviderContext.test.tsx
follow up to https://github.com/Shopify/polaris-react/pull/1033 cc @tmlayton 
Uses the new, simpler App Bridge hooks API, improves test coverage, and adds a changelog entry (does it make sense?).
=> [App Bridge] Use new App Bridge hook shape and expand coverage

UNRELEASED.md, examples/create-react-app/package.json, examples/create-react-app/yarn.lock
Security alerts in our [CRA example](https://github.com/shopify/polaris-react/network/alerts)
Updating deps
* Run example
* Run tests
🎉
=> [CRA Example] Update deps

UNRELEASED.md, src/components/DropZone/DropZone.tsx, src/components/DropZone/components/FileUpload/FileUpload.tsx, src/utilities/capitalize.ts, src/utilities/tests/capitalize.test.ts
Creating a `capitalize` function and using that instead of `_.capitalize`
Test pass? 💯 
=> Remove lodash capitalize

UNRELEASED.md, src/components/Tag/Tag.scss
Fixes #1077 
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/344839/53141351-9b3c9d80-3544-11e9-88e1-9d647619dcd8.png)|![image](https://user-images.githubusercontent.com/344839/53141360-a4c60580-3544-11e9-8b9a-bd1676683ed2.png)|
=> [Tag] Fix rounded corners on tag button

README.md
Resolves https://github.com/Shopify/polaris-react/issues/1088
=> Update instructions for testing on mobile to reflect Storybook iframe

UNRELEASED.md, src/types.ts, src/utilities/isObject.ts, src/utilities/pluckDeep.ts, src/utilities/tests/isObject.test.ts
Part of removing lodash #991
Creating a `isObject` function and using that instead of `_.isObject`
Test pass? 💯 
=> Remove lodash isObject

UNRELEASED.md, src/components/Navigation/Navigation.scss, src/components/Navigation/components/Item/Item.tsx, src/components/Navigation/components/Item/tests/Item.test.tsx, src/components/Navigation/variables.scss, src/styles/shared/icons.scss
Resolves https://github.com/Shopify/polaris-react/issues/885
Inlining user uploaded svgs is potentially dangerous as scripts can be executed if they are part of the svg. In a previous PR, I updated the `Icon` component to take an `untrusted` prop that will tell the component to render the contents in an `img` tag instead of an svg.
This PR changes how Item works by using the Icon component for svg strings instead of using `dangerouslySetInnerHTML`. To make this work, I updated the `recolor-icon` mixin that set's the fill for the icon. I choose to make the `$filter-color` the last param to keep the current functionality for icons.
~⚠️ **Note**: Online Store's icon doesn't work with this solution so if we are okay with this, we'd have to update the Online Store sales channel.~
Edit: Fixed! …
=> [Navigation Item] Use Icon component with `untrusted` instead of `dangerouslySetInnerHTML`

UNRELEASED.md, package.json, src/components/AppProvider/utilities/withSticky/StickyManager.ts, yarn.lock
Part of removing lodash / lodash decoators #991
Uses debounce with specific settings instead of throttle
Removes lodash-decorators
Code from https://github.com/Shopify/polaris-react-deprecated/pull/1119 😄 
<details>
```jsx
import {
Page,
ResourceList,
Card,
AppliedFilter,
FilterType,
AppProvider,
Sticky,
import {autobind} from '@shopify/javascript-utilities/decorators';
const items: any[] = [
{
onClick: true,
url: 'https://www.google.com',
actions: [{content: 'View listing', url: 'http://www.facebook.com'}],
title: 'Has url, onClick, and actions',
},
{
onClick: false,
url: 'https://www.google.com',
actions: …
```
=> Remove lodash decorators

UNRELEASED.md, src/components/DropZone/DropZone.scss, src/components/DropZone/DropZone.tsx, src/components/DropZone/components/Context/Context.tsx, src/components/DropZone/components/FileUpload/FileUpload.tsx, src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx, src/components/DropZone/tests/DropZone.test.tsx, src/components/DropZone/types.ts
This reverts commit c4a52d4b45f472a1ecb4c9b19405f04a2235b1cd.
Reason for the revert: https://github.com/Shopify/polaris-react/pull/1127
=> Revert "Constrain drop zone height based on inherited wrapper height"

UNRELEASED.md, src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
Resolve https://github.com/Shopify/polaris-react/issues/1124
Using real events instead of mocking a listener map
=> [ComboBox] Fix tests

UNRELEASED.md, src/components/Modal/Modal.tsx, src/components/Page/Page.tsx, src/utilities/pick.ts, src/utilities/tests/pick.test.ts
Creating a `pick` function and using that instead of `_.pick`
Test pass? 💯 
=> Remove lodash pick

UNRELEASED.md, examples/browserify/package.json, examples/browserify/yarn.lock
Update example deps
Updating deps and config
Run the example 😄
=> Update browserify example dependencies

examples/browserify/yarn.lock
Hopefully this resolves our security vulnerabilities
=> Regenerate lock file for browserify example

UNRELEASED.md
Forgot to add a log entry for #1202 😅
=> Add unreleased entry

UNRELEASED.md, examples/webpack/package.json, examples/webpack/webpack.config.js, examples/webpack/yarn.lock
* keep examples up to date 
* fix the example since it doesn't compile
* add webpack cli
* update deps
* fix config
run the example 😄
=> Update webpack example

CHANGELOG.md, UNRELEASED.md
Updating the change log with the unreleased changes in preparation for the 3.11.0 release.
=> [3.11.0 Release] Move UNRELEASED to CHANGELOG

UNRELEASED.md, src/components/ResourceList/components/BulkActions/BulkActions.scss, src/components/ResourceList/components/BulkActions/BulkActions.tsx, src/components/ResourceList/components/BulkActions/tests/BulkActions.test.tsx
Only some of the buttons are disabled while loading and some are missing disabled styles
* disabling some buttons
* adding disable styles
https://cl.ly/9ebcb6e65d2b
<details>
```jsx
import {
Avatar,
Card,
Label,
List,
ResourceList,
Select,
TextStyle,
state = {
selectedItems: ['341'],
};
};
return (
id={id}
url={url}
media={media} …
```
=> [ResourceList] Fix buttons not being disabled while loading

UNRELEASED.md, src/components/Autocomplete/README.md, src/components/Autocomplete/components/ComboBox/ComboBox.tsx, src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx, src/components/Autocomplete/tests/Autocomplete.test.tsx
Part two [of two](https://github.com/Shopify/polaris-react/pull/1248), fixes #1246
Replaces custom scroll listening with use of `Popover.Pane`'s `onScrollToBottom` prop.
Play with the new lazy load example in the deployment below (click "Show environments" for link), or copy/paste the playground code below into `playground/Playground.tsx` if you want to play around with and try to break this change.
<details>
<summary>Click to view collapsed …
=> Autocomplete on load more results fix

UNRELEASED.md, src/components/TopBar/components/Search/Search.scss
On small screens, the search overlay can stretch below the viewport if enough results are rendered.
The results rendered below the viewport are then unreachable, even if contained within a Scrollable container.
(related issue: https://github.com/Shopify/core/issues/5144)
Adding a `max-height: 100%;` css attribute to the overlay class seems to fix the issue
<details> …
=> [Search] Add max-height to Search Overlay

package.json, yarn.lock
Don't mind me, just doing some house cleaning! I discovered a dependency that we no longer use in the code base... so I've removed it.
=> Remove unused crypto dependency

package.json, yarn.lock
Use a stable release of percy's storybook plugin
Use a stable release of percy's storybook plugin
=> Use @percy/storybook - the changed the package name with v3

src/components/Banner/README.md
Gives clear answer about when to use the in-context banner vs. full banner without having to look for specific examples
Updates best practices section in Polaris.
=> Added sentence about in-card/modal/context banners

UNRELEASED.md
=> Update changelog entry

UNRELEASED.md, src/components/AppProvider/README.md
@alex-page noticed these errors while 🎩 a change
Changing the component from uncontrolled -> controlled 
Use the search field in the AppProvider examples
=> [AppProvider] Remove console errors in a few examples

UNRELEASED.md, src/components/ResourceList/components/CheckableButton/CheckableButton.tsx, src/components/ResourceList/components/CheckableButton/tests/CheckableButton.test.tsx
Fixes #1319
* add handler
* add test
`ResourceList with all of its example` in storybook has the action to test 👍
=> [CheckableButton] Add keyboard interaction

UNRELEASED.md, src/components/ResourceList/components/BulkActions/BulkActions.tsx, src/components/ResourceList/components/BulkActions/tests/BulkActions.test.tsx
Fixes #1316 
* apply the disabling prop before we spread on the action
* add test coverage to prevent regression
* changlog entry
<details>
```jsx
import {
Avatar,
Card,
Label,
List,
ResourceList,
Select,
TextStyle,
state = {
selectedItems: [341],
};
};
return (
id={id}
url={url}
media={media}
accessibilityLabel={`View details for ${name}`}
>
<h3>
<TextStyle …
```
=> [ResourceList] Fix promotedBulkActions not properly disabling

CHANGELOG.md, UNRELEASED.md
Fixes #0000 
<details>
```jsx
render() {
return (
</Page>
);
}
}
```
</details>
=> 3.13.0 Move unreleased to changelog

translation.yml
**Owners:** @Shopify/polaris
This Pull Request contains the configuration files required to have your source (English) strings sent for translation, and receive translations back into your repository.
- `buyer` for end users of Shopify stores
- `merchant` where the users are merchants
- `partner` for Shopify partners
Questions about this Pull Request? Hop in the [#intl-services](https://shopify.slack.com/messages/C7TJQLVC7) Slack channel. We're happy to help!
@Shopify/translation-platform
=> Add initial configuration for translation platform

UNRELEASED.md, src/styles/shared/skeleton.scss
Fixes https://github.com/Shopify/polaris-ux/issues/234
There wasn't a way to make it works for both normal and Microsoft high contrast, so we chose to use the Windows high contrast media query.
Run the playground locally or click the deployment link on this PR, and open one of the skeleton page examples.
You'll need to look this on Windows high contrast mode.
Talk to me if you need help :)
* [N/A] Tested on …
=> [a11y] Made skeleton works in windows high contrast mode

UNRELEASED.md, src/components/ResourceList/components/Item/Item.tsx
Iv'e seen this bug out a couple times in production. Simplifying the should also help make changes in the future
Make sure to 🎩  with ⌨️ and 🖱 
<details>
```jsx
import {Page, Avatar, Card, ResourceList, FilterType, TextStyle} from '../src';
state = {
sortValue: 'DATE_MODIFIED_DESC',
{
},
],
};
};
this.setState({appliedFilters});
};
handleSortChange = (sortValue) => { …
```
=> [ResourceList] Simplify / Improve interaction state logic

src/components/EmptyState/README.md
=> [documentation] Empty state: fix mobile example

UNRELEASED-V4.md, src/components/Scrollable/Scrollable.tsx, src/components/Scrollable/components/Context/Context.ts, src/components/Scrollable/components/Context/index.ts, src/components/Scrollable/components/ScrollTo/ScrollTo.tsx, src/components/Scrollable/components/ScrollTo/tests/ScrollTo.test.tsx, src/components/Scrollable/components/index.ts, src/components/Scrollable/tests/Scrollable.test.tsx, src/components/Scrollable/types.ts
To use the new context api 🎉 
Using the new context api
* try out storybook examples
=> [Scrollable] Update context api

UNRELEASED.md, src/locales/de.json, src/locales/es.json, src/locales/fr.json, src/locales/hi.json, src/locales/it.json, src/locales/ja.json, src/locales/ms.json, src/locales/nl.json, src/locales/pt-BR.json, src/locales/zh-CN.json, src/locales/zh-TW.json
This PR adds translations to the project. It will append multiple commits. Feel free to merge anytime.
Questions about the format of this Pull Request? Hop in the [#intl-services](https://shopify.slack.com/messages/C7TJQLVC7) Slack channel.
Questions about the translations in this Pull Request? Hop in the [#translation](https://shopify.slack.com/messages/C3XPBC62U) Slack channel.
We're happy to help!
@Shopify/polaris
=> Add translations: default

src/components/RangeSlider/components/DualThumb/DualThumb.scss, src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
Fixes styling inconsistencies between the single and dual range slider.
- Updates thumb styles
- fixes broken error styles
- fixes broken disabled styles.
=> [Range slider] Fix styles

.github/main.workflow
Fixes #0000 
<details>
```jsx
render() {
return (
</Page>
);
}
}
```
</details>
=> Add GH_TOKEN and GH_PAT

README.md
I tried following these guidelines when attempting to tophat the react repo for the first time and couldn't figure out why storybook kept coming up. Then I tried following these instructions and got stuck. I reached out to @dpersing and she gave me the step by step instructions. Tried to communicate the same instructions in this Readme.
=> Clarify instructions for tophatting

UNRELEASED.md, src/components/Icon/Icon.scss, src/components/TextField/README.md, src/components/TextField/TextField.scss, src/components/TextField/TextField.tsx, src/components/TextField/tests/TextField.test.tsx, src/styles/shared/icons.scss
Resolves #1115 
Adds a `clearButton` prop to the `textField` component to show a button that clears the value from the input.
The clear button only shows on `type="search"` inputs, unless `clearButton={false}`.
<details>
```jsx
import {Page, TextField} from '../src';
export default class Playground extends …
```
=> [TextField] Add clear button to textfield

src/components/Select/README.md
Updated first point under "Select options" for clarity
Feedback from CS team on clarity of the placeholder guidance.
Just updating a string of text.
<details>
```jsx
render() {
return (
<Page …
```
=> Update best practice for Select options

UNRELEASED.md, src/components/Frame/components/Toast/Toast.scss
Fixes https://github.com/Shopify/polaris-react/issues/1216
Adds a border to the `Toast` message to make it more visible in Windows high contrast mode:
<details><summary>Before</summary>
</details><br>
<details><summary>After</summary>
</details><br>
- Navigate to `Toast` -> `Basc toast` in the Polaris storybook & click on `Show Toast`.
=> [Toast] Add border for high contrast mode

UNRELEASED-V4.md, src/components/Toast/Toast.tsx
Part of #1484
I'm converting Toast to a functional component and removing `withContext`
=> [v4][Toast] Remove withContext

UNRELEASED-V4.md, src/components/Link/tests/Link.test.tsx, src/components/Navigation/components/Item/tests/Item.test.tsx, src/components/UnstyledLink/UnstyledLink.tsx, src/hooks/use-app-bridge/use-app-bridge.tsx, src/hooks/use-polaris/use-polaris.tsx
Part of #1484
I'm converting UnstyledLink to a functional component and removing `withContext`
=> [v4][UnstyledLink] Remove withRef

UNRELEASED.md, a11y_shitlist.json, scripts/pa11y.js
Last year we wrote an automated a11y test that would use `pa11y`, an a11y testing tool, to automatically check for errors in our code. We enabled it for about a week, before we realized that the test in its current shape was too fragile and was slowing the team down more than it was helping it. We decided to disable the test, and revisit it later.
Flash-forward to today. We've made several improvements in our examples and our playground (huge thanks to Ben for his work on Storybook) that allow us to re-enable the a11y test with more confidence in it.
I enabled the test for every new commit made to the repo, but made it never fail. I have been periodically checking in, and haven't noticed any issues so far. The test seems to work consistently, and identifies real issues.
Having gone …
=> Make the a11y test fail if there's issues

UNRELEASED.md, src/components/Sheet/Sheet.scss
As discussed in slack some browsers/version are seeing spacing issues with the primary button
Using percent instead of `vw`
<details>
```jsx
import {MobileCancelMajorMonotone} from '@shopify/polaris-icons';
import {
Page,
Scrollable,
Card,
Sheet,
List,
AppProvider,
Frame,
FormLayout,
TextField,
TopBar,
Button,
Heading,
ChoiceList,
export default class SheetExample extends React.Component {
state = {
sheetActive: true,
title: 'Big yellow socks',
description:
"They're big, yellow socks. What more could you possibly want from socks? These socks will change your life.\n\nThey're made from light, hand-loomed cotton that's so soft, you'll feel …
```
=> [Sheet] Fix spacing issue with primary button

src/components/Card/README.md
Just a couple of tiny content edits, that I spotted as I was reading through this file.
=> [Card] Apply content strategy syntax guidelines in documentation

src/components/Icon/Icon.tsx
I was going through the Icon's component props and saw a few opportunities for improvement / standardization.
=> [Icon] Documentation fixes on props

src/components/Navigation/Navigation.tsx, src/components/Navigation/tests/Navigation.test.tsx
Merging master into v4 caused a regression with banners inside of navigation
Adding the withinContentContext provider
Percy ⭐️
=> [Navigation] withinContentContext fix

UNRELEASED-V4.md, src/components/ResourceList/components/FilterControl/FilterControl.tsx
Part of #1484
I'm converting ResrouceList.FilterControl to a functional component and removing `withContext`
=> [v4][ResourceList.FilterControl] Remove withContext

src/components/DropZone/tests/DropZone.test.tsx
Unused type definition in test.
Removing unused type definition
=> Remove delay from DropZone test

UNRELEASED.md, src/components/TextField/TextField.scss
=> [TextField] Fixed incorrect prefix spacing and coloring

UNRELEASED.md, src/components/Button/Button.scss, src/components/Button/README.md
The online-store-ui library has a component which uses the Polaris `<Button />` with a red destructive button.
• Change the colour of `<Button plain destructive />` to be red instead of blue when it's passed both the `destructive` and `plain` props.
• Add an example to the component's `README.md`.
| Before | After |
| ------------- | ------------- |
| ![Screen Shot 2019-05-30 at 1 13 55 PM](https://user-images.githubusercontent.com/3886060/58650528-e8b36e00-82dc-11e9-8e91-0daa66ff53f7.png)  | <img width="153" alt="Screen Shot 2019-05-29 at 4 14 38 PM" src="https://user-images.githubusercontent.com/3886060/58650412-983c1080-82dc-11e9-8d58-4b335f8f1445.png"> | …
=> [Button] Make Button with plain and destructive props red

UNRELEASED.md, src/components/Card/Card.scss, src/components/Card/Card.tsx, src/components/Card/README.md, src/components/Card/components/Subsection/Subsection.tsx, src/components/Card/components/Subsection/index.ts, src/components/Card/components/Subsection/tests/Subsection.test.tsx, src/components/Card/components/index.ts
Looks like:
It's a common pattern to want to iterate over resources that might appear in a `<Card.Section>`.  This PR allows you to have a consistent method to do so
<details>
```jsx
import {Page, Card} from '../src';
render() {
return (
<Page …
```
=> [Card.Subsection] Add new <Card.Subsection> to further section <Card.Section>

src/components/index.ts
Fixes #1303
Going to skip a changelog entry since we're not documenting it
=> [v4][WithinContentContext]Export WithinContentContext

UNRELEASED.md, src/components/Popover/Popover.scss, src/components/Tabs/Tabs.scss
Tabs and Popover have issues with Windows High Contrast.
Resolves: https://github.com/Shopify/polaris-ux/issues/258
Also part of https://github.com/Shopify/polaris-ux/issues/153
Added border to popover. Also added hover and selected states to Tabs.
<details>
```jsx
export …
```
=> [Tabs, Popover] Windows high contrast updates

UNRELEASED.md, src/components/Card/Card.tsx, src/components/Card/README.md, src/components/Card/components/Section/Section.tsx
Follow up to https://github.com/Shopify/polaris-react/pull/1603
This PR adds support for destructive footer and section actions. It does not add that support to the header actions formed by `Card.actions` or `Card.Header.actions` because destructive actions should not be taken before reviewing the card or card section.
Check out the new destructible examples "Card with destructive footer action" and "Card section with destructive action" in …
=> [Card] add support for destructive footer and section actions

UNRELEASED-V4.md, translation.yml
Update translations yml to use the new locales directory
=> [v4] Update locale path

CHANGELOG.md, UNRELEASED.md
Update to change log for Polaris 3.17
=> [Change Log] Update to change log for Polaris 3.17

.eslintignore, UNRELEASED-V4.md, src/components/PositionedOverlay/PositionedOverlay.tsx, tests/setup.ts, tests/shims/mutation-observer.ts
Part of https://github.com/Shopify/polaris-react/issues/519 and https://github.com/Shopify/polaris-react-deprecated/pull/506
* using mutation observer to watch for changes
* add test support for mutation observer. MutationObserver support was [finally added after 5 years](https://github.com/jsdom/jsdom/issues/639). However, jest [supports node 6](https://github.com/facebook/jest/pull/7763) and won't be updating `jsdom` for a while.
Autocomplete examples are a perfect case of resizing from changes. The original issues (https://github.com/Shopify/polaris-react-deprecated/pull/506) also has a playground included.
=> [v4][PositionedOverlay] Remove component will receive props

UNRELEASED.md, src/components/Button/Button.scss, src/components/Link/Link.scss, src/styles/shared/links.scss
Fixes https://github.com/Shopify/polaris-react/issues/1652
To generate the underline beneath a monochromatic link, we are currently applying a border to the `:after` pseudoelement of the link component.
This approach does not support multi-line link text across all browsers and devices.
Chrome and Safari:
Firefox:
This PR uses `text-decoration: underline` to generate the expected style for monochromatic links. While `text-decoration` does not support transitions, it is the most robust way to ensure the underline renders appropriately across all browsers, string lengths, and contrast modes.
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/docum …
=> Use text-decoration: underline for monochrome links

src/components/Button/README.md
Don't wrap it in an InlineError as no other example shows that context.
=> [Button] Update plain monochrome Button example

UNRELEASED.md, src/components/Icon/README.md
We're just about to open-source https://github.com/Shopify/polaris-icons 🎉 
Let's make sure people can get the appropriate documentation to use Polaris icons with Polaris react.
=> [Icon] Mention Polaris icons

.eslintignore, UNRELEASED.md, src/components/PositionedOverlay/PositionedOverlay.tsx, tests/setup.ts, tests/shims/mutation-observer.ts
Cherry picked + changelog entry removed from unreleased-v4 -> unreleased - from #1621 for #1692
=> Cherry-pick change from v4 to master

src/components/Icon/README.md
([Project theme](https://vault.shopify.io/projects/8503): **Discoverability**)
This PR adds a Related guidelines section to the icon component page. The section follows the pattern that we use for Related components. 
We need a space on the component page for linking to relevant guidelines that live elsewhere in the style guide or in another place altogether. This is a part of a greater initiative to boost content discoverability by increasing cross-linking throughout the style guide. 
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/docu …
=> [Content] Add related guidelines section to icon component page

CHANGELOG.md, UNRELEASED.md
Simply updating the changelog for a possible 3.18 update.
=> Update to changelog for version 3.18

shipit.yml
=> Hide GitHub automations from Shipit

src/components/Sheet/README.md
=> [Sheet] Remove note about not supported in embedded apps

CHANGELOG.md, UNRELEASED.md
[Change log] Update to changelog  for Polaris 3.19.0
=> [Change log] Update to changelog  for Polaris 3.19.0

UNRELEASED.md, src/components/Navigation/Navigation.scss, src/components/Navigation/_variables.scss
Fixes https://github.com/Shopify/polaris-react/issues/1747
The focus and hover states are now both getting a text color, icon color, and background color change to make the difference in state change more apparent. The styles are also updated for Windows high contrast mode.
Selected:
Focus + hover for item, sub nav item, and action:
**High contrast mode**
Focus + hover for item and sub nav item:
Selected:
Focus + hover for action:
<details> …
=> [a11y] [Navigation] Improve nav focus and hover states

UNRELEASED.md, src/components/TopBar/components/SearchField/SearchField.scss
Fixes https://github.com/Shopify/core/issues/5226
The clear button is not aligned properly in Firefox [Firefox 67.0.4 / MacOS 10.14.5]
Introduced a variable for the clear button width that takes into account the padding and icon size and can be used to calculate the width of the search input.
<details>
```jsx
import {
AppProvider,
Frame,
Page,
TopBar,
Card,
ActionList,
Loading,
Layout,
state = {
isLoading: false,
searchActive: false,
searchText: '',
};
render() {
const {isLoading, searchActive, searchText} = this.state;
const searchResultsMarkup = (
<Card>
<ActionList …
```
=> [SearchInput] fix firefox clear button overflow

CHANGELOG.md, UNRELEASED.md
Update to change log for Polaris 3.20.0
=> Update to change log for Polaris 3.20.0

UNRELEASED-V4.md, src/components/Sheet/README.md, src/styles/foundation/utilities.scss, src/styles/global.scss
When attempting to roll out `v4` some major changes were noticed that could affect production. I'll be writing up an issue later with details
Reverting #1590
=> Revert consistent-rem

locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/hi.json, locales/it.json, locales/ja.json, locales/ms.json, locales/nl.json, locales/pt-BR.json, locales/zh-CN.json, locales/zh-TW.json, src/components/Page/components/Header/Header.tsx, src/components/Page/components/Header/tests/Header.test.tsx
Removing deprecation messages
Removing deprecation messages
Stop wrapping Page Header with WithAppProvider as it was only used to provide the internationalization for this message
Check tests / type-checking passes
=> [v4] Remove deprecation message regarding Page Header icon

UNRELEASED-V4.md, config/typescript/images.d.ts
We've defined a few type definitions / created files that we don't use
=> [v4] Remove unused type defintions

UNRELEASED-V4.md, src/components/DataTable/DataTable.tsx, src/components/Focus/Focus.tsx, src/components/Modal/Modal.tsx, src/components/Page/Page.tsx, src/components/RangeSlider/components/DualThumb/DualThumb.tsx, src/components/ResourceList/components/Item/Item.tsx, src/components/ResourcePicker/ResourcePicker.tsx, src/components/ThemeProvider/ThemeProvider.tsx, src/utilities/is-objects-equal.ts, src/utilities/tests/isObjectsEqual.test.ts, src/utilities/theme/tests/hooks.test.tsx, src/utilities/use-deep-compare-ref.tsx
Part of removing lodash #991 . Previous PR #1017
Creating a `isEquals` function and using that instead of `_.isObjectsEqual`
Test pass? 💯
=> Create isObjectsEqual to replace _.isEqual

UNRELEASED-V4.md
Updating the `v4` changelog so 🎩 ers will know where to focus there attention
=> [v4] Update changelog

UNRELEASED-V4.md, src/components/AppProvider/README.md, src/index.ts
Fixes #1507
Fixes #457
Also updating the example a bit since it won't currently work
=> [v4] Updated appbridge example to use new context

CHANGELOG.md, UNRELEASED.md
=> 3.21.0 changelog

CHANGELOG.md, README.md, UNRELEASED.md, scripts/new-version-pr-generator.js, src/components/Frame/components/ToastManager/ToastManager.tsx, src/components/Frame/components/ToastManager/tests/ToastManager.test.tsx, src/components/Page/README.md, src/components/Page/components/Header/Header.scss, src/components/Page/components/Header/Header.tsx, src/components/Page/components/Header/components/Title/Title.scss, src/components/Page/components/Header/components/Title/Title.tsx, src/components/Page/components/Header/components/Title/index.ts, src/components/Page/components/Header/components/Title/tests/PageTitle.test.tsx, src/components/Page/components/Header/components/index.ts, src/components/Page/components/Header/tests/Header.test.tsx, src/components/Page/tests/Page.test.tsx
The last commit fixes a couple imports
=> [v4] Merging master into v4

src/components/UnstyledLink/UnstyledLink.tsx
Fixes #1898 
Adds a ref so there is no error log during tests.
=> Remove error log in tab test by adding _ref prop and forwardRef

src/components/Navigation/README.md
This is already mentioned in the required components section.
=> [Navigation] Remove duplicate line from docs

src/components/Frame/components/ToastManager/ToastManager.tsx, src/components/OptionList/OptionList.tsx, src/components/Toast/Toast.tsx, src/utilities/use-deep-effect.tsx
=> Renamed useDeepCompare

CHANGELOG.md, UNRELEASED.md, src/components/Filters/Filters.tsx, src/components/Filters/tests/Filters.test.tsx
Base branch `3.21.1` is based on tag `v3.21.0`. This PR then includes the commit from #1948 as well as CHANGELOG prep for a `v3.21.1` release.
=> Prep v3.21.1

UNRELEASED.md
=> [Unreleased] fix typo in unreleased

src/components/Frame/Frame.scss, src/components/Frame/Frame.tsx, src/components/Frame/components/CSSAnimation/CSSAnimation.scss, src/components/Frame/components/CSSAnimation/CSSAnimation.tsx, src/components/Frame/components/CSSAnimation/index.ts, src/components/Frame/components/index.ts
RTG was causing infinite renders with ContextualSaveBar
* adds custom css transition
Frame examples 😎
=> [ContextualSaveBar] Replace RTG

README.md, src/components/AppProvider/README.md, src/components/README.md
Fixing up the last few setup docs that didn't mention how to include translations.
Add translation imports to docs
=> Add translation setup in READMEs

README.md, UNRELEASED.md, package.json, src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx, src/components/Popover/tests/Popover.test.tsx, src/components/README.md
Fixes a popover regression
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Bring master up to date with v4

src/components/ResourceList/README.md
Link to `Filters` in the `ResourceList` README.md was pointing to the wrong location. This fixes it.
No change log because this change is part of this release.
1. Simply ensuring the path is correct should be sufficient. If not then `yarn build-consumer polaris-styleguide`
<details>
```jsx …
```
=> [ResourceList] Fix link to ResourceItem in documentation

CHANGELOG.md, UNRELEASED.md
Update changelog update for `Polaris 4.1`
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Changelog] update for `Polaris 4.1`

UNRELEASED.md, src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx, src/components/Frame/components/ContextualSaveBar/index.ts, src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
related to #1995
change `ContextualSaveBar` to use react hooks
=> [ContextualSaveBar] hookify

src/components/Link/README.md
Fixes https://github.com/Shopify/polaris-styleguide/issues/2942
- Breaks Link monochrome examples in two (as there should only be one code block per example)
- Improves a do/don't section
=> [Link] Fix documentation and examples

UNRELEASED.md, src/utilities/errors.ts, src/utilities/i18n/hooks.tsx, src/utilities/scroll-lock-manager/hooks.tsx, src/utilities/sticky-manager/hooks.ts, src/utilities/theme/hooks.tsx, src/utilities/unique-id/hooks.ts
We have a lot of duplication so this'll make things slightly faster and cleaner moving forward.
Creating a custom error and using it
=> [AppProvider] Creating a custom error

src/components/FooterHelp/README.md
This is to align with our content standard in Grammar and mechanics.
FYI @sadiesaurus @VanjaMitrovic
=> [FooterHelp] Delete period from example

UNRELEASED.md, src/components/ResourceList/components/FilterControl/components/FilterCreator/FilterCreator.tsx, src/components/ResourceList/components/FilterControl/components/FilterCreator/index.ts, src/components/ResourceList/components/FilterControl/components/FilterCreator/tests/FilterCreator.test.tsx
Part of the hookification
Converting FilterCreator to a functional component
A playground with filters is below
<details>
```jsx
import {ResourceList, TextStyle, Avatar, FilterType, Card} from '../src';
export class Playground extends React.Component {
state = {
{
},
],
};
};
this.setState({appliedFilters});
};
return (
<ResourceList.Item id={id} url={url} …
```
=> [FilterCreator] To functional component

package.json
Introduced by mistake in #2113.
=> Move node-cmd from dependencies to devDependencies

UNRELEASED.md, src/components/ActionList/README.md, src/components/OptionList/README.md, src/components/Popover/README.md
To improve accessibility.
Fixes #2147  
Add disclosure to activators on Popover.
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Documentation] Add disclosure to Action list, Popover and Option list buttons

README.md, package.json, src/components/README.md
This reverts commit 84f8f58b508842a6fbe0dda8bf11ec42270558f2.
Looks like when I created the tag and pushed it to master, everything but the tag was pushed. This reverts that.
Fixes #0000 
<details>
```jsx
return ( …
```
=> Revert v4.2.2-rc.1 commit

CHANGELOG.md, UNRELEASED.md
Changelog for update for 4.3.0 release
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Changelog] update for 4.3.0 release

UNRELEASED.md, src/components/Form/README.md, src/components/Frame/README.md, src/components/Loading/README.md
Converting Form, Frame, and Loading class-based examples to hooks
```
- Converted `Form`, `Frame`, and `Loading` examples to functional components ([#2130](https://github.com/Shopify/polaris-react/pull/2130))
```
</details>
=> Hookify Form, Frame, and Loading examples

UNRELEASED.md, src/components/DatePicker/README.md, src/components/DropZone/README.md, src/components/Filters/README.md
Converting DatePicker, DropZone, and Filters class-based examples to hooks
```
- Converted `DatePicker`, `DropZone`, and `Filters` examples to functional components ([#2129](https://github.com/Shopify/polaris-react/pull/2129))
```
</details>
=> Hookify DatePicker, DropZone, and Filters

src/components/DropZone/README.md
A few things I forget to add before I merged this morning
=> [DropZone] Update readme

CHANGELOG.md, UNRELEASED.md
Changelog update for Polaris 4.4.0 release
=> [Changelog] Changelog update for polaris 4.4.0 release

src/components/PolarisTestProvider/PolarisTestProvider.tsx, src/utilities/features/index.ts
Some cleanup following https://github.com/Shopify/polaris-react/pull/2204
=> [Color system] default features to empty object in test environment and export use features hook

README.md
We've been using Polaris React internally for a while now, so this needed updating :)
=> [README] Use present tense in the "Using the React components" section

src/components/ThemeProvider/ThemeProvider.tsx, src/components/ThemeProvider/tests/ThemeProvider.test.tsx, src/utilities/theme/tests/utils.test.ts, src/utilities/theme/types.ts, src/utilities/theme/utils.ts
Addresses https://github.com/Shopify/polaris-react/issues/2034
=> [Color system] Build color variant generation factory

src/components/Frame/README.md
=> Removed log from example

CHANGELOG.md, UNRELEASED.md
Updates the changelog and clears unreleased.
=> Update changelog for v.4.5.0

locales/cs.json, locales/da.json, locales/fi.json, locales/ko.json, locales/nb.json, locales/pl.json, locales/pt-PT.json, locales/sv.json, locales/th.json, locales/tr.json
This PR modifies translations in the project. It will append multiple commits. Feel free to merge anytime.
- Visit [#intl-services](https://shopify.slack.com/messages/C7TJQLVC7) for questions about the format of this pull request.
- Visit [#translation](https://shopify.slack.com/messages/C3XPBC62U) for questions about the translations in this pull request.
@Shopify/polaris
=> Update translations: default

src/components/Button/Button.scss, src/styles/_common.scss, src/styles/foundation.scss, src/styles/foundation/_focus-ring.scss, src/styles/shared/_buttons.scss, src/styles/shared/_typography.scss, src/utilities/theme/utils.ts
Co-authored-by: Dan Rosenthal <dan.rosenthal@shopify.com>
Applying the color system to button. Addresses #2197 
Makes use of the new CSS custom properties for color and applies them to button with a fallback to the current value to maintain backwards compatibility. This change should be invisible unless enabling the theming feature.
<summary>
<h3>Playground</h3>
<details>
```tsx
import {Page, Card, List, AppProvider, Checkbox, Stack} from '../src';
const initDarkMode =
window && window.matchMedia('(prefers-color-scheme: dark)').matches;
const [darkMode, setDarkMode] = useState(initDarkMode);
const [masterbrand, setMasterbrand] = useState(false);
const handleChange = useCallback((newChecked) => …
```
=> [Button][Color system] Apply color system

UNRELEASED.md, src/components/Frame/components/Toast/Toast.tsx, src/components/Frame/components/Toast/tests/Toast.test.tsx
related to #1995
change `Toast` to use react hooks
=> [Frame] hookify Toast

src/components/Badge/Badge.scss, src/components/Badge/Badge.tsx, src/components/Banner/Banner.scss, src/components/Card/Card.scss, src/components/Frame/Frame.scss, src/components/Navigation/Navigation.scss, src/components/Popover/Popover.scss, src/components/TopBar/TopBar.scss, src/components/TopBar/components/Menu/Menu.scss, src/components/TopBar/components/SearchField/SearchField.scss, src/components/TopBar/components/UserMenu/UserMenu.scss, src/utilities/theme/utils.ts
Co-authored-by: Dan Rosenthal <dan.rosenthal@shopify.com>
Addresses #2197. Begins to apply the color system to a set of components. This PR is a backwards compatible version of #2191.
Using the CSS custom properties for the color system, otherwise falling back to current colors and styling. If the feature flag is not enabled, there should be no visual changes.
<details> …
=> [Color system] Initial pass at applying the color system

src/components/Navigation/Navigation.scss, src/components/Navigation/_variables.scss, src/styles/foundation/_focus-ring.scss, src/utilities/theme/tests/utils.test.ts, src/utilities/theme/utils.ts
Addresses #2197. Applies the color system to navigation.
Uses the CSS custom properties from the color system as well as override values, otherwise falling back to current colors and styling.
<details>
```jsx
import {
ArrowLeftMinor,
HomeMajorMonotone,
OrdersMajorTwotone,
ProductsMajorTwotone, …
```
=> [Color system] Apply color system to navigation

UNRELEASED.md, src/components/Filters/Filters.scss, src/components/Filters/Filters.tsx
Fixes #2264 
Hi all, this is my first PR into `polaris-react` in the spirit of this year's Hacktoberfest. I hope I followed all/most of the steps for opening a PR! Please let me know if I'm missing anything!
This PR fixes the above mentioned issue where an additional border appears when the 'more filters' button is clicked with only *one* filter in the list.
Additionally, this PR updates some of the `Filters.scss` styles to prevent borders from sibling filters overlapping each other unintentionally creating inconsistent borders in the filters dropdown. 
- added an additional check using the filter length and skip
the application of the 'last' className rules since this was
causing the strange border behavior in the issue
- updated 'open' rules to use the general sibling combinator '~' …
=> [Filters] Fix filters border styles 

src/components/Button/Button.scss
|:tophat:|
|-|
|![destructive-button](https://user-images.githubusercontent.com/1403188/66782966-eb39ed00-eea4-11e9-8c06-e5f205a4f338.gif)|
```tsx
import {Page, Card, List, AppProvider, Checkbox, Stack, Frame} from '../src';
const [darkMode, setDarkMode] = useState(false);
const [masterbrand, setMasterbrand] = useState(false);
const handleChange = useCallback((newChecked) => setDarkMode(newChecked), []);
const masterbrandToggle = useCallback(
(newChecked) => setMasterbrand(newChecked),
[],
);
return (
<AppProvider
i18n={{}}
theme={{
colors: {
topBar: {
background: '#357997',
},
},
// eslint-disable-next-line babel/camelcase
UNSTABLE_colors: {surface: darkMode ? '#111213' : '#FAFAFA'},
}} …
```
=> [Color system] apply color system to critical button

src/components/Navigation/Navigation.scss, src/components/Navigation/_variables.scss, src/styles/foundation/_focus-ring.scss, src/styles/shared/_buttons.scss, src/utilities/theme/utils.ts
- prefix overrides
- better name for focus ring content variable
- remove unused zero var
=> [Color system] Name cleanup

src/types.ts, src/utilities/theme/index.ts, src/utilities/theme/utils.ts
While testing, consumers should have access to these colors so we can keep a single source of truth. For an example see https://github.com/Shopify/web/pull/19586.
Moving color hex strings to an enum, prefixing with `UNSTABLE`, and exporting.
<details>
```jsx
import {
ArrowLeftMinor,
HomeMajorMonotone, …
```
=> [Color system] Move hex values to an enum and export it

UNRELEASED.md, src/components/Page/components/Header/Header.scss
Fixes https://github.com/Shopify/polaris-react/issues/1904
* Prevents `Header` PrimaryActionsWrapper from shrinking when the title is too long
=> [Page][Header] doesn't shrink button

CHANGELOG.md, UNRELEASED.md
Polaris 4.6.0 Change log update
=> Polaris 4.6.0 Change log update

UNRELEASED.md, src/components/OptionList/OptionList.scss
Fixes #2214 
The section title for `OptionList` was using custom css styling causing it to not match the section titles for `ActionList`.
| Before       | After |
| ![Screen Shot 2019-10-16 at 1 11 37 PM](https://user-images.githubusercontent.com/8629173/66942347-e72ddc80-f016-11e9-84cd-3f7e5da4e45e.png) | ![Screen Shot 2019-10-16 at 1 11 47 PM](https://user-images.githubusercontent.com/8629173/66942329-d9785700-f016-11e9-99f7-0b63b3862ced.png) |
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentat …
=> Remove custom css from `OptionList` section title 

src/components/PositionedOverlay/PositionedOverlay.tsx
Fixes #2310
Brings back pass through classes that were deleted in #2231
=> [Popover] Bring back pass through classes

src/components/Modal/components/Dialog/Dialog.scss, src/components/Modal/components/Footer/Footer.scss, src/components/Modal/components/Header/Header.scss
Applying surface and divider colors to modal
=> [Color system] apply surface and divider colors to modal

UNRELEASED.md
Updates the unreleased message to follow [these](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md) guidelines.
=> Rephrase unreleased message

.github/workflows/discoverability.yml
The splash action fails sometimes. In beta 4 I added bugsnag support so we can debug these issues better. This PR updates our workflow to use beta 4.
=> Update splash action to latest version

CHANGELOG.md, UNRELEASED.md
Migrate entries from unreleased.md to changelog.md.
=> Update changelog for v.4.7.0

src/components/ResourceList/ResourceList.scss, src/components/ResourceList/components/CheckableButton/CheckableButton.scss
Knocking off low hanging fruit for surface colors
=> [Color system] Update surface colors for resource list

UNRELEASED.md, src/components/ResourceItem/ResourceItem.scss
Fixes #2363  
Quick PR to fix the alignement of the disclosure icons on resourceItem. Simply adding flex: 0 0 with a  flex-basis solved the problem.
<details>
```jsx
import {
Page,
Avatar,
Card,
ResourceItem,
ResourceList,
TextStyle,
return (
<Card>
<ResourceList …
```
=> [ResourceItem] Add flex to disclosure to prevent misalignment

UNRELEASED.md, src/components/Filters/Filters.scss, src/components/Filters/Filters.tsx, src/components/Filters/README.md, src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.tsx, src/components/Filters/components/ConnectedFilterControl/tests/ConnectedFilterControl.test.tsx, src/components/Filters/tests/Filters.test.tsx, src/components/TextStyle/TextStyle.tsx, src/components/TextStyle/index.ts
Related to https://github.com/Shopify/store/issues/10681
As part of the solution for https://github.com/Shopify/store/issues/10681 we need to disable the `Filters` in the Products Index Page. Currently the filter component doesn't have a prop to disable it.
This PR adds a `disabled` prop to the `Filter` component.
When the `Filter` is disabled:
* Search-bar is disabled
* Actions from `ConnectedFilterControl` are disabled.
* Popover is closed 
* Sheet filter togglers are disabled
* Sheet filter titles are subdued
| Disabled filters        | Disabled sheet     | 
| ------------- |:-------------:| 
| ![image](https://user-images.githubusercontent.com/1751074/67976286-2bf76d00-fbec-11e9-84b2-8ce5a151445d.png) | ![image](https://user-images.githubusercontent.com/1751074/67976233-1a15ca00-fbec-1 …
=> [Filter] Add 'disabled' prop

src/components/Frame/Frame.scss, src/components/Frame/components/Loading/Loading.scss, src/utilities/theme/utils.ts
Addresses https://github.com/Shopify/polaris-ux/issues/345
=> [Color system] Update loading

src/components/TextStyle/TextStyle.scss, src/styles/shared/_typography.scss, src/utilities/theme/color-adjustments.ts
addresses: https://github.com/Shopify/polaris-ux/issues/366
- Not sure if this is the right approach but I updated the shadowFromDirectLight since it's should look like a border in dark mode.
- Not the success green. It isn't very visible in light mode and really bright in dark mode. Is that correct?
<details>
```jsx
import {Page, …
```
=> [Color system] Apply color system to TextStyle

src/components/Popover/Popover.tsx
TypeScript can't generate types that correctly infer the typing of
subcomponents so explicitly state the subcomponents in the type definition.
Letting this be implicit works in this project but fails in projects that use
generated *.d.ts files.
<details>
```jsx
return (
<Page …
```
=> [Popover] Fixed types for popover as function

CHANGELOG.md, UNRELEASED.md
I noticed a few issues with the changelog after I published the release yesterday. This fixes the issues. 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Changelog] Fix typos in change log

UNRELEASED.md, src/components/Button/Button.tsx, src/components/Button/tests/Button.test.tsx, src/types.ts
Adds onMouseEnter and onTouchStart as props for button and UnstyledLink. These props are used in the shortcutActions on `<ResourceListItem />` to allow prefetching for data.
No UI changes, just useful for prefetching information
<details>
<summary>To view in ResourceList Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>
```jsx
import {Page, ResourceList, ResourceItem, Avatar, TextStyle} from …
```
=> [Button] Add onMouseEnter and onTouchStart prop to Button

.storybook/config.js
Keep a single source of truth for the default colors
=> [Color system] Use default colors from enum

src/components/Breadcrumbs/Breadcrumbs.scss, src/components/Breadcrumbs/Breadcrumbs.tsx, src/utilities/theme/color-adjustments.ts
addresses: https://github.com/Shopify/polaris-ux/issues/334
Apply color system to Breacrumbs
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Color Sytem] Apply color system to Breadcrumbs

src/utilities/use-component-did-mount.ts, src/utilities/use-deep-callback.tsx, src/utilities/use-deep-compare-ref.tsx, src/utilities/use-deep-effect.tsx, src/utilities/use-event-listener.ts, src/utilities/use-is-after-initial-mount.ts, src/utilities/use-lazy-ref.ts
* more awareness
* add-general,  simple examples
Skipping changelog since this is internal
=> [Docs] Add internal hook docs

UNRELEASED.md, src/utilities/merge.ts, src/utilities/tests/merge.test.ts
As seen in the change I did to `merge.test.ts`, merge was mutating the first input object
Started shallowly copying `inputObjA` (if it's not an array), so it won't be mutated anymore.
<details>
```jsx
return (
{/* Add the code you want to test in here …
```
=> Stop merge from mutating objects

src/components/AppProvider/README.md
The perils of suggesting something without doing it first YOLO.
I suggested some webpack chunk config without really understanding what it does and it turns out it didn't work. Whoops. Fortunately @moimael had my back.
See https://github.com/Shopify/web/pull/20727 (notably the last commit) for the fun this caused in web.
Updating the example code so it actually works.
I still don't actually understand what the webpackChunkname stuff does so I'd appreciate someone saying "yeah that's right"
=> Fixup dynamic language loading sample code

UNRELEASED.md, package.json
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Bump react-testing

src/components/Avatar/Avatar.scss, src/components/Avatar/Avatar.tsx, src/components/Avatar/tests/Avatar.test.tsx, src/utilities/theme/color-adjustments.ts, src/utilities/theme/types.ts, src/utilities/theme/utils.ts
This PR handles the first half of https://github.com/Shopify/polaris-ux/issues/333
I'll follow up with another PR to tackle the non latin name styles
Concern:
Dark mode colors are a little muddy and two are not passing our contrast standards. 
Using the new color system to match master brand styles in the Avatar component with fallbacks to the original colors.
<details> …
=> [Avatar] Use new color system

UNRELEASED-v5.md, package.json, yarn.lock
Bumping to `16.9.0` so we can use the profiler api, here's the [react changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#1690-august-8-2019)
* Updating our development react to 16.9.0
* Update peer dependencies
* I'm updating the peer dependencies however it's extremely unlikely we're going to use the profiler in production code at the moment. 
<details> …
=> Update react to 16.9.0

src/components/Popover/components/Section/tests/Section.test.tsx
=> Removed random comments

UNRELEASED.md, src/components/DropZone/DropZone.tsx, src/components/DropZone/index.ts, src/components/DropZone/tests/DropZone.test.tsx
* converting dropzone to a functional component
* reduce complexity 
This is a pretty big changeset. It'll need some good tophatting. I've found a few bugs already and address them already, but just to be safe try and break this ⚒ . The readmes example are a good place to start.
=> Hookify Dropzone

src/components/ContextualSaveBar/ContextualSaveBar.tsx, src/components/DropZone/DropZone.tsx, src/components/Toast/Toast.tsx
TypeScript can't generate types that correctly infer the typing of
subcomponents so explicitly state the subcomponents in the type definition.
Letting this be implicit works in this project but fails in projects that use
generated *.d.ts files.
<details>
```jsx
return (
<Page …
```
=> [Dropzone] Fixing type for subcomponent

UNRELEASED.md, src/components/ResourceList/README.md, src/components/ResourceList/ResourceList.tsx, src/components/ResourceList/tests/ResourceList.test.tsx
This reverts commit 96db90311b89e0e64544b0be7bf6187ac095861f, reversing
changes made to e1506bdbcd7a32ed02e90d94f41ff41e35ebac0e.
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Revert "Merge pull request #2160 from Shopify/resourcelist-emptystate"

UNRELEASED.md, src/components/DatePicker/DatePicker.tsx
This reverts commit a0622b9a1d6e244092499cdb77cd0a3d39557867.
One of the tests in web was hanging because of this
=> Revert "Fix bug that introduced a race condition in consumers (#2373)"

src/components/Thumbnail/Thumbnail.scss
Fixes https://github.com/Shopify/polaris-ux/issues/367
=> [Thumbnail] Applied color system

src/components/ExceptionList/ExceptionList.scss
Fixes https://github.com/Shopify/polaris-ux/issues/342
=> [ExceptionList] Applied color system

CHANGELOG.md, UNRELEASED.md
Release 4.9.0 Change Log Update
=> [Polaris Release] Release 4.9.0 Change Log Update

package.json, scripts/build-shrink-ray.js, yarn.lock
- We've released a `@shopify/shrink-ray` package that provides consumers with a library to interact with the shrink-ray server. This also enables us to easily ship client changes to our consumers.
- This PR also updates to [`v1.0.0`](https://github.com/Shopify/shrink-ray/blob/master/CHANGELOG.md#100-2019-12-05)
💚 CI
=> Use @shopify/shrink-ray package

CHANGELOG.md, UNRELEASED.md
=> Changelog 4.9.1 release

CHANGELOG.md, UNRELEASED.md
This change ended up in the latest patch, but wasn't moved to CHANGELOG.md in time!
=> Move remaining unreleased item to the changelog

.github/PULL_REQUEST_TEMPLATE.md, documentation/Versioning and changelog.md
Removes references to Sketch, as we are moving away from it internally.
=> Remove references to Sketch

CHANGELOG.md, UNRELEASED.md
=> 4.10.0 Change log

CHANGELOG.md, UNRELEASED.md
Reverts Shopify/polaris-react#2563
=> Revert "4.10.0 Change log"

CHANGELOG.md, UNRELEASED.md
prepping changelog for the 4.10.0 release
=> 4.10 Changelog

CHANGELOG.md, UNRELEASED.md
There's a bug in 4.10 so I'd like to get a patch out before the holidays.
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Polaris change log for release 4.10.1

UNRELEASED.md, locales/cs.json, locales/da.json, locales/de.json, locales/en.json, locales/es.json, locales/fi.json, locales/fr.json, locales/hi.json, locales/it.json, locales/ja.json, locales/ko.json, locales/ms.json, locales/nb.json, locales/nl.json, locales/pl.json, locales/pt-BR.json, locales/pt-PT.json, locales/sv.json, locales/th.json, locales/tr.json, locales/zh-CN.json, locales/zh-TW.json, src/components/Filters/Filters.tsx, src/components/Filters/tests/Filters.test.tsx
On a new index we are working on we would like to remove the tags from being output and always use the filter sheet to show which filters have been applied. This is less visually noisy and helps save some space at the top of the page.
I also added a count to the more filters button as well as the title of the sheet to show a feedback indicator as you add or remove filters.
This is what it looks like with this option enabled:
This adds a new `suppressTagOutput ` prop to the `Filters` component to allow suppressing the tags from being output.
📄 [Changelog …
=> [Filters] Adding option to suppress filter tag output

UNRELEASED.md, src/components/Focus/Focus.tsx
This open in a tab, will polish and request reviews after hack days.
=> [Focus] Converted to a functional component

UNRELEASED.md, src/components/OptionList/components/Option/Option.tsx, src/components/OptionList/components/Option/tests/Option.test.tsx
=> [Option] Converted to a functional component

src/components/Tag/Tag.scss, src/components/Tag/Tag.tsx, src/components/Tag/tests/Tag.test.tsx
Addresses https://github.com/Shopify/polaris-ux/issues/365
=> [Tag] Applied color system

src/components/Modal/components/Section/Section.scss
Addresses https://github.com/Shopify/polaris-ux/issues/352
=> [Color system] apply color system to subdued modal section

src/components/Card/Card.scss
Quickie fixing something that was missed.
=> [Color system] update card border radius for new design language

src/components/ColorPicker/ColorPicker.scss
Addresses https://github.com/Shopify/polaris-ux/issues/338 
| Current | Light mode  |  Dark mode |
|---|---|---|
|<img width="237" alt="Screen Shot 2019-12-06 at 7 23 15 PM" src="https://user-images.githubusercontent.com/18447883/70365191-3eee0480-185e-11ea-8791-c0e32e90c48c.png">|<img width="239" alt="Screen Shot 2019-12-06 at 7 23 25 PM" src="https://user-images.githubusercontent.com/18447883/70365194-44e3e580-185e-11ea-924b-0ad49c989a78.png">|<img width="237" alt="Screen Shot 2019-12-06 at 7 23 39 PM" src="https://user-images.githubusercontent.com/18447883/70365202-51683e00-185e-11ea-8543-7ad6ced0e029.png">| …
=> [ColorPicker][Color system] box shadow and border radius

UNRELEASED.md, src/components/Navigation/components/Section/Section.tsx, src/components/Navigation/components/Section/tests/Section.test.tsx, src/test-utilities/legacy.tsx
This open in a tab, will polish and request reviews after hack days.
=> [Section] Converted to a functional component

documentation/Color system.md, src/components/ActionList/ActionList.scss, src/components/Banner/Banner.scss, src/components/Breadcrumbs/Breadcrumbs.scss, src/components/Button/Button.scss, src/components/Checkbox/Checkbox.scss, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/tests/Checkbox.test.tsx, src/components/Choice/Choice.scss, src/components/Choice/Choice.tsx, src/components/Link/Link.scss, src/components/Navigation/Navigation.scss, src/components/Navigation/_variables.scss, src/components/RadioButton/RadioButton.scss, src/components/RadioButton/RadioButton.tsx, src/components/Tag/Tag.scss, src/styles/foundation/_focus-ring.scss, src/styles/shared/_buttons.scss, src/styles/shared/_controls.scss, src/utilities/theme/role-variants.ts, src/utilities/theme/tokens.ts
Partly addresses: https://github.com/Shopify/polaris-ux/issues/336 and https://github.com/Shopify/polaris-ux/issues/357
- Applies color system to checkbox
- Keeps the same logic as today therefore no mark-up change, but added selectors.
- Applies animation
- Radio buttons are not marked as complete in Figma. Showing 2 different styles for mobile and desktop. Not sure if that will remain the same but for now leaving as in. Not sure the reasoning with the 2 different styles. **Even though there are minor changes to button this PR is for Checkboxes**
📄 [Changelog …
=> [Checkbox] apply design language to checkboxes

UNRELEASED.md, src/components/Avatar/README.md, src/components/Banner/README.md, src/components/InlineError/README.md, src/components/Select/README.md, src/components/Thumbnail/README.md, src/components/Toast/README.md
The styleguide is updating a lot of URLs
Updating the docs to reference the new links so we can remove the redirects over there
=> Update styleguide links

UNRELEASED.md, src/components/Subheading/README.md
Improve documentation.
- Adds a period to the end of the description paragraph.
- The default example does not mention card.
- Removes other mentions of card.
=> [Subheading] Update documentation

CHANGELOG.md, UNRELEASED.md
- Moves entries from unreleased.md to changelog.md
=> Prepare changelog for 4.11.0

CHANGELOG.md
Some entries slipped through the cracks and are from previous releases.
Removes duplicated entries.
=> Update changelog to remove older entries

src/components/Pagination/Pagination.scss, src/components/Pagination/Pagination.tsx, src/components/Pagination/tests/Pagination.test.tsx
React portion of https://github.com/Shopify/polaris-ux/issues/355
Applying DL to pagination
<details>
```jsx
import {NoteMinor} from '@shopify/polaris-icons';
import {Page, Pagination, Button, ButtonGroup, Card, Stack} from '../src';
return (
<Card>
<Card.Section>
<Pagination …
```
=> [Pagination] Apply design language

src/components/TopBar/TopBar.tsx
This should reduce dropped frames on scroll due to the scroll handler calling `window.scrollY` on every scroll by adding a debouncer. To be same I'm also adding a requestAnimationFrame when calling setState
Master:
This branch:
Changes seem surprisingly negligible but that leaves me to believe this is something difficult to profile.
Looking for opinions @danrosenthal @tmlayton 
Pull this branch
yarn dev
Visit: http://localhost:6006/iframe.html?id=playground-playground--details-page&contexts=Global%20Theming=Enabled%20-%20Light%20Mode
📄 [Changelog …
=> [TopBar] Improve scroll handler performance

src/components/DropZone/DropZone.scss, src/components/DropZone/DropZone.tsx, src/components/DropZone/components/FileUpload/FileUpload.scss, src/components/DropZone/components/FileUpload/FileUpload.tsx, src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx, src/components/DropZone/tests/DropZone.test.tsx
Fixes *part of* https://github.com/Shopify/polaris-ux/issues/341
=> [DropZone][Fileupload] Applied color system

src/components/ResourceList/components/CheckableButton/CheckableButton.scss
|before|after|
|-|-|
|![Screen Shot 2020-01-24 at 11 51 03 AM](https://user-images.githubusercontent.com/1403188/73087655-d821ba80-3ea0-11ea-9d5a-19b4f6fc67d9.png)|![Screen Shot 2020-01-24 at 11 51 13 AM](https://user-images.githubusercontent.com/1403188/73087667-de179b80-3ea0-11ea-85cd-16566b4a3a8a.png)|
=> [Color system] fix checkable button icon color

src/components/ResourceItem/ResourceItem.scss, src/components/ResourceItem/ResourceItem.tsx, src/components/ResourceItem/tests/ResourceItem.test.tsx, src/components/ResourceList/components/CheckableButton/CheckableButton.scss
[ResourceItem Issue](https://github.com/Shopify/polaris-ux/issues/359)
Applying the design language. Currently, the `focus-ring` isn't working correctly because of `overflow-hidden` & `z-index` issues. I still applied the `focus-ring` for when it's fixed.
=> [ResourceItem] Apply design language

UNRELEASED.md, src/components/Button/Button.tsx
[Issue](https://github.com/Shopify/web/issues/22816)
🤷‍♂ 
Build consumer to web and run the server
=> Fixed react reference error

package.json
Oops didn't realize this was in dependencies
move it to devdependencies
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Move octokit to devdependencies

documentation/Color system.md, src/components/ActionMenu/components/MenuAction/MenuAction.scss, src/components/Checkbox/Checkbox.scss, src/components/DropZone/DropZone.scss, src/components/RadioButton/RadioButton.scss, src/components/TextField/TextField.scss, src/components/TopBar/components/SearchField/SearchField.scss, src/styles/foundation/_focus-ring.scss, src/utilities/theme/tokens.ts
This PR:
1. Cleans up TextField.scss
1. Changes focus ring from border to box-shadow (smooths transitions)
1. Changes transition type from scale to box-shadow (prevents seeing the box-shadow scale down underneath larger items like text fields.
1. Minor improvements to focus rings border-radius
The focus ring looked good on smaller components such as radio buttons and checkboxes but not so much on larger components, like text fields.
@dleroux will be handling z-index overlapping in a separate PR
[Screencast](https://screenshot.click/screencast_2020-01-22_11-56-01.mp4) …
=> Improve focus ring animation

CHANGELOG.md, UNRELEASED.md
Updating the change log in preparation for the 4.13.0 release 📝
=> [CHANGELOG] 4.13.0

src/components/ChoiceList/ChoiceList.scss
Addresses: https://github.com/Shopify/polaris-ux/issues/337
Simply needed to adjust the spacing based on design language.
Have a look at ChoiceList in the playground
=> [ChoiceList] Apply design language to Choicelist

src/components/Card/Card.scss, src/components/OptionList/OptionList.scss, src/components/OptionList/OptionList.tsx, src/components/OptionList/components/Checkbox/Checkbox.scss, src/components/OptionList/components/Checkbox/Checkbox.tsx, src/components/OptionList/components/Checkbox/tests/Checkbox.test.tsx, src/components/OptionList/components/Option/Option.scss, src/components/OptionList/components/Option/Option.tsx, src/components/OptionList/components/Option/tests/Option.test.tsx, src/components/OptionList/tests/OptionList.test.tsx
Fixes: https://github.com/Shopify/polaris-ux/issues/354
Applying design language to OptionList. Unfortunately because of Autocomplete, the checkbox was forked and make for duplicate code.
<details>
```jsx
return ( …
```
=> [OptionList] Apply design language

shipit.yml
Master is red
Let the new pipeline I created fail before the config is merged for it
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Allow failures on new pipeline

.storybook/main.js, .storybook/preview.js, UNRELEASED.md, config/typescript/react-transition-group.d.ts, package.json, yarn.lock
Adds Storybook knobs for playing around with theme colors
Uses Storybooks Knobs addon together with the Contexts addon to allow customizing the theme. Instead of the Contexts addon using the `AppProvider`, I created a wrapping component called `AppProviderWithKnobs` which allows the Knobs UI to properly render. Each color is generated from the default colors coming from Polaris Tokens.
1. Turn on the new design language, either light or dark …
=> [Color system] Add Storybook knobs for customizing theme

src/components/Tabs/Tabs.scss, src/components/Tag/Tag.scss
Decided just to PR these vs creating issues
**Tag**
Before:
After:
**Tabs**
Before:
After:
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Tag, Tabs] Fix high contrast mode

documentation/Color system.md, src/utilities/theme/tokens.ts
Modal has a much broader shadow in figma, it's also darker. I've added a token and modified the modal shadow to match [Figma](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/DL%E2%80%93Polaris-(Web)%3A-Components?node-id=358%3A0)
Before:
After:
<details>
```jsx
return ( …
```
=> [Modal] Fix shadow

src/components/ColorPicker/ColorPicker.scss
Closes https://github.com/Shopify/polaris-ux/issues/338
=> [Color system] use design language on checkers

src/components/DataTable/DataTable.scss
Addresses https://github.com/Shopify/polaris-ux/issues/339
=> [Color system] finish applying color system to datatable

src/components/Filters/Filters.scss, src/components/Filters/Filters.tsx, src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss, src/components/Filters/tests/Filters.test.tsx
Applies the design language to the Filter component
=> Applied design language to Filters

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
Updating Polaris to 4.14.0.
Note: we did this a little differently this time. We are working off a branch as opposed to master. The benefit is that we don't need to worry about locking master while we do our updates.
We will release and then merge this PR into master, therefore, we need to approve the change log before we deploy.
<details>
```jsx
import React …
```
=> [Polaris 4.14.0] version bump

src/components/EmptyState/README.md
Updating the illustration used in the content context empty state example.
|---|---|
|<img width="579" alt="Screen Shot 2020-02-26 at 8 01 52 PM" src="https://user-images.githubusercontent.com/18447883/75402450-db122f80-58d2-11ea-9040-fb4ee7b117da.png">|<img width="655" alt="Screen Shot 2020-02-26 at 12 05 39 PM" src="https://user-images.githubusercontent.com/18447883/75402421-b918ad00-58d2-11ea-8931-58d8e6bf4f25.png">|
[View example in Chroma](https://www.chromaui.com/component?appId=5d559397bae39100201eedc1&name=All%20Components%7CEmpty%20state&buildNumber=3928&specName=Empty%20state%20within%20a%20content%20context)
=> [EmptyState] Update image url for in-context example

UNRELEASED.md
Not sure what happened but somehow I merged the same message 3 times
=> Fix UNRELEASED

src/components/Icon/Icon.tsx, src/components/Icon/tests/Icon.test.tsx, src/components/Link/Link.scss, src/components/Link/Link.tsx, src/components/Link/tests/Link.test.tsx
partially completes this https://github.com/Shopify/polaris-ux/issues/373
Adding an underline to the Link which was missed when applying the design language.
Also updated icon because the 'base' colour was preventing the external link icon to render the wrong colour.
<details>
```jsx …
```
=> [Link] apply design language to link

UNRELEASED.md, src/components/ResourceList/ResourceList.scss, src/components/Select/Select.scss
Fixes https://github.com/Shopify/polaris-react/issues/2773
This PR adds truncation for long sort options on mobile devices.
Before
After
- Use Playground code provided below
- Switch to small mobile mode in Playground
<details>
```jsx
import {Avatar, Card, ResourceItem, ResourceList, TextStyle} from '../src';
export …
```
=> [ResourceList] / Truncate long sort options

scripts/pa11y.js
Currently, in the event no accessibility issues are found in CI, `pa11y.js` prints the following to the logs
========================================================================
The following issues were discovered and need to be fixed before this code can be merged
========================================================================
No issues!
Instead of printing the big banner about issues being discovered, and then contradicting it, we can just announce no issues have been discovered directly in the banner.
`pa11y.js` now outputs the following if no issues were discovered:
========================================================================
No issues were discovered!
========================================================================
=> Improve `pa11y.js` output

src/components/DatePicker/DatePicker.scss, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/components/Day/Day.tsx, src/components/DatePicker/components/Month/Month.tsx, src/components/DatePicker/tests/DatePicker.test.tsx
Applying the new design language to date picker
The first iteration of `DatePicker`. There is still work that needs to be done after the design review. Possibly revisiting of the focus state. As Dan mentioned below, there isn't a nice way to animate the radius without a flicker
Sample playground below
<details>
```jsx
import {Page, DatePicker, Popover, Button} from '../src';
const [{month, year}, setDate] = useState({
month: 1,
year: 2018,
});
const [selectedDates, setSelectedDates] = useState({
start: new Date('Wed Feb 07 2018 00:00:00 GMT-0500 (EST)'),
end: new Date('Wed Feb 07 2018 00:00:00 GMT-0500 (EST)'),
});
const …
```
=> [DatePicker] Applied design Language

src/components/Icon/tests/Icon.test.tsx, src/components/Tabs/Tabs.scss, src/components/Tabs/Tabs.tsx, src/components/Tabs/components/Item/Item.tsx, src/components/Tabs/components/Item/tests/Item.test.tsx, src/components/Tabs/components/List/List.tsx, src/components/Tabs/components/List/tests/List.test.tsx, src/components/Tabs/components/Tab/Tab.tsx, src/components/Tabs/components/Tab/tests/Tab.test.tsx, src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx, src/components/Tabs/tests/Tabs.test.tsx
<details>
<summary>To-do list</summary>
</details>
- Part of https://github.com/Shopify/polaris-ux/issues/364
- [Figma](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/DL%E2%80%93Polaris-(Web)%3A-Components?node-id=898%3A0)
- [CSS Layout in Codepen](https://codepen.io/LauraAubin/pen/rNVmbJR?editors=1100)
Applies the design language to the Tabs component.
<kbd>![image](https://user-images.githubusercontent.com/22782157/75277439-04996100-57d6-11ea-9be4-983fd545e711.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/22782157/75277444-06fbbb00-57d6-11ea-9154-006f18a7757f.png)</kbd>
Fitted:
<kbd>![image](https://user-images.githubusercontent.com/22782157/75472143-0b081400-5961-11ea-87b3-55712e3f4e02.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/22782157/75 …
=> [Tabs] Apply design system

src/components/AppProvider/README.md, src/components/ThemeProvider/README.md
|Theme provider|App provider|
|-|-|
|![screencapture-polaris-myshopify-io-components-structure-theme-provider-2020-03-09-10_19_48](https://user-images.githubusercontent.com/1403188/76221539-9ef29f00-61ef-11ea-982b-24d83ace7dde.png)|![screencapture-polaris-myshopify-io-components-structure-app-provider-2020-03-09-10_19_22](https://user-images.githubusercontent.com/1403188/76221561-a7e37080-61ef-11ea-9dd6-7bf7d1c8609b.png)|
=> update app provider and theme provider readme to discourage production use

src/components/ThemeProvider/ThemeProvider.tsx, src/components/ThemeProvider/tests/ThemeProvider.test.tsx
Closes https://github.com/Shopify/polaris-react/issues/2816
=> [Color system] nested theme providers inherit from their parent

src/components/Filters/Filters.scss, src/components/Filters/Filters.tsx, src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss, src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
Closes https://github.com/Shopify/polaris-ux/issues/343
|:tophat:|:tophat:|
|-|-|
|<img width="1281" alt="Screen Shot 2020-03-18 at 10 38 46 AM" src="https://user-images.githubusercontent.com/1403188/76972348-db677e80-6904-11ea-98d5-30016c3a8cc7.png">|<img width="384" alt="Screen Shot 2020-03-18 at 10 39 21 AM" src="https://user-images.githubusercontent.com/1403188/76972368-e1f5f600-6904-11ea-9ba8-cde5bd91cdd9.png">|
=> [Color system] finish filters

src/components/Navigation/Navigation.scss, src/components/Navigation/components/Item/Item.tsx, src/components/Navigation/components/Item/components/Secondary/Secondary.tsx, src/components/Navigation/components/Item/components/Secondary/tests/Secondary.test.tsx, src/components/Navigation/components/Item/tests/Item.test.tsx
Reverts Shopify/polaris-react#2796
https://github.com/Shopify/web/pull/24837
|bug|
|-|
|![Screen Shot 2020-03-19 at 8 51 44 PM](https://user-images.githubusercontent.com/1403188/77127748-0dbbcd80-6a24-11ea-95df-bbeef89aaaad.png)|
=> Revert "[Navigation] Design language animation"

UNRELEASED.md, package.json, yarn.lock
Update polaris-tokens to use new font stack
Updates polaris-tokens
=> Update polaris-tokens to use new font stack

src/components/Filters/Filters.scss, src/components/Frame/Frame.scss, src/components/Navigation/Navigation.scss, src/components/TopBar/TopBar.scss, src/components/TopBar/components/SearchField/SearchField.scss, src/styles/foundation/_layout.scss
Addresses: https://github.com/Shopify/polaris-react/pull/2887#discussion_r402498626
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Frame] Rename unstable vars / functions

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
=> Polaris release v4.18.0

UNRELEASED.md, locales/cs.json, locales/da.json, locales/de.json, locales/en.json, locales/es.json, locales/fi.json, locales/fr.json, locales/hi.json, locales/it.json, locales/ja.json, locales/ko.json, locales/nb.json, locales/nl.json, locales/pl.json, locales/pt-BR.json, locales/pt-PT.json, locales/sv.json, locales/th.json, locales/tr.json, locales/zh-CN.json, locales/zh-TW.json, src/components/Badge/Badge.scss, src/components/Badge/Badge.tsx, src/components/Badge/README.md
Part of https://github.com/Shopify/polaris-react/issues/1969
There was some discussion in a few issues:  https://github.com/Shopify/polaris-react/issues/1430 & https://github.com/Shopify/polaris-react/issues/1593
We have a few instances where we need to use the critical styling for the badge within Multi-Channel apps.
IE, currently, we have a product table within Google Shopping that uses Rails components and the `critical` badge exists in that environment
We might be migrating it to React in the future, and I wanna have the ground covered. Additionally, we have a product sync status card that has a critical badge as well to get merchants to fix product errors
<details>
```jsx …
```
=> [Badge] Add critical styling

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
Version bump from 4.19.0 to 4.20.0
=> Polaris v4.20.0

README.md
Hi, 
This PR will fix :
2 typos in  `/README.md`
Thanks! 🤖
=> [README.md] fixed typos in README.md

src/components/KonamiCode/KonamiCode.tsx, src/components/KonamiCode/index.ts, src/components/KonamiCode/tests/KonamiCode.test.tsx, src/components/index.ts
Saturday night in quarantine... 🙂
<details>
<summary>Try it out in the Playground</summary>
```tsx
import {Page, KonamiCode} from '../src';
return (
<KonamiCode
handler={() => {
// eslint-disable-next-line no-alert
alert('Hello, world!');
}}
/>
</Page>
);
}
```
</details>
=> KonamiCode

UNRELEASED.md, src/components/TopBar/README.md, src/components/TopBar/TopBar.scss, src/components/TopBar/components/Menu/Menu.scss, src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss, src/components/TopBar/components/SearchField/SearchField.scss, src/components/TopBar/components/UserMenu/UserMenu.scss
References https://github.com/Shopify/destinations/issues/863
Introduces transitions on elements that change color/background-color when the theme of the top bar is switched after the page has loaded. See issue above for the full context.
Note: this doesn't follow the design specification to the letter, as some tweaks were made by @AlexBlaise and I directly in the browser in order to reach a result that wouldn't trigger disproportionate amounts of engineering work.
This PR is safe to revert when we have the ability in `Shopify/web` to determine these conditions server-side rather than client-side: **user has access to a single Plus store in an organization, and the Global nav beta is enabled in this store**. When this can be computed server-side, we'll instantly render the appropriate …
=> [TopBar] Animatable theming

src/utilities/sticky-manager/sticky-manager.ts
Just a tiny code change – not sure it requires a changelog entry?
=> [Sticky manager] Only import the required token

UNRELEASED-v5.md, package.json
Update to the shared browser config
=> Update browser config

UNRELEASED.md, documentation/guides/migrating-from-v4-to-v5.md
=> v5 migration guide

src/components/TextField/components/Resizer/tests/Resizer.test.tsx
The Resizer tests became flakey after I started using the dimensions mocks elsewhere. Hopefully using those mocks here too will fix that.
I've not found out a way to reliably reproduce the issue locally so hopefully the first CI run will tell us if this seems to work
Use the dimension mocks to handle offsetHeight mocking in Resizer.
Tests pass (repeatedly)
=> Use dimensions mocks in resizer tests

examples/create-react-app-ts-react-testing/package.json, examples/create-react-app-ts-react-testing/src/index.tsx, examples/create-react-app-ts-react-testing/yarn.lock, examples/create-react-app/package.json, examples/create-react-app/src/index.js, examples/create-react-app/yarn.lock, examples/next.js/package.json, examples/next.js/pages/_app.js, examples/next.js/yarn.lock, examples/webpack/package.json, examples/webpack/src/index.js, examples/webpack/yarn.lock
Update examples to use polaris 5.
Kaelig already updated the cdn styles example so no need to touch that.
Update examples to use v5, update the style import path. Do a `yarn upgrade` to update all other dependencies for good measure.
=> Example updates

src/components/Badge/Badge.scss
Fixes: https://github.com/Shopify/polaris-react/issues/3131#issuecomment-663041863
This badge doesn't exist in the new design language and shouldn't be used but just in case it ever is this fixes the visual difference we were seeing in the issue above.
<details>
```jsx
return …
```
=> Fix attention badge font-weight visual issue

src/components/AccountConnection/README.md
Code in the documentation had an issue
Noticed that there was an intermediate variable that was unused in the example for AccountConnection
=> [AccountConnection] Fixed the code example

UNRELEASED.md, src/components/Filters/Filters.scss, src/components/Frame/Frame.scss, src/components/Navigation/Navigation.scss, src/components/TopBar/TopBar.scss, src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss, src/styles/foundation/_layout.scss
Fixes #3155
Two commits:
First one fixes a bug:
- Fixes SearchDismissOverlay to use new topbar height token `--p-top-bar-height` so that the grey-ed out overlay is now aligned with the new taller topbar.
Second one does some tidying up:
- Removes usages of the `new-top-bar-height()` sass function and replaces them with references to `--p-top-bar-height`.
- Removes the `new-top-bar-height` sass function - technically a breaking change to the public API but nobody should ever have been using this and we seem to be treating new DL stuff as unstable APIs anyway.
Here is a gargantuan Playground that is a mashup of a Frame and Filters example.
To check regressions in the old DL:
- Type into the topbar search box and note that grey overlay aligns with the bottom of the topbar
- Click "More …
=> [new DL] Always use custom property for topbar heights

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
Release of new version of Polaris v5.2.0
Publish new version of Polaris
=> Polaris v5.2.0

documentation/Color system.md, playground/DetailsPage.scss, src/components/Filters/Filters.scss, src/components/Frame/Frame.scss, src/components/Navigation/Navigation.scss, src/components/Navigation/Navigation.tsx, src/components/Navigation/_variables.scss, src/components/Navigation/tests/Navigation.test.tsx, src/components/TopBar/TopBar.scss, src/components/TopBar/TopBar.tsx, src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss, src/components/TopBar/tests/TopBar.test.tsx, src/utilities/theme/tokens.ts
Fixes https://github.com/Shopify/polaris-react/issues/3190 and fixes https://github.com/Shopify/polaris-react/issues/3188 and fixes https://github.com/Shopify/polaris-react/issues/3189 and fixes https://github.com/Shopify/polaris-ux/issues/405
- [View the changes](https://5d559397bae39100201eedc1-ddklsrszjr.chromatic.com/iframe.html?id=playground-playground--details-page&contexts=New%20Design%20Language%3DEnabled%20-%20Light%20Mode) 
- [Compare with current changes](http://polaris-react.herokuapp.com/iframe.html?id=playground-playground--details-page&contexts=New%20Design%20Language=Enabled%20-%20Light%20Mode) …
=> [Navigation, Topbar] New DL updates

package.json, yarn.lock
Part of https://github.com/Shopify/polaris-tokens/issues/141
Part of https://github.com/Shopify/polaris-react/issues/3220
Bumping polaris tokens to get the updated color values for borderSubdued, borderShadow, borderShadowSubdued, and divider
<details>
```jsx
return (
<Page …
```
=> Bump polaris-tokens to 2.12.5

UNRELEASED.md, src/components/Tag/Tag.scss
- Fixes https://github.com/Shopify/store/issues/17480
- the vertical centering of the tag text breaks when `<Tag/>` is wrapped in a div to apply styling to it in a consuming project. this PR makes sure that the vertical centering stays.
<details>
```jsx
import {Stack, Tag} from '../src';
return (
<Stack …
```
=> [Tag] Vertically center tag text

src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
Fix mismatch in hide on print style for the popover overlay. I made a last minute stylename change in https://github.com/Shopify/polaris-react/pull/3242 and didnt change it in the component :( 
See https://github.com/Shopify/polaris-react/pull/3242
<details>
<summary>Gif of hiding the popover when printing</summary>
</details>
<details>
```jsx
import React, …
```
=> [Popover]Fix mismatch in hide on print style

UNRELEASED.md, src/components/Frame/Frame.scss
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Add pos relative back to frame content

src/components/Button/Button.scss, src/components/Button/README.md, src/styles/shared/_buttons.scss
Co-authored-by: Ashwin Narayanan <ashwin.narayanan@shopify.com>
Fixes: https://github.com/Shopify/polaris-react/issues/3256
This addresses visual updates needed for disabled buttons
Chroma: https://5d559397bae39100201eedc1-yhdyeovwfq.chromatic.com/?path=/story/all-components-button--disabled-state
Locally:
http://localhost:6006/?path=/story/all-components-button--disabled-state
=> [Button] Update disabled states

src/components/Navigation/_variables.scss
Fixes #3265 
This pull request is increasing the size of the navigation items on mobile. It increases the font-size, and increases the margin for icon and text.
To tophat this component, we need the Theme Provider. Go into storybook under details page, and switch to a mobile view.
=> [Navigation] Fix larger nav items on mobile

src/components/ProgressBar/ProgressBar.scss
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Adjust border radius for new design language

src/components/Page/components/Header/Header.scss
Fixes https://github.com/Shopify/polaris-react/issues/3290
Removes border from page component
=> Remove border from page with ndl

UNRELEASED.md, src/components/DatePicker/DatePicker.scss, src/components/DatePicker/components/Day/Day.tsx, src/components/DatePicker/components/Day/tests/Day.test.tsx, src/components/DatePicker/components/Month/Month.tsx, src/components/DatePicker/components/Weekday/Weekday.tsx, src/components/DatePicker/components/Weekday/tests/Weekday.test.tsx, src/components/DatePicker/tests/DatePicker.test.tsx
Fixes #797 
Currently the DatePicker component is misusing role attributes and the result is that it doesn't convey the proper structure to screen readers.
This refactors the DatePicker component to use HTML table markup instead of trying to use divs with role attributes.
Look at the DatePicker examples in Storybook and make sure all still looks and works as expected.
</details>
=> [DatePicker] Update component to use HTML table structure

CHANGELOG.md, UNRELEASED.md
We forgot a change that was included
Adding the change
=> Update Changelog for missing change in v5.4.0

UNRELEASED.md, src/components/Badge/Badge.scss
Fixes https://github.com/Shopify/polaris-react/issues/899 
We are using Polaris-next for Badges in web currently to include this change. To prevent issues/updates with the new design language we would love to get this (or similar) added to Polaris. 
BEFORE 
AFTER
<details>
```jsx
import {Page, Badge} from '../src'; …
```
=> Fixes Badge when it becomes 2 lines due to small viewport.

UNRELEASED.md, src/components/Frame/Frame.scss, src/components/Frame/Frame.tsx, src/components/Frame/tests/Frame.test.tsx
Fixes https://github.com/Shopify/polaris-react/issues/3322
Swapping the element from an `mixin` styled link to a `<Button url`. This also fixes the incorrect appearance as it needs the `.newDesignLanguage` class added to apply the button styles.
1. Open the `Frame.tsx` `README.md` file
2. Add `{{features: {newDesignLanguage:true}}}` to the <AppProvider
3. Test the skip link is styled
=> [new DL] Skip link styles

src/components/Button/Button.scss, src/components/ButtonGroup/README.md, src/styles/shared/_buttons.scss
Outline buttons were pretty broken in terms of layout and focus styles. This was making it really difficult to style pagination buttons proper for header changes but that PR is getting pretty big so I think this makes sense as its own change
Easiest fix was to replace box-shadow with border and move segmented button styles down below all other button styles
<details> …
=> [ButtonGroup] Fix segmented outline button styles

UNRELEASED.md, documentation/Color system.md, playground/DetailsPage.tsx, src/components/ActionMenu/ActionMenu.tsx, src/components/ActionMenu/components/Actions/Actions.scss, src/components/ActionMenu/components/Actions/Actions.tsx, src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx, src/components/ActionMenu/components/RollupActions/RollupActions.scss, src/components/ActionMenu/components/RollupActions/RollupActions.tsx, src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss, src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx, src/components/ActionMenu/components/SecondaryAction/index.ts, src/components/ActionMenu/components/index.ts, src/components/Breadcrumbs/Breadcrumbs.scss, src/components/ButtonGroup/ButtonGroup.scss, src/components/ButtonGroup/ButtonGroup.tsx, src/components/Page/components/Header/Header.scss, src/components/Page/components/Header/Header.tsx, src/components/Page/components/Header/components/Title/Title.scss, src/components/Page/components/Header/components/Title/Title.tsx, src/components/Page/components/Header/tests/Header.test.tsx, src/components/Pagination/Pagination.tsx, src/styles/shared/_buttons.scss, src/styles/shared/_page.scss, src/utilities/theme/tokens.ts
Fixes #3286 
Locally: http://localhost:6006/iframe.html?id=playground-playground--details-page&contexts=New%20Design%20Language%3DEnabled%20-%20Light%20Mode&viewMode=story
Chroma: https://5d559397bae39100201eedc1-qayohpojms.chromatic.com/
=> [Page header] Single row layout

package.json, src/components/Banner/Banner.scss, yarn.lock
Fixes: https://github.com/Shopify/polaris-react/issues/3306
This PR is using tokens that don't exist but I think they should to make our system properly themeable 
I can quickly add them to polaris tokens and create a release for those. For now I'll leave this open
Playground included:
<details>
```jsx
import {Banner, Page} from '../src';
return (
<Banner
title="USPS has updated their rates"
action={{content: 'Learn more'}}
onDismiss={() => {}}
>
<p>Make sure you know how these changes affect your store.</p>
</Banner>
<Banner
title="USPS has updated their rates"
action={{content: 'Learn more'}}
secondaryAction={{content: …
```
=> [Banner] Fix primary action colors

src/components/Badge/Badge.scss, src/components/Badge/Badge.tsx, src/components/Filters/Filters.tsx, src/components/Filters/tests/Filters.test.tsx, src/utilities/within-filter-context.tsx
Square border-radius to match the filters being applied
=> Square badge border radius within filter for new design language

src/components/ResourceList/ResourceList.tsx, src/components/ResourceList/tests/ResourceList.test.tsx
=> Fix build failure

src/components/Page/components/Header/Header.scss
This was previously stuck to the top along with other header items, but it looks weird with short titles, which the admin has in abundance. 
Short title:
Long title's still look good:
<details>
```jsx
return (
{/* Add the code you want to test in here …
```
=> [Page header] Vertically center header title

src/components/Tag/README.md, src/components/Tag/Tag.scss
Card/Modal/Tag backgrounds are all white. Let's align them to [figma](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-Web-Components?node-id=364%3A1478)
Interactions need to write for a release of polaris tokens to be updated. Issue [here](https://github.com/Shopify/polaris-react/issues/3352) so we don't forget about it.
=> Fix tag background

UNRELEASED.md, src/components/index.ts
In order to make use of the focus handle on Banner we need to export it.
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Banner] Export BannerHandles

package.json, src/components/Navigation/Navigation.scss, src/components/Select/Select.tsx, yarn.lock
Fixes https://github.com/Shopify/polaris-react/issues/3356
Updates icons and updates nav border
=> Update polaris-icons, add divider to navigation

src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
Fixes 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Target links as well as buttons

src/components/Page/components/Header/Header.scss
Addresses this comment: https://github.com/Shopify/polaris-react/issues/3377#issuecomment-704281006
Comment out `secondaryActions` and `actionGroups` from details page
<details>
```jsx
return (
</Page>
); …
```
=> Align pagination when no actions are present

src/components/CheckableButton/CheckableButton.scss
Fixes linked issue (see below)
=> [BulkActions][NDL] Fix spacing

src/components/Button/Button.scss
Fixes https://github.com/Shopify/polaris-react/issues/3381
Before:
After:
=> Button loading icon

src/components/Button/Button.scss
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Button loading icon color

src/components/Page/components/Header/Header.scss, src/components/Page/components/Header/Header.tsx, src/components/Page/components/Header/tests/Header.test.tsx
Fixes https://github.com/Shopify/polaris-react/issues/3377
This is just a preliminary fix for page actions. We still need to measure the primary action / add additional navigation, measure that as well and add a min-width to the actions to prevent overlapping
Gif 🎉
<details>
```jsx …
```
=> [Page Header] Fix some layout issues on mobile and large screens

src/components/Connected/Connected.scss
Fixes up flex styles on connected fields
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Fix Alex sillyness

src/components/TextField/TextField.scss
Fixes https://github.com/Shopify/polaris-react/issues/3425
=> Update Disabled textfield appearance

src/components/Button/Button.scss
=> [ButtonGroup] Fix missing rounded corners on single buttons in button group

src/components/ActionMenu/ActionMenu.scss, src/components/Page/components/Header/Header.scss, src/components/Page/components/Header/Header.tsx
#3179 # WHY are these changes introduced?
Fixes #0000 
Fixes a but that was introduced by adding a print hidden wrapper in https://github.com/Shopify/polaris-react/pull/3458
Before:
After:
<details>
```jsx
return ( …
```
=> [ActionMenu] Remove hide from print wrapper

src/components/ActionMenu/components/RollupActions/RollupActions.scss
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Rollup Actions] Right alignment

UNRELEASED.md, src/components/Navigation/Navigation.scss, src/components/Navigation/README.md, src/components/Navigation/_variables.scss
Fixes https://github.com/Shopify/polaris-react/issues/3431
Fixes https://github.com/Shopify/polaris-react/issues/3451
🎩  using this Storybook link: https://5d559397bae39100201eedc1-mumzdavccz.chromatic.com/?path=/story/playground-playground--details-page
Also fixes a vertical alignment issue with badges:
See commits for details.
=> [new DL] Set navitem parent height back to 32px

src/components/ActionMenu/ActionMenu.scss, src/components/ActionMenu/ActionMenu.tsx, src/components/ActionMenu/components/Actions/Actions.scss, src/components/Page/components/Header/Header.scss
Fixes a bug where we were getting some weird rendering issue due to SSR in web
Also addresses a layout issue on pages without breadcrumbs
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Page header] fix layout refresh bug

src/components/Page/components/Header/Header.scss
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Header] only allow wrap when nav is collapsed

src/components/Card/Card.scss
Before:
After:
Fixes: https://github.com/Shopify/web/issues/32935
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Card] Fix border radius on section

src/components/Tabs/Tabs.scss
Fixes https://github.com/Shopify/polaris-react/issues/3287
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Tabs] Update styling

src/components/Frame/components/Loading/Loading.scss, src/components/ProgressBar/ProgressBar.scss
Fixes Shopify/web#32772
This pull request is updating the loading bar (page loading indicator) in the Frame component
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Frame] Update page loading indicator

src/components/ActionList/ActionList.scss
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> ActionList pressed color

src/components/ResourceItem/ResourceItem.scss
Resource list item was using the wrong colors for hover / active. 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Resource list] Update hover and pressed states

src/components/TextField/TextField.scss
Fixes #3404
This pull request updates the prefix and suffix text in the TextField component to text-subdued.
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [TextField] Fix prefix and suffix text color

src/utilities/theme/utils.ts
This function takes somewhere between 5 and 10ms on a fast machine in a sandbox, multiply that by many theme providers, slow machines, and production environments and times go up significantly. 
Memoizing `buildCustomProperties`
<details>
```jsx
return (
<Page …
```
=> memoize buildCustomProperties function

src/components/AppProvider/AppProvider.scss, src/components/Frame/Frame.scss
Some users are reporting that they are seeing a background color when printing views based on Polaris.
This could be related to the fact that the ThemeProvider now sets styles directly on the body. (Although, I get a background when using the old design language as well. 🤔)
Forces `background-color: transparent` on the `body` and `Frame` when printing. Strangely, I found that `background-color: none;` didn't have any effect.
Please tophat this one thoroughly. 
- Try printing pages using with the design language on/off
- Try it in different browsers
- Make sure to have the "background graphics" option set to ON in the browser, as many users are unlikely to know that they can uncheck this.
I used the Storybook -> Playground with the "open in separate window" feature (to remove the Storybook …
=> Remove background from printed pages

src/components/Navigation/Navigation.scss
Fixes https://github.com/Shopify/global-nav/issues/706
Comment out the icons on the details page
=> [Navigation] Fix sub nav item spacing when no icon is present

src/components/Thumbnail/tests/Thumbnail.test.tsx
Fixes tests failing in master
Adding assertions
=> Fix test assertion in thumbnail test

src/components/Avatar/Avatar.scss
I noticed the background color was incorrect
Before
After
[Figma](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Admin-Design-Language-(Web)%3A-Components?node-id=762%3A42)
Updating the color token 
<details>
```jsx
import {Page, Avatar, Stack} from '../src';
return (
<Stack …
```
=> [Avatar] Fix background color

.storybook/preview.js, README.md
Since we're mostly working in the new design language I think it makes sense to default to it to avoid having to click twice every time the page refreshes after a change. Maybe its too early to make this change since we're public facing. Would like to hear some thoughts.
Consideration: I'm fairly sure this wouldn't affect the styleguide components but not 100%. @kaelig would know for sure
Open a story and toggle the different modes
=> Storybook - Add ENV variables to enable the new design language

UNRELEASED.md, src/components/Banner/Banner.tsx, src/components/Banner/tests/Banner.test.tsx
Fixes #2946 
<details>
```jsx
import {Page, Banner} from '../src';
return (
<Banner
title="Some of your product variants are missing weights"
status="warning"
secondaryAction={{content: 'Edit variant weights'}}
onDismiss={() => {}}
>
<p>
Add weights to show accurate rates at …
```
=> [Banner] Fix secondary action only rendering if action also set

UNRELEASED.md, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/tests/Tooltip.test.tsx
* adding escape keypress to close tooltip
* chroma examples should be 💯
=> [Tooltip] Add escape keyboard shortcut

UNRELEASED.md, src/components/Modal/components/CloseButton/CloseButton.scss
* Added new focus styles for the NDL
* Chroma should be 💯
=> [CloseButton] Added focus styles

UNRELEASED.md, src/components/Filters/Filters.tsx, src/components/Filters/tests/Filters.test.tsx
* Making the applied tags a live region
* Chroma + screen reader 🦐
=> [Filters] Announce applied filters

UNRELEASED.md, src/components/Filters/Filters.tsx
* Adding semantic HTML
* Chroma should be 💯
=> [Filters] Add semantic markup to header

UNRELEASED.md, src/components/Tabs/Tabs.tsx, src/components/Tabs/components/List/List.tsx, src/components/Tabs/tests/Tabs.test.tsx
Fixes part of https://github.com/Shopify/web/issues/34845
No visual changes to the component.
ArrowUp and ArrowDown were being used to navigate through the tablist. These keyboard interactions should be used to scroll the page up and down. I have removed the over-ride on `ArrowUp` and `ArrowDown` in this PR. The ArrowRight and ArrowLeft keys are unchanged (still used for navigating the tab list). This issue was found during an accessibility audit.
**Arrow key functionality**
The left and right arrow keys navigate the tablist. The up and down arrows scroll on the page:
<details>
<summary>Summary of gif</summary>
Gif shows right and left arrows being used to navigate the tab list. It then shows that the up and down arrows scroll the page, which is the expected behaviour for these keys …
=> [Tabs] Fixing keyboard interactions on the Tab component

playground/DetailsPage.tsx, src/components/ActionMenu/components/Actions/Actions.tsx
Reverts Shopify/polaris-react#3620
This PR caused a bug in web. Reverting for now so we have a safe main branch
=> Revert "[Actions] Do not re-measure on every re-render"

CHANGELOG.md, UNRELEASED.md
Adds an entry for v5.10.2
Looks like this change made it to the polaris-release branch but not master.
Keeping things inline with the release tag https://github.com/Shopify/polaris-react/releases/tag/v5.10.2
<details>
```jsx
return (
{/* Add the code …
```
=> Add changelog entry for v5.10.2

examples/create-react-app-ts-react-testing/public/manifest.json
Fixing a spelling mistake / typo in the manifest.json file of an example project.
=> Fix typo in example manifest.json

scripts/accessibility-check.js
Investigating then fixing why the a11y test is failing on master
Ignoring warnings that people introduced.
Fix a case where transient errors would not be output, leading to a poor debugging experience
a11y check CI job should pass
=> Investigate a11y fails

UNRELEASED.md, scripts/accessibility-check.js, src/components/ResourceList/README.md, src/components/ResourceList/ResourceList.tsx
Part of https://github.com/Shopify/polaris-react/issues/3565
The spinner content was being rendered as a direct child of a `ul`. Changing its container to `li` fixes a markup issue. I'm also fixing up some duplicate ids on the resouce list readme
<details>
```jsx
return ( …
```
=> [ResourceList] Change fragment to list item

UNRELEASED.md, src/components/Filters/Filters.tsx, src/components/Filters/components/TagsWrapper/TagsWrapper.tsx, src/components/Filters/components/TagsWrapper/index.ts, src/components/Filters/components/TagsWrapper/tests/TagsWrapper.test.tsx, src/components/Filters/components/index.ts, src/components/Filters/tests/Filters.test.tsx, src/components/TextField/TextField.scss, src/components/TextField/TextField.tsx, src/components/TextField/tests/TextField.test.tsx
Fixes https://github.com/Shopify/polaris-react/issues/3687
Fixes https://github.com/Shopify/web/issues/34755
1. Adds missing focus-ring for clear button when using the new design language.
2. Fixes an issue with clear buttons when used in popovers. 
[The popover overlay `handleClick` function](https://github.com/Shopify/polaris-react/blob/6c39f4a00d7431d275d1441230814dca04f0be07/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx#L248) determines whether or not a click was inside the popover to decide if it should close the popover or not. The clear button would inadvertently cause this to happen because the button disappears as soon as it is clicked, causing the `isDescendent` check to fail and the popover to be closed. This change ensures that the `clearButton` remains …
=> [TextField] Include focus-ring on clear button && Fix clear button in popovers

src/components/ActionList/ActionList.scss, src/components/ActionList/ActionList.tsx, src/components/ActionList/tests/ActionList.test.tsx
Fixes https://github.com/Shopify/polaris-ux/issues/585
Remove NDL from ActionList
=> Remove NDL from ActionList

src/components/DataTable/DataTable.scss
Fixes https://github.com/Shopify/polaris-ux/issues/578
Remove new DL fallbacks
Chroma link should be fine
=> [DataTable] Remove new DL fallbacks

src/components/ProgressBar/ProgressBar.scss
These changes are introduced as part of polaris-v6, where all references to the newDesignLanguage are being removed. Fixes Shopify/polaris-ux#552.
This pull request removes all references to the newDesignLanguage in the Progress Bar component on polaris-react.
<details>
```jsx …
```
=> [Progress Bar] Remove new DL fallbacks

src/components/ExceptionList/ExceptionList.scss
These changes are introduced as part of polaris-v6, where all reference to the newDesignLanguage are being removed. Fixes Shopify/polaris-ux#574.
This pull request removes all references to the newDesignLanguage in the ExceptionList component on polaris-react.
<details>
```jsx …
```
=> [ExceptionList] Remove new DL fallbacks

.github/workflows/ci.yml, scripts/build-shrink-ray.js
Fixing Shrink ray PR check
Use base commit info instead of the PR merge commit if it's a PR
=> Fixing shrink ray PR check

src/components/KeyboardKey/KeyboardKey.scss
These changes are introduced as part of polaris-v6, where all reference to the newDesignLanguage are being removed. Fixes Shopify/polaris-ux#565.
This pull request removes all references to the newDesignLanguage in the Keyboard key component on polaris-react.
<details>
```jsx …
```
=> [Keyboard key] Remove new DL fallbacks

src/components/ResourceList/ResourceList.scss, src/components/ResourceList/_variables.scss
These changes are introduced as part of polaris-v6, where all references to the newDesignLanguage are being removed. Fixes Shopify/polaris-ux#548.
This pull request removes all references to the newDesignLanguage and any fallbacks in the ResourceList component on polaris-react.
<details>
```jsx …
```
=> [ResourceList] Remove NDL fallbacks 

src/components/Checkbox/Checkbox.scss, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/tests/Checkbox.test.tsx
Fixes https://github.com/Shopify/polaris-ux/issues/596
Removes references to newDesignLanguage in the Checkbox component
=> [Checkbox] Remove NDL fallbacks

UNRELEASED.md, locales/cs.json, locales/da.json, locales/de.json, locales/en.json, locales/es.json, locales/fi.json, locales/fr.json, locales/it.json, locales/ja.json, locales/ko.json, locales/nb.json, locales/nl.json, locales/pl.json, locales/pt-BR.json, locales/pt-PT.json, locales/sv.json, locales/th.json, locales/tr.json, locales/vi.json, locales/zh-CN.json, locales/zh-TW.json, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx, src/components/Tooltip/components/TooltipOverlay/tests/TooltipOverlay.test.tsx, src/components/Tooltip/tests/Tooltip.test.tsx
* adding a label
* adding role
* Chroma + screen reader 🎉
=> [Tooltip] Add accessibility label to tooltip

src/components/DatePicker/DatePicker.scss, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/tests/DatePicker.test.tsx
Fixes https://github.com/Shopify/polaris-ux/issues/580
Removes references to newDesignLanguage in the Date picker component
=> [Date picker] Remove NDL fallbacks

src/components/TextStyle/TextStyle.scss
These changes are introduced as part of polaris-v6, where all reference to the newDesignLanguage are being removed. Fixes Shopify/polaris-ux#532.
This pull request removes all references to the newDesignLanguage and any fallbacks in the TextStyle component on polaris-react.
<details>
```jsx …
```
=> [TextStyle] Remove new DL fallbacks

src/components/Modal/components/CloseButton/CloseButton.scss, src/components/Modal/components/Dialog/Dialog.scss, src/components/Modal/components/Section/Section.scss
These changes are introduced as part of polaris-v6, where all reference to the newDesignLanguage are being removed. Fixes Shopify/polaris-ux#559.
This pull request removes all references to the newDesignLanguage and any fallbacks in the Modal component on polaris-react.
In order to tophat this, please compare this locally and http://polaris-react.herokuapp.com/.
<details> …
=> [Modal] Remove new DL fallbacks

src/components/Tabs/components/Tab/Tab.tsx
Fixes accessibility issue with incorrect role
```
ul[role="tablist"] > li[role="presentation"] > button[role="tab"]
```
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Fix broken tab role

src/components/Autocomplete/Autocomplete.tsx, src/components/Autocomplete/components/ListBox/components/TextOption/TextOption.scss, src/components/Autocomplete/components/MappedOption/MappedOption.scss, src/components/Autocomplete/components/MappedOption/MappedOption.tsx, src/components/Autocomplete/components/MappedOption/index.ts, src/components/Autocomplete/components/index.ts, src/types.ts
WIP changes into a feature branch
=> [AutoComplete] Map old -> new options

src/components/Scrollable/Scrollable.scss
These changes are introduced as part of polaris-v6, where all reference to the newDesignLanguages are being removed. Fixes Shopify/polaris-ux#547.
This pull request removes all references to the newDesignLanguage and any fallbacks in the Scrollable component on polaris-react.
<details>
```jsx …
```
=> [Scrollable] Remove new DL fallbacks

src/components/Frame/components/Toast/Toast.scss
Chips at: https://github.com/Shopify/polaris-ux/issues/529  
There is no Rails toast component
^^ This is a lie, it is the actually known as the Flash component in those realms, give me a second
To tophat this, please compare your local version and http://polaris-react.herokuapp.com/
</details>
=> [Toast] Remove new design language fallbacks

src/components/Layout/Layout.scss, src/components/Layout/Layout.tsx
Reverts Shopify/polaris-react#3821
=> Revert "[Layout ] Remove new design language fallbacks"

src/components/Layout/Layout.scss, src/components/Layout/Layout.tsx
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> remove new design language fallbacks on layout component

src/components/Breadcrumbs/Breadcrumbs.scss, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx, src/components/Page/components/Header/Header.scss, src/components/Page/components/Header/components/Title/Title.scss
Part of https://github.com/Shopify/polaris-ux/issues/598
Removes all instances of the new design language
Chroma and percy
=> [Breadcrumbs] Remove new DL

src/components/Sheet/Sheet.scss
These changes are introduced as part of polaris-v6, where all reference to the newDesignLanguages are being removed. Fixes Shopify/polaris-ux#544.
This pull request removes all references to the newDesignLanguage and any fallbacks in the Sheet component on polaris-react.
<details>
```jsx
import …
```
=> [Sheet] Remove new DL fallbacks

src/components/Sheet/README.md
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Fix a11y label on sheet example

scripts/accessibility-check.js
We no longer have a new design language param with version 6.
Removing the test URL for new design language
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [accessibility-check.js] Remove NDL url param

src/components/TextField/TextField.scss, src/components/TextField/TextField.tsx, src/components/TextField/tests/TextField.test.tsx, src/styles/shared/_typography.scss
Fixes https://github.com/Shopify/polaris-ux/issues/528
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [TextField] remove ndl fallbacks

src/components/Checkbox/Checkbox.scss, src/components/OptionList/components/Checkbox/Checkbox.scss, src/components/OptionList/components/Checkbox/Checkbox.tsx, src/components/OptionList/components/Checkbox/tests/Checkbox.test.tsx, src/components/OptionList/components/Option/Option.scss, src/components/OptionList/components/Option/Option.tsx, src/components/OptionList/components/Option/tests/Option.test.tsx, src/styles/shared/_controls.scss
Fixes https://github.com/Shopify/polaris-ux/issues/557
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [OptionList] Remove ndl fallbacks

src/components/RadioButton/RadioButton.scss, src/components/RadioButton/RadioButton.tsx, src/components/RadioButton/tests/RadioButton.test.tsx
Fixes https://github.com/Shopify/polaris-ux/issues/551
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Radio] Remove ndl fallbacks

UNRELEASED.md, src/components/Banner/Banner.tsx, src/components/ExceptionList/ExceptionList.tsx, src/components/FooterHelp/FooterHelp.tsx, src/components/Icon/Icon.tsx, src/components/Modal/components/Dialog/Dialog.tsx, src/components/Navigation/components/Item/Item.tsx, src/components/Navigation/components/Section/Section.tsx, src/components/OptionList/OptionList.tsx, src/components/OptionList/components/Option/Option.tsx, src/components/index.ts, src/index.ts, src/types.ts
Fixes https://github.com/Shopify/polaris-react/issues/3848
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Remove color export

src/components/Tabs/Tabs.tsx
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Tabs] ndl cleanup

src/components/Spinner/Spinner.tsx
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Spinner] ndl fallback cleanup

src/components/CheckableButton/CheckableButton.scss, src/components/CheckableButton/CheckableButton.tsx, src/components/CheckableButton/tests/CheckableButton.test.tsx
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [CheckableButton] Remove ndl fallbacks

src/components/AppProvider/AppProvider.tsx
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> V6 ndl true

src/components/Filters/Filters.tsx, src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss, src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Filters] Remove ndl fallbacks

src/components/Card/Card.scss, src/components/CheckableButton/CheckableButton.scss, src/components/Frame/Frame.scss, src/components/Tag/Tag.scss, src/components/TopBar/components/SearchField/SearchField.scss, src/styles/foundation/_borders.scss, src/styles/foundation/_focus-ring.scss, src/styles/shared/_interaction-state.scss, src/styles/shared/_typography.scss
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Clean up fallbacks

src/components/Banner/Banner.scss
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Clean up banner mixin

UNRELEASED.md, src/components/Modal/README.md, src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx, src/components/Scrollable/README.md, src/components/Scrollable/Scrollable.scss, src/components/Scrollable/Scrollable.tsx, src/components/Scrollable/tests/Scrollable.test.tsx
Fixes https://github.com/Shopify/web/issues/36623 where focus is lost when moving between elements in a modal.
Adding an optional property to make the `Scrollable` component focusable.
<details>
```jsx
return ( …
```
=> [Scrollable] Add focusable for when child content is not focusable

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/changelog.yml, .github/workflows/ci.yml, .github/workflows/discoverability.yml, .shopify-build/polaris-react-system-integration-test.yml, .storybook/polaris-readme-loader.js, CHANGELOG.md, README.md, UNRELEASED.md, documentation/Accessibility testing.md, documentation/Accessibility.md, documentation/Console messages.md, documentation/Deprecation guidelines.md, documentation/Tophatting documentation.md, documentation/guides/migrating-from-v3-to-v4.md, examples/README.md, scripts/new-version-pr-generator.js, src/components/AppProvider/README.md, src/components/README.md, src/components/ThemeProvider/README.md, src/utilities/use-deep-compare-ref.tsx
Part of https://github.com/Shopify/polaris-react/issues/3758
Renaming all references of master branch to main
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Change default branch to main

.github/workflows/backlog-automation.yml
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> change alex-page/github-project-automation-plus@master to main

UNRELEASED.md, src/components/Modal/Modal.tsx, src/components/Modal/README.md, src/components/Modal/components/CloseButton/CloseButton.scss, src/components/Modal/components/CloseButton/CloseButton.tsx, src/components/Modal/components/Header/Header.scss, src/components/Modal/components/Header/Header.tsx, src/components/Modal/tests/Modal.test.tsx
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> [Modal] Add titleHidden option

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
Shipping v5.14.1
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Polaris release v5.14.1

src/components/Autocomplete/README.md, src/components/Autocomplete/components/ComboBox/ComboBox.tsx, src/components/Autocomplete/components/ListBox/ListBox.tsx, src/components/Autocomplete/components/ListBox/components/Header/Header.scss, src/components/Autocomplete/components/ListBox/components/Header/tests/Header.test.tsx, src/components/Autocomplete/components/ListBox/components/Loading/tests/Loading.test.tsx, src/components/Autocomplete/components/ListBox/components/Option/tests/Option.test.tsx, src/components/Autocomplete/components/ListBox/components/TextOption/TextOption.scss, src/components/Autocomplete/components/ListBox/components/TextOption/TextOption.tsx, src/components/Autocomplete/components/ListBox/components/TextOption/tests/TextOption.test.tsx, src/components/Autocomplete/components/MappedOption/MappedOption.scss, src/components/Autocomplete/components/MappedOption/MappedOption.tsx, src/components/Checkbox/Checkbox.tsx, src/utilities/combo-box/context.tsx, src/utilities/list-box/context.ts
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Match old component styling & fix stories & add tests

UNRELEASED.md, src/components/Icon/Icon.scss, src/components/Icon/Icon.tsx
Co-Authored-By: Andre Rocha <andrematheus94@gmail.com>
Fixes #0000 
<details>
```jsx
import {CirclePlusMinor} from '@shopify/polaris-icons';
import {Page, Icon, Card} from '../src';
return (
<Card>
<Icon source={CirclePlusMinor} color="success" />
<Icon source={CirclePlusMinor} …
```
=> Fix up backdrops in new design language

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Polaris release v5.15.1

locales/en.json
Test async translations
Adds a translation that can be removed after we are sure async translations work.
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Test async translations [should be reverted]

UNRELEASED.md, src/components/Tooltip/README.md
Temporary fix for https://github.com/Shopify/polaris-react/issues/3924, follow up issue for bigger problems https://github.com/Shopify/polaris-react/issues/3939
Removes the opacity transition by hiding the tooltip in the default example. This resolves the flakey accessibility test.
<details>
```jsx
export …
```
=> [Tooltip] Remove transition on example load, fix a11y test flakiness

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Polaris v6.0.1

src/components/Icon/Icon.scss, src/components/Icon/Icon.tsx, src/components/Icon/tests/Icon.test.tsx
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Rename CSS class in Icon

locales/en.json
Reverts Shopify/polaris-react#3922
Translations came in https://github.com/Shopify/polaris-react/pull/3946
=> Revert "Test async translations [should be reverted]"

src/components/EmptyState/README.md
Fixes https://github.com/Shopify/polaris-react/issues/3954
Updates the layouts to use sectioned card and removed duplicate example.
Removes mention of content context
<details>
```jsx
return (
</Page>
);
} …
```
=> [EmptyState] Update readme layouts

UNRELEASED.md, src/components/ActionList/ActionList.scss, src/components/ActionList/README.md
Fixes #3972
<details>
<summary>Summary of your gif(s)</summary>
| Before        | After           |
|![production-actionlist-nofocus](https://user-images.githubusercontent.com/43223543/106939032-b7b05100-66ed-11eb-8aad-b851b002063b.jpg)|![high-contrast-nofocus-fix](https://user-images.githubusercontent.com/43223543/106938836-7a4bc380-66ed-11eb-981b-7d8f7d827eda.jpg)
| Before        | After           |
|![production-actionlist-focus](https://user-images.githubusercontent.com/43223543/106939631-808e6f80-66ee-11eb-9919-9b65c1f8f423.jpg)|![high-contrast-focus-fix](https://user-images.githubusercontent.com/43223543/106938955-9d767300-66ed-11eb-848c-f13ac6879120.jpg)
</details> …
=> [a11y][ActionList]: make items clearly discernible in high contrast mode

src/components/FooterHelp/README.md
Closes https://github.com/Shopify/polaris-styleguide/issues/3915
=> Adds external prop to Link inside FooterHelp example

src/components/Page/components/Header/Header.scss
Fixes: https://github.com/Shopify/polaris-react/issues/4065
Spacing is a bit tight because it's not in the button group. This is a weird pattern though and the consumer can just add some spacing to their primary button if needed
Add a plain button to the primary action on the details page
```
primaryAction={
<Button primary monochrome plain>
Save
</Button>
}
```
=> vertically align plain buttons in header

README.md
As we're using Storybook more and more, let's start surfacing it in README files.
=> Add Storybook badge to the README

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
Releases v6.3.0
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> v6.3.0 (#4128)

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, .storybook/polaris-readme-loader.js, .storybook/preview.js, README.md, package.json, playground/stories.tsx, shipit.yml, yarn.lock
Removing third party applications, will investigate how to add this functionality back in the future.
Removing packages and config for Percy.
=> Remove percy

examples/create-react-app/package.json, examples/create-react-app/src/App.js, examples/create-react-app/src/index.js, examples/create-react-app/yarn.lock
Bumping old dependencies in CRA example
=> Bump create-react-app example dependencies

examples/next.js/package.json, examples/next.js/yarn.lock
=> Bump dependencies in nextjs example

UNRELEASED.md, src/components/ResourceList/_variables.scss
Fixes #3605 
> The issue is that SpinnerContainer has z-index: 3 and LoadingOverlay has z-index: 2, but the Polaris-ResourceItem__Container also has z-index: 2
Bumped two z-index vars.
👁️ **Before** 👁️
(image / copy appear over loading overlay)
👁️ **After** 👁️
(image / copy appear under loading overlay)
<details>
```jsx
import {Page, …
```
=> [ResourceList] Fixed loading state z-index

CHANGELOG.md, README.md, UNRELEASED.md, package.json, src/components/README.md
Fixes #0000 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Polaris release v6.5.0

.github/CONTRIBUTING.md, documentation/Testing.md
Fixes https://github.com/Shopify/polaris-react/issues/3921
Found several broken links in contributing.md and in documentation/testing.md - removed the testing file because it didn't link anywhere. 
It looks @kaelig or @BPScott might have updated the links a year ago to the web-configs repo, but there is no testing info there. Do either of you know if it will be added soon?
=> Fix links in contributing.md

.shopify-build/polaris-react.yml, config/secrets.production.ejson, infrastructure/runtimes/production-unrestricted-4b2e/manifest.yaml, infrastructure/runtimes/production-unrestricted-4b2e/manifest.yaml.lock, package.json
Deploy storybook and merge to main
Setting up runtimes for storybook to deploy to
=> Deploy storybook

UNRELEASED.md, src/components/Scrollable/Scrollable.tsx
Removes the top shadow when scroll hinting is complete
closes #4272
=> remove top shadow when scroll hint is complete

infrastructure/runtimes/production-unrestricted-4b2e/manifest.yaml, infrastructure/runtimes/production-unrestricted-4b2e/manifest.yaml.lock
Fixes https://github.com/Shopify/services/issues/2434
Followed the instructions from the issue ☝️ 
<details>
```jsx
return (
</Page>
);
}
```
</details>
=> Switch cert-manager Certificate to Shopify Certificate

playground/DetailsPage.scss, scripts/analyze-custom-properties/tests/fixtures.scss, src/components/ActionMenu/ActionMenu.scss, src/components/ActionMenu/_variables.scss, src/components/Backdrop/Backdrop.scss, src/components/Badge/Badge.scss, src/components/Banner/Banner.scss, src/components/Button/Button.scss, src/components/Card/Card.scss, src/components/CheckableButton/CheckableButton.scss, src/components/Checkbox/Checkbox.scss, src/components/Choice/Choice.scss, src/components/ColorPicker/ColorPicker.scss, src/components/FooterHelp/FooterHelp.scss, src/components/Frame/Frame.scss, src/components/IndexTable/IndexTable.scss, src/components/Indicator/Indicator.scss, src/components/Layout/Layout.scss, src/components/MessageIndicator/MessageIndicator.scss, src/components/RadioButton/RadioButton.scss, src/components/Thumbnail/Thumbnail.scss, src/components/TopBar/TopBar.scss, src/components/TopBar/components/Menu/Menu.scss, src/components/TopBar/components/SearchField/SearchField.scss, src/components/TopBar/components/UserMenu/UserMenu.scss, src/styles/foundation/_focus-ring.scss, src/styles/shared/_typography.scss
Fixes: https://github.com/Shopify/polaris-react/issues/4296
=> Remove remaining css fallbacks

UNRELEASED.md, src/components/Avatar/tests/Avatar-ssr.test.tsx, src/components/Avatar/tests/Avatar.test.tsx, src/components/Backdrop/Backdrop.tsx, src/components/Backdrop/tests/Backdrop.test.tsx, src/components/Badge/tests/Badge.test.tsx, src/components/Banner/tests/Banner.test.tsx
Updating existing tests to use the new modern framework and eliminate stale dependencies.
Part of test modernization, updating tests using `{mountWithAppProvider} from 'test-utilities/legacy'` to `{mountWithApp} from 'test-utilities'`
=> [Test modernization] Avatar, Backdrop, Badge, Banner

UNRELEASED.md, src/components/Toast/tests/Toast.test.tsx, src/components/Tooltip/tests/Tooltip.test.tsx
Use the new modern framework to modernize the tests
Changing tests from using {mountWithAppProvider} from 'test-utilities/legacy' to {mountWithApp} from 'test-utilities'
<details>
```jsx
return (
</Page> …
```
=> Modernize test: Tooltip , Toast
