Shopify/polaris-react

documentation/Embedded apps.md
src/components/AppProvider/AppProvider.tsx
src/components/AppProvider/README.md
src/components/ResourcePicker/ResourcePicker.tsx

Updates the documentation links for Shopify App Bridge from the GitHub repository to the public Shopify Help Center.
Also, updates the example to use `Redirect` which is a more common action and publicly documented.

Update Shopify App Bridge documentation links

---

src/utilities/app-bridge-transformers.ts
src/utilities/tests/app-bridge-transformers.test.ts

We want actions used with embedded apps to be able to open a new tab or window.
When `external` is true, the redirect callback will pass the proper payload with `newContext: true` along with `Redirect.Action.REMOTE` per the [Shopify App Bridge Redirect docs](https://help.shopify.com/en/api/embedded-apps/app-bridge/actions/navigation/redirect#redirect-to-an-absolute-url-outside-of-the-app-and-outside-of-shopify-admin).
1. Create an embedded app
1. run `yarn build-cosumer your-embedded-app-directory`
1. Add a `Page` component and pass a primary action with `external: true`

Support opening a new tab or window with embedded app actions

---

src/components/Layout/README.md

Link to `FormLayout` from `Layout`'s readme's related component section uses the term `layout` instead of `form layout`.
Change it to `form layout` to be consistent with the component's name & other references to `FormLayout` component.

[Layout Readme] Fix link text to FormLayout component from Layout readme

---

src/components/Modal/Modal.tsx
src/types.ts

I was dynamically generating these string literal types in an effort to stay in sync with app bridge, but this breaks the props explorer in the style guide.
We will get this fixed in the style guide (https://github.com/Shopify/polaris-styleguide/issues/2359), but in the meantime let’s just use static string literal types.

Static string literal types

---

UNRELEASED.md

Thanks to @michelleyschen who has been working on upgrading their embedded app to use a v3.0.0 release candidate. She kindly pointed out the changelog could provide better upgrade instructions for embedded apps and shared her upgrade notes with me.

Better upgrade instructions for embedded apps

---

src/components/Page/components/Header/Header.tsx
src/components/Page/tests/Page.test.tsx

The updated types for `Page` to support Shopify App Bridge were undone when merging `master` into the beta branch.

[Page] Fix types for actions

---

src/components/Page/components/Header/Header.tsx

The props explorer in the style guide did not render this composed type correctly. This should be an extended interface anyways imo.

[Page] Change SecondaryAction to an interface

---

src/components/Focus/Focus.tsx
src/components/TrapFocus/TrapFocus.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

The issue as been raised on slack that trap focus steals focus from contained nodes.
* Focus will focus on update
* Focus sets initial state based on the DOM then re-renders itself
* Focus will now remain on inner nodes or TrapFocus will be focused
- `git checkout tf-inner-focus`
- `yarn dev` and navigate to localhost:8080
<details>
```jsx
import {
Page,
AppProvider,
Modal,
Button,
TextField,
TrapFocus,
active: boolean;
text: string;
}
state = {
active: false,
text: '',
};
handleChange = () => {
this.setState(({active}) => ({active: …
```

[TrapFocus] Fix TrapFocus stealing focus from contained nodes

---

.eslintignore
.gitignore
.prettierignore
.stylelintignore
package.json
sewing-kit.config.ts

Move code coverage into an already ignored top level folder to avoid
proliferation of top-level ignored files
Simplify the logic for what reporters to use slightly
* Confirm that codecov still picks up the coverage report in the new location, by seeing the codecov check in this PR.
* Run `yarn run test . --no-watch --coverage` and see that:
* A text summary is shown
* An lcov report is generated at build/coverage/lcov.info
* A html report is generated and you can open it with `open build/coverage/index.html`

Move coverage into build/coverage

---

UNRELEASED.md
src/styles/shared/typography.scss

In Shopify/web#7574 we start using the shared `print-hidden` mixin in more places. It was pointed out there that mixins are usually added at the top of selectors so specificity may become a problem.
Adds `!important` to `print-hidden` directly. The thinking is that there should be no reason to ever show an item in print media that you have already explicitly said "hide this during printing".
Pull it down and test various pages in both screen and print. Note how the app chrome and classes with `print-hidden` disappear during printing. You can't test the other case where someone needs to override the `!important` because it currently does not exist in the app.

Use `!important` in print-hidden mixin

---

src/components/Autocomplete/Autocomplete.tsx
src/components/Autocomplete/README.md
src/components/Autocomplete/components/ComboBox/ComboBox.scss
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
src/components/Autocomplete/tests/Autocomplete.test.tsx

This PR allows developers to render an optional empty state if there are no results for their search query.
This PR adds the `emptyState` prop. This prop takes a function that renders some JSX. `emptyState` is called when `options` is empty and there are no before or after actions.
Include the following snippet in the Playground file. Try searching for something that does not return any results. You should see the empty state.
<details> …

[Autocomplete] Adds emptyState prop

---

UNRELEASED.md
src/components/AppProvider/README.md
src/components/Frame/README.md
src/components/Navigation/README.md
src/components/TopBar/README.md

@HYPD pointed out some broken/non-existent links in Frame-related docs. I did a bit of searching and found a few other related issues.
Closes #540.

fix broken or nonexistent links to new frame components

---

playground/index.html
playground/webpack.config.js
playground/webpack.config.shrink-ray.js
scripts/build-shrink-ray.js
tophat/Example.tsx
tophat/index.js
tophat/parseMarkdown.js
tophat/transpileExample.js
tophat/webpack.config.js
tophat/webpack.config.shrink-ray.js

More tidying of playground / shrink-ray / tophat on the road to unification
* In tophat, compile examples as part of the markdown parsing stage. This means we don't need to include babel in our JS output, which knocks about 4mb off our total size.
* Enables code splitting for all three builds. This means we can easily see the size of polaris, without including overheads like react and application code.
Check playground, shrink-ray and `yarn tophat` all still work as expected.
Shrink ray changes are expected due to splitting out items. This does however make it obvious that Webpack 4 does dead code elimination by default so the shrink-ray size isn't representative of our total bundle size (long term this shall be fixed by a move to use sewing-kit to build the tophat environment, and using …

Tophat updates

---

src/components/Autocomplete/components/ComboBox/ComboBox.tsx

Resolves https://github.com/Shopify/polaris-react/issues/472
Up and down arrow keys were not visually selecting the correct option.
Delays the visual update of the selection until setState has completed so the selection is correct. I also cleared the selection on blur.
<details>
```jsx
import {
Page, …
```

[Autocomplete] Fix option selection with arrow keys

---

src/components/Focus/Focus.tsx

Resolves #507
Previously `Focus` had it self focusing logic in a called back passed to `write` which uses `requestAnimationFrame` under the hood. It's an unneeded optimization which was causing the calledback to be invoked after the component has unmounted causing an invariant error.
<details>
Check the console for errors
```jsx
import {Page, AppProvider, Focus, TextStyle} from '@shopify/polaris';
toggle: boolean;
}
state = {
toggle: true,
};
this.setState({toggle: false});
}
render() {
const {toggle} = this.state;
const focusMarkup = toggle && …
```

Fix focus invariant error

---

UNRELEASED.md
src/components/Card/Card.tsx

Resolves #551 
The existing implementation differs from all the other components having a primary & secondary button.
This PR rearranges the primary & secondary footer actions on the card component to their expected order.
Before:
After:

[Card] Rearrange primary & secondary footer actions

---

tophat/snapshots.js

Partial fix for #565
Ensures PERCY_TOKEN is set before running snapshots
This PR is from a forked repo. Ensure that the "ci/circleci: percy" build step passes as a no-op.

Don't fail CI when PERCY_TOKEN is absent

---

package.json
yarn.lock

This removes the need for the PERCY_PROJECT env variable on CI as per https://github.com/percy/percy-puppeteer/releases/tag/v0.4.0
Ensure that percy still builds

Update @percy/puppeteer to 0.4.0

---

package.json
yarn.lock

Bump [`@shopify/javascript-utilities`](https://github.com/Shopify/javascript-utilities/) to 2.2.1 
It fixes specific usecase of Datepicker when `start` and `end` date are the same but different references.
Here is the fix commit: https://github.com/Shopify/javascript-utilities/commit/86f8a7ccb63e322bfc087450e3b8e5c9e72e9c55
It will help https://github.com/Shopify/web/pull/8192 to move forward.

Bump javascript-utilities to 2.2.1

---

UNRELEASED.md
src/components/Autocomplete/README.md

Closes #590 
Fixes misplacement of the Markdown horizontal rule so that the last example gets parsed properly.
| Before        | After           |
|![2018-11-09 13 48 13](https://user-images.githubusercontent.com/18447883/48292774-bae60500-e430-11e8-8f2d-e2b015cc67e5.gif)|![2018-11-09 13 51 08](https://user-images.githubusercontent.com/18447883/48292789-cafde480-e430-11e8-8987-a3feb4ce3f68.gif)|
- `git …

[Autocomplete] Fix section break placement in README

---

src/components/Popover/Popover.scss

A quick ~one~ two-liner.
I noticed that the `border-radius` for `<Popover />` was funky, and tracked it down to inconsistent `border-radius` values.
This PR resolves the visual issue.
Here you can see some of the `Popover` background poking through in the top left and right corner:
Top corners now resolved:

[Popover] Fix inconsistent border-radius

---

src/components/EmptySearchResult/EmptySearchResult.tsx
src/components/Navigation/components/Item/components/Secondary/Secondary.tsx
src/components/Navigation/components/Message/Message.tsx
src/components/TopBar/components/Menu/Menu.tsx
src/components/TopBar/components/Menu/components/Message/Message.tsx
src/components/TopBar/components/UserMenu/UserMenu.tsx

Using a consistent format form importing styles
Changes some instances of `import styles from 'blah.scss'` to `import * as styles from 'blah.scss'`.
Honestly I'm suprised this ever worked in the first place.
Ensure the `Frame` tophat example keeps its styling for the affected components.
Compare the build output by comparing master to this PR
* Checkout master and run `yarn build && yarn mv build build-master`
* Checkout this branch and run `yarn build && diff -r -u build-master build` to compare the build folders. The sass zip is expected to be different (as it includes metadata on file modified times, which differ between the builds). Assert that no other changes in the JS or css files occur.

Use 'import * as styles' format for all imports

---

UNRELEASED.md
src/components/TextStyle/TextStyle.tsx
src/components/TextStyle/tests/TextStyle.test.tsx

~`<b>` tags have gone the way of powdered wigs. Out with the old, in with the new. `TextStyle > strong` now uses a `<strong>` tag!~
We do not want to use `b` for "strong" variants... so using `span` tag instead.

[TextStyle] Change <b> to <span>

---

UNRELEASED.md
src/components/types.ts

Fix frame embedded app context errors

---

UNRELEASED.md
src/components/DataTable/DataTable.tsx
src/components/DataTable/components/Cell/Cell.tsx
src/components/shared.ts

Currently, our DataTable looks for `class*=header` when calculating column visibility. This doesn't work in a production environment where class names are obfuscated, hence this working in a development environment, but not a production environment like an embedded app.
This PR changes the way we target the `headerCells`, from the class-based targeting mentioned above to a data attribute system using `data-polaris-headercell`.
The other option here would be to use `refs` instead of data attributes, but with `Cell` being a subcomponent inside of `DataTable`, we would need to do a ref callback, and that seemed like more trouble than what it was worth.
- Load up the `DataTable` component with some dummy data
- Make sure classes are obfuscated in the DOM
- Confirm that the fixed column works, …

[DataTable] Update class targeting to data attribute targeting

---

UNRELEASED.md
src/components/DatePicker/components/Month/Month.tsx
src/components/DatePicker/components/Month/tests/Month.test.tsx

When DatePicker allow ranges but `start` and `end` dates are different references `start === end` will return false even if they are the same date.
Compare date instead of references.
Best way to tophat is to try this PR with and without the changes:
https://github.com/Shopify/web/pull/8192
Before: 
After:

[DatePicker] Fix date comparision when different references

---

UNRELEASED.md
src/components/Avatar/Avatar.scss
src/components/Avatar/Avatar.tsx
src/components/Avatar/tests/Avatar.test.tsx
src/components/Image/Image.tsx
src/components/Image/tests/Image.test.tsx

Resolves https://github.com/Shopify/shopify/issues/174824
The default option we want for our Avatar component is to show the  logged in user initials if an avatar image is not found. Gravatar gives us the possibility of providing a default image when an image is not found or to return a 404. 
In this [pr](https://github.com/Shopify/web/pull/5377) we attempted to return a transparent image. This was done with the following option in the query:
```
avatar(fallback: TRANSPARENT) {
src
}
```
The idea being that if the fallback was a transparent image it would simply lay over the Initials and wouldn't be visible.
However the Initials are in circle coloured background. As a result when an image was present it would show through [pr](https://github.com/Shopify/polaris-react-deprecated/pull/1157) …

Update Avatar and Image component to handle onError with images.

---

UNRELEASED.md
src/components/Badge/Badge.scss

Closes #631
- updates styling for badge size small to have looser padding, line-height, and a border
- updates status new badge to have sky background and ink text
|Navigation|
|-|
|![screen shot 2018-11-16 at 1 45 16 pm](https://user-images.githubusercontent.com/1403188/48641294-461e4800-e9a7-11e8-8784-9daacd09b17f.png)|
<details>
```jsx …
```

[Navigation][Badge] update size small badge and status new badge for better readability in navigation

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx

Bulk actions at the top of the Resource List should `stick` to the viewport top until the bottom of the list is reached. Currently there's a bug where the Bulk Actions never stop sticking. This is due to the component rendering before the List `ref` is resolved.
Ensure the List Ref is available before rendering the list.
<details>
```jsx
import {
Page,
ResourceList,
Card,
AppliedFilter,
FilterType,
AppProvider,
Sticky,
import {autobind} from '@shopify/javascript-utilities/decorators';
const items: any[] = [
{
onClick: true,
url: 'https://www.google.com',
actions: [{content: 'View listing', url: 'http://www.facebook.com'}], …
```

[Resource List] Fixing Bulk Actions that don't stock sticking

---

src/components/Autocomplete/README.md

Partly addresses https://github.com/Shopify/polaris-react/issues/590 and addresses [these comments](https://github.com/Shopify/polaris-react/pull/503#discussion_r230201606).
Moves `textField` and `emptyState` markup into their own variables in the README examples. 
- `yarn run build-consumer polaris-styleguide`

[Autocomplete] Move props into their own variables in examples

---

documentation/Component READMEs.md
tophat/parseMarkdown.js

If you fatfingered an example in a README then `yarn tophat` can give a cryptic error message. Make it less cryptic by adding more information.
Throw an error message that contains the file and example name that the problem occurs in.
What was:
```
Unexpected token, expected "{" (6:24)
```
Is now:
```
🚨 [Text field] Example "Default text field" contains a syntax error in src/components/TextField/README.md: Unexpected token, expected "{" (6:24)
```
* Go make a syntax error in an example. For instance change `handleChange = (value) =>` to `handleChange (value) =>` in TextField/README.md's "Default text field" example.
* Run `yarn tophat`
* See that the console reports the file and example name within which the error occurs. It'll look something like:
```
🚨 [Text field] Example "Default text …
```

Provide better error messaging when README examples have syntax errors

---

UNRELEASED.md
src/components/Icon/Icon.tsx
src/components/Icon/tests/Icon.test.tsx

fixes: https://github.com/Shopify/polaris-react/issues/449
In create-react-app 2, svg are loaded as components. This break our Icon component.
Allows to use a React Component at the source of the icon.
<details>
```jsx
import {Page, Icon} from '@shopify/polaris';
render() {
const svg = {
body:
"<path d='M17 9h-6V3a1 1 0 1 0-2 0v6H3a1 1 0 1 0 0 2h6v6a1 1 0 1 0 2 0v-6h6a1 1 0 1 0 0-2'  fill-rule='evenodd'/>",
viewBox: '0 0 20 20',
};
return (
<Icon source="placeholder" />
<Icon source="add" />
<Icon source={<Icon source="delete" />} />
<Icon source={svg} /> …
```

[Icon] updating source prop to accept a react node

---

UNRELEASED.md
src/components/EventListener/EventListener.tsx
src/components/EventListener/tests/EventListener.test.tsx

Part of https://github.com/Shopify/polaris-react/issues/519
* Replaces lifecycle method
* Add test
<details>
```jsx
import {Page, AppProvider, Button, EventListener} from '@shopify/polaris';
event: 'resize' | 'scroll';
}
export default class CollapsibleExample extends React.Component<never, State> {
state: State = {
event: 'resize',
};
render() {
const {event} = this.state;
const lines = Array.from({length: 100}, (n: number) => <br key={n} />);
return (
<AppProvider>
<Page title="test">
<EventListener event={event} handler={() => console.log(event)} />
<Button onClick={this.handleToggleClick}>
Current listener {event}
<br />
Previous listener …
```

[EventListener] Remove deprecated lifecycle method

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Part of https://github.com/Shopify/polaris-react/issues/519
* Replaces lifecycle method
* Add test
Add a `console.log` to textfield render to check it's current id during render. Check the console, onChange will trigger the id switch.
<details>
```jsx
import {TextField} from '@shopify/polaris';
id: string | undefined;
}
export default class TextFieldExample extends React.Component {
state = {
id: undefined,
};
handleChange = () => {
this.setState(({id}) => ({
id: id
? undefined
: Math.random()
.toString(36)
.substring(7),
}));
};
render() {
const {id} = this.state;
const props = {
label: 'Store name',
value: '',
onChange: this.handleChange,
id,
}; …
```

[TextField] Remove deprecated lifecycle method

---

package.json
scripts/deploy.js
shipit.yml

- Versions published from the `web` branch should not overwrite the version available on CDN via the `/latest/` release tag.
- `npm publish`, by default, publishes packages under the `latest` tag.
- Prevents `web` branch deploys from getting uploaded to S3 in the `/latest/` directory.
- Prevents `npm publish` from overriding the `latest` dist-tag when deploying from the `web` branch.
(Not sure how to test this without creating a whole new package, stack, s3 bucket, etc… probably not worth the hassle)

Prevent polaris-react 3.0.x hotfixes from getting deployed under the 'latest' tag

---

UNRELEASED.md
src/components/FormLayout/FormLayout.scss
src/components/FormLayout/components/Group/Group.tsx

Resolves https://github.com/Shopify/web/issues/4902
There's a min-width set on FormLayout Items t
hat is used for wrapping of items when inside a group. In the side column however that min-width is too wide.
Adding the min-width to items when in groups only.
Before | After
------------ | -------------
Content from cell 1 | Content from cell 2
1. Below is the Polaris-React Playground
2. `yarn build-consumer web` to 🎩 in web
<details>
```jsx
import {Page, FormLayout, TextField} from '@shopify/polaris';
render() {
return (
<FormLayout>
<FormLayout.Group> …
```

[FormLayout] min-width added to Item only when in Group. 

---

UNRELEASED.md
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/ContextualSaveBar/README.md
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx

Related to: https://github.com/Shopify/business-platform/issues/684
We are currently presenting a separate TopBar in specific scenarios. When they make changes within `web`, the context bar shows the old logo. We are looking to simply hide the logo in this dirty state.
This PR adds a `hideLogo` prop to the ContextualSaveBar component which essentially eliminates the markup for the Logo section in the ContextualSaveBar. Existing CSS for the `message` allows that section to fill in the remaining space out of the box.
📄 [Changelog …

[ContextualSaveBar]: Add prop to extend contents flush with left edge.

---

src/components/AppProvider/types.ts

fixes https://github.com/Shopify/polaris-react/pull/524#issuecomment-441637376
Changes the `prop-types` import to fix the build.
1. Dev up in Web.
2. In `polaris-react` switch to this branch and run `yarn build-consumer web`.
3. In Web start the server.
4. Make sure everything compiles without errors.

fixes prop-types import

---

UNRELEASED.md
src/components/Avatar/README.md
src/components/Banner/README.md
src/components/InlineError/README.md
src/components/Select/README.md
src/components/Thumbnail/README.md

https://github.com/Shopify/polaris-styleguide/pull/2314
Fixing links
Build for the styleguide, then run the broken link checker
<details>
```jsx
import {Page, AppProvider} from '@shopify/polaris';
render() {
return (
<AppProvider>
</Page>
</AppProvider>
);
}
}
```
</details>

Rename links for the updated IA on the styleguide

---

UNRELEASED.md
src/components/InlineError/InlineError.scss
src/components/TextField/TextField.scss
src/styles/shared/controls.scss

Resolves https://github.com/Shopify/polaris-react/issues/651
Updating `InlineError`, borders on our form fields and the Error Icon to be the same red. 
<details>
```jsx
import {Page, TextField, Checkbox} from '@shopify/polaris';
value: string;
checked: boolean;
}
state = {
value: 'Jaded Pixel',
checked: false,
};
handleTextFieldChange = (value) => {
this.setState({value});
};
handleCheckboxChange = (checked) => {
this.setState({checked});
};
render() {
const {value, checked, selected} = this.state;
return (
<Page
title="Playground"
primaryAction={{content: 'View Examples', url: …
```

Updating red colour for errors

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx
src/components/DropZone/tests/DropZone.test.tsx

Because we render different components to output `overlayText` and `errorOverlayText` depending on screen size, the `errorOverlayText` rendered the wrong text.
Ensures the right text is rendered and tests are added to prevent this in the future.
<details>
```jsx
import {DropZone, Stack, Thumbnail, Caption} from '@shopify/polaris';
dirty: boolean;
field: string;
saving: boolean;
}
export default class DropZoneExample extends React.Component {
state = {
files: [],
};
render() {
const {files} = this.state;
const validImageTypes = ['image/gif', 'image/jpeg', 'image/png'];
const fileUpload = !files.length && <DropZone.FileUpload />;
const uploadedFiles = …
```

Fix `errorOverlayText` prop on small screens

---

UNRELEASED.md
src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
src/components/AppProvider/utilities/createAppProviderContext/tests/createAppProviderContext.test.tsx

To prevent server side rendering from failing, which fixes #372.
Not instantiating app bridge if server side. The specific culprit is `getShopOrigin()` which ultimately reads `window.location`
The setup here is fairly involved. I worked through this with @katiedavis and confirmed this fixes the issue with AppProvider. There still may be other components where we are missing a server side check. If you would like to 🎩 please reach out to one of us.
Because this is hard to 🎩 I at least committed a test first which fails then committed the changes which satisfies the test.

[AppProvider] Fix SSR

---

UNRELEASED.md
src/components/Pagination/Pagination.tsx
src/components/Pagination/tests/Pagination.test.tsx

Key events can't be disabled like buttons and will currently fire when `hasNext` or `hasPrevious` are true
* Add default of true for `hasNext` and `hasPrevious`
* Don't add key events if `hasNext` or `hasPrevious` are true
* Add tests
* Add changelog
Use the playground code to toggle `hasNext` and `hasPrevious`
<details>
```jsx
import {Page, Pagination, Button} from '@shopify/polaris';
next: boolean;
prev: boolean;
[key: string]: any;
}
state = {
next: true,
prev: true,
};
toggleState = (key: string) => () => this.setState({[key]: !this.state[key]});
render() {
const {next, prev} = …
```

[Pagination] Fixed event from being called when has previous or next is false

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Some browsers (I'm looking at you Chrome) ignore autocomplete="off" because they think they know better. As a result, setting autocomplete="off" does not disable autocomplete. A better way to disable autocomplete is to use any string that does not match a valid autocomplete value such as "nope". See https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Disabling_autocompletion for more details.
This will not make any UI changes

[TextField] Use autocomplete="nope" instead of autocomplete="off"

---

.github/PULL_REQUEST_TEMPLATE.md

This is now a failing PR check which fails if missing and can be skipped with a label. A checklist item in the PR template feels redundant to me, what do you think?

Remove unreleased entry checklist item

---

UNRELEASED.md
src/components/AppProvider/utilities/createPolarisContext/createPolarisContext.ts
src/test-utilities/enzyme.tsx

`@shopify/app-bridge` imports in the generated types were relative imports which lead to a non-existent node_module when `app-bridge` was not installed.
Explicitly defines a `PolarisContext` return type on the functions that caused issues.
1. Run `yarn build`.
2. In `types` ensure that all `app-bridge` imports are absolute.

fixes app bridge type imports

---

UNRELEASED.md
src/components/SkeletonPage/README.md
src/components/SkeletonPage/SkeletonPage.scss
src/components/SkeletonPage/SkeletonPage.tsx
src/components/SkeletonPage/tests/SkeletonPage.test.tsx

[Link to deprecated PR](https://github.com/Shopify/polaris-react-deprecated/pull/2416)
closes https://github.com/Shopify/polaris-react/issues/2372
Original feature request: https://github.com/Shopify/polaris/issues/443
Added a primaryAction SkeletonDisplayText to mimic primaryAction Button on Page
🗒 [General tophatting guidelines](https://vault.shopify.com/developers/Tophatting)
<details>
<summary>Copy-pasta this code in <code>playground/Playground.tsx</code>:</summary>
```jsx
import {
Button,
Layout, …
```

[SkeletonPage] Add primaryAction as a prop to SkeletonPage

---

playground/index.html

Tracking used to be present in the `yarn tophat` developer tool, but was recently removed (probably when /tophat and /playground got merged).
- Adds tracking back to the playground (and /examples)
- Puts `utf-8` in lowercase, not sure it has an impact but it seems to be the norm

[Playground] Add Google Analytics tracking back

---

UNRELEASED.md
src/components/index.ts

266f1297 accidentally removed this import as part of refactoring
---
#698 Stopped exporting ToastProps and ContextualSaveBarProps. This was my bad as I didn't understand enough about how and where these props are used and didn't realize they are part of our public API. 
#722 Brought back ToastProps. This finishes the job.

Export ContextualSaveBarProps from src/components/index

---

UNRELEASED.md
config/typescript/modules.d.ts
package.json
src/components/DataTable/DataTable.tsx
src/components/DropZone/utils/index.ts
src/components/ResourceList/ResourceList.tsx
src/components/Sticky/Sticky.tsx
src/utilities/breakpoints.ts
yarn.lock

Keeping up to date.
Notably Typescript 3 offers [big improvements in error UX](https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#improved-errors-and-ux) - error messages due to incorrect typing shall be a lot more human readable now.
Update to typescript 3.1.6. Fix new warnings raised by running `yarn run sk type-check`.
Run tests and linting.

Upgrade to use TypeScript 3.1.6

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/components/Spinner/Spinner.tsx
src/components/TextField/components/Spinner/tests/Spinner.test.tsx
src/components/TextField/tests/TextField.test.tsx

Resolves #420
Support press and hold to increment/decrement value in `Spinner` of the numeric `TextField`.
<details>
```jsx
import {Page, TextField} from '@shopify/polaris';
state = {
value: '1',
};
handleChange = (value) => {
this.setState({value});
};
render() {
return (
<TextField
label="Quantity"
type="number"
value={this.state.value}
onChange={this.handleChange}
/>
</Page>
);
}
}
```
</details>

[TextField: Spinner] Support press and hold to increment/decrement value

---

CHANGELOG.md
UNRELEASED.md
src/components/Avatar/Avatar.scss
src/components/Avatar/Avatar.tsx
src/components/Avatar/index.ts
src/components/Avatar/tests/Avatar.test.tsx
src/components/Image/Image.tsx
src/components/Image/tests/Image.test.tsx

Resolves https://github.com/Shopify/shopify/issues/174824
The default option we want for our Avatar component is to show the  logged in user initials if an avatar image is not found. Gravatar gives us the possibility of providing a default image when an image is not found or to return a 404. 
In this [pr](https://github.com/Shopify/web/pull/5377) we attempted to return a transparent image. This was done with the following option in the query:
```
avatar(fallback: TRANSPARENT) {
src
}
```
The idea being that if the fallback was a transparent image it would simply lay over the Initials and wouldn't be visible.
However the Initials are in circle coloured background. As a result when an image was present it would show through [pr](https://github.com/Shopify/polaris-react-deprecated/pull/1157) …

[Avatar] Makes Avatar Image load only if Image load without error 

---

UNRELEASED.md
src/components/Avatar/Avatar.scss

When non-square images were added as a an avatar, it would result in them becoming pill-shaped blobs. This fixes that problem.
Adds `height: 100%` and [`object-fit: cover`](https://caniuse.com/#feat=object-fit) as styles to the image generated by the `Avatar` component.
<details>
```jsx
import {Page, Avatar, Image, Stack} from …
```

[Avatar] - fixed proportion on non-square images

---

UNRELEASED.md
src/components/AppProvider/AppProvider.tsx
src/components/AppProvider/index.ts
src/components/AppProvider/types.ts
src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
src/components/AppProvider/utilities/createPolarisContext/createPolarisContext.ts
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/ContextualSaveBar/index.ts
src/components/Frame/Frame.tsx
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/Frame/components/Toast/Toast.tsx
src/components/Frame/components/Toast/tests/Toast.test.tsx
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/Frame/index.ts
src/components/Frame/types.ts
src/components/Toast/Toast.tsx
src/components/Toast/index.ts
src/components/index.ts

tl;dr: The Props Explorer type parsing script makes assumptions about the format of the data that were never documented, and this update broke those assumptions. This fixes that. Longer version follows, read on if you're interested in how the Props Explorer works.
So, this repository interacts pretty closely with https://github.com/Shopify/polaris-styleguide . The styleguide has a feature called the `Props Explorer`, which allows users to search through any given component's props in a tree-like manner, right from the styleguide, and check out their types, default values, names, etc.
To be able to do this, we implemented the following pipeline on the styleguide:
1. Download the `polaris-react` package as a dependency
2. Run `typedoc` on the types, to generate a JSON file representation of …

Fix consistency issue in prop types

---

CHANGELOG.md
UNRELEASED.md

Prior to this merging, I will cut a release candidate `3.3.0-rc.1`, which will automatically open a PR in `polaris-styleguide`. That will act as our final stability check, and if all goes well, I will merge this PR and push tags for a `3.3.0` release.

update changelog for 3.3.0 release

---

UNRELEASED.md
src/components/Badge/Badge.scss

Closes https://github.com/Shopify/polaris-ux/issues/209 (again).

[Badge] [Navigation] make the new badge simpler and easier to read

---

UNRELEASED.md
scripts/percy-snapshots.js

Because percy has false positives
Adds a 2s delay before taking a screenshot
Run percy a few times locally and make sure the problems that came up because we were taking a scerenshot too fast go away

Fix percy false positives

---

UNRELEASED.md
src/components/AppProvider/AppProvider.tsx
src/components/AppProvider/index.ts
src/components/AppProvider/types.ts
src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
src/components/AppProvider/utilities/createPolarisContext/createPolarisContext.ts
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/ContextualSaveBar/index.ts
src/components/Frame/Frame.tsx
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/Frame/components/Toast/Toast.tsx
src/components/Frame/components/Toast/tests/Toast.test.tsx
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/Frame/index.ts
src/components/Frame/types.ts
src/components/Toast/Toast.tsx
src/components/Toast/index.ts
src/components/index.ts

Continuing the cyclical type import dance (almost there)
#698 Did some refactoring to remove some cyclical type imports. It turns out those changes broke the Props Explorer in the styleguide, as the script in the styleguide that generates props data assumes that each component has an interface called `Props` in it and #698 moved some props declarations outside of the component to remove circularity - as the Props were shared by two components.
#727 reverted the problematic parts of that PR and made the styleguide work again, at the cost of bringing back those cyclical type imports.
This PR fixes the cyclical types in a way that does not break the props explorer.
This PR consists of two commits. The first reverts #727. The second applies a change that allows the props explorer to be …

Fix cyclical imports redux (part2)

---

UNRELEASED.md
src/components/DataTable/DataTable.tsx
src/components/DataTable/components/Cell/Cell.tsx
src/components/DataTable/components/Navigation/Navigation.tsx
src/components/DataTable/index.ts
src/components/DataTable/types.ts
src/components/DataTable/utilities.ts
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/components/Context/Context.tsx
src/components/ResourceList/components/FilterControl/FilterControl.tsx
src/components/ResourceList/components/Item/Item.tsx
src/components/ResourceList/types.ts
src/components/Tabs/Tabs.tsx
src/components/Tabs/components/List/List.tsx
src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
src/components/Tabs/types.ts
src/components/Tabs/utilities.ts
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/index.ts
src/components/ThemeProvider/types.ts
src/components/ThemeProvider/utils/index.ts

Continuing the cyclical type import dance.
#691 removes some cyclical imports. It also stopped exporting a few color helper functions in the final build (see #718) as I incorrectly assumed that they should be internal. It turns out people are using them, so that PR got reverted in #721.
This PR is #691 EXCEPT the shuffling of the color helpers (I shall fix those cyclical imports while ensuring they are exported in a follow up PR).
Note that this does not move around any base `Props` interfaces so the styleguide's props explorer is happy with it. (It breaks if you set your components `Props` as an interface from a different file)
Move us closer to enabling the `import/no-cycle` rule by fixing several violations.
Moves some types around to avoid cyclical imports. See #691 for an example of …

Fix several cyclical type imports (redux)

---

UNRELEASED.md
src/components/Layout/Layout.scss
src/components/Layout/README.md
src/components/Layout/components/Section/Section.tsx
src/components/Layout/tests/Layout.test.tsx
src/styles/foundation/layout.scss

These changes are introduced to allow us to properly achieve an even 2 or 3 column layout. This replaces the old recommendation of using two `secondary` sections. 
This PR adds `oneHalf` and `oneThird` props to `Layout.Section` that adds styles for even width columns. 
**Wide screen**
**Narrow screen**
Try viewing this layout at multiple viewport widths. Make sure that the columns do not become too narrow before wrapping.
<details> …

[Layout] Adds oneHalf and oneThird props

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

Bulk actions do not render on initial load when there are selectedItems
fixes #642 - Dynamically sets initial state based on selected items
<details>
```jsx
import {Avatar, ResourceList, TextStyle, Card} from '@shopify/polaris';
state = {
selectedItems: [341],
};
};
return (
id={id}
url={url}
media={media}
accessibilityLabel={`View details for ${name}`}
>
<h3>
<TextStyle …
```

[ResourceList] Fix `BulkActions` not rendering on initial load

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/components/Item/Item.tsx
src/components/ResourceList/components/Item/tests/Item.test.tsx

* Extra tabstop breaking interaction states
* Items are interact-able while loading
* Removing the tabstop
* Items are not interact-able while loading
Playground stolen from Solona's loading PR 😄 
<details>
```jsx
import {
Avatar,
Card,
ResourceList,
FilterType,
TextStyle,
Page,
AppProvider,
searchValue: string;
appliedFilters: object;
}
export default class ResourceListExample extends React.Component<never, State> {
state: State = {
{
},
],
};
handleSearchChange = (searchValue: string) => {
}; …
```

[ResourceList] Remove extra tabstop

---

UNRELEASED.md
src/components/Page/components/Header/Header.scss
src/components/Page/components/Header/Header.tsx
src/styles/shared/page.scss

Updates the page component's header to align with the Shopify mobile app's layout, which fixes #706.
On small screens, the page component's header now rolls up secondary actions and action groups into a plain ellipsis button, which replaces pagination if it exists.
- `git checkout page-mobile-rollup && yarn dev`
- Copy paste the example code collapsed below into `/playground/Playground.tsx` and navigate to localhost:8080**
- Play with the …

[Page] Sync small screen header with native mobile

---

UNRELEASED.md
src/components/TextField/TextField.scss

Resolves #802
Indigo -> color(red, dark)
<details>
```jsx
import {Page, Button, Tooltip, Link, TextField} from '@shopify/polaris';
export default class TextFieldExample extends React.Component {
state = {
value: 'Jaded Pixel',
};
handleChange = (value) => {
this.setState({value});
};
render() {
return (
<TextField
label="Store name"
value={this.state.value}
onChange={this.handleChange}
error="sdsad"
/>
);
}
}
```
</details>

[TextField] Fix focus error state

---

documentation/Tophatting.md

Shopify doesn't support these browsers/devices.
Removes references to old, unsupported browsers/devices.

Update browser tophatting guide

---

UNRELEASED.md
src/components/PositionedOverlay/PositionedOverlay.tsx

There's currently a `NaN` error thrown while running the positioned overlay component tests. It also shows up in CI traces of any views with tests for components that render Polaris overlay components, like `Popover`. This is because of the lack of browser measurements accessible in the `jsdom` environment when the positioned overlay component calculates its `left` style property based on the activator and scroll container.
Adds a check to the definition of the inline style properties to ensure the value set is not `NaN`.
- `git checkout overlay-console-error` 
- `yarn dev`
- `yarn test PositionedOverlay --no-watch`
- the console error should be gone
- all tests should still pass
- all _foundational_ overlay component examples should render as expected (`Popover`, `Modal`, `Tooltip`)

[PositionedOverlay] Fix test env console error with NaN check

---

dev.yml

[This PR](https://github.com/Shopify/polaris-react/commit/a1a8aaa7d49909a52263dc2ab10dedace1911ebd#diff-5dc22d2579e771cc577fd24987df5029L21) accidentally removed `dev test`. I'm restoring it.

Restore dev test

---

UNRELEASED.md
src/components/ResourceList/README.md
src/components/ResourceList/ResourceList.scss
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

This PR is put in place to achieve [this](https://github.com/Shopify/web/issues/9457) without needing to fork the list.
Currently the only item that can go in the top right of the `ResourceList` is the `ResourceList.Sort`. There are instances where that area could be used for different content. In this particular case a popover of edit actions.
Adding a prop of `customTool` that can take any `ReactNode`
Note that this customTool is added **instead of the sort,**  because the current design does not lend itself well to having more than 1 popover on that row. 
**Before completing this PR with tests I'm looking for feedback on** 
1. Do we want to do this? The reason I am for it is because this looks like an easy win to add some level of flexibility to the list. Worth preventing another fork …

[ResourceList] Add `alternateTool` prop

---

examples/webpack/package.json
examples/webpack/yarn.lock

Upgrading the webpack version in the webpack example as there is a security vulnerability
https://nvd.nist.gov/vuln/detail/CVE-2018-14732

Upgrade webpack example per CVE-2018-14732 and dependencies

---

UNRELEASED.md
documentation/Versioning and changelog.md
package.json
src/components/ExceptionList/ExceptionList.scss
yarn.lock

Fixes #804 
Updates the font, icon, and bullet colors of warning status `ExceptionList` items from dark orange to dark yellow.
| Before | After |
|---|---|
|<img width="274" alt="screen shot 2019-01-04 at 11 51 55 am" src="https://user-images.githubusercontent.com/18447883/50707875-3d490a80-1017-11e9-8d17-e7feb183c0eb.png">|<img width="271" alt="screen shot 2019-01-04 at 11 50 59 am" src="https://user-images.githubusercontent.com/18447883/50707881-45a14580-1017-11e9-848f-9d8622280917.png">|
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master …

[ExceptionList] Change warning status items from orange to yellow

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/components/FilterControl/types.ts
src/components/Select/Select.tsx
src/components/Select/index.ts
src/components/index.ts

Typedoc (which we use for generating prop tables on the styleguide) has
a bug in it where it doesn't correctly resolve types that are imported
from a different file (or we're using it wrong).
Instead of looking at imports it seems to look at a global bucket of
names. In this case there was a clash between Option (as living in Select)
and Option (as living in OptionList/components). 
This resulted it it thinking that the type for ResourceList -> sortOptions was `src/components/OptionList/components/Option/Option.tsx`'s default export instead of the type in `src/components/Select/Select.tsx`
Work around this by renaming Select's Option to "SelectOption".
This allows our type documentation generation in the styleguide to work
correctly.
Strictly speaking the change to SelectGroup isn't …

Rename Option and Group types in Select to workaround typedoc oddness

---

CHANGELOG.md
UNRELEASED.md

- Moved icons to a separate npm package ([#686](https://github.com/Shopify/polaris-react/pull/686))
- Added `oneHalf` and `oneThird` props to `Layout` component ([#724](https://github.com/Shopify/polaris-react/pull/724))
- Added `helpText` prop to `ActionList` items ([#777](https://github.com/Shopify/polaris-react/pull/777))
- Updated `Page` header layout so actions take up less room on small screens ([#707](https://github.com/Shopify/polaris-react/pull/707))
- Added `alternateTool` prop to `ResourceList` component ([#812](https://github.com/Shopify/polaris-react/pull/812))
- Updated color of warning status `ExceptionList` items from dark orange to dark yellow for better differentiation from critical status items ([#813](https://github.com/Shopify/polaris-react/pull/813))
- Fixed …

update changelog for 3.4.0 release

---

yarn.lock

VSCode's stylelint extension checks on typing. Sometimes when you're typing you write unparsable  code  - because you've wrote `if {` but not the `}` yet.
When this happens you get a bunch of problem notifications raised because prior to this change eslint and stylelint crashed when given unparsable code:
This bumps the versions of the eslint and stylelint prettier plugins to not crash when faced
with invalid code, so these errors-because-youve-not-finished-typing are denoted as temporary red squiggly lines instead of those problem popups.
* Have the stylelint VSCode plugin installed
* `yarn install`
* Restart VSCode
* Write some unparsable code in a tsx file. I suggest changing an `export` to `ex}port`. See that no problem notification appears

Bump eslint-plugin-shopify and stylelint-config-shopify versions

---

src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/RangeSlider/types.ts

Resolves https://github.com/Shopify/polaris-react/issues/839
Removes `accessibilityInputs`. A better example in the style guide and clear documentation will be in a separate PR.
Fire up Storybook!

[RangeSlider] Remove accessiblityInputs

---

UNRELEASED.md
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx
src/components/Card/Card.tsx
src/components/Card/tests/Card.test.tsx
src/components/Modal/Modal.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/WithinContentContext/WithinContentContext.tsx
src/components/WithinContentContext/index.ts
src/types.ts

Addresses  #785.
- https://polaris-react-pr-786.herokuapp.com/banner/banner-in-a-modal
- https://polaris-react-pr-786.herokuapp.com/banner/banner-in-a-card
- https://polaris-react-pr-786.herokuapp.com/banner/default-banners

[Banner] [Card] [Modal] convert banner legacy context API to use create context

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx
src/components/DropZone/tests/DropZone.test.tsx

Resolves #425  
This is addressing the issue that the `DropZone` will not allow duplicate files to be added consecutively. This also caused issues when a file was removed , it could not be added again.
<details>
```jsx
import {
Page,
Stack,
Thumbnail,
DropZone,
Button,
Card,
Caption, …
```

[DropZone] Allow duplicate files to be uploaded consecutively/ removed and added again

---

src/components/RangeSlider/RangeSlider.tsx
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/RangeSlider/types.ts

- ~moves `value` out of `mockProps` to avoid casting as `[number, number]`~
- partially addresses #841
- handles cases where the lowerValue and upperValue are out of order
- handles cases where the lowerValue is higher than the max
- handles cases where the upperValue is lower than the min
- tests all sanitization cases

[Range slider] better sanitization and tests

---

src/components/RangeSlider/README.md

Resolves https://github.com/Shopify/polaris-react/issues/854
The example uses a stack component, which does not fully meet the requirements of the design, but it's not possible to do in the example without CSS media queries.
I'm questioning if these really should be handled by the component. A debounce or timeout might solve the issue we were having?
<details>
The need to handle errors seems like an edge case, so we left it out.
**Devon Persing**
Hmm. If someone isn’t interacting directly with the slider it might weird. (Since it’s not going to work with all AT.)
What are the scenarios where an error would get triggered?
**Solona Armstrong**
I had a similar question, Devon, in terms of scenarios. I don't really know. The `type="number"` prevents characters from being typed and the `min` …

[Range Slider] Add example with accessibility inputs for dual thumb

---

UNRELEASED.md
src/components/Navigation/README.md
src/components/Navigation/components/UserMenu/UserMenu.tsx

This reverts commit 6a029c68ad1a5a36d2c756d25733bc60da06a45e because `console.warn` [seems to be causing Jest to fail tests](https://buildkite.com/shopify/web-ci-builder/builds/39591#c85aef2f-bf35-455c-a103-60e0aee05d38).

Revert "Deprecates Navigation.UserMenu (#849)"

---

CHANGELOG.md
UNRELEASED.md

- Update build toolchain to use Babel v7, PostCSS v7 and Rollup v1. Update our build targets match our [supported browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers), leading to a reduction in bundle size ([#837](https://github.com/Shopify/polaris-react/pull/837))
- Ensure disabled `Button` components with a `url` prop output valid HTML ([#773](https://github.com/Shopify/polaris-react/pull/773))
- Fixed `DropZone` which was unable to add a duplicate file back to back or add a file again once removed [#782](https://github.com/Shopify/polaris-react/pull/782). Thank you [@jzsplk](https://github.com/jzsplk) for the contribution [#425](https://github.com/Shopify/polaris-react/issues/425) and [@vladucu](https://github.com/vladucu) for the clear …

update changelog for 3.5.0 release

---

UNRELEASED.md
src/components/Button/Button.tsx
src/components/Button/tests/Button.test.tsx

Porting over from https://github.com/Shopify/polaris-react-deprecated/pull/1820
Add events for the aforementioned.
<details>
```jsx
import {Page, Button} from '../src';
render() {
return (
<Button onKeyPress={log} …
```

[Button] keypress, keydown, and keyup events

---

UNRELEASED.md
src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
src/components/RangeSlider/components/SingleThumb/tests/SingleThumb.test.tsx
src/utilities/clamp.ts
src/utilities/tests/clamp.test.ts

Resolves #815
Creates a clamp function that adjusts a given number based on given min/max bounds.
<details>
```jsx
import {Page, RangeSlider} from '@shopify/polaris';
singleValue: number;
}
state = {
singleValue: 50 as number,
}; …
```

[RangeSlider] Clamp single thumb

---

UNRELEASED.md
src/components/Tabs/README.md

Resolves https://github.com/Shopify/polaris-react/issues/583
Changes style guide examples so panel activates.
<details>
```jsx
import {Page, Tabs, Card} from '../src';
state = {
selected: 0,
};
handleTabChange = (selectedTabIndex) => { …
```

[Tabs] Accessibility

---

UNRELEASED.md
package.json
src/components/Toast/Toast.tsx
src/components/Toast/tests/Toast.test.tsx
yarn.lock

Resolves https://github.com/Shopify/polaris-react/issues/820
- Update to use app-bridge@1.0.3
- [Toast] Use new Toast action from app-bridge instead of legacy Flash
- [Toast] Remove deprecated `isDismissible` prop
1. Clone this app https://github.com/vividviolet/test-shopify-app and run `dev up`. Make sure you stop running the App Bridge Playground as the test app will replace the Playground.
2. In the Polaris directory run `yarn build-consumer DIRNAME` with `DIRNAME` replaced with the directory containing the test app
3. In the Polaris directory run `yarn build-consumer web`
4. Build and run Web
5. Install the test app at http://app-bridge.myshopify.io/auth/shopify?shop=shop1.myshopify.io
6. Open https://shop1.myshopify.io/admin/apps/app-bridge
7. Test all buttons and ensure the `Page`, …

Update to use app-bridge@1.0.3

---

UNRELEASED.md
src/components/ResourceList/components/FilterControl/components/DateSelector/DateSelector.tsx
src/components/ResourceList/components/FilterControl/components/DateSelector/tests/DateSelector.test.tsx

This PR will fix an issue with the `<DateSelector />` component where it display the incorrect date in the `<TextField />` due to it not taking into account the timezone offset.
The issue is that when passing a date without time, e.g `new Date("2018-12-04").toISOString()` it doesn't take the time zone offset into account.
This PR fixes the issue by taking the timezone into account when adding a date either in the `<TextField />` component, or by clicking in the `<DatePicker />`. This PR also fixes https://github.com/Shopify/polaris-react/issues/688.
**Before (computer located in Sweden)**
**After (computer located in Sweden)** …

[DateSelector] Take timezone into account

---

documentation/Deprecation guidelines.md

We give a lot of instructions on how to deprecate a feature and it might be useful to provide some examples.
It adds [the deprecation of `Navigation.UserMenu`](https://github.com/Shopify/polaris-react/pull/849) as an example.

Adds example to deprecation guidelines

---

UNRELEASED.md
src/components/Stack/README.md
src/components/Stack/components/Item/Item.tsx

Resolves #536  
Stack Item properties needed to be listed in the documentation. 

[Stack.Item] Add Stack.Item properties to style guide documentation

---

UNRELEASED.md
src/components/Popover/Popover.tsx

Was cruisin' through the code and noticed the had duplicated a prop. Simple one line removal!

[Popover] Remove duplicate `activatorWrapper` prop

---

UNRELEASED.md
scripts/optimize.js

Previously this tried to optimize all svgs, including those in the node_modules folder - all of which we never use and many of which are complex. Instead lets only target svgs we actually care about - those within our src folder.
This makes the optimize build step take about 250ms instead of 4300ms -
shaving about 4 seconds off our build time.
Only optimize svgs in the `src` folder
- On master, create a build output: `git checkout master && mkdir master-build/node_modules/@shopify && yarn run build-consumer polaris-react/master-build`
- On this branch create a build output: `git checkout only-optimize-our-svgs && mkdir new-build/node_modules/@shopify && yarn run build-consumer polaris-react/new-build`
- Compare the outputs and ensure they are the same: `diff -r -u master-build new-build`

Only optimize our svgs when building

---

src/styles/foundation/colors.scss

Fixes #779
Use an implementation of color-multiply based off
https://github.com/heygrady/scss-blend-modes/blob/master/stylesheets/_blend-modes.scss
This is slightly tricky as we never call this function in our code. The only place it is referenced is if you call `color()` with a 3rd argument - which we never do. The easiest way to prove this is to add an `@error 'HI!'` at the top of the `color-multiply()` function then run `yarn run build` and see that the build still completes successfully.
We can't straight-up delete this function as that would violate our deprecation guidelines.
However we should prove that this new implementation works the same way as the prior implementation:
- Open up https://www.sassmeister.com/
- Add the following code, which contains the old and new …

Don't use math on colors as it is deprecated

---

UNRELEASED.md
src/components/Page/Page.tsx
src/components/Page/tests/Page.test.tsx

Resolves https://github.com/Shopify/polaris-react/issues/669#issuecomment-442485366
Added `forceRender` to title, breadcrumbs, and actions render in the app when app-bridge is use
Default using app bridge 
ie. `<AppProvider apiKey={YOUR_API_KEY}>`
Default without app bridge
ie. `<AppProvider apiKey={undefined}>`
Using app bridge & forceRenderTitle
ie. `<AppProvider apiKey={YOUR_API_KEY}><Page title="test title" forceRenderTitle /></AppProvider>`
Using app bridge & forceRenderActions
ie. `<AppProvider apiKey={YOUR_API_KEY}><Page title="" primaryAction={{content: 'Save'}} forceRenderActions /></AppProvider>`
Using app bridge, forceRenderTitle, and forceRenderActions
ie. `<AppProvider apiKey={YOUR_API_KEY}><Page title="test title" primaryAction={{content: 'Save'}} forceRenderTitle …

[Page][Prototype] ✨ add `forceRender` to force render of the title, actions & breadcrumbs to be in page vs in the top bar.

---

UNRELEASED.md
dev.yml
package.json
scripts/open-styleguide-pr.js
yarn.lock

ShipIt comes with an old version of Yarn, that doesn't support integrity hashes. This means each polaris-styleguide PR coming from polaris-react deploys is deleting thousands of lines (hashes) from yarn.lock.
By leveraging a more recent version of Yarn, we know those hashes will be kept in.
---
To tophat, let's create a new Shipit stack, create a beta version, and see if the resulting PR has a yarn.lock that still contains integrity hashes.
See this PR https://github.com/Shopify/polaris-styleguide/pull/2501/files where the resulting yarn.lock still contains integrity hashes.

Use the latest version of yarn to upgrade Polaris on the style guide

---

.storybook/.babelrc
.storybook/webpack.config.js
babel.config.js
scripts/build.js
sewing-kit.config.ts

To stop repeating ourselves and a slight build process simplification
Unifies our babel config into babel.config.js
- On master, create a build output: `git checkout master && mkdir -p master-build/node_modules/@shopify && yarn run build-consumer polaris-react/master-build`
- On this branch create a build output: `git checkout simpler-babel-config && mkdir -p new-build/node_modules/@shopify && yarn run build-consumer polaris-react/new-build`
- Compare the outputs and ensure they are the same: `diff -r -u master-build new-build`
- Ensure tests pass
- Ensure storybook still works, including hot reloading of tsx and README files.

Specify babel config in babel.config.js

---

UNRELEASED.md
src/components/Modal/components/Header/Header.scss

Resolves issue:
Modal Title - Vertical alignment #868
Bump margin-top up to 0.4rem (from 0.2rem)
Slight change to margin top, modal header component
<details>
```jsx
render() {
return (
<Page …
```

[Modal] update modal title styles

---

UNRELEASED.md
src/components/Caption/README.md

Short and sweet update for the caption component. Ideally should be published along with https://github.com/Shopify/polaris-styleguide/pull/2521 since that PR adds accessibility guidance for the data viz section.
Adds accessibility guidance for web, iOS, and Android for captions. Changes appear at the bottom of the gray examples/props section.
- Adds an accessibility section to the `README.md`
- Adds an entry to `UNRELEASED.md`
1. Check out https://github.com/Shopify/polaris-styleguide/pull/2493 from `polaris-styleguide` to get the changes that support the accessibility section.
1. In another Terminal tab or window, check out this branch from `polaris-react` and [run the instructions for testing in a consuming project](https://github.com/Shopify/polaris-react/#testing-in-a-consuming-projec …

Caption a11y docs

---

UNRELEASED.md
src/components/TopBar/components/UserMenu/components/UserMenu/UserMenu.tsx

Fixes #842 by removing a `title` attribute we don’t need.
- The `title` attribute is [ineffective for people using assistive technology](https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/)
- It seems like the content here should already be available to screen readers

[TopBar] Remove `title` attribute from UserMenu

---

UNRELEASED.md
src/components/DataTable/README.md
src/components/ResourceList/README.md

This PR adds component-level accessibility documentation to the data table and resource list components (which link to each other), to display in the `polaris-react` repo and on the style guide. Changes should appear at the bottom of the gray Examples and Props section.
Adds documentation on accessibility features built into the components.
- Edits the `README.md` files for the data table and resource list components to add a new section.
- Adds an entry to `UNRELEASED.md`.
1. Check out https://github.com/Shopify/polaris-styleguide/pull/2493 from `polaris-styleguide` to get the changes that support the accessibility section.
1. In another Terminal tab or window, check out this branch from `polaris-react` and [run the instructions for testing in a consuming …

Data table and resource list a11y docs

---

UNRELEASED.md
src/components/TopBar/components/UserMenu/context/Consumer.ts

https://github.com/Shopify/polaris-react/pull/852 introduced a [`react.d.ts` not found error](https://circleci.com/gh/Shopify/polaris-styleguide/23123) in Web and the Polaris Styleguide caused by [`UserMenu/context/Consumer.ts`](https://github.com/Shopify/polaris-react/pull/852/files#diff-4fbf566e7626b1d2b295b411e744b33e).
It imports `React` into the file which changes the build output from:
```ts
/// <reference path="../../../../../../../config/typescript/react.d.ts" />
/// <reference types="react" />
declare const _default: import("react").ComponentType<import("react").ConsumerProps<import("./context").UserMenuContextTypes>>;
export default _default;
```
to
```ts
import * as _React from 'react';
declare const _default: _React.ComponentType<_React.ConsumerProps<import("./context").UserMen …
```

fixes typescript/react.d.ts not found error in Consumer.d.ts

---

src/components/Stack/README.md

Per title. This should fix the pa11y test failing in polaris-styleguide when trying out the 3.6.0 rcs.
Removes a hyperlink.

Remove a deep-link to an example as the styleguide doesn't support them

---

UNRELEASED.md
src/components/TextField/README.md
src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx
src/locales/en.json

Resolves #491
TextField lacks the ability to display the remaining characters available when the TextField has a max character length. This PR adds that ability.
Adds in the prop `showCharacterCount` to TextField to enable the displaying of the remaining character count.
The `Labelled` component will then display the number of characters out of the total allowed characters that have been inputted into the TextField.
One item of note is that things can get a little busy as can be seen below:
@dpersing was giving insight into this on the issue.
📄 [Changelog …

[TextField / Labelled] Add character count

---

UNRELEASED.md
src/components/Navigation/Navigation.tsx

Follow up on https://github.com/Shopify/polaris-react/pull/887. Deprecates the `userMenu` prop on `Navigation` as with the deprecation of `Navigation.UserMenu` it won't be needed anymore.
Adds the appropriate deprecation messages to the component.
1. Mount a `<Navigation />` component in the playground.
2. Make sure no deprecation messages show up in the console.
3. Add a `userMenu` to the `<Navigation />`.
4. Make sure the `userMenu` deprecation notice shows up in the console.
<details>
<summary>Playground code</summary>
```tsx
import {Page, Navigation} from '../src';
render() {
return (
<Navigation location="" userMenu={<div />} />
</Page>
); …
```

adds deprecation notice for Navigation's userMenu prop

---

UNRELEASED.md
src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.tsx

I have an instance where I need to nudge a component "outside" of the `<Collapsible />` area - so that when a `Collapsible` is open, our design has an element that "overflows" out of the container.
This is currently not possible because `Collapsible` **always** sets `overflow: hidden`, which is necessary for when the `Collapsible` is closed and transitioning open/closed. But once fully open, its safe to set `overflow: visible`.
This PR achieves this in the _easiest_ way possible by adding a `.fullyOpen` under the following condition: `animationState === 'idle' && props.open`
Perhaps we want to solve the problem a different way... One idea would be to replace the `idle` state with both a `fullyClosed` and `fullyOpened` state. This approach would require more code to change, as well as …

[Collapsible] Set `overflow: visible` once the Collapsible is fully open

---

.storybook/md-parser.js
.storybook/polaris-readme-loader.js
.storybook/stories-from-readme.js
UNRELEASED.md
package.json
yarn.lock

1. Go to https://polaris-react.herokuapp.com/?selectedKind=All%20Components%7CApp%20provider&selectedStory=With%20theme&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel
2. In the "notes" panel, click "top bar"
https://polaris.shopify.com/components/structure/top-bar loads
https://polaris-react.herokuapp.com/components/structure/top-bar loads
Adds `https://polaris.shopify.com` at the beginning of links so they open the style guide correctly.
🥇 Mad props to @BPScott for teaching me how the webpack Markdown loader works and pairing with me on coding this
1. Go to https://polaris-react-pr-933.herokuapp.com/?selectedKind=All%20Components%7CApp%20provider&selectedStory=With%20theme&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel
2. In the …

[Storybook] Direct example description links to https://polaris.shopify.com

---

UNRELEASED.md
src/components/AppProvider/README.md
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/components/ThemeProvider/tests/utils.test.ts
src/components/ThemeProvider/utils/index.ts
src/components/TopBar/README.md
src/components/TopBar/TopBar.scss

We're polishing the new top bar layout by removing the background of the logo in the `TopBar`.
- Removes the `background-color` rule on the `LogoContainer` class.
- Removes `backgroundDarker` theming option as it isn't used anywhere else.
<details>
<summary>1. Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>
```jsx
import {AppProvider, TopBar} from '../src';
render() {
return (
<AppProvider
theme={{
colors: {
topBar: {
background: '#357997',
},
},
logo: {
width: 124,
topBarSource:
'https://cdn.shopify.com/s/files/1/0446/6937/files/jaded-pixel-logo-color.svg?6215648040070010999',
contextualSaveBarSource: …
```

Removes logo background

---

UNRELEASED.md
src/components/TopBar/TopBar.scss
src/components/TopBar/components/Search/Search.scss
src/styles/shared/page.scss

This addresses some of the discussions that we had after this issue popped up https://github.com/Shopify/polaris-react/issues/956 and is also a follow up of https://github.com/Shopify/polaris-react/pull/852. The original PR did change the width of the search input field in the TopBar but did not apply those changes to the search results container. This looks a bit weird and this PR aligns the search result with the input field and also matches the width of the field.
It sets the position rule to be relative on the search container. This allows us to match the width with the absolutely positioned search results container. …

[TopBar] adopt search results to match width and alignment of input field

---

UNRELEASED.md
src/components/Card/README.md
src/components/Card/components/Section/Section.tsx
src/components/Card/components/Section/tests/Section.test.tsx

Reverts Shopify/polaris-react#993

Revert "Revert "Update Card.Section to accept ReactNode as title""

---

UNRELEASED.md
src/components/ResourcePicker/ResourcePicker.tsx
src/components/ResourcePicker/tests/ResourcePicker.test.tsx

Resolves https://github.com/Shopify/app-bridge/issues/717
`showHidden` default value was changed to `false` when App Bridge first launched, but the option didn't actually take effect due to a bug. Now that the bug is fixed by https://github.com/Shopify/web/pull/10116, it exposed behaviour inconsistency with EASDK.
More details on the issue here: https://github.com/Shopify/app-bridge/issues/721
Change the default value back to `true` in order to match the expected behaviour of EASDK, as well as other admin sections.

[Resource Picker] change the default value of `showHidden` to `true`

---

UNRELEASED.md
src/components/Card/Card.scss

Resolves #954  
When a subdued section `Card` and a footer prop were combined there was no padding/margin between the `Button Group` and the edge of the subdued card. 
It was also discovered in the interim there was the same issue with the Header  button Group and a subdued section card as well so this will be resolved.
This request is adding a margin to the footer section.
Before: 
After: 
Small screen:
With no header and regular section cards:
Small screen:
<details>
```jsx
import {Page, Card, List, Popover, Button, ActionList} from '../src';
render() {
return ( …
```

[Card] Adjust padding of Card.Section, footer and header

---

UNRELEASED.md
src/components/ResourceList/README.md

Resolves #888  
Adds an example to of resource list to the styleguide that includes, bulk actions, persistent item shortcut actions, sorting and filtering.
In the styleguide:
<details>
```jsx
import {Page, Avatar, TextStyle, ResourceList, Card, FilterType} from '../src';
state = {
sortValue: 'DATE_MODIFIED_DESC',
{
},
],
};
};
this.setState({appliedFilters});
}; …
```

[ResourceList] Add full example of resource list to styleguide

---

UNRELEASED.md
src/components/TextField/TextField.scss

Resolves #986 
Follow up on #709, we found that having the character count on the same row in a multiline textField caused strange wrapping on narrow inputs. This PR uses `flex-wrap: wrap;` on multiline fields to move the counter to the bottom of the input so we take up vertical instead of horizontal space.  
<details>
```jsx …
```

[TextField] Move character counter to bottom of multiline text input.

---

UNRELEASED.md
src/components/Card/README.md

Resolves #890  
Adds an example to the `styleguide` that includes a combination of all the props available for `Card`.
<details>
```jsx
import {
Card,
Stack,
ActionList,
Popover,
Button,
TextContainer,
ResourceList,
List,
render() {
return (
<Card
secondaryFooterAction={{content: 'Dismiss'}}
primaryFooterAction={{content: 'Export Report'}}
>
<Card.Header
actions={[
{
content: 'Total Sales',
},
]}
title="Sales"
>
<Popover
active={false}
activator={
<Button disclosure plain>
View Sales
</Button>
}
onClose={() => {}}
>
<ActionList
items={[{content: 'Gross …
```

[Card] Add full example to styleguide

---

UNRELEASED.md
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.scss

Resolves https://github.com/Shopify/polaris-react/issues/798. Depends on https://github.com/Shopify/polaris-react/pull/784.
The clickable area for the track was too small.
Widens it. It also adds track click functionality to the manual dual thumb.
http://localhost:6006/?selectedKind=All%20Components%7CRange%20slider&selectedStory=Dual%20thumb%20range%20slider&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel …

[Range slider] Widen track click target area

---

UNRELEASED.md
src/components/Tooltip/Tooltip.scss

The [tip was removed](https://github.com/Shopify/polaris-react-deprecated/commit/17c2ef5e2b868f85295112706d4067a65f0af038) from tooltip and popover. There were some leftover styles that weren't deleted from the tooltip. The distance between the tip and its activator was 5px in tooltip and 4px in popover.
Removes the styles and sets the offset as 4px.
<details> …

[Tooltip] Remove leftover styles from tip in tooltip

---

UNRELEASED.md
src/components/Card/Card.tsx
src/components/Card/tests/Card.test.tsx

Resolves #1031 
When `Card` is missing `title` or it's empty, the header of the `Card` wouldn't show even if there were `actions` specified. 
What @danrosenthal suggested in #1031 comments -- shows the header if at least one of title or actions is truthy.
(Not really tested because I don't have the means or the knowledge to do it efficiently. To test it with my app code I did `yarn build` in polaris-react, then `yarn remove shopify/polaris`, `yarn add file:/path/to/local/polaris-react`, `rm -rf node_modules` and `yarn install` in my app project` which takes a lot of time and probably is not how it's to be done)

[Card] Fix missing header (actions) when title is empty or not specified

---

UNRELEASED.md
src/components/Button/Button.tsx
src/components/Button/tests/Button.test.tsx
src/components/UnstyledLink/UnstyledLink.tsx
src/components/UnstyledLink/tests/UnstyledLink.test.tsx

I've got a use case where I want a Button that triggers the download of a file instead of opening it.
The web provides support for this using the download attribute (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) but there's no way to expose that currently
Adds a `download` prop to the Button and UnstyledLink components. It may either be `true` to render `<a href="foo" download>` or a string to render `<a href="foo" download="downloadPropValue">` which acts as a hint for the filename to use when saving the file.
This only has an effect when you pass a `url` to a button but I think that's ok, as `external` acts in a similar way.
On the playground click the various buttons and see the behaviour.
<details> …

Add download attribute to Button and UnstyledLink

---

UNRELEASED.md
src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/components/Month/Month.tsx
src/components/DatePicker/utilities.tsx
src/locales/en.json

Resolves https://github.com/Shopify/intl-domestic-country-fit/issues/340
Currently, months and week names are hard coded in English, therefore, it breaks in other languages. See:
- Extract strings in `en.json` and use `intl.translate` to load them based on the month or weekday
- Replace the new translations in `en.json` and see them rendered on the storybook.

[DatePicker] Extract months and week names into en.json

---

UNRELEASED.md
src/components/Icon/Icon.scss
src/components/Icon/Icon.tsx
src/components/Icon/README.md
src/components/Icon/tests/Icon.test.tsx
src/styles/foundation.scss
src/styles/foundation/filters.scss

Part of https://github.com/Shopify/polaris-react/issues/885
Inlining svgs is potentially dangerous as scripts can be executed if they are in the svg.
If the user provides an svg, we will display it in an `img` tag instead. Since we can't use fill on img tag we need to use a filter from the polaris-tokens to get the correct colour that we want. 
This is adding a `untrusted` prop to Icon that a user will have to manually set in order to render a svg string. This is temporary as we wait for the work on SVGR to be completed.
| `white` | `black` |
|---|---|
| ![image](https://user-images.githubusercontent.com/9055413/52433977-517f9c00-2adc-11e9-9d18-8eff96207f84.png) | ![image](https://user-images.githubusercontent.com/9055413/52434043-6fe59780-2adc-11e9-8d8f-ac955282eba0.png) |
| `skyLighter` …

[Icon] Use img tag instead of inlining svgs

---

UNRELEASED.md
src/components/SkeletonThumbnail/README.md
src/components/SkeletonThumbnail/SkeletonThumbnail.scss
src/components/SkeletonThumbnail/SkeletonThumbnail.tsx
src/components/SkeletonThumbnail/index.ts
src/components/SkeletonThumbnail/tests/SkeletonThumbnail.test.tsx
src/components/index.ts

Resolves https://github.com/Shopify/polaris-react/issues/1039
I chose 3 size options for now, because in the issues screenshot the thumbnails seem to have a size of 30px, not sure if it is accurate or scaled down, though. In the Home sidebar and on Home cards thumbnails have a size of 40px whereas in other sections of the admin (products) thumbnails have a size of 50px.
Adds a new component that can be used for thumbnails while in loading state …

[Skeleton] Add skeleton for thumbnails

---

UNRELEASED.md
src/components/ResourceList/components/Item/Item.tsx
src/components/ResourceList/components/Item/tests/Item.test.tsx

A resource list item with a URL does not get wrapped in an actual anchor tag in order to prevent having nested links. This is problematic for some stuff we are working on for web where we want to transparently see what URL is being hovered over at any given time (in order to preload that next page).
This PR adds a `data-href` around the top-level wrapper for the item, which will be used alongside normal `href` to find the closest link being hovered over.

[ResourceList] Add data-href to ResourceList.Item wrapper

---

CHANGELOG.md
UNRELEASED.md

This PR prepares us for the latest `3.8.0` release. All I have done here is migrate the UNRELEASED content into the CHANGELOG.

[3.8.0] Prepare for latest release

---

UNRELEASED.md
src/components/DropZone/DropZone.scss
src/components/DropZone/DropZone.tsx
src/components/DropZone/components/Context/Context.tsx
src/components/DropZone/components/FileUpload/FileUpload.tsx
src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
src/components/DropZone/tests/DropZone.test.tsx
src/components/DropZone/types.ts

Resolves #742  
The `DropZone` determines its size (height and width) based on width only. This makes certain valid use cases, where the default `DropZone` height isn't appropriate, impossible. 
This pull request allows the consumer to set a fixed height on a wrapping parent element so that the `DropZone` takes its parent's height if one is provided.
Current Behaviour:  (wrapped with a div given a height of 50px)
New Behaviour: (wrapped with a div given a height of 50px)
Fixed small Height small Width:
Fixed Medium Height Medium Width:
Fixed Large Height Large Width: 
Fixed ExtraLarge Height ExtraLarge Width:
Fixed Small Width ExtraLarge Height
Fixed ExtraLarge Width Small Height
(Note: there are in between size variations (ie. small width, medium height etc.) The `FileUpload` will always …

[DropZone] Constrain drop zone height based on inherited wrapper height

---

src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
src/components/AppProvider/utilities/createAppProviderContext/tests/createAppProviderContext.test.tsx

https://github.com/Shopify/app-bridge/issues/737 (more context: https://github.com/Shopify/app-bridge/issues/730)
> We'd like to be able to track additional information about how [App bridge] is being consumed. With the legacy EASDK we provided a way to include metadata about the interface which Polaris passed in. No such mechanism exists in App Bridge.
This PR adds a tiny middleware which adds a `clientInterface` property to all App bridge actions dispatched from Polaris, so we can track whether people are using App Bridge through Polaris.
Buckle up, this involves 3 repos 😅 
Make sure Core & Web are running.
If you want to see the final Monorail events, you can check out [`app-bridge/version-tracking `](https://github.com/Shopify/web/pull/10560) in Web, but it’s not strictly necessary. …

[App bridge] Add middleware to pass clientInterface data

---

documentation/Deprecation guidelines.md

Deprecation guidelines mention that contributors should add a console warning for deprecated tags.
This PR adds a link to guidelines that will help the contributor write a good console message.

[Documentation] Add link to console message guidelines in deprecation guidelines

---

UNRELEASED.md
src/components/TopBar/components/UserMenu/components/UserMenu/UserMenu.tsx

[This PR](https://github.com/Shopify/polaris-react/pull/1006) merged an unsupported `React.Fragment` syntax _(`<>...</>`)_, which resulted in build container failures for my app.
All I have done here is convert to the supported `<React.Fragment>` syntax.

Resolve unsupported React Fragment syntax

---

CHANGELOG.md
UNRELEASED.md

- Used `base-tight` `spacing` value instead of `rem(12px)` ([#1044](https://github.com/Shopify/polaris-react/pull/1044))
- Fixed the `focused` prop on `TextField` so it sets the focus state ([#990](https://github.com/Shopify/polaris-react/pull/990))
- Resolved an unsupported `React.Fragment` syntax ([#1080](https://github.com/Shopify/polaris-react/pull/1080))
- Constrained `DropZone` height based on inherited wrapper height [#908](https://github.com/Shopify/polaris-react/pull/908)
- Reverted a change that adjusted padding in the `Card` component introduced in ([#962](https://github.com/Shopify/polaris-react/pull/962))

prepare 3.9.0 release

---

UNRELEASED.md
src/components/Loading/README.md

Adds accessibility guidance for the loading component, to appear in `polaris-react` docs and in the style guide.
[See the draft Google doc for editing history for these changes and updates for other components and pages.](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.w5x5ph7nfna7)
1. View changes after examples and props: https://polaris.myshopify.io/components/feedback-indicators/loading
Web content:

Loading a11y docs

---

UNRELEASED.md
src/components/Button/README.md

Fixes documentation of the `ariaPressed` prop to remove reference to an unmerged change (#984).
- Updates the button `README.md`.
- Adds an entry to `UNRELEASED.md`.

Fix for ariaPressed documentation

---

UNRELEASED.md
src/components/AppProvider/utilities/Intl/translate.ts

Replacing lodash replace with native string replace
Test pass? 💯 

Remove lodash replace

---

UNRELEASED.md
examples/create-react-app/package.json
examples/create-react-app/yarn.lock

We shouldn't import packages that aren't dependencies. Lodash isn't a dep. https://github.com/Shopify/polaris-react/blob/master/examples/create-react-app/package.json
Part of #991
Adding lodash
Run the example 👍

Add lodash to CRA example

---

UNRELEASED.md
src/components/Autocomplete/README.md

Few README examples in autocomplete component use label of selected options as selected state in `onSelect` callbacks.
This causes selected options not to be highlighted and developers wondering what `selected` prop does in Autocomplete component.
Update `selected` state with selected props received from `onSelect` callback so selected options are highlighted.

[Autocomplete] Fix incorrect selected state in examples

---

UNRELEASED.md
src/components/Page/README.md
src/components/PageActions/README.md
src/components/Pagination/README.md

Resolves https://github.com/Shopify/polaris-react-deprecated/issues/602
Add cross references to the "Related components" section for the following components: 
- Page
- Page actions
- Pagination
**Page** 
**Page actions component**
**Pagination component**
I'm not 💯 on the context on use-case for each of these components, so please let me know if the content needs adjustment. 
Also, does a minor addition like this warrant a changelog entry?

[Page][Page actions][Pagination] Add cross references for page-related components 

---

src/components/RangeSlider/components/SingleThumb/SingleThumb.scss

Follow-up to https://github.com/Shopify/polaris-react/pull/1044
Uses new polaris-tokens `spacing(base-tight)` instead of `rem(12px)`.

[Range slider] Use spacing base-tight

---

UNRELEASED.md
src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
src/components/AppProvider/utilities/createAppProviderContext/tests/createAppProviderContext.test.tsx
src/configure.ts

Resolves #1104
Providing an internal method to reference Polaris version.
Run an embedded app using Polaris, compiled using sewing kit [in production mode](https://github.com/Shopify/sewing_kit#how-can-i-test-a-production-verison-of-my-changes). Should be no errors when dispatching App Bridge actions (ie opening a modal, resource picker, etc).
Additionally, `APP::` prefixed actions in the Redux inspector should have an actual version number for `clientInterface.version`, not `'{{POLARIS_VERSION}}'`.
I'm working on getting a repo case up and running.

Provide an internal reference to Polaris version that is compile-safe

---

UNRELEASED.md
src/components/Card/Card.scss

Resolves https://github.com/Shopify/polaris-react/issues/954
The first fix was here: https://github.com/Shopify/polaris-react/pull/962 but it created too much spacing with non-subdued sections and the header. This fix targets only the subdued sections.
Add spacing and a border between header and subdued section & footer and subdued section.
<details>
```jsx …
```

[Card] Fix subdued section spacing issues

---

UNRELEASED.md
src/components/Modal/Modal.tsx
src/components/Modal/README.md

Resolves https://github.com/Shopify/polaris-react/issues/1116
When using **Scrollable** within **Modal**, and dynamically rendering its content, the **Scrollable** `onScrolledToBottom` handler isn't triggered.
See [example](https://codesandbox.io/s/n31x1mn0q4?fontsize=14) of that issue
The **Modal**'s **Scrollable** `onScrolledToBottom` prop is brought up to **Modal** as a new prop.
The advantage is if content is scrollable, this new prop can handle callbacks without having to directly add the **Scrollable** component.  Useful for **infinite scrolling** features, for example.
Load the following playground code, you should be able to scroll to the bottom and see an alert pop-up.
<details>
```jsx
import * as …
```

[Modal] Add onScrolledToBottom prop to Modal

---

UNRELEASED.md
src/components/Stack/Stack.scss

Resolves https://github.com/Shopify/polaris-react/issues/947
When using a vertical `Stack` the contents appear to break out of the container and "bleed" into surrounding padding when one of the children starts to wrap.
Removes negative left margin from stack and left margin from item when vertical.
🤓 *1024 - the gigabyte PR*
<details>
```jsx
import * as React …
```

[Stack] Remove margin from vertical

---

UNRELEASED.md
src/components/AppProvider/utilities/Intl/Intl.ts
src/components/AppProvider/utilities/Intl/translate.ts
src/test-utilities/enzyme.tsx
src/types.ts
src/utilities/get.ts
src/utilities/tests/get.test.ts

Creating a `get` function and using that instead of `_.get`
Test pass? 💯 

Remove lodash get

---

UNRELEASED.md
src/components/SkeletonThumbnail/SkeletonThumbnail.scss
src/components/Thumbnail/Thumbnail.scss
src/styles/shared/skeleton.scss

Fixes #1135
<details>
```jsx
import {Page, Card, Stack, Thumbnail, SkeletonThumbnail} from '../src';
loading: boolean;
}
state: State = {
loading: true,
};
toggleLoadingState = () => {
this.setState(({loading}) => ({loading: !loading}));
}; …
```

[SkeletonThumbnail] Align sizes with Thumbnail

---

UNRELEASED.md
src/components/Checkbox/README.md
src/components/ChoiceList/README.md
src/components/RadioButton/README.md

Adds accessibility guidance for the checkbox, radio button, and choice list components, to appear in `polaris-react` docs and in the style guide. The choice list documentation points readers to the other components.
* https://polaris.myshopify.io/components/forms/choice-list (web, iOS, and Android)
* https://polaris.myshopify.io/components/forms/checkbox (web, iOS, and Android)
* …

[a11y] Docs for checkbox, radio button, and choice list

---

UNRELEASED.md
src/components/TextField/components/Resizer/Resizer.tsx
src/components/TextField/components/Resizer/tests/Resizer.test.tsx

The `TextField` component sizes itself incorrectly due to the way it handles some whitespace characters. 
For example, here’s some text that a user submitted in a Rails app. Notice how the text includes carriage returns (`\r`):
This is how the content gets rendered in a multiline `TextField`:
If we take out all the carriage returns, the exact same piece of text renders like this:
The extra height visible seems to stem from two factors: 
1. [This CSS property](https://github.com/Shopify/polaris-react/blob/master/src/components/TextField/TextField.scss#L207):
```
white-space: pre-wrap;
```
2. [This code](https://github.com/Shopify/polaris-react/blob/master/src/components/TextField/components/Resizer/Resizer.tsx#L93) in the `Resizer` component:
``` js
const ENTITIES_TO_REPLACE = {
'&': …
```

[TextField] [Resizer] Stop replacing newline with line break tag 

---

UNRELEASED.md
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx

Minimizes impact of re-rendering navigation if the badge relies on a query to resolve. More detail here: https://github.com/Shopify/web/issues/10481
Allows the nav items badge property to take a react node prop value.
<details>
```tsx
import {Page, Navigation, Badge} from '../src';
export default class Playground extends React.Component<{}, never> {
render() {
return (
<Navigation location="/">
<Navigation.Section
items={[
{
url: '/path/to/place',
label: 'Orders',
icon: 'orders',
badge: <Badge>Hello world</Badge>,
},
]}
/>
</Navigation>
</Page>
);
}
}
```
</details>

[Navigation] badge accepts react element

---

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/ISSUE.md
.github/ISSUE_TEMPLATE/NEW_COMPONENT.md

Pre-filling these labels will help triage and find new issues:
- Feature requests: https://github.com/Shopify/polaris-react/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Feature+request%22
- New components: https://github.com/Shopify/polaris-react/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22New+component%22
- Bugs: https://github.com/Shopify/polaris-react/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Bug%22+
This PR doesn't apply any labels to the ["ISSUE" template](https://github.com/Shopify/polaris-react/blob/master/.github/ISSUE_TEMPLATE/ISSUE.md), as it could be a bug, but also something else. Thoughts on that?

Pre-fill labels for new issues opened using GitHub issue templates

---

UNRELEASED.md
src/components/Collapsible/Collapsible.tsx

While pairing with @alex-page we noticed this context is not being used and removed it.
Removing the context 🔥 
Collapsible exaple
<details>
```jsx
import {Collapsible, Stack, TextContainer, Button, Card} from '../src';
export default class CollapsibleExample extends React.Component {
state = {
open: false,
};
render() {
const {open} = this.state;
return (
<div style={{height: '200px'}}>
<Card sectioned>
<Stack vertical>
<Button onClick={this.handleToggleClick} ariaExpanded={open}>
Toggle
</Button>
<Collapsible open={open} id="basic-collapsible">
<TextContainer>
Your mailing list lets you contact customers or visitors who
have shown an interest in your …
```

[Collapsible] Remove context

---

UNRELEASED.md
src/components/Frame/components/Toast/Toast.scss
src/components/Frame/components/Toast/Toast.tsx
src/components/Frame/components/Toast/index.ts
src/components/Frame/components/Toast/tests/Toast.test.tsx
src/components/Frame/components/index.ts
src/components/Frame/index.ts
src/components/Frame/types.ts
src/components/Toast/README.md
src/components/index.ts
src/locales/en.json

Resolves #553
As highlight on this comment https://github.com/Shopify/polaris-react/issues/553#issuecomment-436714929, there are some use cases for the action inside `Toast` in `online-store-web` project. 
Adds the action prop to `Toast`, shows a `<Button />` when `action` is defined. Follows designs from #553. Adds clarification in the docs about how to use it. As far as app-bridge, for now, there will be no action.
<details>
```jsx
import {Page, Frame, Toast, Button, Pagination, Key} from '../src';
showToast: boolean;
}
state = {
showToast: false,
};
toggleToast = () => { …
```

[Toast] Add `action` prop

---

UNRELEASED.md
package.json
src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
src/components/AppProvider/utilities/createAppProviderContext/tests/createAppProviderContext.test.tsx
yarn.lock

Resolves https://github.com/Shopify/polaris-react/issues/824 https://github.com/Shopify/app-bridge/issues/722
**Polaris** `Page` component renders content differently on the server vs client side because **App Bridge** is set to `undefined` when `window` is not available.
Always call `createApp` and allow **App Bridge** to return a noop version of App Bridge when `window` is unavailable.
1. Check out `shopify` and run test branch `app-bridge/test/ss-app`: `dev up; dev server`
*This will make the sample server side app available to your local shop*
1. Check out and run Hanna's **Test Polaris App Bridge Embedded App**: https://github.com/hannachen/nextjs-app-test
1. Once the app is installed to your shop, it will initially render the correct UI (server side), but mangled once **App Bridge** …

[AppProvider]: Fix server side rendering for embedded apps

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Resolves #1118 
- Add a condition to not render the spinner buttons on TextField when readOnly is 'true' and type is 'number'
- Add a test to confirm the spinner buttons are not rendering when type='number' and readOnly is 'true'

[TextField] Fix the spinner buttons behaviour when readOnly

---

UNRELEASED.md
src/components/EmptyState/EmptyState.scss
src/components/EmptyState/EmptyState.tsx
src/components/EmptyState/README.md
src/components/EmptyState/tests/EmptyState.test.tsx

This change will make the empty state more flexible to what it’s capable of. In the following proposed design from marketing section, the empty state suggests to configure the store before using the section, however, it still allows merchants to create a new campaign if they wanted:
Added `footer` prop that receives `ReactNode` similar to `children`.
I’m open to other prop name suggestions 🙌 
Options considered:
- `helpText`
- `suggestion` …

[Empty State] Add footer prop

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

Resolves #936
Sets selectMode when selected items exists in state
Run the example or create your own, the linked issue has more details on the issue 😄 
<details>
```jsx
import {Avatar, Card, Label, List, ResourceList, Select, TextStyle} from '@shopify/polaris';
state = {
};
this.setState({selectedItems: [256]})
}
};
return (
id={id} …
```

[ResourceList] Fix selectMode when programmatically setting selectedItems

---

UNRELEASED.md
src/components/AppProvider/utilities/Intl/Intl.ts
src/components/AppProvider/utilities/withAppProvider/withAppProvider.tsx
src/components/AppProvider/utilities/withSticky/withSticky.tsx
src/test-utilities/enzyme.tsx
src/utilities/merge.ts
src/utilities/tests/merge.test.ts

Creating a less featureful `merge` function and using that instead of `_.merge`
Test pass? 💯 

Remove lodash merge

---

UNRELEASED.md
src/components/TopBar/TopBar.scss

Fixes part of https://github.com/Shopify/web/issues/11622 (internal link)
Makes the `contextControl` wrapper bigger on wider screens.
<details>
<summary>1. Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>
```jsx
import {ActionList, AppProvider, Card, ContextualSaveBar, DisplayText, Form, FormLayout, Frame, Label, Layout, List, Loading, Modal, Navigation, Page, TextContainer, TextField, Toast, TopBar, SkeletonPage, SkeletonBodyText, SkeletonDisplayText} from '@shopify/polaris';
export default class FrameExample extends React.Component {
defaultState = {
emailFieldValue: 'dharma@jadedpixel.com',
nameFieldValue: 'Jaded Pixel',
};
state = {
showToast: false,
isLoading: false,
isDirty: false,
searchActive: false,
searchText: '',
userMenuOpen: …
```

Makes context control wrapper bigger on wider screens

---

UNRELEASED.md
src/components/Banner/Banner.tsx
src/components/Banner/README.md
src/components/Banner/tests/Banner.test.tsx

There are use cases in web where banner's need to be focused
Adding a function so Banner can focus itself
<details>
```jsx
import {react} from 'babel-types';
import {Page, Banner, Button} from '../src';
node = React.createRef();
render() {
return (
<Banner title="Order archived" onDismiss={() => {}} ref={this.node}>
<p>This order was archived on March 7, 2017 at 3:12pm EDT.</p>
</Banner>
<Button onClick={() => this.node.current && this.node.current.focus()}>
Mr.Focus
</Button>
</Page>
);
}
}
```
</details>

[Banner] Add focus method

---

UNRELEASED.md
src/components/Checkbox/Checkbox.scss
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/tests/Checkbox.test.tsx
src/components/Choice/Choice.tsx
src/components/Choice/tests/Choice.test.tsx
src/components/ChoiceList/tests/ChoiceList.test.tsx

`Checkbox` can lose focus or not receive events.
https://cl.ly/44715b1c9430
https://cl.ly/4ca13de5131c
* Removing pointer events on adjacent elements to precent blocking and bubbling
* Switch from functional to class components. We can utilize on shallow prop comparison with `PureComponent` and removes the need for scoped functions
* Focus input after every change
* Use event delegation with onClick / onKeyUp handlers
* Use a no-op for onChange (input element)
Is this a good approach? Are there good alternatives?
Load up the playground and test checkboxes on multiple browsers and devices 😄 
* Fast clicks
* Slow clicks
* Modified clicks (e.g shift)
* Clicks with focus and without focus
* Keyboard interactions
cc/ @dpersing How does this look to you in terms of accessibility? Previously the …

[Checkbox] Fix focus and problem with events not firing

---

UNRELEASED.md
src/components/ResourceList/components/BulkActions/BulkActions.tsx
src/locales/en.json

The translation for the Cancel button on the resource list bulkActions were missing so I'm adding it.
<details>
```jsx
import {
Avatar,
Card,
Label,
List,
ResourceList,
Select,
TextStyle,
state = {
selectedItems: ['341'],
};
};
return (
id={id}
url={url}
media={media}
accessibilityLabel={`View details for ${name}`}
>
<h3>
<TextStyle …
```

[ResourceList] - Adding bulk action cancel button translation

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Fixes #1244  This will allow the autoComplete prop of TextField to accept a string and set the autocomplete value of the html input to a string. This is because Chrome is known to ignore autocomplete=off, but setting autocomplete=fieldname seems to disable wrongful autocompletion by chrome. 
For background on how chrome ignores autocomplete=off when it comes to autofill: https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill
Longer term if would be good to directly support autofill, but this is an urgent quick fix in the meantime.
cc: @axelerator @Senjai 
Allows autoComplete prop to accept string value and set the value of html input autocomplete to that string (while keeping origin behavior when true, false, or null are given as prop value) …

[TextField] Allow autoComplete prop of TextField to accept string values

---

UNRELEASED.md
src/components/Popover/README.md
src/components/Popover/components/Pane/Pane.tsx
src/components/Popover/components/Pane/tests/Pane.test.tsx

Part one of two for fixing #1246 
Adds an `onScrolledToBottom` prop to the `Popover.Pane` that gets set on the pane's `Scrollable`.
<details>
```jsx
state = {
visibleStaffIndex: 5,
active: false,
};
staff = [
'Abbey Mayert',
'Abbi Senger',
'Abdul Goodwin',
'Abdullah Borer',
'Abe Nader',
'Abigayle Smith',
'Abner Torphy',
'Abraham Towne',
'Abraham Vik',
'Ada …
```

[Popover] add support for lazy loading

---

UNRELEASED.md
src/components/ResourceList/components/FilterControl/FilterControl.tsx
src/components/ResourceList/components/FilterControl/tests/FilterControl.test.tsx

Fixes #1256 
Currently the `FilterControl` component will use the `resourceName.plural` as the placeholder to the `TextField`. This PR adds a `placeholder` prop to `FilterControl` to allow users to have a custom placeholder.
I added an optional `placeholder` prop to the `FilterControl` component. If passed the `placeholder` on the `TextField` will use the value provided, if not passed it will default to the `resourceName.plural` value.
I also removed a `,` from the `mockDefaultContext` plural string, as it seemed unused. Correct me if i am wrong!
I didn't test accessibility since it is passing a string to the `TextField` so I don't think that is required? …

[FilterControl] Adds placeholder prop

---

UNRELEASED.md
src/components/ButtonGroup/README.md

Fixes https://github.com/Shopify/polaris-styleguide/issues/2676
Button group example pinned to a component is confusing.
Removes `Button group joined to the bottom of a proceeding component` example.
**To view changes in the stylguide:**
`dev cd polaris-react`
`git checkout button-group-example`
`yarn run build-consumer polaris-styleguide`
in a new tab
`dev cd polaris-styleguide`
`yarn run build:development`
`dev server`

Remove button group example

---

CHANGELOG.md
UNRELEASED.md

[Release][v3.12.0] Prep CHANGELOG

---

UNRELEASED.md
src/components/Scrollable/Scrollable.tsx

Currently the Scrollable is trying to pass the `polaris` context object into a div in the Scrollable component. That seems somewhat silly, lets not do that.
You can see this in action by visiting https://polaris-react.herokuapp.com/?selectedKind=All%20Components%7CScrollable&selectedStory=Default%20scrollable%20container&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel then running `document.querySelector('[class^="Scrollable-Scrollable"]')` in your console and seeing that it has an attribute `polaris="[object Object]"`
This PR plucks the polaris context out of the list of properties that get passed into the `div`.
Follow the above steps in your local storybook and see that the `polaris="[object Object]"` attribute is removed

Dont pass "polaris" context as a prop to the div within Scrollable

---

UNRELEASED.md
src/components/Modal/components/Header/Header.scss

Modal header titles css look like this:
```scss
.Title {
flex: 1;
margin-top: spacing(extra-tight);
word-break: break-word;
@include breakpoint-after($typography-condensed) {
margin-top: rem(4px);
}
}
```
Both `spacing(extra-tight)` and `rem(4px)` resolve to 0.4rem, which means that mixin is pointless.
Removes that media query.
Look at the modal dialog in storybook and assert that the title does not change position.

Remove redundant styling from Modal Header

---

UNRELEASED.md
src/components/DataTable/DataTable.scss

Fixes #1230
When a `DataTable` column is sortable, hovering over the column header with your mouse changes the colour and reveals the sorting icon, indicating that it is clickable.
However, the area where it is actually clickable is smaller than the area where the hover styles are applied, making the user think they can click to sort when they can't.
In this GIF I'm clicking, it has no effect until it's right on the text label:
Remove padding from the surrounding `Cell` and add it to the `button` when the column is sortable, to expand the clickable area to the whole cell. The button CSS seems to already have the hover styles that now apply to the whole area.
The whole cell area is now clickable:
🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README. …

[DataTable] Fix sortable header clickable area

---

UNRELEASED.md
src/components/Tabs/Tabs.tsx
src/components/Tabs/tests/Tabs.test.tsx

Removes a deprecated lifecycle method
* Makes use of `getDerivedStateFromProps`
* Doesn't close the disclosure everytime props are changed
* Doesn't removed focus outline when a tab is selected from the disclosure
Checkout the tabs examples  at different screen sizes

[Tabs] Remove componentWillReceiveProps

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

Removes deprecated lifecycle method
* Moves logic to componentDidUpdate
* Add update to test
Test out examples and playground code 🎉 
<details>
```jsx
import {Avatar, Card, Label, List, ResourceList, Select, TextStyle} from '@shopify/polaris';
state = {
};
this.setState({selectedItems: [256]})
}
};
return (
id={id}
url={url}
media={media} …
```

[ResourceList] Remove deprecated lifecycle method

---

UNRELEASED.md
package.json
yarn.lock

Until the most recent release, Polaris React didn’t have access to the full Polaris icon set. One of the newer icons is required for #1247.
Updates Shopify/polaris-icons to 3.3.0
Percy should catch any issues, but please spot check in Storybook for any broken or missing icons.
* [N/A] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [N/A] Tested on [multiple …

Update polaris-icons to include the full icon set

---

README.md

This repo gets a number of questions/issues about App Bridge. By redirecting support requests to the API & SDK forum we hope to (a) reduce support load on the Polaris team, and (b) give partners a better support experience. See also [this PR](https://github.com/Shopify/help/pull/6856) in our help docs.
Adds a paragraph to README

Add support note about App Bridge to README

---

.storybook/preview-head.html

We keep getting false positives in percy because dynamic values change between renderings
Uses Percy's media query (see https://docs.percy.io/docs/percy-specific-css) to fix the rendering of elements only when rendered by percy

Stop false positives in percy

---

UNRELEASED.md
src/components/Link/Link.scss
src/components/Link/Link.tsx
src/components/Link/README.md
src/components/Link/tests/Link.test.tsx
src/locales/en.json

Fixes Shopify/polaris-ux#146 
This PR takes the position that we should automatically do the right thing for accessibility whenever possible. It automatically adds screen reader text and an icon when the `external` prop is `true`.
Unfortunately, implementation is complicated by CSS things, historical things, and international things (see comments below).
**I’m looking for comments on this approach before going any further.**
- The icon will be blank when tophatting—we’re waiting on the correct icon to be available (should be in the next release of Polaris Icons).
- Change the viewport width to make sure the icon wraps with the last word in the link, never on its own.
🗒 [General …

[Link] Warn users when links open in a new window

---

UNRELEASED.md
src/components/Banner/Banner.tsx
src/components/CalloutCard/CalloutCard.tsx
src/components/DataTable/components/Navigation/Navigation.tsx
src/components/DatePicker/DatePicker.tsx
src/components/Page/components/Header/Header.tsx
src/components/ResourceList/components/Item/Item.tsx

Following up on #1196. We are looking at deprecating the concept of bundled icons in the future so lets get our house in order first.
Changes cases where we pass a string into `<Button icon>` into passing in a component from polaris-icons.
E.g.
Old:
```jsx
<Button icon="cancelSmall">
```
New: 
```jsx
import {CancelSmallMinor} from '@shopify/polaris-icons';
//...
<Button icon={CancelSmallMinor}>
```
Check Banner, Calloutcard, Navigation, DatePicker, PageHeader and ResourceList in storybook and see that the icons still render the same

Pass icons into Button instead of using strings

---

UNRELEASED.md
src/components/Navigation/README.md
src/components/Navigation/components/Item/Item.tsx

https://github.com/Shopify/polaris-react/pull/1042 deprecated Icon's `untrusted` prop and made it so that passing a string into `<Icon>` would render an untrusted icon - i.e. rendering it as an img with a data URI instead of an inline svg.
Since that point passing an `icon` and and `iconBody` into Navigation's `<Item>` are functionally identical. Having two ways to do the same thing seems silly, so remove `iconBody` and tell people to pass a string into `icon` instead.
Deprecates the iconBody prop. Tweak the logic slightly to remove a conditional that did almost the same thing on both paths.
/cc @theodoretan and @danrosenthal as people who have looked at icon and iconBody before
Checkout the following playground example, and see that passing an icon and iconBody to navigation items still …

Deprecate passing iconBody into Navigation Items

---

.shopify-build/polaris-react.yml

This step has been broken ever since web broke up its build process and increased memory usage. I've tried to fix it but there doesn't seem to be an easy solution besides making web use less memory. This being broken reduces trust in the consumer build test so I believe we should disable it.
See title

Disable web build step in consumer build test

---

UNRELEASED.md
src/components/Banner/Banner.scss
src/components/Labelled/Labelled.scss
src/components/Modal/components/Header/Header.scss

Was cruisin' through the codes and noticed some missed opportunities to use a `typography mixin`.
All I have done is consistently employ the `text-breakword` mixin.

[Code Quality] Consistent use of `text-breakword` mixin

---

UNRELEASED.md
package.json
src/components/Frame/Frame.scss
src/components/Frame/Frame.tsx
src/components/Modal/components/Dialog/Dialog.tsx
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/ResourceList/components/BulkActions/BulkActions.tsx
src/components/shared.ts
src/styles/foundation/duration.scss
yarn.lock

> We have recently added all Polaris `duration` values to the `polaris-tokens` repo and just cut a new `2.5.0` release! [Read more here](https://github.com/Shopify/polaris-tokens/releases/tag/v2.5.0).
The goal of this PR is to consume the newest `polaris-tokens` release and make sure all `duration` references in `polaris-react` are updated and consistent. This PR would resolve: https://github.com/Shopify/polaris-react/issues/1258
We have upgraded from `2.3.0` to `2.5.0`. The `2.4.0` release appears to be just an enhancement - but perhaps @tmlayton can speak more about that release?
**This PR accomplishes the following:**
@kaelig both `spacing` and `color` export 2 different SCSS maps... and Polaris seems to prefer the `spacing.spacing-map.scss` version. Did we accidentally omit this from …

Upgrade to polaris-tokens 2.5.0

---

UNRELEASED-V4.md
src/components/AppProvider/AppProvider.tsx
src/components/AppProvider/tests/AppProvider.test.tsx

Remove deprecated lifecycle methods. This is in preparation for using the new context api.
Storing context on state, getChildContext will be ran every time state changes and making use of componentDidUpdate.
* storybook has some good examples 👍

[AppProvider] Remove componentWillReceiveProps

---

.github/changelog.yml
UNRELEASED.md

New label broke the changelog bot.
Changing the label name

Fix changelog skip failing with new label

---

UNRELEASED.md
package.json
src/components/DropZone/utils/index.ts
yarn.lock

I noticed we're only using `core-js` in one location. [Some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#Browser_compatibility) and [endsWith](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith#Browser_compatibility) appear to have great support and are already used elsewhere in our code base without polyfills
https://github.com/Shopify/polaris-react/blob/d0e6ca5ce82ff6e90d901d617ad9c182cce92c91/src/components/Navigation/components/Item/Item.tsx#L349 
https://github.com/Shopify/polaris-react/blob/9b83385263571a272a6c15dadc92acbf2cc16981/src/components/Navigation/components/Section/Section.tsx#L125
https://github.com/Shopify/polaris-react/blob/d0e6ca5ce82ff6e90d901d617ad9c182cce92c91/src/components …

Remove core-js

---

UNRELEASED.md
src/components/Labelled/Labelled.scss
src/components/Labelled/Labelled.tsx

In our app, we use forms in a `width` restricted space _(max width of around `260px`)_. When using a form that uses `Labelled` under the hood, and renders both a `label` + `action`, we can get some very ugly squished unwrapping content. Now that we are utilizing more translations in our app, this "ugly squishy" problem is more and more prevalent.
All this PR does is allow `Labelled` to use `flex-wrap: wrap;`, and then wraps the `action` in a `div` so I can apply `flex: 0 0 auto;`.

[Labelled] Contents can now wrap onto multiple lines

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

Fixes #1252 
* Applying the logic to display `EmptySeachResult` to header markup
* Add a test
https://cl.ly/64ba392ef321
* Playground provided below
* Can test against discount index in web
<details>
```jsx
import React from "react";
import { Avatar, Card, ResourceList, TextStyle } from "@shopify/polaris";
constructor(props) {
super(props);
this.state = {
searchValue: "",
items: []
};
}
handleSearchChange = searchValue => {
this.setState({ searchValue });
};
setTimeout(() => {
this.setState({
items: [
{
id: 341,
url: "customers/341",
name: "Mae Jemison",
location: "Decatur, USA"
},
{
id: 256,
url: "customers/256",
name: …
```

[ResourceList] Hide header when EmptySearchResult is displayed

---

UNRELEASED-V4.md
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx

Remove deprecated lifecycle methods. This is in preparation for using the new context api.
Storing context on state, getChildContext will be ran every time state changes and making use of componentDidUpdate.
* try out theming examples
* https://github.com/Shopify/polaris-react-deprecated/pull/1947 has quite a few playgrounds from when the theme provider was originally added
</details>

[ThemeProvider] Remove componentWillReceiveProps

---

UNRELEASED.md
src/components/TextField/components/Resizer/Resizer.tsx
src/components/TextField/components/Resizer/tests/Resizer.test.tsx

Improve performance of `Resizer` to avoid forced synchronous layout.
Schedule `handleHeightCheck` to run in next animation frame
> As the JavaScript runs all the old layout values from the previous frame are known and available for you to query.
https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing
<details> …

[Resizer] Improve performance by reading offsetHeight from previous frame

---

UNRELEASED.md
src/components/ResourceList/components/Item/Item.scss

In #1312 @dleroux noticed some issues with how our actions are handled and checkboxes appearing when they shouldn't
I believe the below behaviour was our original intention. A confirmation from @ry5n or @dleroux would be great 😄 
- **Show** persistent actions
- **Show** actions on hover and keyboard interaction
- *Select mode*
- **Show** persistent actions
- **Show** actions on hover and keyboard interaction
- **Show** persistent actions in disclosure
- **Do NOT show** actions on hover or keyboard interaction 
- *Select mode*
- **Do NOT show** actions at all
- **Show** persistent actions in disclosure
- **Do NOT show** actions on hover or keyboard interaction 
- *Select mode*
-  **Do NOT show** actions at all
Play with `ResourceList` items with a mix of small screen / partially condensed …

[ResourceList] Fix checkbox / action visibility on different breakpoints / select mode

---

UNRELEASED.md
src/components/DropZone/DropZone.tsx

These changes capitalize on the enhancements made for refs in >React 16.3.
Resolves https://github.com/Shopify/polaris-react/issues/910
The refs to the DOM nodes are now initialized using createRef(). These refs are linked to the respective DOM elements in the render method, through the ref prop. The refs are now accessed using _this.refname.current_. There are no visible UI changes.

[DropZone] Use createRef() API 

---

UNRELEASED.md
src/styles/shared/breakpoints.scss

We can currently use the `page-when-not-max-width` mixin to break pages as soon as they being to resize, but this is not applicable for layouts that use a frame with the nav section. For these cases we need to also take the nav width in account for the breaking width.
This PR adds a new breakpoint variable `$frame-with-nav-max-width` as well as a new mixin to break before that defined width `frame-with-nav-when-not-max-width()`. 
* ~[ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)~
* ~[ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)~
* ~[ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibil …

add breakpoint mixin for frame with nav max width

---

src/styles/foundation.scss
src/styles/foundation/settings.scss

top-bar-height() is already defined in [src/styles/foundation/layout.scss](https://github.com/Shopify/polaris-react/blob/47fce710baa99adbd7ab85221d83f2a71d8c5386/src/styles/foundation/layout.scss#L58-L60).
I'm kinda suprised that sass lets you redefine functions like that but 🤷‍♂️ 
Fixes #1296
🔥

Remove duplicate declaration of top-bar-height()

---

UNRELEASED.md
package.json
yarn.lock

This drops an unused runtime dependency on core-js

Bump react-utilities

---

CHANGELOG.md
UNRELEASED.md
src/components/DatePicker/DatePicker.scss

Fixes https://github.com/Shopify/polaris-ux/issues/150
The selected date doesn't display in windows high contrast mode.
Use the Windows high contrast media query to display background color for selected states.
<details>
```jsx
import {Page, DatePicker} from '../src';
export default class Playground extends …
```

[a11y] Make selected state work in windows high contrast mode

---

UNRELEASED.md
src/components/Heading/README.md
src/components/Subheading/README.md

Adds accessibility guidance for the heading and subheading components, to appear in `polaris-react` docs and in the style guide.
- https://polaris.myshopify.io/components/titles-and-text/heading (web, iOS, and Android)
- …

[a11y] Added doc updates for the heading and subheading components

---

UNRELEASED.md
src/components/TextStyle/README.md

Adds accessibility guidance for the text style component, to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/titles-and-text/text-style (web, iOS, and Android)

[a11y] Added an accessibility section to the text style component docs

---

UNRELEASED.md
src/components/VisuallyHidden/README.md

Adds accessibility guidance for the visually hidden components, to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/titles-and-text/visually-hidden

[a11y] Added a11y docs to the visually hidden component

---

UNRELEASED.md
src/components/DisplayText/README.md

Adds accessibility information for the display text component, to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/titles-and-text/display-text (web, Android, iOS)

[a11y] Add accessibility guidance for display text

---

UNRELEASED.md
src/components/List/README.md
src/components/Stack/README.md

Adds accessibility information for the list and stack components, to appear in `polaris-react` docs and in the style guide.
- https://polaris.myshopify.io/components/lists-and-tables/list (web, Android, iOS)
- …

Added a11y docs for list and stack

---

UNRELEASED.md
src/components/Link/README.md

Updated to reflect accessibility behavior changes in the `external` prop introduced in 3.13.0 in PR #1247.
- Updates the `README.md` for the link component
- Updates `UNRELEASED.md`
Here's what it looks like in the style guide:

[a11y] Updated accessibility documentation for the external prop

---

UNRELEASED.md
package.json
yarn.lock

Fixes https://github.com/Shopify/polaris-react/issues/998
Fixes https://github.com/Shopify/polaris-react/issues/1028
Allows apps to subscribe to redirect actions and handle its own redirects. This allows single page apps using its own routing (ex. React Router) to navigate without reloading the app.
**Before (iframe is reloaded)**
**After (iframe is not reloaded)**
The following is an example of a component utilizing the App Bridge context from Polaris to subscribe to redirects and add its own handler.
```js
import { RouterProps } from 'react-router';
export default class Section extends React.Component {
static contextTypes = {
polaris: PropTypes.object,
};
cleanup = () => {};
const {
polaris: { appBridge },
} = this.context;
this.cleanup = …
```

App Bridge: Update to v1.3.0

---

UNRELEASED.md
src/components/ResourceList/components/Item/Item.tsx

ResourceList is incredibly slow when selecting items
* Moving selected to an internal state on item
* Implementing a custom `shouldComponentUpdate`
* Check out storybook examples
* Use keyboard / mouse to interact
* Build to web and see some major 📈 perf improvements 
* Should ship with and is currently being used as a base for #1312

[ResourceList] Improve performance 

---

UNRELEASED.md
src/components/Badge/README.md

Adds accessibility guidance for the badge component, to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: /components/images-and-icons/badge (web, iOS, and Android)

[a11y] Add documentation for the badge component

---

UNRELEASED.md
src/components/CalloutCard/README.md
src/components/Card/README.md

Adds accessibility documentation and guidance for the card and callout card components, to appear in `polaris-react` docs and in the style guide.
- …

[a11y] Add docs for card and callout card components

---

UNRELEASED.md
src/components/ActionList/README.md
src/components/OptionList/README.md

Adds accessibility documentation and guidance for the action list and option list components, to appear in `polaris-react` docs and in the style guide.
- …

[a11y] Add action and option list accessibility docs

---

UNRELEASED.md

Fix a typo in the log. The version of App Bridge should be v1.3.0

Fix typo with App Bridge version in UNRELEASED log

---

UNRELEASED.md
src/components/ResourceList/components/Item/tests/Item.test.tsx

[ResourceList.Item] Remove test error

---

UNRELEASED.md
src/components/DropZone/components/FileUpload/FileUpload.tsx
src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx

* Removes outdated lifecycle method
* fixes a bug that keep default action title / hint when removed
Taking advantage of `getDerivedStateFromProps` and adding additional logic to handle the bug fix
Is my logic 🔉 ? Try examples and playground code (on master) - see how after the original default hint and title are shown, they won't show again after you set a hint / title. Even when removed.
<details>
```jsx
import {
Page,
TopBar,
Layout,
SettingToggle,
ContextualSaveBar,
TextStyle,
Frame,
AppProvider,
DropZone,
Button,
export default class ProviderThemeExample extends React.Component {
actionTitle = 'Action Title';
actionHint = 'Action …
```

[FileUpload] Remove outdated lifecycle methods and fix issue with stale state

---

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/ISSUE.md
.github/ISSUE_TEMPLATE/NEW_COMPONENT.md

Let's use headings level 2 for the first heading in issue templates so when displayed on GitHub (the issue's name already is a h1), the heading layout makes sense (one h1, followed by multiple h2s).

Use headings level 2 in issue templates

---

src/components/Spinner/README.md

Fixes a regression introduced in https://github.com/Shopify/polaris-react/pull/1042

[documentation] Fix spinner mobile example

---

src/components/Button/README.md

Fixes a regression introduced in https://github.com/Shopify/polaris-react/pull/821

[documentation] Fix Button mobile examples

---

src/components/DisplayText/README.md

Fixes a regression introduced in #2100
Alternatively, we could add a screenshot for the "Large" example.

[documentation] DisplayText: hide Large example from mobile tabs

---

UNRELEASED.md
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/tests/Checkbox.test.tsx
src/components/Choice/Choice.tsx
src/components/Choice/tests/Choice.test.tsx

Fixes #1363 
* add tests
* won't fire the click event when disabled
* fires onChange when disabled and checked are true
<details>
```jsx
import {Page, Checkbox, Button} from '../src';
export default class CheckboxExample extends React.Component {
state = {
checked: true,
disabled: true,
};
render() {
const {checked, disabled} = this.state;
return (
<div>
<Button onClick={() => this.setState({disabled: !disabled})}>
Click me
</Button>
<Checkbox
checked={checked}
label="Basic checkbox"
onChange={this.handleChange}
disabled={disabled}
/>
</div>
);
}
handleChange = (value) => {
this.setState({checked: value});
};
}
```
</details>

[Checkbox] Fix being clicked while disabled

---

UNRELEASED.md
src/components/Tooltip/Tooltip.scss
src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx

Before:
After:
This addresses an issue where super long unbroken tooltip content is hidden
Fixes: https://github.com/Shopify/core/issues/5822
Three things:
1. Force word-break using `word-break: break-word;`
1. Using min-height vs max-height for wrapped rows of text (Risk: not sure of the implications here)
1. Switch to simpler padding for tooltip content alignment
<details> …

[Tooltip] Allow overflow for non-breaking content

---

.eslintrc
UNRELEASED.md
config/typescript/prop-types.d.ts
package.json
src/components/ActionList/ActionList.tsx
src/components/AppProvider/tests/AppProvider.test.tsx
src/components/AppProvider/utilities/withAppProvider/withAppProvider.tsx
src/components/AppProvider/utilities/withSticky/withSticky.tsx
src/components/ChoiceList/ChoiceList.tsx
src/components/Connected/Connected.tsx
src/components/Icon/Icon.tsx
src/components/Popover/Popover.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/components/Tooltip/Tooltip.tsx
src/components/WithRef/WithRef.tsx
src/utilities/react-compose.tsx
yarn.lock

Consumers can't move past typescript 3.1.6 thanks to us erroring in those versions
Updating to typescript  3.2.4
https://github.com/Shopify/quilt/pull/602 shows how quilt and react-compose were able to compile in TS 3.2, hopefully similar fixes should do the job in our HoCs but my TS-fu isn't up to the task
Thanks to conflicting version dependencies with our linting tools we can't go all the way up to 3.4:
The last release of typescript-eslint-parser is 22.0.0 which only
supports up to TS 3.2.x. We're stuck on this because
eslint-plugin-shopify still uses typescript-eslint-parser and has not
yet moved onto its replacement package @typescript-eslint/parser - which
supports TS 3.2.x and above.
Somehow among all this we now get false positives for violations of the
import/named rule. It's …

Updating to typescript 3.2

---

UNRELEASED.md
src/components/Icon/README.md

Adds accessibility documentation and guidance for the icon component.
1. View changes after examples and props: https://polaris.myshopify.io/components/images-and-icons/icon (web only)

[a11y] Icon accessibility docs

---

UNRELEASED.md
src/styles/global/elements.scss

Due to the [cascade order](https://www.w3.org/TR/CSS21/cascade.html#cascading-order), the browser's User Agent Stylesheet, which defines a style for `button` is overriding the `font-family` value [specified by Polaris](https://github.com/Shopify/polaris-react/blob/master/src/styles/global/elements.scss#L9) on `html, body`. This causes the style not to be inherited as intended for the `button` element. It's why we see different fonts when an `ActionList` contains both `a` and a `button` items.
Fixes https://github.com/Shopify/polaris-react/issues/1340
Adding `button` to the elements targeted by the `font-family` style rule separating out `html, body` so that only `font-family` is applied to all three.
🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/RE …

Applying font-family to button elements

---

UNRELEASED-V4.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/components/Context/Context.tsx
src/components/Autocomplete/components/ComboBox/components/Context/index.ts
src/components/Autocomplete/components/ComboBox/components/TextField/TextField.tsx
src/components/Autocomplete/components/ComboBox/components/index.ts
src/components/Autocomplete/components/types.ts

Part of #1377
Nothing special, using the new context API and updating tests

[AutoComplete] Use new context api

---

UNRELEASED.md
src/components/Banner/README.md
src/components/Navigation/Navigation.tsx
src/components/Navigation/tests/Navigation.test.tsx
src/components/Navigation/types.ts

We are trying to render a banner within the navigation component but it was styled differently than the rest of the navigation items:
After discussing on slack, it was decided that we should add `withinContentContainer` which allows the banner to be rendered as if it belonged in this context.
Adds the `withinContentContainer` context to Navigation
<details> …

[Navigation] Add withinContentContainer context to render Banner in context

---

UNRELEASED-V4.md
src/components/Navigation/Navigation.tsx
src/components/Navigation/components/Context/Context.tsx
src/components/Navigation/components/Context/index.ts
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx
src/components/Navigation/components/Section/Section.tsx
src/components/Navigation/components/Section/tests/Section.test.tsx
src/components/Navigation/components/index.ts
src/components/Navigation/tests/Navigation.test.tsx
src/components/Navigation/types.ts

Part of #1377
Nothing special, using the new context API and updating tests

[Navigation] Use new context api

---

UNRELEASED.md
src/components/Backdrop/Backdrop.scss
src/components/Backdrop/Backdrop.tsx
src/components/Sheet/README.md
src/components/Sheet/Sheet.scss
src/components/Sheet/Sheet.tsx
src/components/Sheet/index.ts
src/components/Sheet/tests/Sheet.test.tsx
src/components/index.ts
src/locales/en.json

⚠️ **This PR is now ready for review**. ~~The only outstanding work needed is improving the existing example, which will be done before merging. Reviewers should not wait on that example to provide review.~~
A sheet is a large container that enters from the edge of the screen when triggered by the merchant. It’s used to provide merchants with actions and information contextual to the page. It doesn’t interrupt their flow like a modal.
|implementation in web|playground desktop|playground mobile|
|-|-|-|
|![sheet-web](https://user-images.githubusercontent.com/1403188/55008691-b83b1500-4fb7-11e9-8de1-291947fc555c.gif)|![sheet-playground](https://user-images.githubusercontent.com/1403188/55008702-bd985f80-4fb7-11e9-8620-981384160194.gif)|![sheet-playground-mobile](https://user-images.githubuse …

[Sheet] build sheet component

---

.storybook/stories-from-readme.js

Modals use fixed positioning so the All Examples page looks like a mess
of modals overlaid one atop the other. That's not useful so stop
generating it.
Fixes #1307
Look at storybook and see that the Modal "All Examples" story is no longer generated.

Storybook: Don't generate All Examples page for modal

---

.github/ISSUE_TEMPLATE/ISSUE.md

envinfo: https://github.com/tabrindle/envinfo
I believe this will make life easier for everybody. Here's an example of the result from the command:
```
❯ npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris
npx: installed 1 in 1.356s
System:
OS: macOS 10.14.3
CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Memory: 242.77 MB / 16.00 GB
Shell: 3.0.2 - /usr/local/bin/fish
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.10.1 - ~/.dev/yarn/1.10.1/bin/yarn
npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Browsers:
Chrome: 73.0.3683.75
Chrome Canary: 75.0.3734.0
Firefox: 63.0.3
Safari: 12.0.3
npmPackages:
@shopify/polaris: ^3.9.0 => 3.9.0 
react: ^16.8.2 => 16.8.2 
react-dom: ^16.8.2 …
```

Use `envinfo` to retrieve the specs when creating an issue

---

UNRELEASED.md
src/components/Pagination/Pagination.scss
src/components/Pagination/Pagination.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1276
There's an issue with how the styling is applied to the previous and next buttons in the Pagination component. 
The issue affects how `margin-left` and `border-radius` properties are applied to the buttons. Its assumed the buttons will be siblings, with the styling based on `first-child` and `last-child`.
As a result several styles aren't applied properly, for example, when a `nextTooltip` is specified, the next button gets styles for both `first-child` and `last-child` & doesn't receive the negative `margin-left` for `:not(:first-child)`.
There's also similar issues when a `previousTooltip` is present or both tooltips.
Similarly there are issues with the `plain` buttons when they have tooltips.
Here are screenshots of different …

[Pagination] Fix styling for Pagination buttons with tooltips

---

UNRELEASED.md
src/components/TextContainer/TextContainer.scss

Fixes https://github.com/Shopify/polaris-react/issues/670
Change from using:
```
.TextContainer > * + * {
margin-top: (spacing($spacing));
}
```
to:
```
.TextContainer > *:not(:first-child) {
margin-top: (spacing($spacing));
}
```
This adds the styling to the same elements (i.e. all direct child elements, except the first one), but increases the specificity so it isn't overwritten by the styling applied to the individual child elements. …

[TextContainer] Fix child specificity for margin-top

---

UNRELEASED.md
src/components/Tooltip/Tooltip.scss

Partially fixes https://github.com/Shopify/polaris-react/issues/793
This PR adds a border to the `Tooltip` in Windows high contrast mode to allow it to be differentiated from the background.
Before: 
After:
- Navigate to `Tooltip -> All Examples` in the Polaris Storybook on a Windows machine/VM running in high contrast mode

[ToolTip] Add border for high contrast mode

---

UNRELEASED.md
src/components/Navigation/components/Section/Section.tsx
src/components/Navigation/components/Section/tests/Section.test.tsx

Fixes #1004
Prevents the rollup from collapsing when an item clicked has sub nav and at the mobile breakpoint 
|Before|After|
|---|---|
|![rollup bug](https://user-images.githubusercontent.com/344839/57260400-44f5db80-7018-11e9-87bd-7e5b64c8f2cb.gif)|![prevent rollup](https://user-images.githubusercontent.com/344839/57260410-4cb58000-7018-11e9-8b05-420d6e86d805.gif)|
<details> …

[Navigation.Section] Prevent rollup from collapsing when sub nav and on mobile

---

UNRELEASED.md
src/components/ContextualSaveBar/README.md

Fixes #1422
Adds the correct copy for a "Don't" example ("Save changes" instead of "Don't example").

Fix contextual save bar typo

---

UNRELEASED.md
src/components/ColorPicker/components/Slidable/Slidable.tsx
src/components/ColorPicker/tests/ColorPicker.test.tsx

While working with `ColorPicker` and testing on mobile, I noticed I was getting a ton of console logs:
Seemed pretty straight forward - we called `event.preventDefault()` within the `handleMove`, and the browser was defaulting to `passing: true`. In a nutshell, `passive=true` means you do not intend to call `preventDefault` within your handler, so the browser doesn't need to check for it. For those interested, you can read more here: https://developers.google.com/web/updates/2017/01/scrolling-intervention
But while I was at it, I also noticed the page was scrolling alongside touch interactions on the ColorPicker. This is an issue a few of us have already come across. The solution is to listen for `touchmove` on the `window` and `preventDefault` when we want to favour _some other_ …

[ColorPicker] Improve touch interactions

---

UNRELEASED.md
src/components/Popover/README.md

Adds accessibility guidance for the popover component, to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/overlays/popover (web, iOS, and Android)

[a11y] Popover accessibility docs

---

UNRELEASED.md
src/components/ColorPicker/components/Slidable/Slidable.tsx
src/components/ColorPicker/tests/ColorPicker.test.tsx

I shipped some code recently that solved a issue with ColorPicker `touchmove` behaviour: https://github.com/Shopify/polaris-react/pull/1414
I made a silly mistake - one that I had already resolved in my own app but forget to transfer over to my `polaris-react` PR.
We need to call `window.addEventListener`, but depending on how your app is configured, that code _could_ get executed on the `server`, where `window` does not exist.
```
[server] Error in server execution, check the console for more info.
window.addEventListener('touchmove', function (event) {
^
ReferenceError: window is not defined
```
All I need to do is wrap that event listener in a conditional to check if `window` is not `undefined`. I've tophatted in my app it everything is working.

[ColorPicker] Do not call `window` if "undefined"

---

CHANGELOG.md
UNRELEASED.md

v3.14.0!
UNREALEASED.md* => CHANGELOG.md
*Made some minor content fixes and moved a couple of line items from bug fixes to enhancements

[CHANGELOG] Prep for v3.14.0

---

src/components/RangeSlider/README.md
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx

Disabling the dual range slider did not disable it.
Early return if `disabled` is set to true

[Range slider] Fix disabled state

---

src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx

Centers the thumbs with the click position to match how the native range slider works.
|Before|After|
|---|---|
|![center thumbs before](https://user-images.githubusercontent.com/344839/57439703-6e229180-71fb-11e9-87cb-708b194dccf5.gif)|![center thumbs](https://user-images.githubusercontent.com/344839/57439724-78449000-71fb-11e9-8539-c1b72d1c6c24.gif)|
- Adds a left offset to the track left position stored in state
- Centers the output (tooltip)
- Removes dead and unneeded code

[Range slider] Center thumbs

---

src/components/RangeSlider/RangeSlider.tsx

This was causing a new ID to be generated and updated on every render.
Converts the top-level `RangeSlider` component to a class and stores the ID as an instance property.

[Range slider] Store ID as an instance property

---

src/components/RangeSlider/README.md
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.scss

Closes #937
|Before|After|
|---|---|
|![single output before](https://user-images.githubusercontent.com/344839/57422744-203f6680-71c6-11e9-967e-0e2818800a64.gif)|![single output](https://user-images.githubusercontent.com/344839/57422794-3e0ccb80-71c6-11e9-9dea-2f48e3fab777.gif)|
|![dual output before](https://user-images.githubusercontent.com/344839/57422743-1fa6d000-71c6-11e9-96f0-494fd823c61b.gif)|![dual output](https://user-images.githubusercontent.com/344839/57422778-30574600-71c6-11e9-8859-f28af966adb5.gif)|
- Adds `output` to default example
- removes tip from output on single range slider and adjusts spacing
- removes tip from output on dual range slider, adjusts spacing, fixes broken animation, and fixes broken horizontal centering.

[Range slider] Remove tip from output and fix styling

---

src/components/RangeSlider/components/DualThumb/DualThumb.tsx

To not increase the bundle size by 20kb
|Before|After|
|---|---|
|<img width="940" alt="Screen Shot 2019-05-08 at 9 44 33 PM" src="https://user-images.githubusercontent.com/344839/57427833-8f26ba80-71da-11e9-9698-4b294d3b8b96.png">|<img width="938" alt="Screen Shot 2019-05-08 at 9 44 43 PM" src="https://user-images.githubusercontent.com/344839/57427844-964dc880-71da-11e9-8c62-ff9b1f18f447.png">|
Converts function declarations into function expressions (it actually doesn’t do this, it compiles down to using a function expression on `prototype` to an instance property so `context` is bound.

[Range slider] Remove decorators

---

UNRELEASED.md
src/components/Popover/Popover.scss
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/ResourceList/components/BulkActions/tests/BulkActions.test.tsx

Popovers were [seen to "flutter"](https://github.com/Shopify/online-store-web/issues/2636) when animating on iOS. The `<Transition>` component was calling `renderOverlay` 5 times per `render` which had the effect of interrupting the CSS transition of the `.Popover` element and causing a flutter. By using the `<CSSTransition>` component instead, we better manage the transition and avoid the flutter.
Fixes https://github.com/Shopify/polaris-react/issues/1315
Swapping `<Transition>` component for `<CSSTransition>`.
|Before | After|
|--|--|
|![flickery_popover](https://user-images.githubusercontent.com/351842/55034738-927c3300-4fec-11e9-92bf-45c18b5142b7.gif)|![May-02-2019 17-59-00](https://user-images.githubusercontent.com/70582/57109709-2cc64980-6d04-11e9-864f-7748e3e04988.gif)|
🖥 [Local …

Switching Transition component for CSSTransition

---

UNRELEASED.md
documentation/Accessibility testing.md

Removes content about Pa11y running during CI. I was under the impression this was running, so this is an oversight on my part.

Removed section about running pa11y during CI

---

src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx

Supports touch
- Adds touch events
- removes the semi-transparent tap styles
- focuses thumbs after clicking on track
- prevents page scrolling on `touchmove`.

[Range slider] Support touch

---

scripts/new-version-pr-generator.js

The @Shopify/polaris-reviewers team doesn't exist, should we remove it from the PR that gets opened when polaris-react is deployed?

PR generator script: remove ping to non-existent team

---

UNRELEASED.md
src/components/Checkbox/Checkbox.tsx

Saw this code while running through some component logic, thought it was worth the quick fix. 
Simple fix to checkbox logic.

[Checkbox] Small fix in checkbox logic

---

UNRELEASED.md
src/components/Link/Link.scss
src/styles/shared/links.scss

Fixes https://github.com/Shopify/polaris-ux/issues/40 and https://github.com/Shopify/polaris-ux/issues/156
In the original issues, we landed on some more accessible focus styles for links:
In implementing these, however, I ran into some problems. The main one is that if `Link` remains styled as an inline element, image links look bad out of the box:
We could fix this by making all images in Polaris block-level by default. This is usually what you want, but may have knock-on effects in consuming apps. Another way would be to set links to be `inline-flex`, but has similar risks for existing apps.
To avoid breaking changes, I’ve opted to go a different route from the original designs and strip back to browser default styles instead.
Here’s how things look now in different browsers. I left …

[Link] Improve accessibility of focus styles

---

UNRELEASED.md
src/components/TextField/README.md
src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

There are a few instances in the admin where the `TextField` is right aligned. Usually in a modal where multiple rows of numbers need to line up.
To achieve this I added an align="left | right | center" prop to Textfield.
<details>
```jsx
import {Page, Card, TextField, Stack} from '../src';
export default class …
```

[TextField] Adding an alignRight prop on TextField

---

UNRELEASED.md
src/components/Modal/README.md

Should be shipped with https://github.com/Shopify/polaris-styleguide/pull/2714
Following up on Polaris day explorations on [tertiary guidelines in modals ](https://docs.google.com/presentation/d/19Dps59g-7NzxhdYeYKjHk9efxY0TKIf3Uij7dpdawtQ/edit#slide=id.g4a721b0e8c_0_110
)
After:
Best practices section:
Content section:

Add tertiary action guideline to modal section

---

.circleci/config.yml
UNRELEASED.md
a11y_shitlist.json
scripts/pa11y-utilities.js
scripts/pa11y.js
src/components/Sheet/README.md
tests/pa11y-utilities.test.js

We experimented with automated a11y testing with pa11y previously, but it was breaking way too often so we decided to disable it. Since then we've made changes to the codebase that I believe should make pa11y more stable:
- Named examples can be checked against more reliably than an array of examples
- Component renames/refactors don't happen as often
Re-enables automated a11y testing in CI.
I re-generated the shitlist to be up to date, and updated the script to deal with example names properly.
Also made the CI job always pass. We can keep it running in master for a week to evaluate whether it would help, or whether it's still failing too often to be useful. After a week we'll decide on the best way forward. The main two options are either fixing all errors and getting rid of the …

Re-enable automated a11y testing in CI

---

src/components/TextField/TextField.tsx

In the styleguide, possible values for the prop "Alignment" are shown as (in a dropdown):
- left
- right
- center
In a left-to-right world, it's more logical to have those as:
- left
- center
- right
Reorders props in a more logical order.

[TextField] Set alignment values in a logical order

---

README.md
package.json
scripts/build.js
src/components/README.md
tsconfig.json

We can't update `polaris-react` in `web` because of this bug.
This issue was introduced when we updated Typescript from 3.1.6 to 3.2.4.
In 3.2.4, `tsc` includes the root directory's `package.json` file in the output build by default
This is a problem because the "files" key in the root `package.json` ends up filtering which files get included in the build output. Ideally the package.json file wouldn't be copied, but I couldn't easily figure out how to configure that, so I delete the `package.json` file before copying the `tsc` output to its proper folder.
Run a build, and run the following command:
```
npm pack 2>&1 | tee packoutput.txt
```
And then inspect `packoutput.txt`. Check that the files included in the `/esnext/` folder look like this: …

Fix issue where tsx would copy the package.json file where it shouldn't

---

UNRELEASED.md
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/tests/Checkbox.test.tsx
src/components/Choice/Choice.tsx
src/components/Choice/tests/Choice.test.tsx

It’s unfortunate that we missed this in the `build-consumer` test. This seems to be a regression caused by not fully understanding #1363. In #1369 I made it so Checkbox cannot be disabled and checked. however, it seems we wanted to remove the ability to fire click events while disabled and keep the ability to change `Checkbox` checked state.
* removing unnecessary code
* moving logic from `Choice` to `Checkbox`
* updating tests 
* Simple playground to toggle `checked` and `disabled` states  ⬇️&
* Build-consumer and check the failing test in web
<details>
```jsx
import {Checkbox, Button} from '@shopify/polaris';
checked: boolean;
disabled: boolean;
}
export …
```

[Checkbox] Fix regression when disabled

---

src/components/Navigation/variables.scss

https://github.com/Shopify/polaris-react/pull/1304 introduced a regression that caused a widely applicable style (a style on all `a` tags coming from Polaris rails) on rails views to have underlines when hovered. React views did not have the same hover underline.
|:tophat: React before|:tophat: Rails before|:tophat: React after|:tophat: Rails after|
|-|-|-|-|
|<img width="1532" alt="Screen Shot 2019-05-14 at 10 45 00 AM" src="https://user-images.githubusercontent.com/1403188/57708599-9cf39a00-7637-11e9-9f16-845362a701c8.png">|<img width="1440" alt="Screen Shot 2019-05-14 at 10 43 19 AM" src="https://user-images.githubusercontent.com/1403188/57708623-a846c580-7637-11e9-841a-45dab1c0e1c5.png">|<img width="1532" alt="Screen Shot 2019-05-14 at 10 57 48 AM" …

[Navigation] fix hover regression on navigation items on rails views

---

UNRELEASED.md
src/utilities/breakpoints.ts

While tophatting a change in web to replace the web implementation of `Sheet` with the Polaris implementation, I saw that the breakpoint in the JavaScript is wrong, as navigation should be displayed inclusive of 768px, but not 769px. This results in a sheet which, for one pixel at `769px` wide appears as the desktop sheet but functions as the mobile sheet (closing towards the bottom). This fixes that issue.

[Breakpoints] fix breakpoint off by 1

---

UNRELEASED.md
src/components/RangeSlider/README.md
src/components/RangeSlider/RangeSlider.tsx
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/index.ts
src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
src/components/RangeSlider/components/SingleThumb/index.ts
src/components/RangeSlider/components/SingleThumb/tests/SingleThumb.test.tsx
src/components/RangeSlider/components/index.ts
src/components/RangeSlider/index.ts
src/components/RangeSlider/tests/RangeSlider.test.tsx
src/components/RangeSlider/types.ts
src/components/RangeSlider/utilities/index.ts
src/components/RangeSlider/utilities/invertNumber.ts
src/components/RangeSlider/utilities/tests/invertNumber.test.ts
src/utilities/clamp.ts
src/utilities/tests/clamp.test.ts

Closes #595. Adds support for a dual range slider.
Extends the `value` prop of `RangeSlider` to accept a tuple and splits the internals of `RangeSlider` into two subcomponents, `SingleThumb` (current `RangeSlider`) and `DualThumb` (new component to support a dual range slider)

[Range slider] Dual range slider

---

src/components/Navigation/README.md

Fixes #1470  
- Removes `UserMenu` option and shortens description now that this sub-component has been deprecated.

[Navigation] Remove deprecated UserMenu option for styleguide

---

.storybook/webpack.config.js
UNRELEASED.md
package.json
src/components/Icon/Icon.tsx
yarn.lock

This was never needed at runtime, we only used it for a trivial type
that we can easily duplicate (and we'll remove the need for that type in
v4)
We don't need it at build time as sk handles our svg optimization
To test:
- Icon unit tests
- Search for `@shopify/images` and see the only mentions are in the yarn.lock files of our examples.

Remove dependency on @shopify/images

---

src/components/index.ts
src/hooks/index.ts
src/hooks/use-app-bridge/index.ts
src/hooks/use-app-bridge/tests/use-app-bridge.test.tsx
src/hooks/use-app-bridge/use-app-bridge.tsx
src/hooks/use-polaris/index.ts
src/hooks/use-polaris/tests/use-polaris.test.tsx
src/hooks/use-polaris/use-polaris.tsx

Preparing for hooks
* create a new directory for hooks `src/hooks`
* create `usePolaris` hook for internal use
* create `useAppBridge` hook for external use
* 🎉 tests 🎉 
Trust in the powers of tests or try the playground - you'll need credentials for testing `useAppBridge`
<details>
```jsx
import {Page, AppProvider, Card} from '../src';
import {usePolaris, useAppBridge} from '../src/hooks';
const credentials = {
apiKey: undefined,
shopOrigin: undefined,
}
export default function() {
const {apiKey, shopOrigin} = credentials;
return (
<AppProvider apiKey={apiKey} shopOrigin={shopOrigin}>
<Card title="usePolaris"> …
```

[v4] Add usePolaris/AppBridge 

---

UNRELEASED-V4.md
tests/setup.ts

Fixes #1483
We're getting spammed with testID warnings
Fixing the regex to match the output

Remove testID warning

---

UNRELEASED.md
src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx

We came across a use case where we wanted to render another component, such as a `Badge` alongside the heading for an `AnnotatedSection`:
We considered passing a React component to the `title` prop that rendered both a `Heading` and a `Badge` component:
```jsx
<Layout.AnnotatedSection
title={
<Stack>
<Heading />
<Badge />
</Stack>
}
>
``` 
While this renders successfuly in the browser, it raises a TypeScript error in the text editor because, at the moment, the `title` prop only supports strings.
After consulting @BPScott, we felt it seemed reasonable to change the type restriction for the `title` prop in this scenario: https://shopify.slack.com/archives/C8H54T86Q/p1557331031274400
This PR updates the type definition for the `title` prop of the `AnnotatedSection` component to accept …

[AnnotatedSection] Update type definition for title prop to accept React.ReactNode

---

UNRELEASED-V4.md
package.json
src/components/Navigation/types.ts
src/components/ThemeProvider/index.ts
src/components/ThemeProvider/types.ts
yarn.lock

Resolves #1504
We removed all of the old context 😄

[v4] Remove prop types

---

UNRELEASED-V4.md
src/components/Loading/Loading.tsx

Part of #1484
I'm converting Loading to a functional component and removing `withContext`

[v4][Loading] Remove withContext

---

UNRELEASED-V4.md
src/components/Scrollable/components/ScrollTo/ScrollTo.tsx
src/components/Scrollable/components/ScrollTo/tests/ScrollTo.test.tsx

Part of #1484
I'm converting Scrollable.ScrollTo to a functional component and removing `withContext`

[v4][Scrollable.ScrollTo] Remove withContext

---

UNRELEASED.md
src/components/Banner/Banner.scss

Partially fixes https://github.com/Shopify/polaris-ux/issues/255
This PR is adding `box-shadow` to the `Banner` in Windows high contrast mode to make it more visible. `border` wasn't used as it was having [an undesired effect](https://github.com/Shopify/polaris-ux/issues/255#issuecomment-492634471).
Non-focused:
Focused:
- Navigate to `Banner` -> `Default banners` on a Windows machine running in high contrast mode
- Also navigate to `Banner` …

[Banner] Add box-shadow in Windows high contrast mode

---

UNRELEASED.md
src/components/Card/Card.scss

Partially fixes https://github.com/Shopify/polaris-ux/issues/255
This PR is adding `box-shadow` to the `Card` in Windows high contrast mode to make it more visible.
The `background-color` is also removed from subdued sections in Windows high contrast mode as it doesn't have any effect other than hiding the `box-shadow` used to highlight the border.
- Navigate to `Card` -> `All examples` on a Windows machine running in high contrast mode

[Card] Add box-shadow in Windows high contrast mode

---

UNRELEASED-V4.md
package.json

We updated the devDependencies, but forgot the peer deps

Increase react and react-dom peer dependencies to 16.8.6

---

UNRELEASED-V4.md
src/components/DropZone/components/FileUpload/FileUpload.tsx

Part of #1484
I'm converting FileUpload to a functional component and removing `withRef` / `withContext`

[v4][FileUpload] Remove withContext/withRef

---

UNRELEASED.md
src/components/Navigation/Navigation.scss
src/components/Navigation/variables.scss

Closes https://github.com/Shopify/polaris-react/issues/1487
I was unable to reproduce the cursor inconsistency described in the issue.
|:tophat: before|:tophat: after |
|-|-|
|![navigation-before](https://user-images.githubusercontent.com/1403188/58178029-6d661280-7c73-11e9-803d-19aa4175d743.gif)|![navigation-after](https://user-images.githubusercontent.com/1403188/58178062-75be4d80-7c73-11e9-88b8-9dc533e93723.gif)|
- `dev up` in `shopify/web`
- pull this branch down
- `dev up` in `shopify/polaris-react`
- `yarn build-consumer web` in `shopify/polaris-react`
- `dev server` in `shopify/web`
- :tophat: `Customers/index` (a rails route), hovering over other navigation items

[Navigation] Fix hover and active states

---

src/components/RangeSlider/RangeSlider.scss
src/components/RangeSlider/RangeSlider.tsx
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
src/components/RangeSlider/index.ts
src/components/RangeSlider/types.ts
src/components/index.ts

Props table was not rendering in the style guide AND the styles were not getting built
- Defines `Props` in the component. This is what the style guide parses.
- Adds an empty-ish top-level SCSS file so the styles get built

[Range slider] Fix types and styles

---

UNRELEASED-V4.md
src/components/OptionList/OptionList.tsx
src/components/OptionList/tests/OptionList.test.tsx
src/hooks/index.ts
src/hooks/use-deep-compare/index.ts
src/hooks/use-deep-compare/use-deep-compare.tsx

Part of https://github.com/Shopify/polaris-react/issues/519
* Removing `componentWillReceiveProps` from option list
* Fix tests
* Create a hook to address deep comparison
* Add changelog
Tests / Percy / Heroku deployment playground
The reason for a deep comparison hook is that react doesn't do very much work comparing your dependencies. They only use [Object.is](https://github.com/facebook/react/blob/101901dc2d09509fa0b667196e1ac63ec17bc656/packages/react-reconciler/src/ReactFiberHooks.js#L300)(link to source code) and offer suggestions like [`JSON.stringify`](https://github.com/facebook/react/issues/14476#issuecomment-471199055). We often have complex types that we need to compare so this hook will be very useful in the future as well.

[v4][OptionList] Remove componentWillReceiveProps

---

UNRELEASED.md
src/components/ColorPicker/ColorPicker.tsx

Fixes #1542. Text outside the color picker was being selected when dragging the picker.
No UI changes. Simply prevented the mousedown event from bubbling up to other elements in the DOM to stop other text from being able to detect they were being dragged over to select.

[ColorPicker] Fix errant text selection

---

UNRELEASED.md
src/components/ActionList/tests/ActionList.test.tsx
src/components/Button/Button.tsx
src/components/Icon/Icon.tsx
src/components/TextField/TextField.tsx

To shrink polaris-react we should stop bundling icons, and instead make people explicitly reference the icon they need.
This PR deprecates passing a string into `<Icon source />` and instead tells people to import an icon from polaris-icons instead. e.g. instead of 
```jsx
const x = <Icon source="add" />
```
do:
```jsx
import {PlusMinor} from '@shopify/polaris-icons';
const x = <Icon source={PlusMinor} />
```
The groundwork to enable this - updating our own code to import from polaris-icons was done in #1196 and #1297.
This PR also tightens the type for `<Button icon>` from `ReactNode|IconSource` to `ReactElement|IconSource` as ReactNode is far too broad - we only want people passing in some kind of html element, we don't want to handle strings or anything else that a ReactNode could be. …

Deprecate passing a stringy name of a bundled icon into <Icon source>

---

UNRELEASED.md
src/components/Banner/Banner.scss

Fixes #737 
Currently, long single word titles overflow the `Banner`'s boundary instead of wrapping to the next line. This PR ensures the line will wrap instead of overflowing.
Adds handling of `word-wrap` to the `Banner-Heading` class.
|---|---|
|<img width="811" alt="Screen Shot 2019-05-22 at 1 48 15 PM" src="https://user-images.githubusercontent.com/18447883/58196433-4cfc7f00-7c98-11e9-9b06-c557e5d0066b.png">|<img width="796" alt="Screen Shot 2019-05-22 at 1 34 12 PM" src="https://user-images.githubusercontent.com/18447883/58196448-54238d00-7c98-11e9-9632-717b41f47c1e.png">|
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/mas …

[Banner] Break word in title instead of overflowing line

---

UNRELEASED-V4.md
src/components/ChoiceList/ChoiceList.tsx
src/components/ChoiceList/tests/ChoiceList.test.tsx

Fixes #1566 
Makes the title required on `ChoiceList`. This is necessary as it creates a legend for the fieldset. Without a legend the HTML is not semantic and fails WCAG.
As this is a breaking change it will go into v4.

Make choicelist title required

---

UNRELEASED.md
src/components/EmptyState/EmptyState.tsx
src/components/EmptyState/tests/EmptyState.test.tsx

To match our rails implementation this PR makes the action prop optional on the EmptyState component
Also took advantage and polished the code and reorganized tests.
- Ensure EmptyState renders as it did before in various browser size with various prop combinations
<details>
```jsx
import {EmptyState} from '../src';
export default …
```

[EmptyState] Make action prop optional

---

UNRELEASED.md
src/components/Modal/Modal.scss

Nobody seems to be able to remember why it was added in the first place and it is preventing full width body content.
We are currently building a non-white full width content application in React and noticed that the `Modal` body has a border radius that we are not sure it should have.
Usually you don’t notice it, because the backgrounds are white and the content has no borders.
Removes the border radius from the modal body
<details>
```jsx
import {Page, Modal} from '../src';
render() {
return (
<Modal open large>
<Modal.Section>hello</Modal.Section>
</Modal> …
```

[MODAL] remove unnecessary border radius from modal body

---

UNRELEASED-V4.md
src/components/ResourceList/components/Item/Item.tsx

Part of #1484
I'm removing `withContext` in favor of a wrapper component

[v4][ResourceList.Item] Remove withContext

---

UNRELEASED-V4.md
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx

Part of #1484
I'm converting Navigation.Item to a functional component and removing `withContext`

[v4][Navigation.Item] Remove withRef

---

UNRELEASED.md
src/styles/global/elements.scss

Firefox adds a special, separate dotted inner border to focused buttons. Since we already define focus styles, we can remove this using [the same basic approach as projects like Normalize.css](https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L203).
Removes the extra border from buttons and inputs in Firefox.
* [N/A] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [N/A] Updated the component's `README.md` with documentation changes
* [N/A] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide

Prevent Firefox from showing an inner dotted border on focused buttons

---

UNRELEASED.md
src/components/ResourceList/README.md
src/components/ResourceList/ResourceList.scss
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/components/Item/Item.tsx
src/components/ResourceList/components/Item/tests/Item.test.tsx
src/components/ResourceList/tests/ResourceList.test.tsx
src/components/ResourceList/types.ts

Add multi-select to `ResourceList`
Fixes: #935
* Add example to readme
* Add multiselect logic
* Add tests
* Fix failing tests
https://cl.ly/9e5e755caa40
* Playground with multiselect is provided below
* I'm linking to an example PR in web adding multiselect that can be used for 🎩  (hidden between the deploys)
<details>
```jsx
import {Card, ResourceList, Avatar, TextStyle} from '../src';
const items = [
{
id: 341,
url: 'customers/341',
name: 'Mae Jemison',
location: 'Decatur, USA',
},
{
id: 256,
url: 'customers/256',
name: 'Ellen Ochoa',
location: 'Los Angeles, USA',
},
{
id: 3412341,
url: 'customers/341',
name: 'Mae Jemison',
location: 'Decatur, USA',
},
{
id: 25566546,
url: …
```

[ResourceList] Multiselect

---

UNRELEASED.md
src/components/AppProvider/README.md
src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
src/components/Loading/Loading.tsx
src/components/Loading/README.md
src/components/Modal/Modal.tsx
src/components/Modal/README.md
src/components/Page/Page.tsx
src/components/Page/README.md
src/components/ResourcePicker/README.md
src/components/ResourcePicker/ResourcePicker.tsx
src/components/Toast/README.md
src/components/Toast/Toast.tsx

Adds deprecation messages for our App Bridge usage.
For example:
Adds console warnings, a deprecation doc tag, and deprecation rationale in the component documentation.

[App bridge] Add deprecation messages

---

UNRELEASED-V4.md
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx

Part of #1484
I'm converting ContextualSaveBar to a functional component and removing `withContext`

[v4][ContextualSaveBar] Remove withContext

---

UNRELEASED.md
src/components/ResourcePicker/ResourcePicker.tsx
src/components/ResourcePicker/tests/ResourcePicker.test.tsx

When developing an app that adds line items to a draft order, I noticed that my ResourcePicker kept resetting my line items to the initial state. Since this component requires being inside of an embedded app and I am working on a private project, I put together an example app that demonstrates the issue: https://github.com/katzenbar/shopify-resource-picker-bug
This example app takes the products selected in the ResourcePicker, and adds them to the end of the list in the card. https://github.com/katzenbar/shopify-resource-picker-bug/blob/master/app/javascript/components/ProductPage.tsx#L24-L28
But when `handleSelection` is run, the `products` array is empty. This results in the old selection being replaced.
The expected behavior should be that the newly selected products are added to the …

[Resource Picker] Fix reference to old callback function

---

UNRELEASED.md
src/components/Tag/Tag.scss

Tag button hover state should be immediate.
Removes excessive hover state transition on tag button.
<details>
```jsx
render() {
return (
{/* Add the code you want to test here …
```

remove-tag-button-transition

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Button/Button.tsx
src/components/Button/README.md

Needed for edge case of https://github.com/Shopify/web/issues/13270.
We wanted left-align on plain buttons which means we needed a new prop since we weren't sure if all plain buttons want left-alignment.
This prop changes the inner text-align of the button. It is useful for edge-cases when the button overflows to another line. It will be used mainly for plain and monochrome buttons but it also works with fullsize buttons. By default it will not affect any styling unless the prop is used.
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/do …

[Button] Add textAlign Property

---

UNRELEASED.md
src/components/Card/README.md
src/components/Card/components/Section/Section.tsx
src/components/Card/components/Section/tests/Section.test.tsx

A common pattern we've been seeing is to allow Card.Section titles to have their own "header action", visually this looks like:
A common problem is that every time you want to do this, you must supply something like `title={<Stack>...</Stack>}` and a lot of code to compose the actions.  Further, people may not be composing their stacks in a consistent manner.
I introduce the ability for `<Card.Section>` to take multiple `actions`, like this:
```tsx
<Card.Section
title="Section 1 title"
actions={[
{
content: 'Subfoo',
onAction: () => {
alert('Subfoo action clicked');
},
},
{
content: 'Subbar',
onAction: () => {
alert('Subbar action clicked');
},
},
]}
>
```
It is up to the user's discretion whether you should be using >1 action here (much as is the case for `Card`'s `actions` prop). …

[Card.Section] Allow <Card.Section> to accept "actions" prop, an array of DisableableAction

---

UNRELEASED.md
src/components/Collapsible/README.md

(I was browsing the example for my own personal project and came across this documentation issue)
As described in the props of the component, the `Button` toggler should have an `aria-controls` prop pointing to the collapsible component it controls.

[Collapsible] Add aria-controls on the button in the example

---

src/components/Button/Button.scss
src/components/Select/Select.scss

I stumbled upon two instances where we were using `rem(8px)` for padding values. Just swapping that out for `spacing(tight)`.

[Code Quality] Replace rem(8px) with spacing(tight)

---

UNRELEASED-V4.md
src/components/Button/tests/Button.test.tsx
src/components/Icon/Icon.tsx
src/components/Icon/tests/Icon.test.tsx

Remove deprecated functionality.
Fixes #1298 and is the final step in #1061
Icon now only supports a source of 'placeholder' to use a placeholder,
a component that returns an SVG element (i.e. something provided by
polaris-icons or svgr imports) or a string (for untrusted svgs)
- Remove passing a string into source to use a bundled icon
- Remove passing a SvgSource shaped object into source (this was the legacy shopify-style icon imports that we have replaced with using SVGr in sewing-kit)
- Remove passing a React element into source
- Remove the deprecated 'untrusted' prop
check tests and an storybook for no regressions

[v4] Deprecate icon source

---

.storybook/stories-from-readme.js
UNRELEASED.md

Fixes an issue where the Card component example story wouldn't render correctly in Percy since Storybook was upgraded to 5.1.0 (https://github.com/Shopify/polaris-react/pull/1488).

[Storybook] Test Card individually in Percy

---

.github/ISSUE_TEMPLATE/NEW_COMPONENT.md
src/components/Navigation/README.md
src/components/TopBar/README.md

This PR changes instances of `Component dependencies` to `Required components` in the new component template and in the documentation for 2 components. 
This change was made following a component documentation clinic where folks agreed that `Required components` should be the standardized heading.

[Content] Change template and heading for required components

---

UNRELEASED.md
src/components/TextField/TextField.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1587
The `TextField` component is unnecessarily defining the input's `aria-label` and `aria-labelledby` attributes in cases where the value of the label node is sufficient on its own.
As mentioned in https://github.com/Shopify/polaris-react/issues/1587, "Only one method is needed, and extra methods may cause duplicate reading by assistive tech."
This pull request implements the recommended behaviour outlined in https://github.com/Shopify/polaris-react/issues/1587.
1. Use only the default <label> with the for/id pair by default, and do not set the `aria-label` and `aria-labelledby` attributes
2. If multiple labels are required, set the `aria-labelledby` attribute …

[TextField] [a11y] Define aria-labelledby only if multiple labels are required

---

yarn.lock

Partial fix for #1617.
These audits are mostly noise. They're complaining about our development dependencies and thus in a place that exposes a security concern for our users. That said it's nice to cut down on noise.
Updating a bunch of our transitive dependency versions
Before:
> 555 vulnerabilities found - Packages audited: 82316 // Severity: 305 Low | 234 Moderate | 16 High
After:
> 78 vulnerabilities found - Packages audited: 93837 // Severity: 70 Low | 8 Moderate
This doesn't fix everything but it gets the low-hanging fruit.
The rest of this can be solved by
- kicking js-uploader to not used fixed old versions for dependencies (while you're fixing this can you publish it to npm so we don't have to rely on a github dependency as I think that slows installs down)
- updating sewing-kit …

Update dependency versions to quieten yarn audit

---

UNRELEASED-V4.md
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx
src/components/Card/Card.tsx
src/components/Card/tests/Card.test.tsx
src/components/Modal/Modal.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/Navigation/Navigation.tsx
src/components/Navigation/tests/Navigation.test.tsx
src/components/WithinContentContext/context.tsx
src/components/WithinContentContext/index.ts

Fixes #1521
Changing WithinContentContextType from `{withinContentContext: boolean}` to `boolean`

[v4] Simplify withinContentContext

---

UNRELEASED.md
src/components/Icon/Icon.tsx

Separate comments will create separate jsdocs.

[Icon] Fix jsdoc for the untrusted prop

---

UNRELEASED.md

Added a bug fix for Windows high contrast (Tabs and Popovers) on `UNRELEASED.md `
https://github.com/Shopify/polaris-react/pull/1629
<details>
```jsx
render() {
return (
{/* …
```

Added bug fix for Windows high contrast

---

UNRELEASED.md
src/components/Collapsible/README.md

Adds accessibility guidance for the collapsible component, to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/behavior/collapsible (web, iOS, and Android)

[a11y] Collapsible a11y docs

---

UNRELEASED.md
src/components/KeyboardKey/README.md

Adds accessibility guidance for the [keyboard key component](https://polaris.shopify.com/components/images-and-icons/keyboard-key), to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/images-and-icons/keyboard-key (web only)

[a11y] Add keyboard key docs

---

UNRELEASED-V4.md
src/components/Page/Page.scss
src/components/Page/Page.tsx
src/components/Page/README.md
src/components/Page/tests/Page.test.tsx
src/components/Sheet/README.md
src/components/SkeletonPage/SkeletonPage.scss
src/components/SkeletonPage/SkeletonPage.tsx
src/components/SkeletonPage/tests/SkeletonPage.test.tsx

Fixes #1572
@tmlayton For documentation, what do you think about sectioning out deprecated props rather than removing them? Where `Deprecated Props` could be our `DeprecatedProps` interface?

[v4][Page] Narrow width page

---

UNRELEASED.md
src/components/ExceptionList/README.md

Adds accessibility guidance for the [exception list component](https://polaris.shopify.com/components/lists-and-tables/exception-list), to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/lists-and-tables/exception-list (web only)

[a11y] Exception list a11y docs

---

UNRELEASED.md
src/components/Form/README.md

Adds accessibility guidance for the [form component](https://polaris.shopify.com/components/forms/form), to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/forms/form (web only)

[a11y] Form a11y docs

---

UNRELEASED.md
src/components/DescriptionList/README.md

Adds accessibility guidance for the description list component, to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/lists-and-tables/description-list (web, iOS, and Android)

[a11y] Description list a11y docs

---

UNRELEASED.md
src/components/Modal/README.md

Adds accessibility guidance for the [modal component](https://polaris.shopify.com/components/overlays/modal), to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props, and in the best practices section: https://polaris.myshopify.io/components/overlays/modal (web, iOS, and Android)

[a11y] Adds docs for the modal

---

UNRELEASED.md
package.json
src/components/AppProvider/types.ts
yarn.lock

Below type error solved with d52c0a6
```
┌🤘-🐧danrosenthal@ 💻 Daniels-MacBook-Pro - 🧱 polaris-react on 🌵  typescript-3.5.1-upgrade •2 ✗
└🤘-> yyarn sewing-kit type-check
yarn run v1.13.0
$ /Users/danrosenthal/Projects/polaris-react/node_modules/.bin/sewing-kit type-check
[type-check] Checking tsconfig.json
src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts:60:7 - error TS2322: Type 'ClientApplication<unknown> | undefined' is not assignable to type 'ClientApplication<{}> | undefined'.
Type 'ClientApplication<unknown>' is not assignable to type 'ClientApplication<{}>'.
Type 'unknown' is not assignable to type '{}'.
60       appBridge,
~~~~~~~~~
src/components/AppProvider/types.ts:41:5
41     appBridge?: ClientApplication<{}>;
~~~~~~~~~
The expected type …
```

Upgrade Typescript to 3.5.1 

---

UNRELEASED.md
src/components/Tag/README.md

Adds accessibility guidance for the [tag component](https://polaris.shopify.com/components/forms/tag), to appear in `polaris-react` docs and in the style guide.
1. View changes after examples and props: https://polaris.myshopify.io/components/forms/tag (web, iOS, and Android)

[a11y] Docs for the tag component

---

UNRELEASED.md
src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
src/components/Tabs/components/TabMeasurer/tests/TabMeasurer.test.tsx

This PR prevents the reflow that happens when we initialize the `Tabs` component. We need to measure the width of the tabs to determine how many we can fit in to a row and how many we need to hide.
This PR uses `requestAnimationFrame` in the `handleMeasurement` method to defer the actions that cause the reflow.
Here's what the reflow looked like on a slow device. `handleMeasurement` took about ~500ms.
Check that the tab component still behaves …

[TabMeasure] Prevents reflow when measuring tabs

---

UNRELEASED.md
src/components/Card/Card.tsx
src/components/Card/README.md
src/components/Card/tests/Card.test.tsx
src/locales/de.json
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/locales/hi.json
src/locales/it.json
src/locales/ja.json
src/locales/ms.json
src/locales/nl.json
src/locales/pt-BR.json
src/locales/zh-CN.json
src/locales/zh-TW.json

~~Should merge after https://github.com/Shopify/polaris-react/pull/1622 to minimize merge conflicts~~
- Adds ability to supply array of `secondaryFooterActions`, and adds deprecation notes to `secondaryFooterAction` (singular)
- Allows `primaryFooterAction` and `secondaryFooterAction` to be disableable
With an array of actions, you can now easily achieve this:
With an array of just 1 action, it falls back to rendering as if you had supplied a `secondaryFooterAction` (singular):
Here's a picture of disabling the secondary, and of a custom disclosure text:
📄 …

[Card] Add support for multiple secondary actions in footer and the option to disable them

---

.storybook/polaris-readme-loader.js
src/components/TextField/README.md

See https://github.com/Shopify/polaris-react/issues/1662
- Adds support for function component examples.
- Adds support for React hooks to the examples.
- Updated the first 5 TextField examples to use hooks instead of class syntax.
To be able to fully support this the styleguide editor will also need to support function syntax and hooks. I have a PR up for that here: https://github.com/Shopify/polaris-styleguide/pull/2818.
1. Run `yarn dev`.
1. In StoryBook navigate to the first 5 `TextField` examples and confirm they still work.

Adds support for function component examples and React hooks

---

.storybook/polaris-readme-loader.js
UNRELEASED-V4.md
src/components/TextField/README.md

These examples were introduced in https://github.com/Shopify/polaris-react/pull/1665
* use usecallback
* skipping a changelog entry since one was never added noting the conversion

[v4][TextField] Fix textfield examples

---

src/components/Card/README.md

Some examples shouldn't appear in iOS/Android tabs on https://polaris.shopify.com/components/structure/card

[Card] Fix example / content assignment

---

examples/webpack/package.json

Currently `npm start` throws the following errors:
```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/core'
babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
```
```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-env'
```
```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-react'
```
Simply updating webpack dependencies in package.json so that `npm start` works.

[examples/webpack] Fixing webpack dependencies in package.json

---

UNRELEASED-V4.md
src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/tests/Collapsible.test.tsx

Final fix in #https://github.com/Shopify/polaris-react/issues/519 🎉 
@dleroux and I 
* Removed `componentWillReceiveProps` / make collapsible a functional component
* Simplified the animation using css vars
* Added a duration function to slightly increase the animation speed when collapsing larger areas
* percy + tests
* storybook deploy
<details>
```jsx
import {Page, Select, Collapsible, TextContainer, Button, Stack} from '../src';
const options = [
{label: 'short', value: 'short'},
{label: 'medium', value: 'medium'},
{label: 'long', value: 'long'},
{label: 'really long', value: 'really long'},
];
const [selected, setSelected] = useState('short');
const [open, setOpen] = useState(false);
const …
```

[v4][Collapsible] Remove componentWillReceiveProp from Collapsible

---

UNRELEASED.md
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx
src/components/Link/Link.tsx
src/components/Link/README.md
src/components/Link/tests/Link.test.tsx
src/utilities/banner-context.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1620
When links are passed as children to the `Banner`, they are rendered in the `blue` colour that is applied to `Link` components. The colour contrast ratio between the link text colour and the background colours used for Banner components fails to meet WCAG 2.1 standards.
This PR uses the `withinContentContainer` context to ensures that links passed as children of a Banner component are rendered as monochrome links. This means they will be underlined and will inherit the grey font colour used for other text content in the Banner, which meets Level AA and AAA standards of WCAG 2.1. …

[Banner] Improve colour contrast ratio of links passed as children

---

.eslintrc
UNRELEASED-V4.md

We removed the last deprecated lifecycle method 🎉 I was going to add strict mode to storybook but it looks like we use ReactDOM.findDOMNode which is also a nono for strict mode, and will need to be handled but should be an easy fix.

[v4] Update no unsafe eslint rule

---

UNRELEASED-V4.md
src/components/Focus/Focus.tsx
src/components/Focus/tests/Focus.test.tsx
src/components/ResourceList/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx
src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
src/components/TrapFocus/TrapFocus.tsx
src/types.ts

Last change before we can enable strict mode 🎉 
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of StyledComponent which is inside StrictMode. Instead, add a ref directly to the element you want to reference.
```
Luckily none of our uses require findDOMNode to find a child element without any context so we can replace them with refs.

[v4] Removed all usage of findDOMNode

---

UNRELEASED.md
src/components/ResourceList/README.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

Changes introduced in the scope of issue #1536 
Introduced an additional property `selectable` to Resource List component that allows Resource List to display its standard selection controls (select all in header and checkboxes in front of every item) without need to provide `bulkActions` or `promotedBulkActions`
<details>
```jsx
import {Page, ResourceList, Card, Avatar, TextStyle} from '../src';
class ResourceListExample extends React.Component {
state = {
};
};
const media = <Avatar customer …
```

[Resource List] Add selectable property to Resource List

---

UNRELEASED.md
src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

2 years ago, @ry5n added the following code: https://github.com/Shopify/polaris-react/commit/cbbe3df9a95e7934786174eb183c022658e4dd04
This was specifically to:
> Fix left and right ends of `TextField` not responding to clicks
So the intention was definitely to prevent clicks on any `prefix` or `suffix` and have those clicks pass through, allowing the `focus` state to be triggered for the component.
2 years later I find myself attempting to achieve the following design:
In the screenshot above, you will see a `<TextField />` that uses:
- An `icon` for a `prefix`
- A "Visit" `<Link />` as a `suffix`
- And a  "X" `<Button />` for `connectedRight`
It turns out, my "Visit" `Link` was not interactable... and after some digging, I arrived on the `pointer-events: none;` code that @ry5n had added. …

[TextField] `prefix/suffix` props: Allow clickable actions but retain unselectable text

---

.storybook/webpack.config.js
babel.config.js

A few weeks ago I taught babel-plugin-shopify how to read typescript files with the flick of an option. We should use that instead having to pass TS files into ts-loader then into babel-loader.
- Enable typescript mode for our babel config
- Remove ts-loader from storybook config
- Remove `useBuiltins: entry` from babel config as it is the default so no need to specify it.
- Ensure storybook runs without errors (check percy). There will be some console warnings regarding unfound imports of interfaces but they were there before too.

Storybook: Make babel read ts files instead of using ts-loader

---

src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/InlineError/InlineError.tsx
src/components/List/List.tsx

When investigating UXPin I found that it is sometimes quite picky about formatting of code it expects. In particular it doesn't really like it when you define a function and then export it later, and if the component's name doesn't match the name of the function.
Conveniently we follow their expectations 99% of the time so fixing these foibles is also improving our own consistency.
- Immediately export functions
- Rename the function in List to match the name of the component

Export classes immediatly instead of in a trailing line

---

UNRELEASED-V4.md
examples/create-react-app/src/tests/utils/enzyme.js
src/components/AppProvider/utilities/Intl/Intl.ts
src/components/Banner/Banner.tsx
src/components/Banner/tests/Banner.test.tsx
src/components/DropZone/DropZone.tsx
src/components/DropZone/components/FileUpload/FileUpload.tsx
src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
src/components/Link/Link.tsx
src/components/Modal/Modal.tsx
src/components/Page/Page.tsx
src/components/Pagination/Pagination.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
src/components/TopBar/tests/TopBar.test.tsx
src/test-utilities/document-has-style.ts
src/test-utilities/index.ts
src/test-utilities/legacy.tsx
src/test-utilities/react-testing.tsx
src/utilities/banner-context.tsx
src/utilities/capitalize.ts
src/utilities/clamp.ts
src/utilities/is-input-focused.ts
src/utilities/merge.ts
src/utilities/pick.ts
src/utilities/tests/capitalize.test.ts
src/utilities/tests/clamp.test.ts
src/utilities/tests/is-input-focused.test.tsx
src/utilities/tests/merge.test.ts
src/utilities/tests/pick.test.ts

To stay consistent. Occasionally we had default exports, other times we had named exports. This will keep all our utilities / test-utilities consistent.
* using named exports for utils/test-utils

[v4] Removed default exports from utils

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

(Try 2 for CodeCov) 
We're using the TextField component inside a very long form. When switching context (e.g. changing the form data but keeping the form), we need to update the values of the form..
When doing so, the `aria-live` state of the character counters is causing them to be read out one after another without any context. I'm setting the aria-live state to off unless the TextField has focus.
Feel free to slack `@emarchak` for more context on this. Related to the same problem as #1699.
I'm piggy-backing off of the existing `focus` state in the TextField component to toggle between `off` and `polite` to the character count.
1. Set up the playground with the following code. You'll get an input field with a character count and a button that says "Update textfield."
2. Boot up your …

[TextField] Improve TextField so that character count is only announced on focus.

---

UNRELEASED.md
src/components/Banner/Banner.tsx
src/components/Banner/README.md
src/components/Banner/tests/Banner.test.tsx

(Try 2 for CodeCov)
We're using the `Banner` component multiple times on a page to communicate information in a form. When switching context (e.g. changing the form data but keeping the form), we need to update the banners. 
When doing so, the `aria-live` state of the banners is causing them to be read out one after another. I'd like the option of turning `aria-live` off until we need it.
Feel free to slack `@emarchak` for more context on this.
Adding a new prop to the banner component, `stopAnnouncements` that allows devs to set `aria-live` to `off`.
1. Set up the playground with the following code. You'll get a warning banner that has a primary action that updates text.
2. Boot up your screen reader, and click the `Update banner` button. 
- You should hear the new content being read …

[Banner] Support disabling screen reader announcements when changing content.

---

UNRELEASED.md
src/components/ContextualSaveBar/README.md

Notify users that the Contextual Save Bar is now available through App Bridge directly
Update the docs
<details>
```jsx
render() {
return (
{/* Add the code you want to test …
```

[Contextual Save Bar]: updated embedded app docs

---

UNRELEASED.md
src/components/Card/README.md

Fixes #562
Adds an example of the card where custom buttons are added, similar to how they are used in some parts of Shopify. The example adds a secondary button and a plain button to the footer of the card.

[Card] Add example for card with footer action + plain button

---

src/components/ActionMenu/ActionMenu.scss
src/components/ActionMenu/ActionMenu.tsx
src/components/Page/components/Header/Header.scss

While building out some UI in my app, I realized that I stuck `margin-top` on the `ActionMenu` when in reality it should be up to the consuming parent how to provide spacing.
All I have done is simply move `margin-top` from `ActionMenu.scss` into `Header.scss`. The visual result within Polaris is exactly the same.
I'm keeping the negative `margin-left` as that is specifically for offsetting the action padding - so that spacing logic makes sense within `ActionMenu`.
Below is a gif of my app. This is with the **current ActionMenu** _(with `margin-top`)_. You can see me toggling the `margin-top` on/off. Once this PR merges, I won't have to worry about this spacing discrepancy.
Also, I have applied the `skip changelog` label, as there is no change for the end user, and the ActionMenu has not …

[ActionMenu] Move margin-top to Page > Header.scss

---

.storybook/config.js
UNRELEASED-V4.md
src/components/Page/components/Header/tests/Header.test.tsx
src/test-utilities/legacy.tsx
src/test-utilities/react-testing.tsx
src/test-utilities/tests/legacy.test.tsx
src/test-utilities/tests/react-testing.test.tsx

Fixes: #1709 - This will keep us on track in the future 🤓

[v4] Enable strict mode

---

UNRELEASED.md
src/components/DataTable/DataTable.scss
src/components/DataTable/DataTable.tsx
src/components/DataTable/components/Cell/Cell.tsx
src/components/DataTable/components/Cell/tests/Cell.test.tsx
src/components/DataTable/tests/DataTable.test.tsx
src/components/DataTable/types.ts
src/components/DataTable/utilities.ts

Fixes #1426 
The absolute positioning of the first column cells is no longer working across supported browsers, specifically Safari iOS (which means it doesn't work in any mobile browser in iOS). After @dleroux and I each explored other ways to accomplish the same UX with different CSS, there wasn't a clear path forward that doesn't cause other parts of the table to break. 
I concluded that the fixed column experience is not worth the hacks or tradeoffs needed to fix in iOS nor the risk of future breaks. Removing the fixed first column enables removal of all the excessive complexity that went into maintaining the default table behavior of row height change etc.
🗒 [General …

[DataTable] Remove fixed column UX

---

UNRELEASED.md
src/components/TextField/TextField.scss

Fixes #1739 
The use of `will-change` for the background of the text field segment button is causing paint loss on scroll when several textfields are rendered on a page in Chrome 75. This can be seen in production if you look at the Inventory list view at `/admin/inventory`.
This bug brings to light a greater issue with the use of `will-change` across the code base. I believe we are pre-maturely addressing performance issues where they don't exist, causing paint flash unintentionally. [MDN strongly advises against this](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change). Creating a separate issue for this.
Removes the `will-change` property from the `.Segment`, fixing the paint loss. This does not affect the performance of the transitions.
|---|---| …

[TextField][Segment] 🔥 will-change causing perf issues

---

src/components/Modal/README.md

The modal was fixed in the `open` state

[Modal] Fix example so the modal closes

---

UNRELEASED.md
config/rollup/index.js

Fix deprecation warnings in build output
Use mainFields option in node-resolve plugin to fix the following
warnings:
node-resolve: setting options.module is deprecated, please override options.mainFields instead
node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
node-resolve: setting options.main is deprecated, please override options.mainFields instead
- Checkout master do a build and copy it to a master-build folder `git checkout master && yarn && yarn run build && mv build master-build`
- Checkout this branch and do a build `git checkout simpler-sass && yarn && yarn run build`
- Diff the master-build and build folders `diff -ru master-build build`
- Note that there are no changes to the build (except the sass zip file differing but that's …

Fix deprecation warnings in build output

---

UNRELEASED.md
src/components/Link/Link.scss

Fixes #1724
The Link component is primarily intended for text links, but it can and is used for links around images and other content. Currently, all icons inside `Link` are set to the current text color, which doesn’t make sense except for text links
This problem was introduced in #1247 which adds an icon automatically for `external` links.
The fix is to scope the icon color change to the external link case only.
<details>
<summary>Copy-paste …

Avoid recoloring any old icon inside Link

---

UNRELEASED.md
config/rollup/index.js
config/rollup/plugins/styles.js
package.json
yarn.lock

This is the preliminary work on my investigation of how we can have a simpler and stricter sass build.
This simplifies the contents of our styles rollup plugin while retaining functionality identical to current build output. The one change is that the final item in `styles` objects that gets provided to js files
does not have a trailing comma.
e.g. 
```
const object = {
foo: "Foo",
bar: "Bar",
};
```
becomes
```
const object = {
foo: "Foo",
bar: "Bar"
};
```
This will make future changes easier to make and understand as there's less indirection and boilerplate.
- Prefer using sync APIs over async ones where possible (cssnano is the only case where a promise is required)
- Use JSON.stringify over an object instead of rolling our own version.
- Hardcode some values instead of them being …

Simplify the internals of our styles plugin

---

UNRELEASED.md
src/components/ChoiceList/ChoiceList.tsx
src/components/ChoiceList/tests/ChoiceList.test.tsx

It can be tedious to pass down a `disable` prop to each `choice` of a `<ChoiceList />`, especially when the component is wrapped, or when the list of choices is long.
Mentioned in [#114](https://github.com/Shopify/polaris-react/issues/114).
📹  https://www.youtube.com/watch?v=r6gPRukvCbQ&feature=youtu.be
<details>
```jsx
import …
```

[ChoiceList] Disable all choices at once

---

src/components/ResourceList/README.md

Only place in Polaris style guide that talks about filtering and sorting extensively doesn't show up on search right now because it's buried in h3/h4 headers.
Add filter and sort keywords so it's searchable on style guide.

Add filter and sort keywords to resource list page

---

src/components/Frame/Frame.tsx
src/components/Stack/Stack.tsx

Frame was missing this (it's implied by React.Component but we state
this in every other component with children and it's desired by UXPin)
Stack had the typing set to any which is way too broad (and
React.ReactNode is desired by UXPin)
Adds typing to Frame, and fixes the type on Stack
Ensure type-check still passes

Add children typing to Frame and Stack

---

UNRELEASED.md
src/components/Navigation/Navigation.scss
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/variables.scss

Fixes #1659
Wraps the item content, excluding sub-navigation items, in a non-wrapping flex container. Alignment of the content was changed to `flex-start` to ensure the badge stays where expected.
|---|---|
|<img width="230" alt="Screen Shot 2019-06-12 at 4 06 50 PM" src="https://user-images.githubusercontent.com/18447883/59452082-f556bc80-8dda-11e9-8703-ac00256af70b.png">|<img width="235" alt="Screen Shot 2019-06-12 at 4 03 59 PM" src="https://user-images.githubusercontent.com/18447883/59452115-08698c80-8ddb-11e9-820a-71c23d039e00.png">|
📄 …

[Navigation] Fix item secondary action wrapping

---

UNRELEASED-V4.md
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/Toast/Toast.tsx
src/hooks/use-deep-compare/use-deep-compare.tsx
src/types.ts
src/utilities/use-deep-callback.tsx
src/utilities/use-deep-compare-ref.tsx

StrictMode found an error in toast and is currently breaking it. `ToastManager` is currently relying on side-effects to work properly
* abstracting some of the logic in useDeepCompare to create useDeepCallback
* change toast manager logic
* add eslint ignore because we're smarter 🤔 
Check out toast examples in the deploy 😄 
If you want to see `Toast` not working check out `version-4.0.0` (doesn't currently have a deployment)

Fixed toast manager

---

UNRELEASED.md
src/components/Frame/Frame.scss
src/components/Frame/Frame.tsx
src/components/Frame/tests/Frame.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1746
Uses an actual link for the `skipToContent` link as opposed to a button.
This was done as opposed to using a `<Link>`or a `<Button>` with a URL because there's an issue with react router and anchors. By using an `<a>` 
<details>
```jsx
import {Page} from …
```

[Frame] Make skip to content link an actual link

---

UNRELEASED.md
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/Frame/components/ContextualSaveBar/components/DiscardConfirmationModal/tests/DiscardConfirmationModal.test.tsx
src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx

resolves: https://github.com/Shopify/polaris-react/issues/1052
Ensure the `DiscardConfirmationModal` gets closed when Discard is clicked.
<details>
```jsx
import {Page, Frame, ContextualSaveBar} from '../src';
render() {
return (
<Frame> …
```

[ContextualSaveBar] Add closing of confirmation modal

---

UNRELEASED-V4.md
src/components/Badge/Badge.tsx
src/components/Button/Button.tsx
src/components/ChoiceList/ChoiceList.tsx
src/components/Collapsible/Collapsible.tsx
src/components/DataTable/components/Cell/Cell.tsx
src/components/DataTable/components/Navigation/Navigation.tsx
src/components/DatePicker/components/Month/Month.tsx
src/components/Frame/components/ContextualSaveBar/components/DiscardConfirmationModal/DiscardConfirmationModal.tsx
src/components/Icon/Icon.tsx
src/components/Modal/components/CloseButton/CloseButton.tsx
src/components/Pagination/Pagination.tsx
src/components/ProgressBar/ProgressBar.tsx
src/components/ProgressBar/tests/ProgressBar.test.tsx
src/components/ResourceList/components/CheckableButton/CheckableButton.tsx
src/components/Sheet/Sheet.tsx
src/components/Spinner/Spinner.tsx
src/components/Tag/Tag.tsx

Hooks! Hooks! Hooks!
Death to withAppProvider! Death to withAppProvider! Death to withAppProvider!
Many of our components are already functions, but got wrapped with withAppProvider to provide translations. This PR changes them to use the `useI18n` hook so we avoid the need for the withAppProvider HoC.
Class components haven't been touched, so we're still using withAppProvider in plenty of places, but this targets the components where this change is easy to make.
Check everything still gets translations

[v4] Use hooks in components where it's easy

---

UNRELEASED.md
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/tests/Tooltip.test.tsx

Fixes #1782.
MouseEnter events are not triggered when cursor enters from a disabled element.
Uses MouseOver with a "mouseEntered" boolean flag rather than MouseEnter.
<details>
```jsx
import {Page, Tooltip} from '../src';
render() {
return (
<button type="button" disabled>
Previous
</button>
<Tooltip content="Next">
<button type="button">Next</button>
</Tooltip>
</Page>
);
}
}
```
</details>

[Tooltip] Implement fix for MouseOver event not firing when cursor enters after leaving a disabled element

---

UNRELEASED.md
src/components/DataTable/DataTable.scss
src/components/DataTable/DataTable.tsx
src/components/DataTable/components/Cell/Cell.tsx
src/components/DataTable/tests/DataTable.test.tsx
src/components/DataTable/types.ts

Fixes https://github.com/Shopify/polaris-react/issues/1789
There is no good way to adjust the vertical alignment of text in `DataTable` cells:
This PR adds a `verticalAlign` prop to `DataTable` that controls the vertical alignment of content in the cells.
Possible values are `top`, `bottom`, `middle`, and `baseline`, mirroring the [possible CSS values](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align#Values_for_table_cells).
To preserve backwards-compatibility, the default value is `top`.

[DataTable] Add vertical alignment prop

---

src/components/Link/Link.tsx

#1247 made Link be wrapped in withAppProvider as it needed translations. It also passed down that prop to UnstyledLink, however UnstyledLink is already wrapped in withAppProvider which already handles passing in the polaris context.
Having Link pass that through isn't needed
Stopping passing polaris into UnstyledLink
View the external Link example and see it still gets a translation in the aria label.

Don't pass polaris from Link into UnstyledLink

---

src/components/Button/README.md
src/components/ButtonGroup/README.md

([Project themes](https://vault.shopify.io/projects/8503): *Accuracy**, **Discoverability**)
This PR removes repetitious content and adds cross links. 
This helps to make content easier to maintain and ensures that the right information is available to everyone, regardless of where they're looking in the style guide (components section vs content section). 

[Content] Add cross link to button content guidelines

---

scripts/new-version-pr-generator.js

The description for the PR automatically opened in `web` after a release doesn't include tophatting instructions. Specifically, the instructions for tophatting with production assets, which is required when upgrading key dependencies like `polaris-react`.
Adds the pre-deploy self-checklist and prod asset tophatting instruction link to the template.

[Shopify/polaris-bot] Update post-release web upgrade PR description

---

UNRELEASED.md
src/components/Filters/Filters.tsx
src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
src/components/Filters/components/ConnectedFilterControl/components/Item/Item.tsx
src/components/Filters/components/ConnectedFilterControl/components/Item/tests/Item.test.tsx
src/components/Filters/components/ConnectedFilterControl/tests/ConnectedFilterControl.test.tsx
src/components/Filters/tests/Filters.test.tsx

We still need this syntax for the moment in v3, before we change to `import React` in v4.
This is because this syntax requires the consuming project to set `allowSyntheticDefaultImports` or `esModuleInterop` (which implies `allowSyntheticDefaultImports`) in their typescript options. It's an acceptable breaking change in v4 as the [typescript team recommends setting esModuleInterop](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop) for all projects, and it's only a flag for backwards compatibility reasons.
Fixes #1818
Replaces `import React` with `import * as React`

Use `import * as React` in Filters

---

UNRELEASED.md
src/components/Frame/Frame.tsx
src/components/Frame/tests/Frame.test.tsx

In this PR: https://github.com/Shopify/polaris-react/pull/1785 We added focus to the `<main>` element by adding tabIndex={-1}. This broke the Polaris-rails popover. In rails clicking the popover sends the target and hides the popover if the target isn't inside a popover. Adding the tabIndex on the main element made it the target, therefore always closed the popover.
Fixes #1816
Adding an `<a>` tag at the beginning of the content and focusing it instead.
To test this properly it is best to do it web.
1. Start web
2. In polaris-react: `yarn build-consumer web`.
3. Tab to the skip to content link and click it. You should skip to the content. Also, use voice over to ensure the correct text is being read.
<details> …

[Skip to content] Fix tabIndex issue

---

src/components/Link/Link.tsx

Death to withAppProvider, follow up to #1797 and #1805
Stops wrapping Link with withAppProvider
Test external link icon label still gets a translation

[v4] Hookify Link component

---

src/components/AccountConnection/README.md
src/components/ActionList/README.md
src/components/Avatar/README.md
src/components/Badge/README.md
src/components/DatePicker/README.md
src/components/Layout/README.md
src/components/List/README.md
src/components/PageActions/README.md
src/components/SettingToggle/README.md
src/components/TextField/README.md

([Project themes](https://vault.shopify.io/projects/8503): **Style** )
Latin abbreviations:
- are more likely to be unfamiliar than English phrases 
- can make content more difficult to localize or internationalize
Removing the following Latin abbreviations, often replacing them with English phrases: 
- e.g. 
- etc.
- ie.

[Content] Remove Latin abbreviations from component pages

---

src/components/Avatar/tests/Avatar-ssr.test.tsx
src/components/Avatar/tests/Avatar.test.tsx
src/components/ColorPicker/tests/ColorPicker-ssr.test.tsx
src/components/ColorPicker/tests/ColorPicker.test.tsx
src/utilities/with-app-provider.tsx

Lots of indentation looks silly and it's a pain in React devtools, lets use hooks instead of render props in withAppProvider so we have a single wrapping component instead of 5.
Uses hooks in withAppProvider's wrapping component to save on indentation and nesting of components in the React devtools.
This didn't play nice with how we overrode isServer in
server-side-rendering tests due to funky mocking. Splitting the mocks
out into separate files fixes this. Strictly speaking this only caused
problems in Avatar as it is a functional component, but I figured lets
preemptively fix ColorPicker's test too
Confirm various AppProvider functionality still works:
- setting translations
- setting links
- settings themes
- scrolling / sticky managing

Hooky withAppProvider

---

UNRELEASED.md
src/components/ActionList/ActionList.scss

Fixes https://github.com/Shopify/polaris-react/issues/1835
Before | After
----------|----------
Uses the `recolor-icon()` mixin to recolor the icon for destructive ActionList items. 
Please see the _Action list with destructive item_ example in Storybook.

[ActionList] Fix color of icon in destructive ActionList item

---

package.json
src/test-utilities/matchers/index.ts
src/test-utilities/matchers/types.ts
tests/each-test.ts
tests/matchers/index.ts
tests/matchers/props.ts
tsconfig.json
yarn.lock

Sorry, I missed the PR where we added react-testing.
I noticed a few things that I dislike:
- ~`The test-utilities folder should only contain things we want to share with the world to make their test harnesses easier to work with Polaris. Matchers should be private to only our tests, we don't want anybody else to use them, so they shouldn't live in the src folder.~ The test-utilities folder should only contain things we need to import in our test files, matchers get imported by each-test.ts, so they should live in the tests folder
- Our own custom matchers are cool but I'd like to try and stick with using the ones `@shopify/react-testing` provides until it is clearly untenable. `toBeDisabled()` can be trivially implemented as `.toHaveReactProps({disabled: true})`, I don't think saving …

[v4] Change matcher layout

---

UNRELEASED.md
src/components/Autocomplete/components/TextField/TextField.tsx

Fixes #1834
Allows users to set Autocomplete.TextField's autoComplete prop that gets passed into TextField
In the playground, create an Autcomplete with user-defined autoComplete field, and see that value is applied to the rendered input element. See code below.
<details>
```jsx
import {Page, Autocomplete} from '../src';
render() {
const noop = () => {};
const textField = (
<Autocomplete.TextField
label="Tags"
value=""
placeholder="Search"
onChange={noop}
autoComplete="braaaap"
/>
);
return (
<Autocomplete
textField={textField}
options={[]}
selected={[]} …
```

Allow Autocomplete.TextField's autoComplete to be overridable

---

src/components/Card/README.md

Card's `secondaryFooterAction` prop is deprecated, let's not use it in our readmes
Use `secondaryFooterActions` instead of `secondaryFooterAction`
Check `Card => Card with destructive footer action` example renders the same as before and no longer throws a deprecation notice

Update Card README to not used deprecated prop

---

src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/tests/Collapsible.test.tsx

This was the original functionality and some tests in consuming apps relied on this. 
Content is no longer rendered when exited
https://cl.ly/5b62ec0b699a
Check the animation in the chrome dev tools 🔍

[Collapsible] Hide content when exited

---

UNRELEASED-V4.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx

Removing some odd aliases when people should use the original
Instead of using Autocomplete.ComboBox.TextField use Autocomplete.Textfield
Instead of using Autocomplete.ComboBox.Optionlist use Optionlist
I can't see any point where people used these component aliases and triggering a deprecation warning for them is convoluted as it requires creating intermediate components so I'm going to skip that.
Removes those two static definitions
Check Autocomplete still works

[v4] Remove unwanted subcomponent aliases in Autocomplete Combobox

---

UNRELEASED-V4.md
src/components/Card/Card.tsx
src/components/Card/README.md
src/components/Card/tests/Card.test.tsx
src/components/Navigation/README.md
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx
src/components/Select/Select.tsx
src/components/Select/tests/Select.test.tsx
src/styles/shared/lists.scss

Removing deprecated functionality that we said we'd remove in v4
- Remove `secondaryFooterAction` prop on `Card`
- `iconBody` prop on `Navigation`
- `groups` prop on `Select`
- `plain-list` sass mixin
Ensure the above items continue to work by checking tests
Search the codebase for other deprecated functionality and ensure the only ones left are things that will go in v5 (namely app-bridge related things)

[v4] Remove deprecated functionality

---

src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
src/components/Loading/tests/Loading.test.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/Page/tests/Page.test.tsx
src/components/ResourcePicker/tests/ResourcePicker.test.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/components/Toast/tests/Toast.test.tsx
src/components/TopBar/tests/TopBar.test.tsx
src/components/UnstyledLink/tests/UnstyledLink.test.tsx
src/test-utilities/PolarisTestProvider.tsx
src/test-utilities/legacy.tsx
src/test-utilities/react-testing.tsx
src/test-utilities/types.ts
src/utilities/theme/context.tsx
src/utilities/theme/hooks.tsx
src/utilities/theme/index.ts
src/utilities/theme/utils.ts

Tweaking some of our test and context config to make it a bit less verbose, so you have half a chance of understanding what is happening.
- Simplify args of mountWithAppProvider in legacy tests - There's no need to nest the context values inside another object. This API matches the modern testing API for custom mounts.
-  Stop exporting the Theme context type from utilities/theme - Consuming sites should use `React.contextType<typeof ThemeProviderContext>` like the calling sites of all other contexts we provide
- Rename ThemeProviderContext to ThemeContext  - All our other provided contexts don't have Provider in their name, neither should this
- Make legacy withAppProvider use the modern types - Have a single suite of types for our mounting functions in enzyme and react-testing instead …

[v4] Further test and context tidying

---

tests/setup.ts

AppBridge related deprecation warnings are super noisy and make test
output hard to scroll through. Silence them so they don't get in the
way.
Overrides `console.warn` with a version that ignores AppBridge related deprecation warnings.
Check the console output for a `yarn build` and see that it's not full of warnings. (there are still some there, but all the AppBridge related noise is quietened.

Ignore deprecation noisy deprecation warnings in tests

---

UNRELEASED.md
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/tests/Checkbox.test.tsx
src/components/ChoiceList/ChoiceList.tsx
src/components/ChoiceList/README.md
src/components/ChoiceList/tests/ChoiceList.test.tsx
src/components/InlineError/InlineError.tsx
src/components/InlineError/index.ts
src/components/InlineError/tests/InlineError.test.tsx
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/tests/RadioButton.test.tsx
src/components/index.ts

Fixes https://github.com/Shopify/polaris-react/issues/1589
1. add `ariaDescribedBy` prop to Checkbox and RadioButton
2. remove `aria-describedby` from the ChoiceList fieldset 
3. updated the ChoiceDescriptor with a `describedByError` key to indicate whether to link the Error to the input or not.
4. added some tests
Using the playground, ensure the radio buttons `aria-describedby` attribute matches the ID of the error field.
<details>
```jsx
import {Page, ChoiceList} from '../src';
render() {
return (
<ChoiceListExample />
</Page>
);
}
}
class ChoiceListExample …
```

[ChoiceList] Connecting the ChoiceList error the input with errors via describedByProp

---

package.json
src/utilities/with-app-provider.tsx
yarn.lock

Filters.test.tsx caused the above error due to us using an old version
of hoist-non-react-statics
[Example of a build containing this error](https://circleci.com/gh/Shopify/polaris-react/23684?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
Update the version of hoist-non-react-statics we use.
Remove a pointless reassign of contextTypes - I'm pretty sure we won't ever need this.
Check the test output, see there is no "Function components do not support contextType" error

[v4] Fix "Function components do not support contextType" error in tests

---

UNRELEASED.md
src/components/Tabs/Tabs.scss
src/components/Tabs/Tabs.tsx
src/components/Tabs/components/Panel/Panel.tsx
src/components/Tabs/tests/Tabs.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1577
Our tabs generate an aria-control that points to tab panels that don't exist because only render the selected tab.
This generates all Panel and adds a `display: none` on the tabs that aren't selected.
To top hat, simply go to the Tab example in the playground and ensure that the value of the `aria-controls` prop of each tab (on buttons) matches the corresponding id of the panel content.
<details>
```jsx
render() {
return ( …
```

[Tabs] Fix Tabs accessibility issue

---

src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/PositionedOverlay/PositionedOverlay.tsx

Fixes #1799
* removing the problem div that's causing the positioning issue
* passing our animation class names to the overlay, similarly to how react-transition-group handles it
* consume the classes in overlay
https://cl.ly/b64fde6f30e9
Check out some popover examples in the deployment to see if the animation is still 👌
Skipping a changelog entry since this bug hasn't shipped

[v4] Fixed popover overlay positioning

---

src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.tsx

Overflow content remains hidden
Applying overflow visible like was [previously done](https://github.com/Shopify/polaris-react/pull/902/files#diff-2ebd5f6d700a607bf58b3c27882b28f5L23)
* Open filters example
* Open sheet
* Open money spent filter
* Do the "tooltips" show?

[v4][Collapsible] Fix collapsible regression

---

package.json
yarn.lock

Keeping up  to date, making a good base for #1829 
Updates SK
Dedupes browserslist dependency
This results in a near-identical build, the only change is that vendor prefixes for `-moz-fit-content` have been dropped as they are no longer needed - this was only used in Stack
- `git checkout master && yarn && yarn run build && mv build master-build`
- `git checkout sk-bump is && yarn && yarn run build`
- `diff -ru master-build build` and note that JS files are identical and the css file changes only mention -moz-fit-content
Check linting and tests still pass

Bump sewing-kit to latest

---

UNRELEASED.md
config/typescript/images.d.ts
config/typescript/styles.d.ts
tsconfig.json

We now have [base typescript configurations](https://github.com/Shopify/sewing-kit/tree/master/packages/typescript-configs) that project can pull in.
I am using polaris here as a test for library project. 
Note that `@shopify/typescript-configs` actually come with the latest sewing-kit. 
However I am too afraid to update sewing-kit myself so I pull in `@shopify/typescript-configs` separately instead.
As long as type-check passed we are all …

🔥 add base tsconfig

---

UNRELEASED-V4.md
src/components/Autocomplete/tests/Autocomplete.test.tsx
src/utilities/app-bridge/tests/app-bridge.test.ts
src/utilities/tests/app-bridge-transformers.test.ts
tsconfig.json

Tightening up our TS config
Fixes #1881
- Enables esModuleInterop (it's enabled in the base config, and allowSyntheticDefaultImports can be removed as that is implied to be true if esModuleInterop is set)
- Enables strict mode (its enabled in the base config). We still have quite a lot of violations for strictFunctionTypes and strictPropertyInitialization and the fixes aren't as trivial as the others in this PR so I've disabled those for now and we can tidy them up later. I expect most of the strictPropertyInitialization issues to go away as we migrate to hooks
- Changes module type to be the default (which is esnext, but that only allows for `import()` functions which recently hit stage 4 so it's stable anyway)
Check type-check and tests pass. Ensure the output of the esnext folder is …

Improve tsconfig

---

UNRELEASED.md
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/Frame/components/ToastManager/tests/ToastManager.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1215
In order to announce the Toast using the aria-live attribut, NVDA require the element with the aria-live prop to be on screen when the content changes.
Our Toasts are wrapped in a Toast manager. This pr moves the aria-live attribute from the Toast to the Toast Manager    
Using NVDA (on windows) navigate to:
http://localhost:6006/?path=/story/all-components-toast--basic-toast
and ensure that the Toast messages are being announced.
<details>
```jsx
render() {
return (
<Page …
```

[ToastManager] Move aria-live to containing div for a11y using NVDA

---

UNRELEASED.md
src/components/Page/README.md
src/components/Page/components/Header/Header.scss
src/components/Page/components/Header/Header.tsx
src/components/Page/components/Header/components/Title/Title.scss
src/components/Page/components/Header/components/Title/Title.tsx
src/components/Page/components/Header/components/Title/index.ts
src/components/Page/components/Header/components/Title/tests/PageTitle.test.tsx
src/components/Page/components/Header/components/index.ts
src/components/Page/components/Header/tests/Header.test.tsx
src/components/Page/tests/Page.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1711 and adds a subtitle prop
Add 2 props to page: Thumbnail and Subtitle.
We opted with props for now until we get time to investigate the best approach to have more composable components.
<details>
```jsx
import {PageDownMajorMonotone} from '@shopify/polaris-icons';
import …
```

[Page] Add thumbnail and subtitle to Page

---

scripts/new-version-pr-generator.js

Changes to the `new-version-PR-generator` script made in #1815 currently apply to PRs opened in the `polaris-styleguide` as well as in `web`, but were only meant for `web`.
Updates the changes to the `new-version-PR-generator` script made in #1815 to only apply to upgrade PRs opened in `web`.

[scripts] Only add prod asset checklist to post-release upgrade PRs in web

---

src/components/Navigation/components/Item/tests/Item.test.tsx
src/test-utilities/legacy.tsx

Fixes one of the two warnings in #1898
Wraps a trigger in act.
Migrating this whole file to use modern testing looked like it'd take a while so here's a stopgap.
Check Navigation Item test no longer emits the warning detailed in #1898

Use act in Navigation Item test to fix warning

---

UNRELEASED-V4.md
src/components/Modal/Modal.tsx
src/components/Modal/tests/Modal.test.tsx
src/components/Tabs/Tabs.tsx

Fixes #1788 
These components are never used or documented publicly and should be
part of our internal API. These have never been used in the wild in the
Shopify org.
Removing the ability to do `<Modal.Dialog>` and `<Tabs.Panel>`

Remove Modal.Dialog and Tabs.Panel public subcomponents

---

src/components/PolarisTestProvider/PolarisTestProvider.tsx
src/components/PolarisTestProvider/index.ts
src/components/PolarisTestProvider/tests/PolarisTestProvider.test.tsx
src/components/index.ts
src/index.ts
src/test-utilities/legacy.tsx
src/test-utilities/react-testing.tsx

Our `test-utilities` folder is being [deleted in `web`](https://github.com/Shopify/web/blob/68750baa3c14bf7390045d260430309d37cdde12/scripts/builder/delete-test-files.sh#L6). I'm temporarily moving `PolarisTestProvider` into `src/components` until node_modules are ignored.

Move PolarisTestProvider into components

---

src/components/Scrollable/Scrollable.tsx
src/components/Scrollable/components/ScrollTo/ScrollTo.tsx
src/components/Scrollable/components/ScrollTo/tests/ScrollTo.test.tsx
src/components/Scrollable/context.ts
src/components/Scrollable/tests/Scrollable.test.tsx
src/utilities/with-app-provider.tsx

This removes the need for the WithScrollable HoC in withAppProvider,
leading to a drastically simpler withAppProvider implementation.
Moves the responsibility for creating a new StickyManager into Scrollable
Simplify SrollableContext - It's a single value so there is no value to nesting it in an object.
Also use a named export for the context as we're moving towards that for everything
Add the following to the playground, scroll up and down and see that the sticky paragraph sticks to the top of the scrollable area
Ensure that the Scrollable -> ScrollTo example still works by jumping to the mid point scroll position
<details>
```jsx
import {Page, Scrollable, Sticky} from '../src'; …
```

[v4] Override StickyManager context in Scrollable

---

src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/context.tsx
src/components/Autocomplete/components/TextField/TextField.tsx
src/components/DropZone/DropZone.tsx
src/components/DropZone/components/FileUpload/FileUpload.tsx
src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
src/components/DropZone/context.tsx
src/components/Filters/Filters.tsx
src/components/Navigation/Navigation.tsx
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx
src/components/Navigation/components/Section/tests/Section.test.tsx
src/components/Navigation/context.tsx
src/components/Navigation/tests/Navigation.test.tsx
src/components/RangeSlider/utilities/index.ts
src/components/RangeSlider/utilities/invertNumber.ts
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/components/FilterControl/FilterControl.tsx
src/components/ResourceList/components/FilterControl/tests/FilterControl.test.tsx
src/components/ResourceList/components/Item/Item.tsx
src/components/ResourceList/components/Item/tests/Item.test.tsx
src/components/ResourceList/context.tsx
src/components/ResourceList/index.ts
src/types.ts

Default exports are low-key annoying as you need to name something
every time you import it instead of using the existing name.
Let's name our things once, and make sure all our contexts follow that same pattern
After this PR the only files that continue to use named exports shall be:
- Component files (e.g. src/components/Button/Button.tsx)
- Component file indexes (e.g. src/components/Button/index.ts) (I've got a plan for removing default exports in these but that should wait till after we get v4 merged)
- src/components/Scrollable/context.ts - This will be converted to use named exports only in #1908
- src/components/Frame/context.tsx - This will be converted to use named exports only in #1906
Use named exports for context (oh and that one utility that was still using a default …

[v4] Use named exports for contexts and utilities

---

config/rollup/plugins/styles.js
tests/build.test.js

There is no value in having individual files per component in the styles
folder. It is unneeded overhead and people shouldn't be digging into
that folder trying to include a single component's styles in the first place.
Where styles/components.scss previously was a list imports to
per-component files, instead inline the contents of the per-component scss
into styles/components.scss. The listing of the contents is preserved so
the computed css out the other end will be idential.
At this point global.scss and components.scss both contain pure css.
They are only distributed as scss files for the sake of convinience and
ease of @importing (I have future plans to potentially simplify this further but that's a story for another day).
Run `yarn run build` and see the `styles/components` folder …

[v4] Styles build: combine all components into one file

---

UNRELEASED-V4.md
src/components/ResourceList/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx

Noticed this wasn't working while 🎩 a change
We cast the type of our ref so we don't have to do an existence check.
* Remove typecast as it's no longer needed
* Add check to see if the ref exists
This example will fail on version-4.0.0 but work in this branch 👍 
<details>
```jsx
import {
Page,
ResourceList,
Card,
AppliedFilter,
FilterType,
Modal,
Button,
import {autobind} from '@shopify/javascript-utilities/decorators';
const items: any[] = [
{
onClick: true,
url: 'https://www.google.com',
actions: [{content: 'View listing', url: 'http://www.facebook.com'}],
title: 'Has url, onClick, and actions',
},
{
onClick: false,
url: 'https://www.google.com', …
```

[v4][ResourceList] Add existence check to ref

---

UNRELEASED.md
src/components/ActionMenu/ActionMenu.tsx
src/components/ActionMenu/components/MenuAction/MenuAction.tsx
src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx
src/components/ActionMenu/components/RollupActions/RollupActions.tsx
src/components/ActionMenu/tests/ActionMenu.test.tsx
src/components/Page/components/Header/Header.tsx
src/types.ts

Fixes #1889
When the actions from `Page` `Header` were extracted into a separate component called `ActionMenu`, the types of `Page.secondaryActions` and `Page.actionGroups.actions` were accidentally combined into a single type called `MenuActionDescriptor`. Properties like `badge` and `helpText` are only supported in the items of action lists (which `actionGroups` render as).
Fixing the types for `MenuAction` and `MenuGroup` to align with `Page.secondaryActions` and `Page.actionGroups` again.
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/mast …

[ActionMenu] Fix type sharing between MenuAction and MenuGroup.actions

---

UNRELEASED-V4.md
src/components/DropZone/tests/DropZone.test.tsx
src/components/Frame/Frame.tsx
src/components/Icon/Icon.tsx
src/components/Loading/Loading.tsx

[v4] Minor changes to bump test coverage slightly

---

UNRELEASED-V4.md
src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/tests/Collapsible.test.tsx

Resize event doesn't fire divs. Another test to boost coverage and confidence ✌️
* switching the resize event from ref -> window
* adding additional test

[v4][Collapsible] Polish - resize bug/test

---

UNRELEASED.md
src/components/index.ts

Missed this one and needed for https://github.com/Shopify/web/pull/15425
Exporting the interfaces for filters and applied filters so they can be imported by consumers

[Filters] Export interface for filters and applied filters

---

CHANGELOG.md
UNRELEASED.md
src/components/ActionMenu/ActionMenu.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1849
This PR toggles the `activeMenuGroup` in the `ActionMenu` when clicking the secondary action trigger. This allows an open `Popover` to be closed when clicking the secondary action trigger while it is open.
Here are some videos to illustate:
<details>
```jsx
import {Badge, Page} …
```

[ActionMenu] Toggle activeMenuGroup when clicking secondary action trigger

---

src/components/Page/components/Header/tests/Header.test.tsx

Rerun Percy without pushing to master (v4 master 😛)

Remove unused spread operator

---

UNRELEASED.md
src/components/Badge/Badge.scss

Fixes #1749 
Uses a linear gradient for the fulfilled badge pip instead of a background color (currentColor doesn't work on backgrounds in Edge, only text and images, so linear gradient works since they are processed by Edge as images).

[Badge] Fix progress pip high contrast color

---

src/components/ResourceList/README.md

A `placeholder` prop was added to `FilterControl` in #1257, but is missing from the prop list in the docs.
Adds `placeholder` to the `FilterControl` prop list.

[ResourceList.FilterControl] Add placeholder to prop list

---

src/components/Navigation/README.md

We have two duplicated documentation of navigation with separator:
> Navigation with sections and separator
> Navigation with section separator
Removing duplicated examples

Remove duplicated example for navigation with separator

---

src/components/ContextualSaveBar/ContextualSaveBar.tsx

Save action and discard action are compared by reference and could fail an object is comparison so this will reduce unnecessary renders

[ContextualSaveBar] Changed useEffect to useDeepEffect

---

src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/OptionList/OptionList.tsx
src/components/Toast/Toast.tsx
src/utilities/use-deep-effect.tsx

Follow up to #1938.
That PR renamed the files but didn't rename the exported function
Renames `useDeepCompare` to `useDeepEffect` to match the filename

Rename export from use-deep-effect to be useDeepEffect

---

UNRELEASED.md
src/components/Button/Button.scss
src/components/Link/Link.scss

Fixes https://github.com/Shopify/polaris-ux/issues/147
The current hover/focus styles rely on a change in color alone which isn't visible in Windows High Contrast, and may be difficult for other low vision users to distinguish. An underline that's displayed when a user starts to interact with the link would help cement the idea that it's a link and clarify exactly what that particular link does.
Add underline to Links and Plain button on hover, so it doesn't rely on color alone for accessibility.
📄 [Changelog …

[Link, Plain button] Add underline to Links and Plain button on hover

---

UNRELEASED.md
src/components/Filters/Filters.tsx
src/components/Filters/tests/Filters.test.tsx

Current functionality in web relies on an `onQueryFocus` callback on the ListFilters component in polaris-next. This is used to instrument the search behaviour, where a focus event on the query field indicates the beginning of the users intent to search.
Tim's excellent PR to replace the polaris-next ListFilters with the proper Filter component from Polaris means we can no longer do this. (see https://github.com/Shopify/web/pull/15425#discussion_r311870970)
Adding a callback to the Filters component to be triggered when the query field is focused.

[Filters] Add onQueryFocused callback

---

UNRELEASED.md
a11y_shitlist.json
src/components/Tabs/README.md
src/components/Tabs/Tabs.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1577
This issue was missed the original pr. Our tab component uses list items with buttons for the tabs but the role of presentation on them was causing a11y issue because the child element had semantic meaning.
This PR removed the presentation role and removes the rule from the shitlist.
If a11y tests then ✅

[Tabs] remove presentation role from list item

---

src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.tsx
src/components/Collapsible/tests/Collapsible.test.tsx

Fixes #1950
* Using our old style of collapsing content to manage nested animations
[link](https://cl.ly/6a78aec92904)
Playground with nested collapsible's below
<details>
```jsx
import {Page, Collapsible, Button} from '../src';
function Playground() {
const [open, setOpen] = useState(false);
const [openChild, setOpenChild] = useState(false);
const divStyle = {
backgroundColor: 'red',
};
const parentStyle = {
backgroundColor: 'blue',
};
return (
<Collapsible id="parent" open={open}>
<div style={parentStyle}>
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever …
```

[Collapsible] Fixed nested Collapsible animation

---

.eslintignore
.gitignore
.prettierignore
.stylelintignore
.vscode/settings.json
package.json
scripts/build.js
tests/build.test.js

Maintaining our own CDN distribution of our CSS files is a little annoying as it leads to more complex builds. Let's let unpkg handle our CDN styles.
The first step to that is adding minified styles into npm package - that's this PR.
The second step is ripping out our build config that uploads files to sdks.shopifycdn.com and updates our links to unpkg.com files (that'll be a new PR after we do an RC containing this change)
Adds `styles.min.css` to our npm package
- Run `yarn run build` and see that `styles.min.css` is generated
- Run `npm pack` then extract the generated tgz and see that styles.min.css is included in the package folder
- See that `styles.min.css` is excluded from git and linting configs
- See that running `yarn run clean` deletes `styles.min.css`

Add minified styles to npm package

---

src/components/Collapsible/Collapsible.tsx

It turns out all of the types may be broken on components that use `getDerivedStateFromProps` however they've all been using `withAppProvider` which is forcing a correct type. Whether it's a web issue or a `@types` issue, this will solve it short term.

Fixed getDerivedStateFromProp type with cast

---

.circleci/config.yml
.storybook/config.js
.storybook/stories-from-readme.js
UNRELEASED.md
package.json
yarn.lock

[Chroma](https://www.chromaui.com/) is a hosted platform for Storybook stories, which is free for open-source projects. Let's leverage that instead of hosting our own jerry-rigged versions of deployed storybooks using heroku.
Chroma lets us see the stories on our master branch and PRs (like our old solution) but also allows us to see peek into the history of our components on any commit too.
Using this off-the-shelf solution means other component library teams can easily copy our config and get the same great tooling without needing to host any of their own infrastructure.
Read their introductory blog post for more information: https://blog.hichroma.com/introducing-storybook-loop-6bac7bd0a85b (ChromaUI is the rebranded name of "Storybook loop")
- Adding Chroma config to our storybook …

Add ChromaUI integration

---

UNRELEASED.md
src/components/Collapsible/tests/Collapsible.test.tsx
src/components/Focus/tests/Focus.test.tsx
src/components/Tabs/components/TabMeasurer/tests/TabMeasurer.test.tsx
src/components/TrapFocus/tests/TrapFocus.test.tsx

At some point, these mocks became redundant, lets strip away this extra code

Removed mocks that are no longer needed

---

UNRELEASED.md
a11y_shitlist.json
src/components/ResourceList/README.md
src/components/ResourceList/components/Item/Item.tsx

Fixes **Shortcut actions** part of  https://github.com/Shopify/polaris-react/issues/792
**Shortcut actions**
1. Smaller-breakpoint, persistent shortcut action buttons have no text equivalent for the ... icon. Screen reader users may not be able to tell what the button does.
2. Controls that repeat for persistent shortcut actions for each list item do not have unique text. Non-visual users may have difficulty distinguishing which resource item they relate to as they tab through the controls and hear them read.
For item 1 the wrong attribute was being added to the button so changing it to `aria-label` to `accessibilityLabel` makes the already translated label appear. However @dpersing you suggested a label like: "Actions for Mae Jemison". Since we don't have control over what people put in …

[ResourceList] Make item actions accessible

---

README.md
UNRELEASED.md

We've added two new examples and removed one so let's get this update!

[docs] Updated example section

---

UNRELEASED.md

Test helpers are a little different to UX components, and it is not
documented with a README so don't announce it as a new component.
Move PolarisTestProvider changelog item into the `Development workflow` section.

Downplay PolarisTestProvider in changelog

---

UNRELEASED.md
src/styles/shared/_buttons.scss

Resolves #1541
Removes `tap-highlight-color` for buttons. This looks nice for our default button, but I think our other buttons need some work.
|😄|😐|😞|
|---|---|---|
|![default button active](https://user-images.githubusercontent.com/344839/58121550-8cee3400-7bbc-11e9-8606-1ac8465998e6.gif)|![primary button active](https://user-images.githubusercontent.com/344839/58121554-8d86ca80-7bbc-11e9-9b4f-eea5b76180b9.gif)|![plain button active](https://user-images.githubusercontent.com/344839/58121553-8d86ca80-7bbc-11e9-9132-a0a9088c090a.gif)|

[Button] Remove tap-highlight-color for buttons

---

UNRELEASED.md
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
src/components/Autocomplete/tests/Autocomplete.test.tsx

Need to fix keyboard navigation and item selection in Autocomplete combo box.
Fixes #1380. Fixes #1346  
Added an EventListener for the `keydown` event and only use the handler to track the Enter key events. This prevents any `submit` events from being triggered on Enter key press inside the combo box. `stopPropagation()` does not seem to work in this case. 
https://stackoverflow.com/questions/895171/prevent-users-from-submitting-a-form-by-hitting-enter  - `The keydown event is preferred over keyup as the keyup is too late to block form submit`
📄 [Changelog …

[Autocomplete]Fix keyboard navigation and item selection in Autocomplete combo box.

---

UNRELEASED.md
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx

Fixes a bug where the context bar actions are overflowing when the content is too long.
Tweaks the styles to prevent the actions from shrinking. Instead forcing the message to shrink further. I think there is a separate issue for the fact that the message gets truncated on smaller screens.
| Before  | After |
| ------------- | ------------- |
| <img width="344" alt="Screen Shot 2019-08-14 at 1 44 53 PM" src="https://user-images.githubusercontent.com/4441303/63043632-9d037000-be9a-11e9-83af-3779390577c3.png"> | <img width="350" alt="Screen Shot 2019-08-14 at 1 43 01 PM" src="https://user-images.githubusercontent.com/4441303/63043725-cd4b0e80-be9a-11e9-943f-1fb440ccedab.png"> |
🗒 …

[ContextualSaveBar] Prevent context bar actions from shrinking

---

src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

I switched the sort select to use an inline label in #1774, but did not hide the label on small screen.
|Before|After|
|---|---|
|<img width="431" alt="Screen Shot 2019-08-18 at 3 07 38 PM" src="https://user-images.githubusercontent.com/344839/63231119-c3dbe200-c1cb-11e9-8980-3944f5c1440a.png">|<img width="422" alt="Screen Shot 2019-08-18 at 3 07 43 PM" src="https://user-images.githubusercontent.com/344839/63231121-cdfde080-c1cb-11e9-807f-614278a9e480.png">|
Tracking `smallScreen` in state and using the existing resize handler to set it. If `smallScreen` is true then hide the inline label. Not adding a changelog entry as the inline label change has not yet been released.
Bonus: bumps the test coverage by 3% for resource list.

[Resource list] Hide inline label on small screen

---

src/components/ResourceList/ResourceList.scss

The use of these styles was removed in #1774

[Resource list] Remove unused styles

---

UNRELEASED.md
src/components/Modal/Modal.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1985
We are getting cross-origin errors in the modal because the modal assumed the src of the frame was on the same domain and try to get the height of the content.
This only occurs when an admin modal tries to open a standalone app.  
This pull request simply does a try/catch and sets a default height in the catch block. The default height is the same default height used in the embedded app: https://github.com/Shopify/web/blob/1617c9b80602a410347f6512a5ebbb068791bd1c/app/sections/Apps/EmbeddedApp/components/Modal/Modal.tsx#L10
**In Polaris-react:**
1. Tophat the change in polaris react with the playground below. Ensure that there are no cross-origin error in the console when the modal launches
**In Web**
In order to tophat in web you …

[Modal] Set default iframe height when src on different domains 

---

UNRELEASED.md
locales/de.json
locales/en.json
locales/es.json
locales/fr.json
locales/hi.json
locales/it.json
locales/ja.json
locales/ms.json
locales/nl.json
locales/pt-BR.json
locales/zh-CN.json
locales/zh-TW.json
src/components/Tabs/Tabs.scss
src/components/Tabs/Tabs.tsx
src/components/Tabs/components/Item/Item.tsx
src/components/Tabs/components/Tab/Tab.tsx
src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
src/components/Tabs/tests/Tabs.test.tsx
src/components/Tabs/utilities.ts

Fixes https://github.com/Shopify/polaris-ux/issues/153
Implements recommendations two and three, adding a focus state to the tab rollup activator and fixes the tab order.
- The `role="presentation"` on the `li` that wraps each `Tab` as well as the disclosure/rollup activator was causing the a11y check to fail [so I 🔥it](https://github.com/Shopify/polaris-react/pull/1933/commits/16424da601af5b0ab5b45ed6a785a0278ca1fb99). Should there be a different `role` here (like `navigation`?), or is it alright that it's been removed?
📄 [Changelog …

[Tabs] Fix disclosure a11y

---

UNRELEASED.md
scripts/readme-update-version.js
src/components/Autocomplete/components/ComboBox/ComboBox.tsx
src/components/Choice/Choice.tsx
src/components/ContextualSaveBar/ContextualSaveBar.tsx
src/components/DropZone/README.md
src/components/Frame/components/CSSAnimation/CSSAnimation.tsx
src/components/Frame/components/ToastManager/ToastManager.tsx
src/components/Labelled/Labelled.tsx
src/components/Loading/Loading.tsx
src/components/Navigation/components/Item/Item.tsx
src/components/Navigation/components/Section/Section.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
src/components/ResourceList/components/FilterControl/FilterControl.tsx
src/components/Scrollable/components/ScrollTo/ScrollTo.tsx
src/components/Sheet/Sheet.tsx
src/components/Toast/Toast.tsx
src/types.ts
src/utilities/components.tsx
src/utilities/with-app-provider.tsx
yarn.lock

This version of prettier formats hooks a bit more cleanly which is handy
as we're going to be using them a lot
Updates to latest prettier, and runs `yarn run format` over the content.
One manual fix to Sheet.tsx had to be applied as prettier's formatting and ignoring the exhaustive-deps check didn't play nice.
- Check lint/tests pass
- Review code while supressing whitespace-only changes to make it easier to review (a bit over half of this PR is whitespace changes)

Update to latest Prettier and reformat

---

UNRELEASED.md
src/components/ActionMenu/components/RollupActions/RollupActions.tsx
src/components/ActionMenu/components/RollupActions/index.ts
src/components/ActionMenu/components/RollupActions/tests/RollupActions.test.tsx
src/components/Autocomplete/Autocomplete.tsx
src/components/Autocomplete/index.ts
src/components/Card/Card.tsx
src/components/Card/index.ts
src/components/EmptySearchResult/EmptySearchResult.tsx
src/components/EmptySearchResult/index.ts
src/components/EmptySearchResult/tests/EmptySearchResult.test.tsx
src/components/Form/Form.tsx
src/components/Form/index.ts
src/components/Form/tests/Form.test.tsx
src/components/SkeletonPage/SkeletonPage.tsx
src/components/SkeletonPage/index.ts
src/components/SkeletonPage/tests/SkeletonPage.test.tsx
src/components/TopBar/TopBar.tsx
src/components/TopBar/index.ts
src/components/TopBar/tests/TopBar.test.tsx
src/utilities/use-toggle.ts

*This PR is best viewed if you disable whitespace changes, as the hookification saves a level of indentation, which makes it look like i changed EVERYTHING*
Starting down the path of removing withAppProvider usage into the new world of hooks.
Part of #1995
Remove withAppProvider, and use hooks for the following components:
ActionMenu/RollupAction
Autocomplete
Card
EmptySearchResult
Form
SkeletonPage
TopBar
- ActionMeni/RollupAction: Confirm ... popover on with Page with action group example at small screen sizes renders and toggles on click
- Autocomplete: Check interactions on any Autocomplete example
- Card: Confirm secondary actions popover still works on Card
- EmptySearchResult: Check `<EmptySearchResult title="Title" description="Description" withIllustration />` renders in …

Convert a few simple components to use hooks

---

UNRELEASED.md
src/components/Modal/components/Dialog/Dialog.tsx

Fixes #1897 
The normal fade up animation present in the modal component currently doesn't appear when setting the component directly to true.
This PR addresses this by appending additional `appear` animation classes to the component so its consistent throughout. S/o to @dleroux for suggesting this solution in the issue 🙏
<details>
<summary>Click to view collapsed before and after gifs</summary>
</details>
If you have any questions reach out to @ mitchell.soares on Slack!

[Modal] Fixed animation issue present in async Modal rendering

---

UNRELEASED.md
src/components/TextField/TextField.tsx

Fixes #1988 
Allows `number | string`, updates the prop description
<details>
```jsx
import {Page, TextField} from '../src';
const [value, setValue] = useState('2008-07-22');
return (
<TextField
label="Any time this decade 🙄"
value={value}
onChange={setValue} …
```

[Text field] Allow min and max to accept a string

---

UNRELEASED.md
src/components/AppProvider/AppProvider.tsx
src/components/ChoiceList/ChoiceList.tsx
src/components/FormLayout/components/Group/Group.tsx
src/components/Navigation/components/Item/components/Secondary/Secondary.tsx
src/components/OptionList/OptionList.tsx
src/components/OptionList/components/Checkbox/Checkbox.tsx
src/components/PolarisTestProvider/PolarisTestProvider.tsx
src/components/RadioButton/RadioButton.tsx
src/components/Scrollable/components/ScrollTo/ScrollTo.tsx
src/components/Select/Select.tsx
src/components/Toast/Toast.tsx
src/utilities/unique-id/context.ts
src/utilities/unique-id/hooks.ts
src/utilities/unique-id/index.ts
src/utilities/unique-id/tests/hooks.test.tsx
src/utilities/unique-id/tests/unique-id-factory.test.ts
src/utilities/unique-id/unique-id-factory.ts

We want components to have stable ids between rerenders, otherwise their ids will constantly increment on every render which leads to additional wasteful dom reconciliation.
Currently that's not easily possible with functional components.
Adds a useUniqueId hook that returns an ever incrementing ID when called multiple times but remains constant through rerenders. See the hook tests for examples of how this works in practice.
This hook returns a stable value across multiple rerenders, and can optionally be overridden with a fixed value for components that allow the user to provide their own id.
Use this hook in several functional components that currently have unstable ids that change between rerenders.
The idFactory for this hook is populated in the AppProvider, with eye to eventually …

Add useUniqueId hook and fix several needlessly incrementing ids

---

UNRELEASED.md
src/components/Stack/Stack.scss

Fixes https://github.com/Shopify/polaris-react/issues/1707
Content inside a Stack item is overflowing past the container.
This PR removes the `Item` class.
I also tried using `calc(100% - #{spacing($spacing)})` which fixed this specific issue, but according to https://github.com/Shopify/polaris-react/commit/ab23144519d5793e41f0a4933d75f077d972fdae, would reintroduce a bug with Safari.
Another possible solution was to set the `flex shrink` value to 1 (without changing the `min width`), but with multiple items and a smaller container, this caused some overlap:
📄 …

[Stack] Fix stack item content from overflowing past the container

---

UNRELEASED.md
src/components/DropZone/DropZone.scss
src/components/DropZone/DropZone.tsx
src/components/DropZone/components/FileUpload/FileUpload.scss
src/components/DropZone/components/FileUpload/FileUpload.tsx
src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
src/components/DropZone/context.tsx
src/components/DropZone/tests/DropZone.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/762
1. The focus issue is revolved by allowing users to focus the `file input` and turning the button into a simple div. Visually it looks like a button but cannot be tabbed to focused to via keyboard.
2. The dropzone keeps tracks of being focused via its state and communicates it to the fileUpload component via context. The same has been done for hovering and disabling of the dropzone. 
3. We explored adding a hover state to the dropzone. This was challenging because in many cases (like the web image card), once images are uploaded, the outline prop is changed to false to accommodate the design. Having a hover isn't ideal. So this PR only adds a hover state when outline is set to true. (once this is finalized a UX issue will be opened …

[Dropzone] fix various accessibility issues

---

UNRELEASED.md
src/components/ChoiceList/README.md

Fixes #1943 
Adds references to single choice list error state images (added in https://github.com/Shopify/polaris-styleguide/pull/2928)

Add images for Single ChoiceList error state

---

UNRELEASED.md
locales/de.json
locales/en.json
locales/es.json
locales/fr.json
locales/hi.json
locales/it.json
locales/ja.json
locales/ms.json
locales/nl.json
locales/pt-BR.json
locales/zh-CN.json
locales/zh-TW.json
src/components/ResourceItem/README.md
src/components/ResourceItem/ResourceItem.tsx
src/components/ResourceItem/tests/ResourceItem.test.tsx

Fixes part of: https://github.com/Shopify/polaris-react/issues/792
In order to meet accessibility requirements we need to provide the ability to identify the item being rendered.
There is currently and accessibilityLabel prop on the ResourceItem which is used for the entire list items and our examples give `View details for ${name}` as example values.
However, this accessibility is used for the Checkbox which results in:
`Select: View details for ${name}`.
This PR tackled adding the same approach to the disclosure button of the persistentActions, which is what highlighted the issue.
The `name` referred to in our example is not a prop used by the component. It is simply part of the examples. In order to not break the current implementation, I added the name `prop` to the example in order …

[ResourceItem] add name props for accessibility

---

UNRELEASED.md
src/components/Modal/components/Section/Section.scss

Fixes #2061 
The [Modal](https://polaris.shopify.com/components/overlays/modal) component currently has an inconsistent top and bottom spacing in the _section_ subcomponent.
This very simple change removes a repeated function call that made the top padding set to the _base_ Polaris token value rather than the correct _loose_ one. Now the top and bottom padding for the section is set to _loose_.

[Modal] Removed inconsistent padding of modal section

---

src/components/Heading/README.md
src/components/Layout/README.md
src/components/Modal/README.md
src/components/Subheading/README.md

This PR updates links to the headings content guidelines which is being moved in this `polaris-styleguide` PR https://github.com/Shopify/polaris-styleguide/pull/2947 
FYI @kaelig

[Content] Update links to headings content guidelines

---

UNRELEASED.md
src/components/Autocomplete/Autocomplete.tsx
src/components/Card/Card.tsx
src/components/TopBar/TopBar.tsx

Working around awkwardness in TypeScript
Given a functional component with subcomponents, TypeScript
will fail to infer the typing of the subcomponents, so we have to be
explicit about it
- Run `yarn run build-consumer polaris-styleguide` and check that running `yarn run type-check` in the styleguide passes

Fix issue where TS couldn't infer types for things with subcomponents

---

CHANGELOG.md
UNRELEASED.md

v4.2.0 shipped with a type issue that causes the build to fail in consuming apps. This PR preps the change log for a patch.

[CHANGELOG] Prep for v4.2.1

---

UNRELEASED.md
src/components/Frame/Frame.tsx
src/components/Frame/README.md
src/components/Frame/tests/Frame.test.tsx

I discovered a problem working on a project for experts.shopify.com. 
We were planning on using a `<Toast />` component for some user feedback but the `<Toast />` component relies on the `<Frame />` component to function. 
The `<Frame />` component adds a skip to content link for a11y purposes that is not configurable and does not work the way we need it to work. 
We already have a skip to content link of our own that places the user past our main navigation to the top of the content area. When we add the frame component to the app we end up with 2 skip to content links (ours that does the thing we want and the one created by the frame that does not function correctly).
Making the skip to content link configurable will allow us to use the Polaris components that rely on the frame …

[Frame] Skip to content target / ref

---

UNRELEASED.md
src/components/Tabs/Tabs.scss

Fixes #2086. 
Adds `display: block` style to Tabs `.DisclosureActivator` to match the styling of `.Tab` and fix the vertical alignment issue.
<details>
```jsx
import {Card, Page, Tabs} from '../src';
const [selected, setSelected] = React.useState(0);
const tabs = [
{
id: 'alpha',
content: 'Alpha',
},
{
id: 'bravo',
content: 'Bravo',
},
{
id: 'charlie',
content: 'Charlie',
},
{
id: 'delta',
content: 'Delta',
},
{
id: 'echo',
content: 'Echo',
},
{
id: 'foxtrot',
content: 'Foxtrot',
},
{
id: 'golf',
content: 'Golf',
},
{
id: 'hotel',
content: 'Hotel',
},
{
id: 'india',
content: 'India',
},
{
id: 'juliet',
content: 'Juliet',
},
{
id: 'kilo',
content: …
```

[Tabs] Fix vertical alignment of Tabs DisclosureActivator

---

UNRELEASED.md
src/components/ResourceItem/ResourceItem.tsx
src/components/ResourceItem/index.ts
src/components/ResourceItem/tests/ResourceItem.test.tsx

Hookifying the whole class is going to be hard, but hookifying the
wrapper component is pretty easy
This should save 2 levels of nesting - the WithAppProvider, and the context consumer
Remove withAppProvider and a context consumer from ResourceItem
Check ResourceItem still renders correctly within a ResourceList

[ResourceItem] Avoid using withAppProvider

---

UNRELEASED.md
src/components/Page/components/Header/Header.tsx
src/components/Page/components/Header/tests/Header.test.tsx

We are bringing back the ability to have a non-primary/indigo button as the pages primary actions. We previously made the decision to remove this ability but there are use cases that having a non-indigo button does make sense.
Making the default button indigo/primary but allowing the ability to make it a regular button.
Paste the code below in the playground and toggle primary key of the primaryAction.
<details>
<summary>Copy-paste this code …

[Page] Allow for non-primary page action

---

UNRELEASED.md
src/components/AppProvider/AppProvider.tsx
src/components/ThemeProvider/ThemeProvider.tsx

AppProvider uses `{React.Children.only(children)}` which has not been typed. 
* Adding a children type to the AppProvider prop interface
* Remove `React.Children.only` from `AppProvider` & `ThemeProvider` as it's an arbitary restriction

[AppProvider] Added children type to props interface

---

UNRELEASED.md
src/components/ActionMenu/components/RollupActions/tests/RollupActions.test.tsx
src/components/Card/tests/Card.test.tsx
src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
src/components/Navigation/components/Item/tests/Item.test.tsx
src/test-utilities/legacy.tsx

We use `trigger` over 150 so it's going to be easier to update the function rather than always using act
Copying over the trigger function from `enzyme-utilities`. Since we're migrating away from enzyme I don't think it's worth adding it as a dependency and having more enzyme utilities 😄 
Watch the tests run errorless 😎

Updated trigger to use act

---

UNRELEASED.md
src/components/Collapsible/README.md
src/components/ColorPicker/README.md
src/components/DataTable/README.md

Converting Collapsible, ColorPicker and DataTable class-based examples to hooks
```
- Converted `Collapsible`, `ColorPicker`, and `DataTable` examples to functional components ([#2128](https://github.com/Shopify/polaris-react/pull/2128))
```
</details>

Hookify Collapsible, ColorPicker, and DataTable examples

---

src/components/UnstyledLink/UnstyledLink.tsx

Slightly simpler code
Use generics for typing React.forwardRef

Use generics for typing UnstyleLink's forwardRef

---

UNRELEASED.md
src/components/TextField/README.md
src/components/Toast/README.md
src/components/TopBar/README.md

Converting TextField, Toast, and TopBar class-based examples to hooks
```
- Converted `TextField`, `Toast`, and `TopBar` examples to functional components ([#2135](https://github.com/Shopify/polaris-react/pull/2135))
```
</details>

Hookify TextField, Toast, and TopBar examples

---

UNRELEASED.md
src/components/RadioButton/README.md
src/components/RangeSlider/README.md
src/components/ResourceItem/README.md

Converting RadioButton, RangeSlider, and ResourceItem class-based examples to hooks
```
- Converted `RadioButton`, `RangeSlider`, and `ResourceItem` examples to functional components ([#2132](https://github.com/Shopify/polaris-react/pull/2132))
```
</details>

Hookify RadioButton, RangeSlider, and ResourceItem

---

UNRELEASED.md
src/components/Modal/README.md
src/components/OptionList/README.md
src/components/Popover/README.md

Converting Modal, OptionList, and Popover class-based examples to hooks
```
- Converted `Modal`, `OptionList`, and `Popover` examples to functional components ([#2131](https://github.com/Shopify/polaris-react/pull/2131))
```
</details>

Hookify Modal, OptionList, and Popover examples

---

UNRELEASED.md
src/components/Autocomplete/README.md
src/components/Banner/README.md
src/components/ChoiceList/README.md

Converting Autocomplete, Banner and ChoiceList class-based examples to hooks
```
- Converted `Autocomplete`, `Banner`, and `ChoiceList` examples to functional components ([#2127](https://github.com/Shopify/polaris-react/pull/2127))
```
</details>

Hookify Autocomplete, Banner, and ChoiceList examples

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/components/Resizer/Resizer.tsx
src/components/TextField/index.ts
src/components/TextField/tests/TextField.test.tsx

Part of https://github.com/Shopify/polaris-react/issues/1995
change `TextField` and `Resizer`  to use react hooks
- Loading the Textfield examples in the playground and ensuring they all behave as expected should be sufficient.
<details>
```jsx
return (
<Page …
```

[TextField] Converting TextField and Resizer to functional components using React Hooks

---

UNRELEASED.md
src/components/Link/Link.tsx
src/components/Link/README.md
src/utilities/link/types.ts

People are unclear if the `external` prop on links should be used for sites external to shopify, or anything that opens in a new tab.
You should use it for anything that opens in a new tab.
Make it clear external is to be used for an page that opens in a new tab
Make wording and ordering consistent between Link and UnstyledLink
Clarify readme to make it clear the important thing is "you're going anywhere in a new tab", not "you're going outside your current domain"

[Link] Improve docblocks and readme for links

---

UNRELEASED.md
src/utilities/tests/use-lazy-ref.test.tsx
src/utilities/use-lazy-ref.ts

@beefchimi and I added this while working on #2105, I broke this out of the other PR so we can take our time working on 2105 and use this hook in the meantime.
It'll allow for lazy initialization of refs, see jsdocs for a little more information
* Adding hook + jsdoc
* Adding tests

Add useLazyRef hook

---

UNRELEASED.md
src/components/Avatar/Avatar.tsx
src/components/Avatar/index.ts
src/components/Avatar/tests/Avatar-ssr.test.tsx
src/components/Avatar/tests/Avatar.test.tsx
tests/build.test.js

Starting down the path of removing withAppProvider usage into the new world of hooks.
Part of #1995
Converts Avatar to use hooks.
Reworks the logic for how we handle falling back to using initials if an image fails to load so it relies on a single `status` state that can be either "pending, errored or loading" rather than two `hasError` and `hasLoading` states.
Use react-testing in some Avatar tests as Enzyme doesn't seem to accurately reflect props chagnes for functional components.
Play with the following to investigate how the onError fallback to initials logic behaves:
<details>
```jsx
import {Page, Button, Avatar} from '../src'; …
```

[Avatar] Hookify component

---

.github/CODEOWNERS

The public Sass API is set to be gradually deprecated.
@tmlayton @BPScott and @danrosenthal should be aware of any changes made to it
to prevent any new helpers from sneaking in.
If anyone feels like they should be added to this list, I'll be happy to add them.

Add CODEOWNERS file to notify them of any public Sass API changes

---

UNRELEASED.md
src/components/Select/Select.scss

Fixes https://github.com/Shopify/web/issues/18619
As outlined [here](https://bugs.webkit.org/show_bug.cgi?id=202055) webkit has a bug that cause the browser to crash when a `select` `text-rendering` is set to `optimizeLegibility`
Changes the `text-rendering` of the `Select input` to `auto`
In the playground, navigate to the Select examples and ensure that on Safari 13 the browser doesn't crash.
<details>
```jsx
return (
</Page>
);
}
```
</details>

[Select] change text-rendering to auto to fix Safari bug

---

UNRELEASED.md
src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/components/Day/Day.tsx
src/components/DatePicker/components/Day/index.ts
src/components/DatePicker/components/Day/tests/Day.test.tsx
src/components/DatePicker/index.ts
src/components/DatePicker/tests/DatePicker.test.tsx

We're updating our components to use hooks and functions instead of classes and HoCs like before, this is part of that work
https://github.com/Shopify/polaris-react/issues/1995
Hookifies Day and DatePicker
<details>
```jsx
return (
{/* Add the code …
```

[DatePicker] Hookify

---

src/components/Card/Card.scss

PostCSS throws warnings about this, which blocks sewing-kit compilation:
```
ModuleWarning: Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning
(1:1639) start value has mixed support, consider using flex-start instead
at Object.emitWarning (node_modules/@shopify/sewing-kit/node_modules/webpack/lib/NormalModule.js:158:6)
at result.warnings.forEach (node_modules/postcss-loader/src/index.js:146:16)
at Array.forEach (<anonymous>)
at postcss.process.then (node_modules/postcss-loader/src/index.js:145:27)
```

[Card] Improve standards compliance via flex-start

---

src/components/AfterInitialMount/AfterInitialMount.tsx
src/components/AfterInitialMount/index.ts
src/components/AfterInitialMount/test/AfterInitialMount.test.tsx
src/utilities/tests/use-is-after-initial-mount.test.tsx
src/utilities/use-is-after-initial-mount.ts

Adding two small utilities that'll help with code that needs to be separated from server/client.
Adding `RenderAfterMount` and `useMounted`
<details>
```jsx
return (
</Page>
);
}
```
</details>

[RenderAfterMount][useMounted] Add utilities

---

UNRELEASED.md
src/components/AppProvider/AppProvider.tsx
src/components/AppProvider/tests/AppProvider.test.tsx
src/components/Filters/Filters.tsx
src/components/Frame/Frame.tsx
src/components/Frame/tests/Frame.test.tsx
src/components/MediaQueryProvider/MediaQueryProvider.tsx
src/components/MediaQueryProvider/index.ts
src/components/MediaQueryProvider/tests/MediaQueryProvider.test.tsx
src/components/Navigation/components/Item/Item.tsx
src/components/Page/components/Header/Header.tsx
src/components/Page/components/Header/tests/Header.test.tsx
src/components/Page/tests/Page.test.tsx
src/components/PolarisTestProvider/PolarisTestProvider.tsx
src/components/PolarisTestProvider/tests/PolarisTestProvider.test.tsx
src/components/Sheet/Sheet.tsx
src/components/Sheet/tests/Sheet.test.tsx
src/utilities/media-query/context.tsx
src/utilities/media-query/hooks.tsx
src/utilities/media-query/index.ts
src/utilities/media-query/tests/hooks.test.tsx
src/utilities/with-app-provider.tsx

Reduce duplicated logic and add a location where we can easily add to it
* Create MediaQueryProvider, hooks, and context
* Add it to AppProvider, withAppProvider, PolarisTestProvider
* Add tests
* Replace all occurrences of navigationBarCollapsed() with useMediaQuery or mediaQuery
You'll want to check Filters, Frame, Navigation, Page and Sheet in the deployment across screen sizes to ensure navigation collapsed is still working correctly.
</details>

[MediaQueryProvider] Add media query provider

---

src/components/Banner/README.md

There is an extra period in the link of the [Dismissible banner example](https://www.chromaui.com/component?appId=5d559397bae39100201eedc1&name=All%20Components%7CBanner&buildNumber=857&specName=Dismissible%20Banner).
Removes the period in those links.
* [N/A] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [N/A] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [N/A] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [N/A] Updated the component's `README.md` with documentation changes
* [N/A] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/docu …

[Banner] Remove period in example link

---

UNRELEASED.md
src/components/TextField/README.md

There is an initiative to eliminate Latin abbreviations, and part of that work includes replacing `e.g.` with `Example:`.

[TextField] Replace “e.g.” with “Example:”

---

UNRELEASED.md
src/components/AccountConnection/README.md
src/components/ActionList/README.md
src/components/AppProvider/README.md

Converting AccountConnect, ActionList and AppProvider class-based examples to hooks
```
- Converted `AccountConnection`, `ActionList`, and `AppProvider` examples to functional components ([#2126](https://github.com/Shopify/polaris-react/pull/2126))
```
</details>

Hookify AccountConnect, ActionList and AppProvider examples

---

UNRELEASED-v5.md
package.json

Generally speaking Shopify supports the last three version of browsers. In reality we're a little more lax so sometimes we end up supporting older versions as conditional transpilation using babel-preset-env is pretty easy. Supporting older versions of safari and ios was useful for point-of-sale apps on older hardware that couldn't update to latest.
Earlier this year Shopify publicly dropped support for ios9 and we recently removed transpilation support in [web](https://github.com/Shopify/web/pull/18235). Now it is Polaris's turn.
This drastically decreases our bundle size as we no longer need to transpile several aspects of class syntax, object destructuring and arrow functions.
This shrinks the uncompressed esm build from 614914 bytes to 530242 bytes - A saving
of 85KB or 15%! Gzipped …

[v5] Drop support for ios9

---

UNRELEASED.md
src/components/TextField/TextField.tsx

The default `type` for button is [`submit`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type), which means whenever you click the clearButton, it will fire `submit` event on the form.
Here's an example [on codesandbox](https://codesandbox.io/s/pensive-grass-t45xl).
It sets the type to `button` to fix the bug.

[TextField] Fix type for button

---

UNRELEASED.md
src/components/SettingToggle/README.md
src/components/Sheet/README.md
src/components/Tabs/README.md

Converting SettingToggle, Sheet, and Tabs class-based examples to hooks
```
- Converted `SettingToggle`, `Sheet`, and `Tabs` examples to functional components ([#2134](https://github.com/Shopify/polaris-react/pull/2134))
```
</details>

Hookify SettingToggle, Sheet, and Tabs examples

---

UNRELEASED.md
src/components/Icon/Icon.scss

Currently we apply a z-index to icons to allow for them to sit above the backdrop when using one. This causes strange issues in consumers because it means icons get an arbitrary z-index of 2, lifting them over things that they shouldn't be.
This removes the z-indexes and instead changes the `::after` used for the backdrop to be a `::before` which naturally stacks correctly without a z-index.
Ideally any regressions here will be caught by …

Removing z-index on icons

---

src/components/AppProvider/AppProvider.tsx

Since `features` are pass-through they don’t need to be persisted in state. I was under the impression we were doing this as some kind of work around for children that were not updating.
Removing features from state

[AppProvider] Remove features from state

---

UNRELEASED.md
src/components/Popover/Popover.scss
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx

https://github.com/Shopify/polaris-react/commit/c6d321bcf899c039f7a4078cde2d60649b38d723 created a 200ms visual delay before starting the animation.
Adds an `entering` class which is added immediately and starts animating the opacity. Also clears the timeouts when the component updates in case subsequent updates are triggered in < 200ms.
<details>
```jsx
import …
```

[Popover] Fix 200ms visual delay when activating a popover

---

UNRELEASED.md
src/components/ResourceItem/ResourceItem.tsx

Fixes https://github.com/Shopify/polaris-react/issues/1882
This PR addresses an issue where the `ResourceList` `Item`s (with selection) would retain a focused state when deselected by clicking on the `Item` itself in the `ResourceList` ([video of issue](https://screenshot.click/24-22-iv47s-hvvll.mp4)).
The `ResourceList` `Item` component's `handleSelection` handler is called whenever an `Item` is selected. This includes clicking on the `Item` when it is already selected using the checkbox.
This PR changes the logic from `handleSelection` always setting the `focused` and `focusedInner` values in state to true, to setting them to `!selected` which means that they are set to false when the `Item` is deselected by clicking on it. …

[ResourceList] Fix Item click deselect

---

UNRELEASED.md
src/components/Tabs/components/Tab/Tab.tsx
src/components/Tabs/components/Tab/index.ts
src/components/Tabs/components/Tab/tests/Tab.test.tsx

related to #1995
change `src/components/Tabs/components/Tab/Tab.tsx` to use react hooks

[Tabs] hookify tab

---

UNRELEASED.md
src/styles/shared/_typography.scss

Related to #2214 
Font-weight of subheading should be 600 (semibold), not 700 (bold), as per polaris-rails, the UI Kits, and @jessebc's specs:
What it says in the title.
Not sure what kind of tophatting is necessary here.

[SubHeading] Fix font-weight (bold -> semibold)

---

UNRELEASED.md
src/components/Connected/Connected.tsx
src/components/Connected/tests/Connected.test.tsx
src/components/TextField/tests/TextField.test.tsx

Fixes: https://github.com/Shopify/polaris-react/issues/2169
Fixes: https://github.com/Shopify/online-store-web/issues/4181
Ensuring that the `Connected` component always returns fragments at the same DOM depth so as not to cause a `TextField`'s `input` field to unmount and lose focus.
<details>
<summary>Introducing a "Search" button (`connectedRight`) while typing causes a loss of focus</summary>
</details>
<details>
<summary>Ensuring maintained focus by always returning a TextField at the same depth in the DOM (what this PR does)</summary>
</details>
📄 [Changelog …

[Connected] Preventing loss of TextField focus caused by shifting DOM position

---

UNRELEASED.md
src/components/Card/Card.scss

Fixes #2226
This fixes `fullWidth` `Card.Section`s not appearing full width when a Nav is present.
This adds a padding override inside the page breakpoint as well as fixing the default padding.
Add a `Card` with a `fullWidth` `Card.Section` to a page that also has a `Frame` and a `Nav`

Fixing fullWidth section on Card

---

UNRELEASED.md
src/components/Portal/Portal.tsx
src/components/Portal/tests/Portal.test.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/shared.ts

Co-authored-by: Tim Layton <tim.layton@shopify.com>
Currently (in `master`) the `Portal` component renders portals directly within the `body` element. This places any components rendered in a `Portal` (`Modal`, `Sheet`) outside the scope of the `ThemeProvider` node. The theme provider component sets its custom properties on a node, so in order to make the modal and sheet components theme-able with the the theme provider component, they need to be rendered within the theme provider component's node.
This pull request adds a way to hook into the theme provider component's node, and moves the portal component's node within that node.
Use the chromaui build to tophat `z-index` and anything else you can think of on the examples for `Frame`, `Modal`, `Sheet`, and `Filters`.

[Portal][ThemeProvider][Color System] move portal node within theme provider node to enable theming

---

UNRELEASED.md
src/components/AppProvider/AppProvider.tsx
src/components/PolarisTestProvider/PolarisTestProvider.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/utilities/color-manipulation.ts
src/utilities/color-transformers.ts
src/utilities/tests/color-manipulation.test.ts
src/utilities/tests/color-transformers.test.ts
src/utilities/theme/index.ts
src/utilities/theme/tests/utils.test.ts
src/utilities/theme/types.ts
src/utilities/theme/utils.ts

Co-authored-by: Tim Layton <tim.layton@shopify.com>
Co-authored-by: Ben Scott <ben.scott@shopify.com>
Depends on #2224
- updated type for `theme` prop to `ThemeConfig` to distinguish from the type `Theme` which is shared over context. A `Theme` contains only the logo properties, while `ThemeConfig` can contain a `colors` property.
- converted `ThemeProvider` to use hooks
- created symmetry in context between app provider and test provider
- added better tests for default topBar colors
- fixed an issue where `colorToHsla` returned HSLA strings instead of HSLA objects when given HSL or HSLA strings
- fixed an issue with `colorToHsla` where RGB colors with no saturation could result in a divide by zero error
- fixed an issue where `colorToHsla` inconsistently returned an alpha value
- fixed …

[ThemeProvider][Color system] clean up theme provider in preparation for color system work

---

translation.yml

Since the initial support of internationalization at Shopify, seven more languages have since been added to the beta: `da` (Danish), `ko` (Korean),`nb` (Norwegian), `pt-PT` (Portuguese), `th` (Thai), `tr` (Turkish), and `sv` (Swedish). There are also two additional languages Shopify will be supporting in the future: `cs` (Czech) and `pl` (Polish). 
(Shout out to @beefchimi and @tleunen for bringing this to our attention!)
Updating our `translation.yml` with the latest list of supported languages so that the translation platform keeps our locales in sync with what the product supports.

[i18n] Add new beta and future supported languages

---

package.json

Makes better use of the "Homepage" link on npm, because as seen in the screenshot below, https://www.npmjs.com/package/@shopify/polaris links to the GitHub repository twice.

[package.json] Point homepage field to polaris.shopify.com

---

UNRELEASED.md
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/index.ts
src/components/Checkbox/tests/Checkbox.test.tsx
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/components/BulkActions/BulkActions.tsx
src/components/ResourceList/components/BulkActions/tests/BulkActions.test.tsx
src/components/ResourceList/components/CheckableButton/CheckableButton.tsx
src/components/ResourceList/tests/ResourceList.test.tsx
src/types.ts
src/utilities/resource-list/context.ts
src/utilities/resource-list/index.ts
src/utilities/resource-list/types.ts

Fixes https://github.com/Shopify/polaris-react/issues/792
I believe this is the last of the ResourceList a11y issues outline in [#792].
In order to switch focus between the plain `CheckableButton` checkbox and the ones inside the BulkActions, we needed to keep track of the button that was clicked and which of the 3 possible buttons that would receive focus.
1. The 3 buttons are tracked via context.
2. `handleToggleAll` is only called when the bulk action or plain button are clicked. From there, depending on screen size we focus the right button.
3. To enable focus on the checkbox I needed to forwardRef on the checkbox. According to this: https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers This would be a breaking changes. Discussed with @AndrewMusgrave and …

[ResourceList-BulkAction][Checkbox] Handle focus on bulk actions and converts checkbox into a functional component.

---

src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/utilities/theme/utils.ts

During https://github.com/Shopify/polaris-react/pull/2225, I made a mistake and inverted the default colors for the TopBar. This wasn't caught in VRT since we don't have an example just using the default colors.
|before|after|
|-|-|
|<img width="1083" alt="Screen Shot 2019-10-04 at 10 22 09 AM" src="https://user-images.githubusercontent.com/1403188/66215102-e0a37a80-e690-11e9-88d8-a3bc317d91f3.png">|<img width="1088" alt="Screen Shot 2019-10-04 at 10 22 22 AM" src="https://user-images.githubusercontent.com/1403188/66215122-e6995b80-e690-11e9-923d-a5ff5744330e.png">|

[Color system] fix default topbar colors

---

UNRELEASED.md
src/components/Tabs/Tabs.scss

Fixes: https://github.com/Shopify/polaris-react/issues/1677
Fixes: https://github.com/Shopify/online-store-web/issues/4667
Causes `<Tabs />` component to collapse correctly on small screens in pre-iOS 13 versions of Safari. The screenshots go back to iOS 11 but it fixes the issue all the way back to iOS 9. (The tabs don't render properly in iOS 8.)
| Before        | After           |
|<img width="745" alt="Screen Shot 2019-10-03 at 1 55 28 PM" src="https://user-images.githubusercontent.com/70582/66152132-d0cf5c00-e5e6-11e9-9e34-72680b76121b.png">|<img width="750" alt="Screen Shot 2019-10-03 at 1 55 47 PM" src="https://user-images.githubusercontent.com/70582/66152133-d0cf5c00-e5e6-11e9-8c14-0bba538a36f0.png">|
|<img width="748" alt="Screen Shot 2019-10-03 …

Ensuring tabs collapse in small screens on <iOS 13

---

UNRELEASED.md
src/components/EmptyState/README.md

Adds accessibility guidance for the empty state component, to appear in `polaris-react` docs and in the style guide.
* https://polaris.myshopify.io/components/actions/account-connection (web only)
* https://polaris.myshopify.io/components/actions/setting-toggle (web only)
FYI @dpersing ❤️

[a11y] Add empty state component a11y docs 

---

UNRELEASED.md
src/components/DatePicker/README.md

Adds accessibility guidance for the date picker component, to appear in `polaris-react` docs and in the style guide.
* https://polaris.myshopify.io/components/actions/account-connection (web only)
* https://polaris.myshopify.io/components/actions/setting-toggle (web only)
FYI @dpersing ❤️

[a11y] Add date picker component a11y docs

---

UNRELEASED.md
src/components/Spinner/README.md
src/components/Spinner/Spinner.tsx
src/components/Spinner/tests/Spinner.test.tsx

Fixes #791
* Adding `hasFocusableParent` to spinners public API
* Add a focus management example
* Add tests
* Add accessibility docs section
<details>
```jsx
import {Page, Spinner} from '../src';
return (
<Spinner accessibilityLabel="label here" />
</Page>
);
}
```
</details>
<details>
```jsx
import {Page, Spinner} from '../src';
return (
<div tabIndex={0}>
<Spinner hasFocusableParent accessibilityLabel="label here" />
</div>
</Page>
);
}
```
</details>

[Spinner] Fix not being read by screen readers

---

UNRELEASED.md
src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx

Fixes #2245
Only clear timeouts if active prop changes. See the regression test failure in the first commit, then the code to satisfy the regression in the second commit.
<details>
```jsx
import {Page, Popover, Button, ActionList} from '../src';
const [popoverActive, …
```

[Popover] Only clear timeouts if active prop changes

---

src/components/RangeSlider/README.md

Fixes #2221 
`RangeSlider` has animated tooltips for the current `value` when `output` is `true`. The tooltips in the dual range slider example get cut off unless they have enough space within the `Card` since `Card` hides `overflow` content. Right now this is accomplished by adding `margin-top` to the event listening `div` that wraps the input, but this looks strange.
Play with each of the `RangeSlider` examples in the [Chroma …

[RangeSlider] Fix example spacing; specify dual range slider example as web only

---

UNRELEASED.md
src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx

Fixes https://github.com/Shopify/polaris-react/issues/2251
The `Breadcrumbs` component that is rendered on `Page` accepts the `accessibilityLabel` prop. However when we pass a value in, it doesn't get rendered.
This PR is passing the value given in `accessibilityLabel` down to the rendered <a> tag or <button> tag.
```tsx
<Page breadcrumbs={[{content: 'Go back', url: '#', accessibilityLabel: 'Go back to some page'}]} title="Playground" />
```
```tsx
<Page breadcrumbs={[{content: 'Go back', onAction: () => {}, accessibilityLabel: 'Go back to some page'}]} title="Playground" />
```

[Breadcrumbs] Pass accessibilityLabel through to rendered components

---

UNRELEASED.md
src/components/DataTable/DataTable.tsx

- Updated the description to remove `totals for t`
- Updated the unreleased notes to match the new prop name

[Data table] Fix showTotalsInFooter prop description typo

---

UNRELEASED.md
locales/de.json
locales/en.json
src/components/ResourceList/README.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

Currently, when the Resource list renders a header, we show the number of resource items, ie. `Showing 10 products`. There are cases where it would be valuable to also include the total number of items in the header, ie. `Showing 10 of 50 products`. 
cc @dfmcphee and @dleroux (we had briefly discussed this via slack)
To support this, we add at `totalItemsCount` prop to the ResourceList component.
When the prop is passed, and the header is to be shown, we will display `Showing {itemsCount} of {totalItemsCount} resourceName`.
Before: 
After: 
📄 [Changelog …

[ResourceList] Add totalItemsCount prop to ResourceList

---

UNRELEASED.md
src/components/DropZone/README.md

- Adds accessibility guidance for the drop zone component, to appear in `polaris-react` docs and in the style guide.
- Edits the drop zone component description
* https://polaris.myshopify.io/components/actions/account-connection (web only)
* https://polaris.myshopify.io/components/actions/setting-toggle (web only)
FYI @dpersing ❤️

[a11y] Add drop zone component a11y docs and edit description

---

UNRELEASED.md
src/components/ResourceList/components/FilterControl/components/DateSelector/DateSelector.tsx
src/components/ResourceList/components/FilterControl/components/DateSelector/index.ts
src/components/ResourceList/components/FilterControl/components/DateSelector/tests/DateSelector.test.tsx

Part of #1995
Convert DateSelector to a functional component
I noticed while converting this component,the `setState` callback was used quite often however I couldn't figure out why, except when setting state with the date. I'm adding @dleroux since he'll have the most context on this
Playground with date filter
<details>
```jsx
import {ResourceList, TextStyle, Avatar, FilterType, Card} from '../src';
export class Playground extends React.Component {
state = {
{
},
],
};
}; …
```

[DateSelector] Hookify component

---

UNRELEASED.md
src/components/Spinner/README.md

[Spinner] Improved accessibility docs

---

src/utilities/tests/use-component-did-mount.test.tsx
src/utilities/tests/use-event-listener.test.tsx
src/utilities/use-component-did-mount.ts
src/utilities/use-event-listener.ts

I needed these while converting dropzone to a functional component
* add hooks
* add tests
* add docs
* tests
* try to break them in the playground

[useEventListener][useComponentDidMount] Add useComponentDidMount & useEventListener

---

UNRELEASED.md
src/components/Stack/Stack.scss
src/components/TextField/README.md

In fixing this issue https://github.com/Shopify/polaris-react/issues/1707 we removed min-width thinking it wasn't needed. Turns out it is. 
fixes: https://github.com/Shopify/polaris-react/issues/2260
Simply bringing back the min-width so that the flex-items takes the space it requires.
We do still have an issue where if `textOverflow: 'ellipsis',` is used on the child of the flex item, overflow is a little off. In which case its probably best to write flexbox for this edge case.
This fixed the bigger issue of the column not appearing.
📄 [Changelog …

[Stack] Fix min-width issue on Stack.Item

---

src/components/Banner/tests/Banner.test.tsx
src/components/Popover/tests/Popover.test.tsx
src/components/Portal/tests/Portal.test.tsx
src/components/ScrollLock/tests/ScrollLock.test.tsx

Part of #1995
Use functional components in tests

Use functional components in tests

---

UNRELEASED.md
src/utilities/tests/with-app-provider.test.tsx
src/utilities/with-app-provider.tsx

Simplifying withAppProvider, stopping it doing work that is no longer required
Removes `link`, `theme` and `scrollLockManager` from the object returned by withAppProvider as nothing consumes them any more
check tests and type check pass.

Remove unused items from withAppProvider

---

src/utilities/theme/tests/utils.test.ts
src/utilities/theme/utils.ts

The CSS var lookup and actual names did not match. I opted for the shorter version.

[Color system] Fix surface role name

---

.storybook/addons.js
.storybook/config.js
.storybook/preview-head.html
UNRELEASED.md
package.json
src/components/Select/Select.tsx
yarn.lock

Preliminary theming work is rad. Having an easy way to preview it on existing stories would be even radder.
And while I'm playing with contexts, being able to disable react strict mode so I can get accurate counts of how often things get rerendered when debugging would be super useful too.
Use storybook's addon-contexts addon to allow for theme toggling, and react strict mode toggling
- Add addon-contexts and remove addon-backgrounds
- Configure context to allow toggling React strict mode on/off
- Configure context to allow configuring theme setups. There is a
choice of default, global theming light mode and global theming dark
mode
Visit a story of a component that is themed, e.g. Banner. Click through the options available in the theme button (the paintbrush in the Storybook topbar, …

Use storybook's addon-contexts to allow for theme toggling

---

UNRELEASED.md
src/styles/shared/_icons.scss

This PR safely moves `color: $secondary-color` into the `svg` block alongside `fill: $primary-color`.
Previously, the mixin was expected to be used like so:
```scss
.Component {
color: blue;
// more styles for the component
@include recolor-icon(red, green);
}
```
Within the `recolor-icon` mixin, `fill` was scoped to to the `svg` selector... but `color` was outside of it. This meant that in the above example, my `color: blue` will get overridden with `green`, when really my intention is to have `.Component` use `blue` text, while making the primary color of the icon `red` and the secondary color of the icon `green`.

🐛[Sass] Fix recolor-icon mixin

---

.eslintignore
UNRELEASED.md
src/components/Popover/Popover.scss
src/components/PositionedOverlay/PositionedOverlay.tsx
src/components/PositionedOverlay/tests/PositionedOverlay.test.tsx
src/components/PositionedOverlay/utilities/math.ts
src/components/TopBar/TopBar.scss
src/components/TopBar/components/Menu/Menu.scss
src/components/TopBar/components/Menu/Menu.tsx
src/components/TopBar/components/UserMenu/UserMenu.tsx

Fixes #1673 
Using mutation observer so that the resize calculation is being run at the correct time. It is also resetting the left value to 0 which is needed for the recalc.
This needs to be tested in web and in Polaris with around 6-7 menu items.
<details>
```jsx
import {ArrowLeftMinor} from '@shopify/polaris-icons';
import …
```

[Popover][TopBar] Overlay width fix

---

UNRELEASED.md
src/components/Portal/Portal.tsx
src/components/Portal/tests/Portal.test.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/shared.ts

This reverts commit d62cff649c1db363efa461b02cf600270394f4e6.
Co-authored-by: Tim Layton <tim.layton@shopify.com>
Closes https://github.com/Shopify/polaris-react/issues/2302

Revert "move portal node within theme provider node to enable theming"

---

UNRELEASED.md
src/components/PolarisTestProvider/PolarisTestProvider.tsx
src/components/Portal/Portal.tsx
src/components/Portal/tests/Portal.test.tsx
src/components/ThemeProvider/ThemeProvider.tsx
src/components/ThemeProvider/tests/ThemeProvider.test.tsx
src/utilities/theme/index.ts
src/utilities/theme/tests/utils.test.ts
src/utilities/theme/types.ts
src/utilities/theme/utils.ts

Co-authored-by: Tim Layton <tim.layton@shopify.com>
This PR enables components rendered in a `Portal` to be themed using the generated CSS custom properties. Otherwise components rendered in a `Portal` are out of scope (rendered outside of the `ThemeProvider`) and do not have access to the CSS custom properties.
#2224 was the first attempt at solving this issue which moved the `Portal` container within the `ThemeProvider`. But this broke `Popover` positioning if an app had a positioned wrapper (e.g `position: relative; top: 50px`, see #2302) and was reverted in #2305.
1. Adds the generated CSS custom properties used for global theming to the theme context
1. Sets the CSS custom properties on the `Portal` container

[Color system] set theme css custom properties on portal node

---

UNRELEASED.md
src/components/Modal/README.md
src/components/Stack/Stack.scss

An issue was found with Stack items with display inline content. In case the sibling element is too long the proportions of this Item will not be correct and will possibly overflow.
Here is an example from the Payments Settings page:
Making sure that the Stack Item has the `flex-shrink` role set to 0
<details>
```jsx
import {Page} from …
```

[Stack] Fix Item proportion when shrinking

---

.storybook/addons.js
.storybook/config.js

Mystery meat navigation is silly, lets used words rather than icons
Removes icons, use words for context switching
Open storybook, see the new "Strict Mode" and "Global Theming" toggles as words rather than wondering what the paintbrush and speedometer icons are for

Use words rather than icons for storybook contexts

---

UNRELEASED.md
src/components/Collapsible/Collapsible.scss
src/components/Collapsible/Collapsible.tsx

Fixes #1133
I believe the issue is caused by [collapsing margins](https://www.w3.org/TR/CSS22/box.html#collapsing-margins). Height of element with `overflow: hidden` includes margins of children, while margins of children of `overflow: visible` element spills through the parent and are not included in parent's height.
- changes collapsible animation property from height to max-height

[Collapsible] animate collapsible max-height property

---

UNRELEASED.md
src/components/ResourceList/ResourceList.tsx
src/components/ResourceList/tests/ResourceList.test.tsx

Fixes #2299 
When the `ResourceList` has only item showing, but a `totalItemsCount` greater than 1, it was using the singular form of the resource name when it should use the plural.
Whenever there's a `totalItemsCount` and it's not equal to 1, it will use the plural form of the resource name.

[ResourceList] Fix for the plural resource name when totalItemsCount is greater than 1

---

scripts/pa11y.js

Making sure new stuff is accessible
Add light mode versions of all our stories to the pa11y test suite
Ignore dark mode for now it is still very work-in-progress
Check pa11y tests pass
Check they testing lines include light mode query strings - Can you add them to https://polaris-react.herokuapp.com/iframe.html? and you get light mode versions

Run pa11y tests over Global Themeing light mode

---

UNRELEASED.md
src/components/ChoiceList/ChoiceList.tsx
src/components/ChoiceList/tests/ChoiceList.test.tsx

I have a couple of use cases, where I want to increase the font weight of a group of words in a choice's label, in a `<ChoiceList />`. Also, `<Checkbox />` and `<RadioButton />` already allow `ReactNode`s on the `label` prop, while `<ChoiceList />` doesn't. It is also possible in rails.
Replacing the `string` type of the `label` sub prop by a more permissive `ReactNode` type. Adding tests accordingly.
You can just play with the `Playground` …

[ChoiceList] Allow JSX in a choice's label

---

src/components/Portal/tests/Portal.test.tsx

Adds a couple more tests for work done in #2306 and #2327 which expect that we are adding and removing the CSS custom property styles to and from the portal node. 
By spying on the `Element` prototype we can get access to instance methods.

[Color system] Add tests for adding and removing styles

---

src/components/Button/Button.scss

- Addresses https://github.com/Shopify/polaris-react/issues/2197
- Does not implement color system for `pressed` state for plain `Button`
- ~Adds a focus style for `Link` **outside** of global theming~

[Color system] backwards compatibly implement color system for plain button

---

UNRELEASED.md
src/components/Choice/Choice.scss
src/components/OptionList/components/Option/Option.scss

Inconsistent alignment of controls between `OptionList` and `ChoiceList` items. In `OptionList` items are center-aligned which causes things to look off when the items wrap.
Fixes #1310 
Adds vertical adjustment to `OptionList` control items
| Before       | After |
| ![Screen Shot 2019-10-17 at 11 12 18 AM](https://user-images.githubusercontent.com/8629173/67022980-0c325600-f0d0-11e9-9eab-990d84642bd2.png) | ![Screen Shot 2019-10-17 at 11 11 49 AM](https://user-images.githubusercontent.com/8629173/67022939-fe7cd080-f0cf-11e9-9f9c-38bb65fac03e.png) |
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentati …

Add vertical adjustment to `OptionList` control items

---

UNRELEASED.md
src/components/Button/Button.scss
src/styles/shared/_buttons.scss

Co-authored-by: @danrosenthal 
Fixes https://github.com/Shopify/web/issues/20016. Partially reverts 834a741 due to a bug related to https://bugs.webkit.org/show_bug.cgi?id=194332
Partial revert of #2252. It appears using a `var` function in CSS with a fallback to a linear gradient in combination with some other styles on our `Button` component cause an infinite layout loop and pegs the CPU.

[Color system] Revert button changes

---

src/components/ActionList/ActionList.scss
src/components/Filters/Filters.scss
src/components/OptionList/components/Option/Option.scss
src/components/ResourceItem/ResourceItem.scss
src/components/Tabs/Tabs.scss

Address #2197. Flattens the output from the `state` mixin to make it possible to implement CSS var overrides and fallbacks in a sane way. 
Find and replaces the `state` uses with the raw output based on arguments.

[Color system] Flatten interaction states

---

UNRELEASED.md
src/components/ResourceList/components/FilterControl/components/FilterValueSelector/FilterValueSelector.tsx
src/components/ResourceList/components/FilterControl/components/FilterValueSelector/index.ts
src/components/ResourceList/components/FilterControl/components/FilterValueSelector/tests/FilterValueSelector.test.tsx
src/utilities/tests/use-is-mounted-ref.test.tsx
src/utilities/use-is-mounted-ref.ts

Part of #1995
* Converting FilterValueSelector to a functional component
* Add useIsMountedRef hook
Playground with filters below
<details>
```jsx
import {ResourceList, TextStyle, Avatar, FilterType, Card} from '../src';
export class Playground extends React.Component {
state = {
{
},
],
};
};
this.setState({appliedFilters});
};
return ( …
```

[FilterValueSelector] Convert to functional component & add isMountedRef

---

UNRELEASED.md
config/rollup/plugins/styles.js
package.json
tests/build.test.js
yarn.lock

We're moving the Sass.zip generation to polaris-styleguide.
Another PR is coming in polaris-styleguide to generate the Sass.zip, and remove the need for uploading any assets with the GitHub releases.
This change makes it less convenient to download the Sass.zip for older versions of Polaris. People who want to get an older version of the Sass files will have to go through the trouble of downloading a package via this type of URL:
```
https://registry.yarnpkg.com/@shopify/polaris/-/polaris-POLARIS_VERSION.tgz
```
For example:
https://registry.yarnpkg.com/@shopify/polaris/-/polaris-4.7.0.tgz

Stop generating Sass.zip

---

UNRELEASED.md
documentation/guides/migrating-from-v3-to-v4.md
src/components/AppProvider/README.md

Current migration docs didn't provide clear explanation what kind of `translations` should be used while migrating `<AppProvider>`.  I saw migration examples in different projects - in total, around 4-5 options what developers passed into translations. It wasn't clear which option is correct one. I saw other people looking for examples with translations and being confused what approach to take and what each approach means.
I'm describing options what to put into `translations` and for what case each option is sutable.
Is it the right place to put it? Maybe this info should be rather in README of `AppProvider`, and in migration guide there will be enough to insert a link to the updated `AppProvider` docs?  In case if this info is okay/needed in your opinion in the first place.

[Migration guide] Improve part about using translations in AppProvider

---

UNRELEASED.md
src/components/TextField/TextField.tsx
src/components/TextField/tests/TextField.test.tsx

Comply with the [WAI-ARIA-1.1 guidelines](https://www.w3.org/TR/wai-aria-1.1/#aria-multiline) by normalizing the `aria-multiline` attribute for `TextField` components that have `multiline: number` prop.
Fixes #2349 
Automated accessibility tools (e.g. Axe, Lighthouse) currently flag invalid aria-multiline values for TextField when specifying a number value for its multiline prop.
| `multiline` prop        | before           | after       |
| ------------- |:-------------:| --------:|
| number > 0    | `aria-multiline={number}` | `aria-multiline={true}`|
📄 [Changelog …

[TextField] Fix aria-multiline attribute values

---

UNRELEASED.md
src/components/ChoiceList/ChoiceList.tsx
src/components/ChoiceList/tests/ChoiceList.test.tsx

There are cases where a `ChoiceList` requires nested translations/HTML tags in its `title`.
Switching `title`'s prop type from `string` to a more permissive `ReactNode`.
`yarn dev` / playground
<details>
```jsx
import {Page, ChoiceList} from '../src';
const choices = [
{label: 'One', value: 'one'},
{label: 'Two', value: 'two'},
{label: …
```

[ChoiceList] Add JSX support to the title prop

---

.storybook/webpack.config.js
package.json
scripts/splash/README.md
scripts/splash/index.tsx

As discussed with @amrocha – let's go with an approach where logic is more contained to the splash script itself, and people are given a single way of disabling the console output of yarn splash.

[yarn splash] DISABLE_SPLASH redux
